'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iCLMInfoChklst.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Service.
        '''</summary>
        Friend ReadOnly Property str1098() As String
            Get
                Return ResourceManager.GetString("str1098", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Requirement.
        '''</summary>
        Friend ReadOnly Property str1099() As String
            Get
                Return ResourceManager.GetString("str1099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information Checklist.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Service.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Requirement.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;File.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return To &amp;Navigator.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - General.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim Number:.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend ReadOnly Property str1107() As String
            Get
                Return ResourceManager.GetString("str1107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property str1108() As String
            Get
                Return ResourceManager.GetString("str1108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference.
        '''</summary>
        Friend ReadOnly Property str1109() As String
            Get
                Return ResourceManager.GetString("str1109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Critical.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Requirement.
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Service.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit.
        '''</summary>
        Friend ReadOnly Property str1113() As String
            Get
                Return ResourceManager.GetString("str1113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service:.
        '''</summary>
        Friend ReadOnly Property str1114() As String
            Get
                Return ResourceManager.GetString("str1114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party ....
        '''</summary>
        Friend ReadOnly Property str1115() As String
            Get
                Return ResourceManager.GetString("str1115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date requested:.
        '''</summary>
        Friend ReadOnly Property str1116() As String
            Get
                Return ResourceManager.GetString("str1116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date received:.
        '''</summary>
        Friend ReadOnly Property str1117() As String
            Get
                Return ResourceManager.GetString("str1117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date critical:.
        '''</summary>
        Friend ReadOnly Property str1118() As String
            Get
                Return ResourceManager.GetString("str1118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact:.
        '''</summary>
        Friend ReadOnly Property str1119() As String
            Get
                Return ResourceManager.GetString("str1119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requirement:.
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference:.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Received.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Details.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will lose all of your current details.
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is a Mandatory field. You must enter data in this field..
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter Only Numbers.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data in a Mandatory Field is Missing.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information Checklist.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date entered.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date. Cannot be earlier than Date Requested.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Time Entered.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Date Requested and time should be 
        ''' less than or equal to current date &amp; time.
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter Valid Time HH:MM.
        '''</summary>
        Friend ReadOnly Property str1319() As String
            Get
                Return ResourceManager.GetString("str1319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date. Cannot be earlier than Reported Date.
        '''</summary>
        Friend ReadOnly Property str1320() As String
            Get
                Return ResourceManager.GetString("str1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Date Received and time should be 
        ''' less than or equal to current date &amp; time.
        '''</summary>
        Friend ReadOnly Property str1321() As String
            Get
                Return ResourceManager.GetString("str1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service/Requirement.
        '''</summary>
        Friend ReadOnly Property str1322() As String
            Get
                Return ResourceManager.GetString("str1322", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
