; ======================================
; INI file for Pure Patch Installation
; ======================================

[General]

MainTitle=Pure Patch Installer

; Installer Tile displayed whilst installing files
InstallerTitle1=Pure Insurance - 3.0 Build 15 Patch 1
PatchVersion=300.000.0015.1

; Set the version compatibility
PureCompatibleVersion=300.000.0015






