'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace FileUploadService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WebFile", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Partial Public Class WebFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private FileContentField() As Byte
        
        Private FileNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileContent() As Byte()
            Get
                Return Me.FileContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileContentField, value) <> true) Then
                    Me.FileContentField = value
                    Me.RaisePropertyChanged("FileContent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="Pure.Portals.FileUpload", ConfigurationName:="FileUploadService.FileUpload")>  _
    Public Interface FileUpload
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="Pure.Portals.FileUpload/FileUpload/InsertFile", ReplyAction:="Pure.Portals.FileUpload/FileUpload/InsertFileResponse")>  _
        Function BeginInsertFile(ByVal file As FileUploadService.WebFile, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndInsertFile(ByVal result As System.IAsyncResult) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FileUploadChannel
        Inherits FileUploadService.FileUpload, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InsertFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FileUploadClient
        Inherits System.ServiceModel.ClientBase(Of FileUploadService.FileUpload)
        Implements FileUploadService.FileUpload
        
        Private onBeginInsertFileDelegate As BeginOperationDelegate
        
        Private onEndInsertFileDelegate As EndOperationDelegate
        
        Private onInsertFileCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event InsertFileCompleted As System.EventHandler(Of InsertFileCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FileUploadService_FileUpload_BeginInsertFile(ByVal file As FileUploadService.WebFile, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements FileUploadService.FileUpload.BeginInsertFile
            Return MyBase.Channel.BeginInsertFile(file, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FileUploadService_FileUpload_EndInsertFile(ByVal result As System.IAsyncResult) As String Implements FileUploadService.FileUpload.EndInsertFile
            Return MyBase.Channel.EndInsertFile(result)
        End Function
        
        Private Function OnBeginInsertFile(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim file As FileUploadService.WebFile = CType(inValues(0),FileUploadService.WebFile)
            Return CType(Me,FileUploadService.FileUpload).BeginInsertFile(file, callback, asyncState)
        End Function
        
        Private Function OnEndInsertFile(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = CType(Me,FileUploadService.FileUpload).EndInsertFile(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnInsertFileCompleted(ByVal state As Object)
            If (Not (Me.InsertFileCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent InsertFileCompleted(Me, New InsertFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub InsertFileAsync(ByVal file As FileUploadService.WebFile)
            Me.InsertFileAsync(file, Nothing)
        End Sub
        
        Public Overloads Sub InsertFileAsync(ByVal file As FileUploadService.WebFile, ByVal userState As Object)
            If (Me.onBeginInsertFileDelegate Is Nothing) Then
                Me.onBeginInsertFileDelegate = AddressOf Me.OnBeginInsertFile
            End If
            If (Me.onEndInsertFileDelegate Is Nothing) Then
                Me.onEndInsertFileDelegate = AddressOf Me.OnEndInsertFile
            End If
            If (Me.onInsertFileCompletedDelegate Is Nothing) Then
                Me.onInsertFileCompletedDelegate = AddressOf Me.OnInsertFileCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginInsertFileDelegate, New Object() {file}, Me.onEndInsertFileDelegate, Me.onInsertFileCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As FileUploadService.FileUpload
            Return New FileUploadClientChannel(Me)
        End Function
        
        Private Class FileUploadClientChannel
            Inherits ChannelBase(Of FileUploadService.FileUpload)
            Implements FileUploadService.FileUpload
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of FileUploadService.FileUpload))
                MyBase.New(client)
            End Sub
            
            Public Function BeginInsertFile(ByVal file As FileUploadService.WebFile, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements FileUploadService.FileUpload.BeginInsertFile
                Dim _args((1) - 1) As Object
                _args(0) = file
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("InsertFile", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndInsertFile(ByVal result As System.IAsyncResult) As String Implements FileUploadService.FileUpload.EndInsertFile
                Dim _args((0) - 1) As Object
                Dim _result As String = CType(MyBase.EndInvoke("InsertFile", _args, result),String)
                Return _result
            End Function
        End Class
    End Class
End Namespace
