Public Class BaseCoreCashListItemType
    Public Property BranchCode As String
    Public Property AccountShortCode As String
    Public Property AccountKey As Integer
    Public Property AllocationStatusCode As String
    Public Property AllocationStatusKey As Integer
    Public Property Amount As Decimal
    Public Property Amount_Tendered As Decimal
    Public Property BankReference As String
    Public Property TransDetailKey As Integer
    Public Property CashListItemKey As Integer
    Public Property CashListItemKeySpecified As Boolean
    Public Property ChequeDate As DateTime
    Public Property Collection_Date As DateTime
    Public Property ContactName As String
    Public Property FurtherDetails As String
    Public Property IsProduceDocument As Boolean
    Public Property MediaReference As String
    Public Property MediaTypeCode As String
    Public Property MediaTypeKey As Integer
    Public Property Original_Amount As Decimal
    Public Property OurReference As String
    Public Property SkipPosting As Boolean
    Public Property TaxAmount As Decimal
    Public Property TaxAmountSpecified As Boolean
    Public Property TaxBandCode As String
    Public Property TaxBandKey As Integer
    Public Property TaxBandKeySpecified As Boolean
    Public Property TheirReference As String
    Public Property PartyKey As Integer
    Public Property TransactionDate As DateTime
    Public Property OverrideReason As Integer
    Public Property CurrencyBaseDate As DateTime?
    Public Property CurrencyBaseXrate As Decimal?
    Public Property AccountBaseDate As DateTime?
    Public Property AccountBaseXrate As Decimal?
    Public Property SystemBaseDate As DateTime?
    Public Property SystemBaseXrate As Decimal?
End Class
