SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS ON
GO

EXECUTE DDLDropProcedure 'spu_wp_insurancefileall'
GO

Create PROCEDURE spu_wp_insurancefileall  
    @PartyCnt INT,  
    @InsuranceFileCnt INT,  
    @RiskID INT,  
    @ClaimCnt INT,  
    @DocumentRef VARCHAR(25),  
    @Instance1 INT,  
    @Instance2 INT,  
    @Instance3 INT  
AS  
  
-------------------------------------------------------------------------------  
-- Changes  
--  
-- Added insured_name                                       RWH 15/05/01  
-- Added lead_agent_commission                          JMK 14/01/02  
-- Added VAT Amount                                         KN(CMG) 22/10/02  
-- Added anniversary_date                                   AMB 22-Oct-2003  
-- Added added credit card fields                           CLG 06-Jan-2005  
-- Added total_agent_commission           		VKG 03/04/08 
-- Added File_type        John White 6/Dec/2016  												 
-------------------------------------------------------------------------------  
  
DECLARE @insurance_ref VARCHAR(30),  
    @product VARCHAR(255),  
    @lead_insurer VARCHAR(100),  
    @lead_insurer_logic VARCHAR(50),  
    @lead_agent VARCHAR(100),  
    @lead_agent_logic VARCHAR(50),  
    @lead_agent_percent NUMERIC(12,8),  
    @lead_agent_amount NUMERIC(19,8),  
    @account_handler VARCHAR(100),  
    @acc_hand_logic VARCHAR(50),  
    @insured VARCHAR(255),  
    @business_type VARCHAR(255),  
    @collect_type VARCHAR(100),  
    @collection_from VARCHAR(255),  
    @branch VARCHAR(255),  
    @currency VARCHAR(255),  
    @language VARCHAR(255),  
    @date_issued DATETIME,  
    @cover_start_date DATETIME,  
    @expiry_date DATETIME,  
    @renewal_date DATETIME,  
    @renewal_method VARCHAR(255),  
    @renewal_frequency VARCHAR(255),  
    @is_referred_at_renewal TINYINT,  
    @lapsed_reason VARCHAR(255),  
    @lapsed_date DATETIME,  
    @lapsed_description VARCHAR(255),  
    @is_referred_on_mta TINYINT,  
    @policy_version INT,  
    @gemini_policy_status INT,  
    @gemini_business_type INT,  
    @deferred_ind INT,  
    @policy_ignore INT,  
    @broker VARCHAR(100),  
    @risk_code VARCHAR(255),  
    @risk_code_logic VARCHAR(50),  
    @analysis_code VARCHAR(255),  
    @analysis_code_logic VARCHAR(50),  
    @proposal_date DATETIME,  
    @diary_date DATETIME,  
    @review_date DATETIME,  
    @renewal_day_number INT,  
    @policy_type VARCHAR(255),  
    @indicator VARCHAR(1),  
    @clause VARCHAR(4),  
    @cover VARCHAR(1),  
    @area VARCHAR(1),  
    @long_term_undertaking_date DATETIME,  
    @renewal_stop_code VARCHAR(255),  
    @renewal_stop_code_logic VARCHAR(50),  
    @vbs_type VARCHAR(2),  
    @vbs_status VARCHAR(1),  
    @is_insurer_rate_table TINYINT,  
    @is_related_policies TINYINT,  
    @is_retained_documents TINYINT,  
    @schemes_postcode VARCHAR(8),  
    @paid_direct VARCHAR(1),  
    @scheme VARCHAR(100),  
    @brokerage_amount NUMERIC(19,4),  
    @is_minimum_brokerage_flag TINYINT,  
    @annual_premium NUMERIC(19,4),  
    @this_premium NUMERIC(19,4),  
    @net_premium NUMERIC(19,4),  
    @commission_amount NUMERIC(19,4),  
    @iptable_amount NUMERIC(19,4),  
    @ipt_percentage NUMERIC(7,4),  
    @is_ipt_overridden TINYINT,  
    @tax_amount NUMERIC(19,4),  
    @vatable_amount NUMERIC(19,4),  
    @vat_percentage NUMERIC(7,4),  
    @payment_method VARCHAR(60),  
    @pay_meth_logic VARCHAR(60),  
    @commission_percentage NUMERIC(7,4),  
    @invariant_key INT,  
    @insured_name VARCHAR(255),  
    @alternate_reference VARCHAR(80),  
    @is_client_invoiced TINYINT,  
    @old_policy_number VARCHAR(30),  
    @quote_expiry_date DATETIME,  
    @alternate_account VARCHAR(255),  
    @endorsement_count INT,  
    @created_by VARCHAR(100),  
    @date_created DATETIME,  
    @modified_by_id VARCHAR(100),  
    @last_modified DATETIME,  
    @last_trans_date DATETIME,  
    @last_trans_type VARCHAR(255),  
    @last_trans_description VARCHAR(255),  
    @last_trans_debit_credit VARCHAR(1),  
    @last_trans_document_ref VARCHAR(25),  
    @last_trans_cover_start_date DATETIME,  
    @last_trans_expiry_date DATETIME,  
    @code VARCHAR(40),  
    @description VARCHAR(255),  
    @inception_date DATETIME,  
    @quote_insurance_ref VARCHAR(255),  
    @next_insurance_ref VARCHAR(255),  
    @last_insurance_ref VARCHAR(255),  
    @renewal_count INT,  
    @insured_name2 VARCHAR(255),  
    @lead_agent_address_1 VARCHAR(60),  
    @lead_agent_address_2 VARCHAR(60),  
    @lead_agent_address_3 VARCHAR(60),  
    @lead_agent_address_4 VARCHAR(60),  
    @lead_agent_address_5 VARCHAR(20),  
    @lead_agent_country VARCHAR(20),  
    @lead_agent_commission NUMERIC(19,4), 
    @total_agent_commission numeric(19,8),  
    @vat_amount NUMERIC(19,4),  
    @lead_agent_account VARCHAR(255),  
    @anniversary_date DATETIME,  
	@policy_status VARCHAR(255),  
	@currency_ISO_code VARCHAR(4),  
	@currency_symbol VARCHAR(4),  
	@InceptionDateTPI DATETIME,  
	@UWYearCode VARCHAR(10),  
	@UWYearDesc VARCHAR(255),  
    @fsa_customer_category VARCHAR(255),  
    @fsa_contract_location VARCHAR(255),  
    @fsa_underwriter VARCHAR(255),  
    @fsa_type_of_sale VARCHAR(255),  
    @fsa_renewal_consent VARCHAR(255),  
    @cc_number VARCHAR(30),  
    @cc_exipry_date VARCHAR(10),  
    @cc_valid tinyint,  
    @fsa_terms_agreed VARCHAR(255),  
    @fsa_terms_agreed_date VARCHAR(255),  
    @fsa_inception_renewal_date VARCHAR(255),  
    @fsa_policy_documents_issued_date VARCHAR(255),  
    @fsa_policy_documents_correct VARCHAR(255),  
    @fsa_date_errors_notified_to_insurer VARCHAR(255),  
    @risk_transfer_agreement VARCHAR(3),  
    @cover_note_book VARCHAR(50),    
    @cover_note_number INT,
    @quote_version INT,  
	@file_type VARCHAR(255)							   
						  
  
 DECLARE @OCI_Site TinyInt  
 IF EXISTS (SELECT * FROM Hidden_Options WHERE option_number = 1 and value = 'U')  
  Begin  
  select @OCI_Site = 0  
 End  
 Else  
 Begin  
  if exists(select null from pmproduct where description = 'Sirius Installer' and code = 'Orion')  
  Begin  
   select @OCI_Site = 1  
  End  
  Else  
  Begin  
   select @OCI_Site = 0  
  End  
 End  
  
    EXEC spu_wp_insurance_file_1  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @insurance_ref OUTPUT,  
        @product OUTPUT,  
        @lead_insurer OUTPUT,  
        @lead_insurer_logic OUTPUT,  
        @lead_agent OUTPUT,  
        @lead_agent_logic OUTPUT,  
        @lead_agent_percent OUTPUT,  
        @account_handler OUTPUT,  
        @acc_hand_logic OUTPUT,  
        @insured OUTPUT,  
        @business_type OUTPUT,  
        @collect_type OUTPUT,  
        @collection_from OUTPUT,  
        @branch OUTPUT,  
        @currency OUTPUT,  
        @language OUTPUT,  
        @date_issued OUTPUT,  
        @cover_start_date OUTPUT,  
        @expiry_date OUTPUT,  
        @renewal_date OUTPUT,  
        @renewal_method OUTPUT,  
        @renewal_frequency OUTPUT,  
        @is_referred_at_renewal OUTPUT,  
        @lapsed_reason OUTPUT,  
        @lapsed_date OUTPUT,  
        @lapsed_description OUTPUT,  
        @is_referred_on_mta OUTPUT,  
        @policy_version OUTPUT,  
        @gemini_policy_status OUTPUT,  
        @gemini_business_type OUTPUT,  
        @deferred_ind OUTPUT,  
        @policy_ignore OUTPUT,  
        @broker OUTPUT,  
        @insured_name2 OUTPUT,  
        @lead_agent_commission OUTPUT,  
        @anniversary_date OUTPUT,  
		@policy_status OUTPUT,  
		@currency_ISO_code OUTPUT,  
  		@currency_symbol OUTPUT,  
		@InceptionDateTPI OUTPUT,  
		@UWYearCode OUTPUT,  
		@UWYearDesc OUTPUT,  
		@fsa_customer_category OUTPUT,  
		@fsa_contract_location OUTPUT,  
		@fsa_underwriter OUTPUT,  
        @fsa_type_of_sale OUTPUT,  
        @fsa_renewal_consent OUTPUT,  
        @fsa_terms_agreed OUTPUT,  
 @fsa_terms_agreed_date OUTPUT,  
 @fsa_inception_renewal_date OUTPUT,  
 @fsa_policy_documents_issued_date OUTPUT,  
 @fsa_policy_documents_correct OUTPUT,  
 @fsa_date_errors_notified_to_insurer OUTPUT,  
        @risk_transfer_agreement OUTPUT,
        @quote_version OUTPUT,
		@file_type OUTPUT							
					  
  
    EXEC spu_wp_insurance_file_2  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @risk_code OUTPUT,  
        @risk_code_logic OUTPUT,  
        @analysis_code OUTPUT,  
        @analysis_code_logic OUTPUT,  
        @proposal_date OUTPUT,  
        @diary_date OUTPUT,  
        @review_date OUTPUT,  
        @renewal_day_number OUTPUT,  
        @policy_type OUTPUT,  
        @indicator OUTPUT,  
        @clause OUTPUT,  
		@cover OUTPUT,  
        @area OUTPUT,  
        @long_term_undertaking_date OUTPUT,  
        @renewal_stop_code OUTPUT,  
        @renewal_stop_code_logic OUTPUT,  
        @vbs_type OUTPUT,  
        @vbs_status OUTPUT,  
        @is_insurer_rate_table OUTPUT,  
        @is_related_policies OUTPUT,  
        @is_retained_documents OUTPUT,  
        @schemes_postcode OUTPUT,  
        @paid_direct OUTPUT,  
        @scheme OUTPUT,  
        @brokerage_amount OUTPUT,  
        @is_minimum_brokerage_flag OUTPUT,  
        @annual_premium OUTPUT,  
        @this_premium OUTPUT,  
        @net_premium OUTPUT,  
        @commission_amount OUTPUT,  
        @iptable_amount OUTPUT,  
        @ipt_percentage OUTPUT,  
        @is_ipt_overridden OUTPUT,  
        @tax_amount OUTPUT,  
        @vatable_amount OUTPUT,  
        @vat_percentage OUTPUT,  
        @payment_method OUTPUT,  
        @commission_percentage OUTPUT,  
        @invariant_key OUTPUT,  
        @insured_name OUTPUT,  
        @alternate_reference OUTPUT,  
        @is_client_invoiced OUTPUT,  
        @old_policy_number OUTPUT,  
        @quote_expiry_date OUTPUT,  
        @alternate_account OUTPUT,  
        @lead_agent_address_1 OUTPUT,  
        @lead_agent_address_2 OUTPUT,  
        @lead_agent_address_3 OUTPUT,  
        @lead_agent_address_4 OUTPUT,  
        @lead_agent_address_5 OUTPUT,  
        @lead_agent_country OUTPUT,  
        @vat_amount OUTPUT, --KN(CMG)  
        @cc_number OUTPUT,  
        @cc_exipry_date OUTPUT,  
        @cc_valid OUTPUT  
  
    EXEC spu_wp_insurance_file_3  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @this_premium,  
        @lead_agent_percent OUTPUT,  
        @lead_agent_amount OUTPUT  
  
    EXEC spu_wp_insurance_file_system  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @endorsement_count OUTPUT,  
        @created_by OUTPUT,  
        @date_created OUTPUT,  
        @modified_by_id OUTPUT,  
        @last_modified OUTPUT,  
        @last_trans_date OUTPUT,  
        @last_trans_type OUTPUT,  
        @last_trans_description OUTPUT,  
        @last_trans_debit_credit OUTPUT,  
        @last_trans_document_ref OUTPUT,  
        @last_trans_cover_start_date OUTPUT,  
        @last_trans_expiry_date OUTPUT  
  
    EXEC spu_wp_insurance_folder  
        @PartyCnt,  
        @InsuranceFileCnt,  
		@RiskID,  
        @ClaimCnt,  
        @code OUTPUT,  
        @description OUTPUT,  
        @inception_date OUTPUT,  
        @quote_insurance_ref OUTPUT,  
        @next_insurance_ref OUTPUT,  
        @last_insurance_ref OUTPUT,  
        @renewal_count OUTPUT  
  
    EXEC spu_wp_party_leadagent  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @lead_agent OUTPUT,  
        @lead_agent_address_1 OUTPUT,  
        @lead_agent_address_2 OUTPUT,  
        @lead_agent_address_3 OUTPUT,  
        @lead_agent_address_4 OUTPUT,  
        @lead_agent_address_5 OUTPUT,  
        @lead_agent_country OUTPUT,  
        @lead_agent_account OUTPUT    --AK 24072003  
  
If (ISNULL(@insurance_ref, '') <> '')
	SELECT TOP 1 @cover_note_book = CNB.Book_Number,
		@cover_note_number = CNS.Cover_Sheet_Number
	From Cover_Note_Sheet CNS
		INNER JOIN Cover_Note_Book CNB
			ON CNB.Cover_Note_Book_Id = CNS.Cover_Note_Book_Id
		INNER JOIN Insurance_File IFI on IFI.insurance_file_cnt = CNS.insurance_file_cnt
		Where CNS.insurance_file_cnt In 
		(Select insurance_file_cnt From insurance_file Where insurance_ref like @insurance_ref) 

--Added Query to find the total agent commission
	SELECT @total_agent_commission=sum(ACC.commission_value) 
	FROM Agent_Commission ACC 
	INNER JOIN  Insurance_File IFI on IFI.insurance_file_cnt = ACC.insurance_file_cnt 
	WHERE ACC.insurance_file_cnt = @InsuranceFileCnt  AND is_lead_agent = 1
    --- added for last insurance file type ----

	SELECT @last_trans_type = IFT.description FROM Insurance_File_Type IFT
	INNER JOIN Insurance_File I ON I.insurance_file_type_id = IFT.insurance_file_type_id
	WHERE I.insurance_file_cnt = @InsuranceFileCnt

    SELECT  
        'insurance_ref' = @insurance_ref,  
        'product' = @product,  
        'lead_insurer' = @lead_insurer,  
        'lead_insurer_logic' = REPLACE(@lead_insurer_logic, ' ', ''),  
        'lead_agent' = @lead_agent,  
        'lead_agent_logic' = REPLACE(@lead_agent_logic, ' ', ''),  
        'lead_agent_percent' = @lead_agent_percent,  
        'lead_agent_amount' = @lead_agent_amount,  
        'account_handler' = @account_handler,  
        'acc_hand_logic' = REPLACE(@acc_hand_logic, ' ', ''),  
        'insured' = @insured,  
        'business_type' = @business_type,  
        'collect_type' = @collect_type,  
        'collection_from' = @collection_from,  
        'branch' = @branch,  
        'currency' = @currency,  
        'language' = @language,  
        'date_issued' = @date_issued,  
        'cover_start_date' = @cover_start_date,  
        'expiry_date' = @expiry_date,  
        'renewal_date' = @renewal_date,  
        'renewal_method' = @renewal_method,  
        'renewal_frequency' = @renewal_frequency,  
        'is_referred_at_renewal' = @is_referred_at_renewal,  
        'lapsed_reason' = @lapsed_reason,  
        'lapsed_date' = @lapsed_date,  
        'lapsed_description' = @lapsed_description,  
        'is_referred_on_mta' = @is_referred_on_mta,  
        'policy_version' = @policy_version,  
        'gemini_policy_status' = @gemini_policy_status,  
        'gemini_business_type' = @gemini_business_type,  
        'deferred_ind' = @deferred_ind,  
        'policy_ignore' = @policy_ignore,  
        'broker' = @broker,  
        'risk_code' = @risk_code,  
        'risk_code_logic' = REPLACE(@risk_code_logic, ' ', ''),  
        'analysis_code' = @analysis_code,  
        'analysis_code_logic' = REPLACE(@analysis_code_logic, ' ', ''),  
        'proposal_date' = @proposal_date,  
        'diary_date' = @diary_date,  
        'review_date' = @review_date,  
        'renewal_day_number' = @renewal_day_number,  
        'policy_type' = @policy_type,  
        'indicator' = @indicator,  
        'clause' = @clause,  
        'cover' = @cover,  
        'area'= @area,  
        'long_term_undertaking_date' = @long_term_undertaking_date,  
        'renewal_stop_code' = @renewal_stop_code,  
        'renewal_stop_code_logic' = REPLACE(@renewal_stop_code_logic, ' ', ''),  
        'vbs_type' = @vbs_type,  
        'vbs_status' = @vbs_status,  
        'is_insurer_rate_table' = @is_insurer_rate_table,  
        'is_related_policies' = @is_related_policies,  
        'is_retained_documents' = @is_retained_documents,  
        'schemes_postcode' = @schemes_postcode,  
        'paid_direct' = @paid_direct,  
        'scheme' = @scheme,  
        'brokerage_amount' = @brokerage_amount,  
        'is_minimum_brokerage_flag' = @is_minimum_brokerage_flag,  
        'annual_premium' = @annual_premium,  
        'this_premium' = @this_premium,  
        'net_premium' = @net_premium,  
        'commission_amount' = @commission_amount,  
        'iptable_amount' = @iptable_amount,  
        'ipt_percentage'= @ipt_percentage,  
        'is_ipt_overridden' = @is_ipt_overridden,  
        'tax_amount' = @tax_amount,  
        'vatable_amount' = @vatable_amount,  
        'vat_percentage' = @vat_percentage,  
        'payment_method' = @payment_method,  
        'pay_meth_logic' = case When @OCI_Site = 1 then @payment_method else REPLACE(@payment_method,' ','') end,  
        'commission_percentage' = @commission_percentage,  
        'invariant_key' = @invariant_key,  
        'insured_name' = @insured_name,  
        'alternate_reference' = @alternate_reference,  
        'is_client_invoiced' = @is_client_invoiced,  
        'old_policy_number' = @old_policy_number,  
        'quote_expiry_date' = @quote_expiry_date,  
        'alternate_account' = @alternate_account,  
        'endorsement_count' = @endorsement_count,  
        'created_by' = @created_by,  
        'date_created' = @date_created,  
        'modified_by_id'= @modified_by_id,  
        'last_modified' = @last_modified,  
        'last_trans_date' = @last_trans_date,  
        'last_trans_type' = @last_trans_type,  
        'last_trans_description' = @last_trans_description,  
        'last_trans_debit_credit' = @last_trans_debit_credit,  
        'last_trans_document_ref' = @last_trans_document_ref,  
        'last_trans_cover_start_date' = @last_trans_cover_start_date,  
        'last_trans_expiry_date' = @last_trans_expiry_date,  
        'code' = @code,  
        'description' = @description,  
        'inception_date' = @inception_date,  
        'quote_insurance_ref' = @quote_insurance_ref,  
        'next_insurance_ref' = @next_insurance_ref,  
        'last_insurance_ref' = @last_insurance_ref,  
        'renewal_count' = @renewal_count,  
        'insured_name2' = @insured_name2,  
        'lead_agent_address_1' = @lead_agent_address_1,  
        'lead_agent_address_2' = @lead_agent_address_2,  
        'lead_agent_address_3' = @lead_agent_address_3,  
        'lead_agent_address_4' = @lead_agent_address_4,  
        'lead_agent_address_5' = @lead_agent_address_5,  
        'lead_agent_country' = @lead_agent_country,  
     'lead_agent_commission' = @lead_agent_commission,  
     'vat_amount' = @vat_amount,  
     'agent_reference' = @lead_agent_account,  
        'anniversary_date' = @anniversary_date,  
        'policy_status' = @policy_status,  
        'currency_ISO_code' = @currency_ISO_code,  
        'currency_symbol' = @currency_symbol,  
        'InceptionDateTPI' = @InceptionDateTPI,  
        'UWYearCode' = @UWYearCode,  
        'UWYearDesc' = @UWYearDesc,  
        'fsa_customer_category' = @FSA_customer_category,  
        'fsa_contract_location' = @FSA_contract_location,  
        'fsa_underwriter' = @FSA_underwriter,  
        'fsa_type_of_sale' = @FSA_type_of_sale,  
        'fsa_renewal_consent' = @FSA_renewal_consent,  
        'cc_expiry_date' = @cc_number,  
        'cc_number' =  @cc_exipry_date,  
        'cc_valid' = @cc_valid,  
        'fsa_terms_agreed' = @fsa_terms_agreed ,  
	'fsa_terms_agreed_date' = @fsa_terms_agreed_date ,  
	'fsa_inception_renewal_date' = @fsa_inception_renewal_date ,  
	'fsa_policy_documents_issued_date' = @fsa_policy_documents_issued_date ,  
	'fsa_policy_documents_correct' = @fsa_policy_documents_correct ,  
	'fsa_date_errors_notified_to_insurer' = @fsa_date_errors_notified_to_insurer,  
	'risk_transfer_agreement' = @risk_transfer_agreement,
	'cover_note_book' = @cover_note_book,
	'cover_note_number' = @cover_note_number, 
	'total_agent_commission'=@total_agent_commission,
  'Insurance_File_Cnt'=@InsuranceFileCnt,  
  'QuoteVersion'=@quote_version,
	'file_type' = @file_type