SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
EXECUTE DDLDropProcedure spu_wp_farm
GO

CREATE PROCEDURE spu_wp_farm
    @PartyCnt INT,  
    @InsuranceFileCnt INT,  
    @ClaimCnt INT,  
    @DocumentRef VARCHAR(25),  
    @Instance1 INT,  
    @Instance2 INT,  
    @Instance3 INT,  
    @address1 VARCHAR(255),  
    @address2 VARCHAR(255),  
    @address3 VARCHAR(255),  
    @address4 VARCHAR(255),  
    @postal_code VARCHAR(255),  
    @is_property_damage TINYINT OUTPUT,  
    @pd_produce_sum_insured NUMERIC,  
    @pd_poultry_sum_insured NUMERIC,  
    @pd_buildings_sum_insured NUMERIC,  
    @pd_misc_sum_insured NUMERIC,  
    @pd_liability_sum_insured NUMERIC,  
    @is_business_interruption TINYINT OUTPUT,  
    @bi_description VARCHAR(255),  
    @bi_sum_insured NUMERIC,  
    @bi_indemnity_period INT OUTPUT,  
    @is_livestock TINYINT OUTPUT,  
    @l_sum_insured NUMERIC,  
    @l_in_transit_limit NUMERIC,  
    @l_disease_sum_insured NUMERIC,  
    @is_farm_liabilities TINYINT OUTPUT,  
    @fl_wages_estimate NUMERIC,  
    @fl_employers_liability_limit NUMERIC,  
    @fl_public_liability_limit NUMERIC,  
    @is_money_and_assault TINYINT OUTPUT,  
    @ma_money_in_transit NUMERIC,  
    @ma_money NUMERIC,  
    @ma_not_in_safe NUMERIC,  
    @ma_in_dwellings NUMERIC,  
    @ma_locked NUMERIC,  
    @ma_any_other NUMERIC,  
    @is_personal_accident TINYINT OUTPUT,  
    @pa_insured_person VARCHAR(255),  
    @pa_age INT OUTPUT,  
    @pa_duties VARCHAR(255),  
    @pa_compensation NUMERIC,  
    @is_engineering TINYINT OUTPUT,  
    @e_property_insured VARCHAR(255),  
    @e_cover NUMERIC,  
    @e_indemnity_limit NUMERIC,  
    @e_excess NUMERIC,  
    @is_uncollected_milk TINYINT OUTPUT,  
    @um_days_compensation INT OUTPUT,  
    @um_compensation NUMERIC,  
    @um_number_of_cows INT OUTPUT,  
    @is_farm_home TINYINT OUTPUT,  
    @fh_buildings_sum_insured NUMERIC,  
    @fh_contents_sum_insured NUMERIC,  
    @fh_possessions_sum_insured NUMERIC,  
    @fh_unspecified_sum_insured NUMERIC,  
    @fh_specified_sum_insured NUMERIC,  
    @fh_buildings_excess NUMERIC,  
    @fh_subsidence_excess NUMERIC,  
    @fh_contents_excess NUMERIC,  
    @is_farm_motor TINYINT OUTPUT,  
    @fm_year INT OUTPUT,  
    @fm_registration_number VARCHAR(255),  
    @fm_value NUMERIC,  
    @fm_cover NUMERIC
AS
BEGIN  
  
SELECT  
    @address1 = address.address1,  
    @address2 = address.address2,  
    @address3 = address.address3,  
    @address4 = address.address4,  
    @postal_code = address.postal_code,  
    @is_property_damage = farm.is_property_damage,  
    @pd_produce_sum_insured = farm.pd_produce_sum_insured,  
    @pd_poultry_sum_insured = farm.pd_poultry_sum_insured,  
    @pd_buildings_sum_insured = farm.pd_buildings_sum_insured,  
    @pd_misc_sum_insured = farm.pd_misc_sum_insured,  
    @pd_liability_sum_insured = farm.pd_liability_sum_insured,  
    @is_business_interruption = farm.is_business_interruption,  
    @bi_description = farm.bi_description,  
    @bi_sum_insured = farm.bi_sum_insured,  
    @bi_indemnity_period = farm.bi_indemnity_period,  
    @is_livestock = farm.is_livestock,  
    @l_sum_insured = farm.l_sum_insured,  
    @l_in_transit_limit = farm.l_in_transit_limit,  
    @l_disease_sum_insured = farm.l_disease_sum_insured,  
    @is_farm_liabilities = farm.is_farm_liabilities,  
    @fl_wages_estimate = farm.fl_wages_estimate,  
    @fl_employers_liability_limit = farm.fl_employers_liability_limit,  
    @fl_public_liability_limit = farm.fl_public_liability_limit,  
    @is_money_and_assault = farm.is_money_and_assault,  
    @ma_money_in_transit = farm.ma_money_in_transit,  
    @ma_money = farm.ma_money,  
    @ma_not_in_safe = farm.ma_not_in_safe,  
    @ma_in_dwellings = farm.ma_in_dwellings,  
    @ma_locked = farm.ma_locked,  
    @ma_any_other = farm.ma_any_other,  
    @is_personal_accident = farm.is_personal_accident,  
    @pa_insured_person = farm.pa_insured_person,  
    @pa_age = farm.pa_age,  
    @pa_duties = farm.pa_duties,  
    @pa_compensation = farm.pa_compensation,  
    @is_engineering = farm.is_engineering,  
    @e_property_insured = farm.e_property_insured,  
    @e_cover = farm.e_cover,  
    @e_indemnity_limit = farm.e_indemnity_limit,  
    @e_excess = farm.e_excess,  
    @is_uncollected_milk = farm.is_uncollected_milk,  
    @um_days_compensation = farm.um_days_compensation,  
    @um_compensation = farm.um_compensation,  
    @um_number_of_cows = farm.um_number_of_cows,  
    @is_farm_home = farm.is_farm_home,  
    @fh_buildings_sum_insured = farm.fh_buildings_sum_insured,  
    @fh_contents_sum_insured = farm.fh_contents_sum_insured,  
    @fh_possessions_sum_insured = farm.fh_possessions_sum_insured,  
    @fh_unspecified_sum_insured = farm.fh_unspecified_sum_insured,  
    @fh_specified_sum_insured = farm.fh_specified_sum_insured,  
    @fh_buildings_excess = farm.fh_buildings_excess,  
    @fh_subsidence_excess = farm.fh_subsidence_excess,  
    @fh_contents_excess = farm.fh_contents_excess,  
    @is_farm_motor = farm.is_farm_motor,  
    @fm_year = farm.fm_year,  
    @fm_registration_number = farm.fm_registration_number,  
    @fm_value = farm.fm_value,  
    @fm_cover = farm.fm_cover  
FROM    
    farm
    LEFT OUTER JOIN address  
        ON farm.address_cnt = address.address_cnt
WHERE 
    farm.insurance_file_cnt = @insurancefilecnt    
 
END

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO
