SET QUOTED_IDENTIFIER ON SET ANSI_NULLS ON
GO


EXECUTE DDLDropProcedure 'spu_wp_PFPremiumFinance'
GO


CREATE PROCEDURE spu_wp_PFPremiumFinance
    @PartyCnt INT,
    @InsuranceFileCnt INT,
    @RiskID INT,
    @ClaimCnt INT,
    @DocumentRef VARCHAR(25),
    @Instance1 INT,
    @Instance2 INT,
    @Instance3 INT
AS

DECLARE @pfprem_finance_cnt INT
DECLARE @pfprem_finance_version INT

IF ISNUMERIC(@DocumentRef) = 1
BEGIN
    /*@DocumentRef contains the pfprem_finance_cnt*/
    SELECT @pfprem_finance_cnt = CAST(@DocumentRef AS INT)
END
ELSE
BEGIN
    /*Try to find the pfprem_finance_cnt from the insurance_file_cnt*/
    SELECT  
        @pfprem_finance_cnt = MAX(pfprem_finance_cnt)
    FROM pfpremiumfinance 
    WHERE insurance_file_cnt = @InsuranceFileCnt
    
    IF @pfprem_finance_cnt IS NULL
    BEGIN
        SELECT  
            @pfprem_finance_cnt = MAX(pfprem_finance_cnt)
        FROM pftransaction_id 
        WHERE insurance_file_cnt = @InsuranceFileCnt
    END
END

/*Now get the latest version of that finance plan*/
SELECT  
    @pfprem_finance_version = MAX(pfprem_finance_version)
FROM pfpremiumfinance 
WHERE pfprem_finance_cnt = @pfprem_finance_cnt

SELECT 
    pf.pfprem_finance_cnt,
    pf.pfprem_finance_version,
    pf.ClientId,
    pf.CompanyNo,
    pf.SchemeNo,
    pf.SchemeVersion,
    pf.StartDate,
    pf.EndDate,
    pf.SystemTag,
    pf.CompanyName,
    pf.SchemeName,
    pf.ProductClass,
    pf.TransType,
    pf.AmountToFinance,
    pf.APR,
    pf.InterestRate,
    pf.DaysDelay,
    pf.NoOfInstallments,
    pf.FirstInstallment,
    pf.OthInstallments,
    pf.CostOfProtection,
    pf.Deposit,
    pf.NetAmount,
    pf.TotalCost,
    pf.InterestCost,
    pf.MinFinanceChrge,
    pf.PayProtection,
    pf.ClientName,
    pf.ClientAddr1,
    pf.ClientAddr2,
    pf.ClientAddr3,
    pf.ClientTown,
    pf.ClientPCode,
    pf.ClientAddr4,
    pf.ClientCountry,
    pf.ClientAreaCode,
    pf.ClientPhoneNo,
    pf.ClientExtension,
    pf.ClientFaxAreaCode,
    pf.ClientFaxNo,
    pf.BankName,
    pf.BankSortCode,
    pf.BankAccountNo,
    pf.BankBranch,
    pf.BankAddr1,
    pf.BankAddr2,
    pf.BankAddr3,
    pf.BankTown,
    pf.BankPCode,
    pf.BankRegion,
    pf.BankCountry,
    pf.BankAreaCode,
    pf.BankPhoneNo,
    pf.BankExtension,
    pf.BankFaxAreaCode,
    pf.BankFaxNo,
    pf.StatusInd,
    pf.BankAccountName,
    pf.AutoGeneratedPlanRef,
    pf.FinanceCollatedPlanRef,
    pf.ClientCode,
    pf.InterestFree,
    pf.IsQuote,
    pf.IsParentPlan,
    pf.Parent_finance_cnt,
    pf.Parent_finance_version,
    pf.PlanTransaction_id,
    pf.Insurance_File_Cnt,
    pf.source_id,
    pf.pfrf_id,
    pf.tax_cost,
    pf.first_instalment_date,
    pf.next_instalment_date,
    pf.last_instalment_date,
    pf.cc_number,
    pf.cc_expiry_date,
    pf.cc_start_date,
    pf.cc_issue,
    pf.cc_pin,
    pf.commission_transdetail_id,
    CASE 
        (
            SELECT
                ISNULL(SUM(1), 0)
            FROM source 
            WHERE source_id = iff.source_id 
            AND underwriting_branch_ind = 1 
            AND iff.alternate_reference IS NOT NULL
        )
        WHEN 0 THEN
            iff.insurance_ref
        ELSE
            iff.alternate_reference
    END 'insurance_ref',
    ccs.step_number,
    cci.recurrence_count,
    cci.will_auto_cancel,
    pf.original_amount,
    pf.last_instalment,
    pf.claim_debt_id,
    pf.user_id,
    pf.agent_cnt,
    pf.agent_ref,
    pf.date_created,
    pf.date_modified,
    pf.date_confirmed,
    pf.date_review,
    pf.date_laststatement,
    pf.date_lastgeneration,
    pf.final_statement_set,
    pf.no_statements,
    pf.statement_pffrequency_id,
    pf.review_pmwrk_task_instance_id,
    frequency = f.description,
    media = m.description
FROM pfpremiumfinance pf
LEFT JOIN insurance_file iff 
    ON iff.insurance_file_cnt = pf.insurance_file_cnt
LEFT JOIN credit_control_item cci 
    ON cci.pfprem_finance_cnt = pf.pfprem_finance_cnt
    AND cci.pfprem_finance_version = pf.pfprem_finance_version 
LEFT JOIN credit_control_step ccs 
    ON ccs.credit_control_step_id = cci.credit_control_step_id
LEFT JOIN pfrf 
    ON pfrf.pfrf_id = pf.pfrf_id
LEFT JOIN pffrequency f 
    ON f.pffrequency_id = pfrf.pffrequency_id 
LEFT JOIN pfscheme s 
    ON s.companyno = pf.companyno 
    AND s.schemeno = pf.schemeno 
    AND s.schemeversion = pf.schemeversion 
LEFT JOIN mediatype m 
    ON m.mediatype_id = s.mediatype_id
WHERE pf.pfprem_finance_cnt=@pfprem_finance_cnt
AND pf.pfprem_finance_version=@pfprem_finance_version


GO
