SET QUOTED_IDENTIFIER ON SET ANSI_NULLS ON
GO


EXECUTE DDLDropProcedure 'spu_wp_PfPremiumFinanceThirdParty'
GO

CREATE PROCEDURE spu_wp_PFPremiumFinanceThirdParty
    @PartyCnt INT,
    @InsuranceFileCnt INT,
    @RiskID INT,
    @ClaimCnt INT,
    @DocumentRef VARCHAR(25),
    @Instance1 INT,
    @Instance2 INT,
    @Instance3 INT
AS

DECLARE @pfprem_finance_cnt INT
DECLARE @pfprem_finance_version INT

IF ISNUMERIC(@DocumentRef) = 1
BEGIN
    /*@DocumentRef contains the pfprem_finance_cnt*/
    SELECT @pfprem_finance_cnt = CAST(@DocumentRef AS INT)
END
ELSE
BEGIN
    /*Try to find the pfprem_finance_cnt from the insurance_file_cnt*/
    SELECT  
        @pfprem_finance_cnt = MAX(pfprem_finance_cnt)
    FROM pfpremiumfinance 
    WHERE insurance_file_cnt = @InsuranceFileCnt
    
    IF @pfprem_finance_cnt IS NULL
    BEGIN
        SELECT  
            @pfprem_finance_cnt = MAX(pfprem_finance_cnt)
        FROM pftransaction_id 
        WHERE insurance_file_cnt = @InsuranceFileCnt
    END
END

/*Now get the latest version of that finance plan*/
SELECT  
    @pfprem_finance_version = MAX(pfprem_finance_version)
FROM pfpremiumfinance 
WHERE pfprem_finance_cnt = @pfprem_finance_cnt

SELECT 
    pf.CompanyNo,
    pf.SchemeNo,
    pf.SchemeVersion,
    pf.StartDate,
    pf.EndDate,
    pf.SystemTag,
    pf.CompanyName,
    pf.SchemeName,
    pf.ProductClass,
    pf.TransType,
    pf.AmountToFinance,
    pf.APR,
    pf.InterestRate,
    pf.DaysDelay,
    pf.NoOfInstallments,
    pf.FirstInstallment,
    pf.OthInstallments,
    pf.CostOfProtection,
    pf.Deposit,
    pf.NetAmount,
    pf.TotalCost,
    pf.InterestCost,
    pf.MinFinanceChrge,
    pf.PayProtection,
    pf.ClientName,
    pf.ClientAddr1,
    pf.ClientAddr2,
    pf.ClientAddr3,
    pf.ClientTown,
    pf.ClientPCode,
    pf.ClientAddr4,
    pf.ClientCountry,
    pf.ClientAreaCode,
    pf.ClientPhoneNo,
    pf.ClientExtension,
    pf.ClientFaxAreaCode,
    pf.ClientFaxNo,
    pf.BankName,
    pf.BankSortCode,
    pf.BankAccountNo,
    pf.BankBranch,
    pf.BankAddr1,
    pf.BankAddr2,
    pf.BankAddr3,
    pf.BankTown,
    pf.BankPCode,
    pf.BankRegion,
    pf.BankCountry,
    pf.BankAreaCode,
    pf.BankPhoneNo,
    pf.BankExtension,
    pf.BankFaxAreaCode,
    pf.BankFaxNo,
    pf.StatusInd,
    pf.BankAccountName,
    pf.AutoGeneratedPlanRef,
    pf.FinanceCollatedPlanRef,
    pf.ClientCode,
    pf.InterestFree,
    pf.IsQuote,
    pf.IsParentPlan,
    pf.Parent_finance_cnt,
    pf.Parent_finance_version,
    pf.PlanTransaction_id,
    pf.Insurance_File_Cnt,
    pf.source_id,
    pf.pfrf_id,
    pf.tax_cost,
    pf.first_instalment_date,
    pf.next_instalment_date,
    pf.last_instalment_date,
    pf.cc_number,
    pf.cc_expiry_date,
    pf.cc_start_date,
    pf.cc_issue,
    pf.cc_pin,
    pf.commission_transdetail_id,
    iff.insurance_ref,
    (CONVERT(VARCHAR(100),CAST((ISNULL(pf.InterestCost,0) + ISNULL(pf.financefee,0)) AS MONEY),1)) 'TotalCharge',
    CASE ProductClass
        WHEN 'M' THEN 'X'
        ELSE '' 
    END 'XisMTA',
    CASE ProductClass
        WHEN 'NB' THEN 'X'
        ELSE '' 
    END 'XisNB',
    CASE ProductClass
        WHEN 'REN' THEN 'X'
        ELSE '' 
    END 'XisREN',
    isnull(pf.NoOfInstallments,1)-1 NoOtherPayments,
    SUBSTRING(pf.BankAccountNo,1,1) 'BankAccountNo1',
    SUBSTRING(pf.BankAccountNo,2,1) 'BankAccountNo2',
    SUBSTRING(pf.BankAccountNo,3,1) 'BankAccountNo3',
    SUBSTRING(pf.BankAccountNo,4,1) 'BankAccountNo4',
    SUBSTRING(pf.BankAccountNo,5,1) 'BankAccountNo5',
    SUBSTRING(pf.BankAccountNo,6,1) 'BankAccountNo6',
    SUBSTRING(pf.BankAccountNo,7,1) 'BankAccountNo7',
    SUBSTRING(pf.BankAccountNo,8,1) 'BankAccountNo8',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),1,1) 'BankSortCode1',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),2,1) 'BankSortCode2',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),3,1) 'BankSortCode3',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),4,1) 'BankSortCode4',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),5,1) 'BankSortCode5',
    SUBSTRING(REPLACE(pf.BankSortCode,'-',''),6,1) 'BankSortCode6',
    pf.agent_ref,
    freq.description Frequency,    
    PFParty.name as 'FinanceProvider' 
FROM pfpremiumfinance pf
INNER JOIN PFRF rf 
      ON rf.companyno = pf.companyno  
      AND rf.schemeno = pf.schemeno  
      AND rf.schemeversion = pf.schemeversion  
      AND rf.pfrf_id = pf.pfrf_id  
LEFT JOIN PFFrequency freq 
    ON freq.pffrequency_id = rf.pffrequency_id
LEFT JOIN insurance_file iff
    ON iff.insurance_file_cnt = pf.insurance_file_cnt
LEFT JOIN party p
    ON p.party_cnt = pf.clientid
    INNER JOIN    
        PFScheme S    
    ON    
        S.companyno = pf.companyno    
    AND    
        S.schemeno = pf.schemeno    
    AND    
        S.schemeversion = pf.schemeversion
left JOIN Party PFParty    
    ON  PFParty.party_cnt=s.party_cnt

WHERE pf.pfprem_finance_cnt=@pfprem_finance_cnt
AND pf.pfprem_finance_version=@pfprem_finance_version


GO