SET QUOTED_IDENTIFIER ON SET ANSI_NULLS ON
GO

EXECUTE DDLDropProcedure 'spu_wp_partyall'
GO

CREATE PROCEDURE spu_wp_partyall  
    @PartyCnt INT,  
    @InsuranceFileCnt INT,  
    @RiskID INT,  
    @ClaimCnt INT,  
    @DocumentRef VARCHAR(25),  
    @Instance1 INT,  
    @Instance2 INT,  
    @Instance3 INT  
AS  
  
DECLARE  
    @party_type_code VARCHAR(10),  
    @party_type VARCHAR(255),  
    @shortname VARCHAR(20),  
    @name VARCHAR(60),  
    @resolved_name VARCHAR(387),  
    @currency_code VARCHAR(255),  
    @collect_type VARCHAR(255),  
    @accum_treatment_type VARCHAR(255),  
    @stats_treatment_type VARCHAR(255),  
    @party_category VARCHAR(255),  
    @agent_name VARCHAR(100),  
    @consultant_name VARCHAR(100),  
    @consultant_logic VARCHAR(50),  
    @created_by VARCHAR(100),  
    @date_created DATETIME,  
    @last_modified DATETIME,  
    @modified_by VARCHAR(100),  
    @payment_method_code VARCHAR(255),  
    @payment_term_code VARCHAR(255),  
    @credit_card_code VARCHAR(70),  
    @file_code VARCHAR(50),  
    @abc_count INT,  
    @statements TINYINT,  
    @reminder_type VARCHAR(255),  
    @renewals TINYINT,  
    @status VARCHAR(6),  
    @last_action_type VARCHAR(20),  
    @is_travel_agent TINYINT,  
    @is_prospect TINYINT,  
    @is_deleted TINYINT,  
    @abi_code_on_406 VARCHAR(4),  
    @abi_code_on_81 VARCHAR(3),  
    @abi_codelist VARCHAR(6),  
    @area VARCHAR(255),  
    @invariant_key INT,  
    @record_status VARCHAR(5),  
    @CCJs INT,  
    @party_group_type VARCHAR(255),  
    @is_registered_charity TINYINT,  
    @charity_number VARCHAR(255),  
    @number_of_members INT,  
    @company_reg VARCHAR(60),  
    @trading_since_date DATETIME,  
    @party_business VARCHAR(255),  
    @location INT,  
    @no_of_offices INT,  
    @no_of_employees VARCHAR(255),  
    @financial_year DATETIME,  
    @trade_code VARCHAR(70),  
    @wage_roll NUMERIC(19, 4),  
    @turnover VARCHAR(255),  
    @vat_code VARCHAR(20),  
    @agent_type VARCHAR(255),  
    @agent_origin VARCHAR(255),  
    @agency_agreement_date DATETIME,  
    @agency_next_review_date DATETIME,  
    @agency_account_number VARCHAR(255),  
    @is_branch TINYINT,  
    @is_head_office TINYINT,  
    @default_commission_percent FLOAT,  
    @trading_name VARCHAR(255),  
    @witholding_tax MONEY,  
    @department VARCHAR(255),  
    @agency_number VARCHAR(255),  
    @binder_indicator INT,  
    @report_indicator INT,  
    @is_reinsurer INT,  
    @reinsurance_type INT,  
    @is_reinsurance_debit_credit TINYINT,  
    @default_comm_rate FLOAT,  
    @party_title_code VARCHAR(70),  
    @forename VARCHAR(60),  
    @initials VARCHAR(20),  
    @surname VARCHAR(60),  
    @employment_status_code VARCHAR(70),  
    @employer_name VARCHAR(100),  
    @employer_business VARCHAR(255),  
    @secondary_employment_status VARCHAR(70),  
    @secondary_employer_business VARCHAR(255),  
    @marital_status_code VARCHAR(70),  
    @number_of_children INT,  
    @nationality VARCHAR(255),  
    @mailshot TINYINT,  
    @is_pet_owner TINYINT,  
    @accommodation_type_code VARCHAR(70),  
    @agent_reference VARCHAR(20),  
    @current_intermediary VARCHAR(100),  
    @prospect_status VARCHAR(255),  
    @seasonal_gift VARCHAR(255),  
    @SIC_code VARCHAR(255),  
    @previous_insurer VARCHAR(100),  
    @previous_broker VARCHAR(100),  
    @service_level_logic VARCHAR(50),  
    @salutation VARCHAR(255),  
    @contact VARCHAR(255),  
    @loyalty_number VARCHAR(20),  
    @trading_name_party VARCHAR(255),  
    @source VARCHAR(255),  
    @sub_branch VARCHAR(255),  
    @payment_terms VARCHAR(7),  
    @service_level_description VARCHAR(255),  
    @alternative_identifier VARCHAR(15),  
    @tob_letter DATETIME,  
    @tps TINYINT,  
    @emps TINYINT,  
    @is_smoker TINYINT,  
    @tax_number VARCHAR(50),  
    @domiciled_for_tax TINYINT,  
    @tax_exempt TINYINT,  
    @tax_percentage FLOAT,  
    @risk_transfer_agreement BIT,  
    @GCTurnover VARCHAR(255),  
    @branch_address1 varchar(40),  
    @branch_address2 varchar(40) ,  
    @branch_address3 varchar(40),  
    @branch_address4 varchar(40),  
    @branch_postal_code varchar(20),  
    @Title varchar(255),  
    @Contact_Person varchar(255),  
    @First_Name varchar(255),  
    @lead_agent_cnt INT  
		
	IF ISNULL(@PartyCnt,0)=0 AND @DocumentRef<>''
	SELECT @PartyCnt = account_key FROM account a 
			INNER JOIN TransDetail td ON a.account_id=td.account_id
			INNER JOIN document d ON d.document_id=td.document_id 
			WHERE d.document_ref=@DocumentRef AND ISNULL(a.account_key,0)<>0 AND d.documenttype_id IN (22,23)
  
EXEC spu_wp_party  
    @PartyCnt,  
    @InsuranceFileCnt,  
    @ClaimCnt,  
    @party_type_code OUTPUT,  
    @party_type OUTPUT,  
    @shortname OUTPUT,  
    @name OUTPUT,  
    @resolved_name OUTPUT,  
    @currency_code OUTPUT,  
    @collect_type OUTPUT,  
    @accum_treatment_type OUTPUT,  
    @stats_treatment_type OUTPUT,  
    @party_category OUTPUT,  
    @agent_name OUTPUT,  
    @consultant_name OUTPUT,  
    @consultant_logic OUTPUT,  
    @created_by OUTPUT,  
    @date_created OUTPUT,  
    @last_modified OUTPUT,  
    @modified_by OUTPUT,  
    @payment_method_code OUTPUT,  
    @payment_term_code OUTPUT,  
    @credit_card_code OUTPUT,  
    @file_code OUTPUT,  
    @abc_count OUTPUT,  
    @statements OUTPUT,  
    @reminder_type OUTPUT,  
    @renewals OUTPUT,  
    @status OUTPUT,  
    @last_action_type OUTPUT,  
    @is_travel_agent OUTPUT,  
    @is_prospect OUTPUT,  
    @is_deleted OUTPUT,  
    @abi_code_on_406 OUTPUT,  
    @abi_code_on_81 OUTPUT,  
    @abi_codelist OUTPUT,  
    @area OUTPUT,  
    @invariant_key OUTPUT,  
    @record_status OUTPUT,  
    @CCJs OUTPUT,  
    @service_level_logic OUTPUT,  
    @loyalty_number OUTPUT,  
    @trading_name_party OUTPUT,  
    @source OUTPUT,  
    @sub_branch OUTPUT,  
    @payment_terms OUTPUT,  
    @service_level_description OUTPUT,  
    @alternative_identifier OUTPUT,  
    @tob_letter OUTPUT,  
    @tax_number OUTPUT,  
    @domiciled_for_tax OUTPUT,  
    @tax_exempt OUTPUT,  
    @tax_percentage OUTPUT,  
    @seasonal_gift OUTPUT,  
    @branch_address1  OUTPUT,  
    @branch_address2  OUTPUT,  
    @branch_address3 OUTPUT,  
    @branch_address4 OUTPUT,  
    @branch_postal_code OUTPUT  
  
IF @party_type_code = 'GC'  
BEGIN  
    EXEC spu_wp_party_group_client  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @party_group_type OUTPUT,  
        @is_registered_charity OUTPUT,  
        @charity_number OUTPUT,  
        @number_of_members OUTPUT,  
        @GCTurnover OUTPUT,  
        @contact OUTPUT  
END  
  
IF @party_type_code = 'CC'  
BEGIN  
    EXEC spu_wp_party_corporate_client  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @company_reg OUTPUT,  
        @trading_since_date OUTPUT,  
        @party_business OUTPUT,  
        @location OUTPUT,  
        @no_of_offices OUTPUT,  
        @no_of_employees OUTPUT,  
        @financial_year OUTPUT,  
        @trade_code OUTPUT,  
        @wage_roll OUTPUT,  
        @turnover OUTPUT,  
        @SIC_code OUTPUT,  
        @salutation OUTPUT,  
        @contact OUTPUT  
END  
  
Select @lead_agent_cnt = lead_agent_cnt FROM insurance_file WHERE insurance_file_cnt = @InsuranceFileCnt  
  

IF (@party_type_code = 'AG') or (@party_type_code = 'TR')  OR (ISNULL(@lead_agent_cnt,0) <>0 )  
BEGIN  
    EXEC spu_wp_party_agent  
        @lead_agent_cnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @agent_type OUTPUT,  
        @agent_origin OUTPUT,  
        @agency_agreement_date OUTPUT,  
        @agency_next_review_date OUTPUT,  
        @agency_account_number OUTPUT,  
        @is_branch OUTPUT,  
        @is_head_office OUTPUT,  
        @default_commission_percent OUTPUT,  
        @trading_name OUTPUT,  
        @binder_indicator OUTPUT,  
        @report_indicator OUTPUT,  
        @witholding_tax OUTPUT,  
        @Title OUTPUT,  
        @Contact_Person OUTPUT,  
        @First_Name OUTPUT  
END  
  
IF @party_type_code = 'CO'  
BEGIN  
    EXEC spu_wp_party_consultant  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @forename OUTPUT,  
        @initials OUTPUT,  
        @department OUTPUT,  
        @party_title_code OUTPUT  
END  
  
IF @party_type_code = 'AH'  
BEGIN  
    EXEC spu_wp_party_account_handler  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @forename OUTPUT,  
        @initials OUTPUT,  
        @department OUTPUT,  
        @party_title_code OUTPUT  
END  
  
IF @party_type_code = 'IN'  
BEGIN  
    EXEC spu_wp_party_insurer  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @agency_number OUTPUT,  
        @binder_indicator OUTPUT,  
        @report_indicator OUTPUT,  
        @is_reinsurer OUTPUT,  
        @reinsurance_type OUTPUT,  
        @is_reinsurance_debit_credit OUTPUT,  
        @default_comm_rate OUTPUT,  
        @risk_transfer_agreement OUTPUT  
END  
  
IF @party_type_code = 'PC'  
BEGIN  
    EXEC spu_wp_party_personal_client  
        @PartyCnt,  
        @InsuranceFileCnt,  
        @ClaimCnt,  
        @party_title_code OUTPUT,  
        @forename OUTPUT,  
        @initials OUTPUT,  
        @surname OUTPUT,  
        @employment_status_code OUTPUT,  
        @employer_name OUTPUT,  
        @employer_business OUTPUT,  
        @secondary_employment_status OUTPUT,  
        @secondary_employer_business OUTPUT,  
        @marital_status_code OUTPUT,  
        @number_of_children OUTPUT,  
        @nationality OUTPUT,  
        @mailshot OUTPUT,  
        @is_pet_owner OUTPUT,  
        @accommodation_type_code OUTPUT,  
        @salutation OUTPUT,  
        @trading_name_party OUTPUT,  
        @tps OUTPUT,  
        @emps OUTPUT,  
        @is_smoker OUTPUT  
END  
  
EXEC spu_wp_party_prospect  
    @PartyCnt,  
    @InsuranceFileCnt,  
    @ClaimCnt,  
    @agent_reference OUTPUT,  
    @current_intermediary OUTPUT,  
    @prospect_status OUTPUT  
  
SELECT  
    'party_type' = @party_type,  
    'shortname' = @shortname,  
    'name' = @name,  
    'resolved_name' = @resolved_name,  
    'currency_code' = @currency_code,  
    'collect_type' = @collect_type,  
    'accum_treatment_type' = @accum_treatment_type,  
    'stats_treatment_type' = @stats_treatment_type,  
    'party_category' = @party_category,  
    'agent_name' = @agent_name,  
    'consultant_name' = @consultant_name,  
    'consultant_logic' = REPLACE(@consultant_logic, ' ', ''),  
    'created_by' = @created_by,  
    'date_created' = @date_created,  
    'last_modified' = @last_modified,  
    'modified_by' = @modified_by,  
    'payment_method_code' = @payment_method_code,  
    'payment_term_code' = @payment_term_code,  
    'credit_card_code' = @credit_card_code,  
    'file_code' = @file_code,  
    'abc_count' = @abc_count,  
    'statements' = @statements,  
    'reminder_type' = @reminder_type,  
    'renewals' = @renewals,  
    'status' = @status,  
    'last_action_type' = @last_action_type,  
    'is_travel_agent' = @is_travel_agent,  
    'is_prospect' = @is_prospect,  
    'is_deleted' = @is_deleted,  
    'abi_code_on_406' = @abi_code_on_406,  
    'abi_code_on_81' = @abi_code_on_81,  
    'abi_codelist' = @abi_codelist,  
    'area' = @area,  
    'invariant_key' = @invariant_key,  
    'record_status' = @record_status,  
    'CCJs' = @CCJs,  
    'party_group_type' = @party_group_type,  
    'is_registered_charity' = @is_registered_charity,  
    'charity_number' = @charity_number,  
    'number_of_members' = @number_of_members,  
    'company_reg' = @company_reg,  
    'trading_since_date' = @trading_since_date,  
    'party_business' = @party_business,  
    'location' = @location,  
    'no_of_offices' = @no_of_offices,  
    'no_of_employees' = @no_of_employees,  
    'financial_year' = @financial_year,  
    'trade_code' = @trade_code,  
    'wage_roll' = @wage_roll,  
    'turnover' = @turnover,  
    'vat_code' = @tax_number,  
    'agent_type' = @agent_type,  
    'agent_origin' = @agent_origin,  
    'agency_agreement_date' = @agency_agreement_date,  
    'agency_next_review_date' = @agency_next_review_date,  
    'agency_account_number' = @agency_account_number,  
    'is_branch' = @is_branch,  
    'is_head_office' = @is_head_office,  
    'default_commission_percent' = @default_commission_percent,  
    'trading_name' = @trading_name,  
    'witholding_tax' = @witholding_tax,  
    'forename' = @forename,  
    'initials' = @initials,  
    'surname' = @surname,  
    'department' = @department,  
    'agency_number' = @agency_number,  
    'binder_indicator' = @binder_indicator,  
    'report_indicator' = @report_indicator,  
    'is_reinsurer' = @is_reinsurer,  
    'reinsurance_type' = @reinsurance_type,  
    'is_reinsurance_debit_credit' = @is_reinsurance_debit_credit,  
    'default_comm_rate' = @default_comm_rate,  
    'party_title_code' = @party_title_code,  
    'employment_status_code' = @employment_status_code,  
    'employer_name' = @employer_name,  
    'employer_business' = @employer_business,  
    'secondary_employment_status' = @secondary_employment_status,  
    'secondary_employer_business' = @secondary_employer_business,  
    'marital_status_code' = @marital_status_code,  
    'number_of_children' = @number_of_children,  
    'nationality' = @nationality,  
    'mailshot' = @mailshot,  
    'is_pet_owner' = @is_pet_owner,  
    'accommodation_type_code' = @accommodation_type_code,  
    'agent_reference' = @agent_reference,  
    'current_intermediary' = @current_intermediary,  
    'prospect_status' = @prospect_status,  
    'seasonal_gift' = @seasonal_gift,  
    'branch_address1'= @branch_address1 ,  
    'branch_address2'=@branch_address2 ,  
    'branch_address3'= @branch_address3 ,  
    'branch_address4'= @branch_address4 ,  
    'branch_postal_code'= @branch_postal_code ,  
    'SIC_code' = @SIC_code,  
    'previous_insurer' = @previous_insurer,  
    'previous_broker' = @previous_broker,  
    'service_level_logic' = REPLACE(@service_level_logic, ' ', ''),  
    'salutation' = @salutation,  
    'contact' = @Contact,  
    'loyalty_number' = @loyalty_number,  
    'trading_name_party' = @trading_name_party,  
    'source' = @source,  
    'sub_branch' = @sub_branch,  
    'payment_terms' = @payment_terms,  
    'service_level_description' = @service_level_description,  
    'alternative_identifier' = @alternative_identifier,  --PN7732  
    'tob_letter' = @tob_letter,  
    'tps' = @tps,  
    'emps' = @emps,  
    'is_smoker' = @is_smoker,  
    'tax_number' = @tax_number,  
    'domiciled_for_tax'  = @domiciled_for_tax,  
    'tax_exempt' = @tax_exempt,  
    'tax_percentage' = @tax_percentage,  
    'risk_transfer_agreement' = @risk_transfer_agreement,  
    'GCTurnover'=@GCTurnover,  
    'Title' =  @Title ,  
    'ContactPerson' = @Contact_person,  
    'FirstName' = @First_Name  


GO
