SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_wp_commercialcombined'
GO


CREATE PROCEDURE spu_wp_commercialcombined
    @PartyCnt INT,
    @InsuranceFileCnt INT,
    @ClaimCnt INT,
    @DocumentRef VARCHAR(25),
    @Instance1 INT,
    @Instance2 INT,
    @Instance3 INT,
    @is_fire_damage TINYINT OUTPUT,
    @fd_buildings_sum NUMERIC,
    @fd_stock_and_materials NUMERIC,
    @is_all_risks TINYINT OUTPUT,
    @ar_buildings_sum NUMERIC,
    @landlord_f_and_f_sum NUMERIC,
    @stock_in_trade_sum NUMERIC,
    @property_sum_insured NUMERIC,
    @is_burglary TINYINT OUTPUT,
    @machinery_sum_insured NUMERIC,
    @b_stock_and_materials NUMERIC,
    @s_i_t_tobacco NUMERIC,
    @s_i_t_alcohol NUMERIC,
    @s_i_t_radio NUMERIC,
    @s_i_t_non_ferrous NUMERIC,
    @is_business_interruption TINYINT OUTPUT,
    @gross_profit_sum NUMERIC,
    @maximum_indemnity_period INT OUTPUT,
    @is_glass TINYINT OUTPUT,
    @glass_type INT OUTPUT,
    @glass_cover_amount NUMERIC,
    @is_employers_liability TINYINT OUTPUT,
    @e_indemnity_limit NUMERIC,
    @e_description VARCHAR(255),
    @wages_and_salaries NUMERIC,
    @is_public_liability TINYINT OUTPUT,
    @pl_indemnity_limit NUMERIC,
    @pl_description VARCHAR(255),
    @pl_rating_basis VARCHAR(255),
    @pl_excess NUMERIC,
    @is_money_and_assault TINYINT OUTPUT,
    @ma_cards_limit NUMERIC,
    @ma_not_locked NUMERIC,
    @ma_locked NUMERIC,
    @ma_premises NUMERIC,
    @ma_any_other NUMERIC,
    @ma_insured_persons INT OUTPUT,
    @ma_compensation_amount NUMERIC,
    @is_goods_in_transit TINYINT OUTPUT,
    @git_make_of_vehicle VARCHAR(255),
    @git_registration_number VARCHAR(255),
    @git_tools_limit NUMERIC,
    @git_liability_limit NUMERIC,
    @git_retained_liability NUMERIC,
    @is_personal_accident TINYINT OUTPUT,
    @pa_insured_person VARCHAR(255),
    @pa_age INT OUTPUT,
    @pa_duties VARCHAR OUTPUT,
    @pa_compensation NUMERIC,
    @is_supp_all_risks TINYINT OUTPUT,
    @sar_property_insured VARCHAR(255),
    @sar_sum_insured NUMERIC,
    @sar_liability_limit NUMERIC,
    @is_engineering TINYINT OUTPUT,
    @e_property_insured VARCHAR(255),
    @e_cover NUMERIC,
    @e_liability_limit NUMERIC,
    @e_excess NUMERIC,
    @is_frozen_food TINYINT OUTPUT,
    @ff_unit_description VARCHAR(255),
    @ff_date_of_make DATETIME OUTPUT,
    @ff_sum_insured NUMERIC,
    @ff_liability_limit NUMERIC
AS


SELECT
    @is_fire_damage = commercial_combined.is_fire_damage,
    @fd_buildings_sum = commercial_combined.fd_buildings_sum,
    @fd_stock_and_materials = commercial_combined.fd_stock_and_materials,
    @is_all_risks = commercial_combined.is_all_risks,

    @ar_buildings_sum = commercial_combined.ar_buildings_sum,
    @landlord_f_and_f_sum = commercial_combined.landlord_f_and_f_sum,
    @stock_in_trade_sum = commercial_combined.stock_in_trade_sum,
    @property_sum_insured = commercial_combined.property_sum_insured,
    @is_burglary = commercial_combined.is_burglary,
    @machinery_sum_insured = commercial_combined.machinery_sum_insured,
    @b_stock_and_materials = commercial_combined.b_stock_and_materials,
    @s_i_t_tobacco = commercial_combined.s_i_t_tobacco,
    @s_i_t_alcohol = commercial_combined.s_i_t_alcohol,
    @s_i_t_radio = commercial_combined.s_i_t_radio,
    @s_i_t_non_ferrous = commercial_combined.s_i_t_non_ferrous,
    @is_business_interruption = commercial_combined.is_business_interruption,
    @gross_profit_sum = commercial_combined.gross_profit_sum,
    @maximum_indemnity_period = commercial_combined.maximum_indemnity_period,
    @is_glass = commercial_combined.is_glass,
    @glass_type = commercial_combined.glass_type,
    @glass_cover_amount = commercial_combined.glass_cover_amount,
    @is_employers_liability = commercial_combined.is_employers_liability,
    @e_indemnity_limit = commercial_combined.e_indemnity_limit,
    @e_description = commercial_combined.e_description,
    @wages_and_salaries = commercial_combined.wages_and_salaries,
    @is_public_liability = commercial_combined.is_public_liability,
    @pl_indemnity_limit = commercial_combined.pl_indemnity_limit,
    @pl_description = commercial_combined.pl_description,
    @pl_rating_basis = commercial_combined.pl_rating_basis,

    @pl_excess = commercial_combined.pl_excess,
    @is_money_and_assault = commercial_combined.is_money_and_assault,
    @ma_cards_limit = commercial_combined.ma_cards_limit,
    @ma_not_locked = commercial_combined.ma_not_locked,
    @ma_locked = commercial_combined.ma_locked,
    @ma_premises = commercial_combined.ma_premises,
    @ma_any_other = commercial_combined.ma_any_other,
    @ma_insured_persons = commercial_combined.ma_insured_persons,
    @ma_compensation_amount = commercial_combined.ma_compensation_amount,
    @is_goods_in_transit = commercial_combined.is_goods_in_transit,
    @git_make_of_vehicle = commercial_combined.git_make_of_vehicle,
    @git_registration_number = commercial_combined.git_registration_number,
    @git_tools_limit = commercial_combined.git_tools_limit,
    @git_liability_limit = commercial_combined.git_liability_limit,
    @git_retained_liability = commercial_combined.git_retained_liability,
    @is_personal_accident = commercial_combined.is_personal_accident,
    @pa_insured_person = commercial_combined.pa_insured_person,
    @pa_age = commercial_combined.pa_age,
    @pa_duties = commercial_combined.pa_duties,
    @pa_compensation = commercial_combined.pa_compensation,
    @is_supp_all_risks = commercial_combined.is_supp_all_risks,
    @sar_property_insured = commercial_combined.sar_property_insured,
    @sar_sum_insured = commercial_combined.sar_sum_insured,
    @sar_liability_limit = commercial_combined.sar_liability_limit,
    @is_engineering = commercial_combined.is_engineering,
    @e_property_insured = commercial_combined.e_property_insured,
    @e_cover = commercial_combined.e_cover,
    @e_liability_limit = commercial_combined.e_liability_limit,
    @e_excess = commercial_combined.e_excess,
    @is_frozen_food = commercial_combined.is_frozen_food,
    @ff_unit_description = commercial_combined.ff_unit_description,
    @ff_date_of_make = commercial_combined.ff_date_of_make,
    @ff_sum_insured = commercial_combined.ff_sum_insured,
    @ff_liability_limit = commercial_combined.ff_liability_limit
FROM commercial_combined
WHERE commercial_combined.insurance_file_cnt = @insurancefilecnt
GO


