namespace SSP.PureInsuranceRestAPIHandler.Enums
{
    public enum SystemOption
    {
        DMEInstalled = 10,
        DuplicateClaimCheck = 5002,
        InclusionOfCoinsuranceOnClaims = 1015,
        AllowNegativeReserve = 1016,
        ClaimHandlerAcknowlegedTaskAllowedTime = 1017,
        ClaimHandlerPreliminaryReportTaskAllowedTime = 1018,
        ClaimTaskGroup = 1019,
        ClaimUserGroup = 1020,
        PrintRenewalSchedule = 1036,
        PrintRenewalCertificate = 1037,
        PrintRenewalDebitNote = 1038,
        ClaimPaymentAuthority = 2020,
        ClaimPaymentIsGross = 5018,
        AdvanceTaxScriptEnabled = 5007,
        GenerateClaimDocumentRILimit = 1014,
        DirectBusinessReturnPremiumUserGroup = 5051,
        AgentBusinessReturnPremiumUserGroup = 5055,
        ClaimPaymentWorkflow = 5017,
        EnhancedResolvedName = 5148,
        DisableWildcardSearch = 5065,
        EnablePartialWildcardSearch = 5066,
        SalvageAndTPRecoveryReservesExcludeTax = 5067,
        CreditCardProcessingMethod = 5069,
        CancelInstalmentPlanonPolicyCancellation = 5076,
        EnableAgentProductLink = 5088,
        AddressLookupInstallation = 13,
        QuoteVersioning = 5089,
        UserAttemptCount = 5107,
        PasswordStrengthRegularExpression = 5101,
        SingleCashListItemPerAllocation = 5087,
        DisableTempMTAs = 5116,
        EnableExclusiveLocking = 5174,
        DocumentProductionInHouseOrCCM = 5163,
        IsKCMApplicableForSelectedDocument = 5207,
        IsSharepointOnline = 5177,
        ChequeProductionEnabled = 60,
        AllowClientPolicyAssociations = 5182,
        DefaultReceiptDocument = 61,
        DefaultPaymentDocument = 63,
        OnlyAllowClaimClosureWhenReserveIsZero = 5073,
        KCMApplicableForSelectedTemplate = 5207,
        AutoAllocateCancelFromInception = 5246,
        AutoAllocateCancelToleranceDays = 5247,
        AutoAllocateCancelToleranceAmount = 5248
    }
}
