namespace SSP.PureInsuranceRestAPIHandler.Enums
{
    public enum UserAuthorityOptions
    {
        HasUnrestrictedEnquiry = 0,
        HasUnrestrictedUpdate = 1,
        HasWriteOffAuthority = 2,
        HasPaymentsAuthority = 3,
        CanOverridePrePolicyDate = 4,
        CanOverridePrePolicyRate = 5,
        CanOverrideDate = 6,
        CanOverrideRate = 7,
        CanDuplicateClaimOverride = 8,
        CanOverridePostingPeriod = 9,
        CanPerformBrokerTransfer = 10,
        HasClaimPaymentsAuthority = 11,
        CanUserChangeReserves = 12,
        CanMakeLiveInvoice = 13,
        CanMakeLivePayNow = 14,
        CanMakeLiveInstalments = 15,
        HasPaynowWriteOffAuthority = 16,
        AllowAddRemoveRatingSections = 17,
        AllowEditRatingSections = 18,
        CanOverrideCollectionDate = 19,
        CanMakeLiveBankGuarantee = 20,
        AllowEditAgentCommission = 21,
        CanMakeLiveCashDeposit = 22,
        BackDatedMtaAndMtcAuthorityType = 23,
        IsRecommender = 24,
        RecommenderCurrencyKey = 25,
        RecommenderCurrencyAmount = 26,
        DisplayReinsurance = 27,
        DisplayClaimReinsurance = 28,
        IsClientManagerViewonly = 29,
        AllowReverseAllocation = 30,
        EditDefaultCommissionNBRN = 31,
        EditDefaultCommissionMTA = 32,
        EditDefaultCommissionMTC = 33,
        EditDefaultCommissionMTR = 34,
        AgentEditableDuringMTAMTC = 35,
        AllowReverseReceipt = 36,
        CanChangeInstalmentDefaultCurrency = 182,
        CanUpdateInstalmentStatus = 183,
        CanUpdateInstalmentDueDate = 184,
        EditInstalmentNoOfDays = 185,
        HasManualJournalAuthority = 186
    }
}
