SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO
EXEC DDLDropProcedure 'spu_sir_scheduled_reports_detail_sel'
GO
CREATE  PROCEDURE spu_sir_scheduled_reports_detail_sel	
	@report_scheduler_id INT	
AS  
DECLARE 
@StartDate DATETIME,
@EndDate DATETIME,
@Is_Period INT,--Flag used for seperating Simple End_Date and Period_End_Date 
@Is_Auto INT,--Flag used for Auto Update of Start Date and End Date
@PName_StartDate VARCHAR(50),--For Storing Start Parameter Name
@PName_EndDate VARCHAR(50),----For Storing End Parameter Name
@Frequency VARCHAR(50),--For Storing Frequency
@Is_UpdateStartDate INT,--Flag used for Auto Update of Start Date 
@Is_UpdateEndDate INT --Flag used for Auto Update of  End Date

--CHECKING FREQUENCY OF REPORT
SELECT @Frequency=UPPER(FREQUENCY) 
FROM REPORT_SCHEDULER 
WHERE REPORT_SCHEDULER_ID=@REPORT_SCHEDULER_ID

--CHECKING PARAMETER NAME(PERIOD END DATE/NORMAL END DATE)
SELECT @Is_Period=Count(*)  
FROM REPORT_SCHEDULER_PARAMETERS 
WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID
AND PATINDEX('%PERIOD%',UPPER(PARAMETER_NAME))>0 AND PATINDEX('%END%',UPPER(PARAMETER_NAME))>0

IF @Is_Period>0--User Period Table
	BEGIN
		SELECT @PName_StartDate=UPPER(PARAMETER_NAME)   
		FROM REPORT_SCHEDULER_PARAMETERS 
		WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND 
		PATINDEX('%PERIOD%',UPPER(PARAMETER_NAME))>0 AND 
		PATINDEX('%START%',UPPER(PARAMETER_NAME))>0

		SELECT @PName_EndDate=UPPER(PARAMETER_NAME)   
		FROM REPORT_SCHEDULER_PARAMETERS 
		WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND 
		PATINDEX('%PERIOD%',UPPER(PARAMETER_NAME))>0 AND 
		PATINDEX('%END%',UPPER(PARAMETER_NAME))>0
	END
ELSE--Use Normal Calulation
	BEGIN
		SELECT @PName_StartDate=UPPER(PARAMETER_NAME)   
		FROM REPORT_SCHEDULER_PARAMETERS 
		WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND 
		PATINDEX('%PERIOD%',UPPER(PARAMETER_NAME))=0 AND 
		PATINDEX('%START%',UPPER(PARAMETER_NAME))>0 AND
		PATINDEX('%DATE%',UPPER(PARAMETER_NAME))>0
		
		SELECT @PName_EndDate=UPPER(PARAMETER_NAME)   
		FROM REPORT_SCHEDULER_PARAMETERS 
		WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND 
		PATINDEX('%PERIOD%',UPPER(PARAMETER_NAME))=0 AND 
		PATINDEX('%END%',UPPER(PARAMETER_NAME))>0 AND
		PATINDEX('%DATE%',UPPER(PARAMETER_NAME))>0
	END

---CHECKING AUTO INCREMENT FLAG
SELECT TOP 1 @Is_Auto=IS_AUTOMATIC 
FROM REPORT_SCHEDULER_PARAMETERS 
WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND 
(UPPER(PARAMETER_NAME) =@PName_StartDate OR 
 UPPER(PARAMETER_NAME) =@PName_EndDate)


 SELECT TOP 1 @Is_UpdateStartDate=IS_AUTOMATIC
FROM REPORT_SCHEDULER_PARAMETERS
WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND
(UPPER(PARAMETER_NAME) =@PName_StartDate)

SELECT TOP 1 @Is_UpdateEndDate=IS_AUTOMATIC
FROM REPORT_SCHEDULER_PARAMETERS
WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND
(UPPER(PARAMETER_NAME) =@PName_EndDate)

-----Calulation from period table
IF @Is_Period>0 
	BEGIN
		SELECT TOP 1 @EndDate=PERIOD_END_DATE 
		FROM PERIOD WHERE PERIOD_END_DATE<GETDATE() ORDER BY PERIOD_END_DATE DESC

		IF @Frequency='DAILY' OR @Frequency='MONTHLY'
		BEGIN	
			SELECT TOP 1 @StartDate=PERIOD_END_DATE FROM PERIOD WHERE 
			PERIOD_END_DATE<@ENDDATE ORDER BY PERIOD_END_DATE DESC
		END
		IF @Frequency='ANNUALLY'
		BEGIN	
			SELECT TOP 1 @StartDate=PERIOD_END_DATE FROM (SELECT TOP 12 PERIOD_END_DATE FROM
			PERIOD WHERE PERIOD_END_DATE<@EndDate ORDER BY PERIOD_END_DATE DESC) A
			ORDER BY PERIOD_END_DATE ASC
		END
	END
ELSE---Normal Calulation
---Calculating Start date manually from current date as [end date]
	BEGIN
		SELECT @EndDate=GETDATE()
		
		IF @Frequency='DAILY'
		BEGIN	
			SELECT @StartDate=@EndDate
		END
		
		IF @Frequency='MONTHLY'
		BEGIN	
			SELECT @StartDate=DATEADD(MONTH,-1,@EndDate)
		END
		
		IF @Frequency='ANNUALLY'
		BEGIN	
			SELECT @StartDate=DATEADD(YEAR,-1,@EndDate)
		END
	END

--UPDATE IF AUTO UPDATE IS ON=1
IF @Is_UpdateStartDate=1
BEGIN
  --Updating Start Date
	UPDATE REPORT_SCHEDULER_PARAMETERS SET DEFAULT_VALUE=CONVERT(VARCHAR,@StartDate,106)
	WHERE UPPER(PARAMETER_NAME)=@PName_StartDate
	AND REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND IS_AUTOMATIC=1
END

IF @Is_UpdateEndDate=1
BEGIN
   --Updating END Date
	UPDATE REPORT_SCHEDULER_PARAMETERS SET DEFAULT_VALUE=CONVERT(VARCHAR,@EndDate,106)
	WHERE UPPER(PARAMETER_NAME)=@PName_EndDate
	AND REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID AND IS_AUTOMATIC=1
END
----------------------- 
SELECT REPORT_SCHEDULER_PARAMETER_ID,
REPORT_SCHEDULER_ID,
PARAMETER_NAME,
DEFAULT_VALUE,
DATA_TYPE,PROMPT,
CURRENTID_VALUE,
PARTY_SEARCH,
EMPTY,
IS_AUTOMATIC 
FROM REPORT_SCHEDULER_PARAMETERS
WHERE REPORT_SCHEDULER_ID = @REPORT_SCHEDULER_ID
ORDER BY REPORT_SCHEDULER_PARAMETER_ID

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO