SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS ON 
GO

Execute DDLDropProcedure 'spu_tax_band_rate_add'
GO

CREATE PROCEDURE spu_tax_band_rate_add
    @tax_band_id int,
    @tax_band_rate_id int output,
    @code char(10),
    @caption_id int,
    @description varchar(255),
    @effective_date datetime,
    @is_deleted tinyint,
    @is_value tinyint,
    @rate float, 
    @Calc_basis int, 
    @Basis_value money, 
    @NB tinyint,
    @AMTA tinyint, 
    @RMTA tinyint, 
    @CANC tinyint, 
    @REN tinyint,
    @sum_insured_rounded tinyint,
    @currency_id smallint,
    @allow_tax_credit tinyint,
    @country_id int,
    @state_id int,
    @class_of_business_id int,
    @TTRI tinyint,
    @TTRIC tinyint,
    @TTAC tinyint,
    @TTF tinyint,
    @TTCP tinyint,
    @TTCS tinyint,
    @TTCR tinyint,
    @TTIC tinyint,
    @TTI tinyint,
    @MTA_threshold_date datetime,
    @Is_passed_to_insurer tinyint,
    @TTE tinyint,
    @risk_group_id int,
    @risk_code_id int,
    @COB_rating_section_id int,
    @use_for_refund_when_expired tinyint,
    @use_for_backdated_nb tinyint,
    @nTTRIPR TINYINT,
	@userid INT = NULL,
	@uniqueid VARCHAR(50) = NULL,
	@screenhierarchy VARCHAR(100) = NULL
AS

    -- Ensure correct caption id
    EXEC spu_pm_caption_id_return 1, @description, @caption_id Output

    -- Get next id
    --SELECT @tax_band_rate_id = ISNULL(MAX(tax_band_rate_id), 0) + 1
    --FROM    tax_band_rate
	SELECT @screenhierarchy=@screenhierarchy + ' / ' + @description + ' / ' + CAST(convert(date,@effective_date,103) AS VARCHAR)

    -- Insert new row
    INSERT INTO tax_band_rate (
        tax_band_id,
        code,
        caption_id,
        description,
        effective_date,
        is_deleted,
        is_value,
        rate, 
        calc_basis, 
        Basis_value, 
        NB, 
        AMTA, 
        RMTA, 
        CANC, 
        REN,
        sum_insured_rounded,
        currency_id,
        allow_tax_credit,
        country_id,
        state_id,
        class_of_business_id,
        TTRI,
        TTRIC,
        TTAC,
        TTF,
        TTCP,
        TTCS,
        TTCR,
        TTIC,
        TTI,
        MTA_Threshold_date,
        Is_passed_to_insurer,
        TTE,
    	risk_group_id,
    	risk_code_id,
        COB_rating_section_id,
        use_for_refund_when_expired,
        use_for_backdated_nb,
        TTRIPR,
		userid,
	    uniqueid ,
	    screenhierarchy)
    VALUES (
        @tax_band_id,
        @code,
        @caption_id,
        @description,
        @effective_date,
        @is_deleted,
        @is_value,
        @rate, 
        @calc_basis, 
        @Basis_value, 
        @NB, 
        @AMTA, 
        @RMTA, 
        @CANC, 
        @REN,
        @sum_insured_rounded,
        @currency_id,
        @allow_tax_credit,
        @country_id,
        @state_id,
        @class_of_business_id,
        @TTRI,
        @TTRIC,
        @TTAC,
        @TTF,
        @TTCP,
        @TTCS,
        @TTCR,
        @TTIC,
        @TTI,
        @MTA_Threshold_date,
        @Is_passed_to_insurer,
        @TTE,
    	@risk_group_id,
    	@risk_code_id,
    	@COB_rating_section_id,
        @use_for_refund_when_expired,
        @use_for_backdated_nb,
        @nTTRIPR,
		@userid,
	    @uniqueid ,
	    @screenhierarchy)

SET @tax_band_rate_id=@@IDENTITY

GO
