SET QUOTED_IDENTIFIER OFF 
SET ANSI_NULLS ON
GO

EXECUTE DDLDropProcedure 'spu_Transdetail_Add'
GO

CREATE PROCEDURE spu_Transdetail_Add    
    @transdetail_id Int OUTPUT,    
    @account_id Int,    
    @postingstatus_id SmallInt,    
    @company_id Int, 
    @sub_branch_id int,   
    @currency_id SmallInt, 
    @period_id Int,   
    @document_id Int,    
    @document_sequence SmallInt,    
    @accounting_date DateTime,    
    @amount numeric(19,4),    
    @base_amount_unrounded numeric(19,4),    
    @fully_matched bit,    
    @currency_amount numeric(19,4),    
    @currency_amount_unrounded numeric(19,4),    
    @currency_base_xrate numeric(19,4),  
    @operator_Id SmallInt,    
    @amount_currency_id SmallInt,    
    @account_currency_id SmallInt,    
    @account_amount Money,    
    @account_amount_unrounded Money,    
    @account_base_xrate float,    
    @system_currency_id SmallInt,    
    @system_amount Money,    
    @system_amount_unrounded Money,    
    @system_base_xrate float,  
    @outstanding_amount Money,  
    @outstanding_currency_amount Money,  
    @outstanding_account_amount Money  
AS    
INSERT INTO transdetail    
   (account_id,    
    postingstatus_id,    
    company_id, 
    sub_branch_id,   
    currency_id,
    period_id,    
    document_id,    
    document_sequence,    
    accounting_date,    
    amount,    
    base_amount_unrounded,    
    fully_matched,    
    currency_amount,    
    currency_amount_unrounded,    
    currency_base_xrate,  
    operator_Id,    
    amount_currency_id,    
    account_currency_id,    
    account_amount,    
    account_amount_unrounded,    
    account_base_xrate,    
    system_currency_id,    
    system_amount,    
    system_amount_unrounded,    
    system_base_xrate,  
    outstanding_amount,  
    outstanding_currency_amount,  
    outstanding_account_amount)    
VALUES    
   (@account_id,    
    @postingstatus_id,    
    @company_id,
    @sub_branch_id,    
    @currency_id,
    @period_id,    
    @document_id,    
    @document_sequence,    
    @accounting_date,    
    @amount,    
    @base_amount_unrounded,    
    @fully_matched,    
    @currency_amount,    
    @currency_amount_unrounded,    
    @currency_base_xrate,  
    @operator_Id,    
    @amount_currency_id,    
    @account_currency_id,    
    @account_amount,    
    @account_amount_unrounded,    
    @account_base_xrate,    
    @system_currency_id,    
    @system_amount,    
    @system_amount_unrounded,    
    @system_base_xrate,  
    @outstanding_amount,  
    @outstanding_currency_amount,  
    @outstanding_account_amount)    
    
SELECT @transdetail_id=@@IDENTITY    
GO
