using SSP.PureInsuranceRestAPIHandler.Enums;
using System.Collections.Generic;

namespace SSP.PureInsuranceRestAPIHandler.BaseClasses
{
    public class BaseGetHeaderAndSummariesResponseType : BasePagedResponse
    {
        public int PartyKey { get; set; }
        public System.DateTime CoverStartDate { get; set; }
        public System.DateTime CoverEndDate { get; set; }
        public string Description { get; set; }
        public string ProductCode { get; set; }
        public int InsuranceFolderKey { get; set; }
        public int InsuranceFileKey { get; set; }
        public string InsuranceFileRef { get; set; }
        public System.DateTime QuoteExpiryDate { get; set; }
        public byte[] QuoteTimeStamp { get; set; }
        public bool QuoteIsLocked { get; set; }
        public List<BaseGetHeaderAndSummariesResponseTypeRow> Risks { get; set; }
        public string SubBranchCode { get; set; }
        public bool ConsolidatedLeadAgentCommission { get; set; }
        public bool ConsolidatedLeadAgentCommissionSpecified { get; set; }
        public bool ConsolidatedSubAgentCommission { get; set; }
        public bool ConsolidatedSubAgentCommissionSpecified { get; set; }
        public string CurrencyCode { get; set; }
        public double ThisPremium { get; set; }
        public bool ThisPremiumSpecified { get; set; }
        public double AnnualPremium { get; set; }
        public bool AnnualPremiumSpecified { get; set; }
        public double NetPremium { get; set; }
        public bool NetPremiumSpecified { get; set; }
        public double TaxAmount { get; set; }
        public bool TaxAmountSpecified { get; set; }
        public BaseTaxesAndFeesType PolicyLevelTaxesAndFees { get; set; }
        public string AlternativeRef { get; set; }
        public string InsuredName { get; set; }
        public string ProductName { get; set; }
        public string BranchCode { get; set; }
        public string Regarding { get; set; }
        public string PolicyStatusCode { get; set; }
        public string AnalysisCode { get; set; }
        public string BusinessTypeCode { get; set; }
        public System.DateTime InceptionDt { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public string PolicyTypeCode { get; set; }
        public System.DateTime InceptionTPI { get; set; }
        public System.DateTime IssueDate { get; set; }
        public bool IssueDateSpecified { get; set; }
        public System.DateTime ProposalDate { get; set; }
        public bool ProposalDateSpecified { get; set; }
        public string RenewalFrequencyCode { get; set; }
        public System.DateTime LTUExpiryDate { get; set; }
        public bool LTUExpiryDateSpecified { get; set; }
        public string StopReasonCode { get; set; }
        public int RenewedCount { get; set; }
        public string RenewalMethodCode { get; set; }
        public string LapsedReasonCode { get; set; }
        public System.DateTime LapseDate { get; set; }
        public bool LapseDateSpecified { get; set; }
        public bool ReferredAtRenewal { get; set; }
        public bool ReferredOnMTA { get; set; }
        public string StandardPolicyWordingCode { get; set; }
        public string StandardPolicyDescription { get; set; }
        public string PolicyStyleCode { get; set; }
        public string AccountHandlerCode { get; set; }
        public string AccountHandler { get; set; }
        public int? AccountHandlerCnt { get; set; }
        public bool AccountHandlerCntSpecified { get; set; }
        public string RenewalStatusTypeCode { get; set; }
        public string RenewalStatusTypeDesc { get; set; }
        public int LeadAgentKey { get; set; }
        public string LeadAgentCode { get; set; }
        public string LeadAgent { get; set; }
        public System.DateTime HCExpiryDate { get; set; }
        public string PolicyDeductible { get; set; }
        public string PolicyLimits { get; set; }
        public string UnderwritingYear { get; set; }
        public bool MarkedForCollection { get; set; }
        public int BaseInsuranceFolderKey { get; set; }
        public QuoteStatusType QuoteStatusKey { get; set; }
        public int QuoteVersion { get; set; }
        public int ContactuserKey { get; set; }
        public string ContactUserName { get; set; }
        public int IsDeletedContactuser { get; set; }
        public string ContactUserFullName { get; set; }
        public string ContactUserEmail { get; set; }
        public bool PutOnNextMTAInstallmentRenewal { get; set; }
        public bool AnniversaryCopy { get; set; }
        public int RenewalDayNo { get; set; }
        public int UnderwritingYearId { get; set; }
        public string OldPolicyNumber { get; set; }
        public bool IsValidAnniversaryToAccept { get; set; }
        public bool IsMigratedPolicy { get; set; }
        public bool IsPolicyInAnnualRenewal { get; set; }
        public bool IsPolicyInRenewal { get; set; }
        public System.DateTime AnniversaryDate { get; set; }
        public bool AnniversaryDateSpecified { get; set; }
        public string CorrespondenceType { get; set; }
        public string DefaultPreferredCorrespondence { get; set; }
        public bool IsAgentReceiveCorrespondence { get; set; }
        public bool IsMarketPlacePolicy { get; set; }
        public string DefaultPaymentMethod { get; set; }
        public string BranchName { get; set; }
        public int DefaultInstalmentPlan { get; set; }
        public int DefaultInstalmentPlanVersion { get; set; }
        public int DefaultSchemeNumber { get; set; }
        public int DefaultSchemeVersion { get; set; }
        public int OriginalInsuranceFileKey { get; set; }
        public int OriginalPremiumFinanceCnt { get; set; }
        public int OriginalPremFinanceVersion { get; set; }
        public int ActivePlans { get; set; }
        public System.DateTime SavedPreferredDate { get; set; }
        public int MtaReasonId { get; set; }
        public int SavedDayInMonth { get; set; }
        public string Frequency { get; set; }
        public string MtaReasonCode { get; set; }
        public int DefaultPFRF_Id { get; set; }
        public string SenderEmail { get; set; }
        public string ReceiverEmail { get; set; }
        public string LapsedReasonDescription { get; set; }
        public string RenewalStatusTypeDescription { get; set; }
        public string InsuranceFileType { get; set; }
        public int? CollectionFrequency { get; set; }
        public int? PaymentTerms { get; set; }
        public System.DateTime PolicyStartDate { get; set; }
        public System.DateTime PolicyEndDate { get; set; }
        public string CoverNoteBookNumber { get; set; }
        public int CoverNoteSheetNumber { get; set; }
        public List<GetHeaderAndSummariesByKeyResponseTypeRow> InsuredParties { get; set; }
        public string CoInsurancePlacement { get; set; }
        public int BaseCurrencyID { get; set; }
        public int TransCurrencyID { get; set; }
        public bool HasClaimLink { get; set; }
        public string InsuranceFileTypeCode { get; set; }

    }
}
