using SSP.PureInsuranceRestAPIHandler.Enums;

namespace SSP.PureInsuranceRestAPIHandler.BaseClasses
{
    public class BasePremiumFinancePlanHistoryType
    {
        //[DBCol("AutoGeneratedPlanRef")]
        public string AutoGeneratedPlanRef { get; set; }
        //[DBCol("amounttofinance")]
        public double FinanceAmount { get; set; }
        //[DBCol("pfPrem_finance_cnt")]
        public int PFPremiumFinanceKey { get; set; }
        //[DBCol("pfPrem_finance_version")]
        public int PFPremiumFinanceVersionKey { get; set; }
        //[DBCol("StartDate")]
        public System.DateTime StartDate { get; set; }
        public FinancePlanStatus StatusInd { get; set; }
        //[DBCol("TotalCost")]
        public double TotalCost { get; set; }
    }
}
