namespace SSP.PureInsuranceRestAPIHandler.BaseClasses
{
    public class BaseTransactResponseTypePolicyMultiplePolicies
    {
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
        public string AutoGeneratedPlanRef { get; set; }
        public decimal CommissionAmount { get; set; }
        public int DepositTransDetailID { get; set; }
        public string DocumentComment { get; set; }
        public string PolicyRef { get; set; }
        public decimal PremiumDueGross { get; set; }
        public decimal PremiumDueNet { get; set; }
        public decimal PremiumDueTax { get; set; }
        public decimal TotalAnnualTax { get; set; }
    }
}
