EXECUTE DDLDropProcedure 'spu_add_stats_details_Reverse'
GO
SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS ON
GO

CREATE PROCEDURE spu_add_stats_details_Reverse
@nNewStatsFolderCnt INT,
@nInsuranceFileCnt INT

AS
BEGIN
DECLARE @nOldStatsFolderCnt INT

SELECT TOP 1 @nOldStatsFolderCnt=stats_folder_cnt FROM stats_folder WHERE insurance_file_cnt=@nInsuranceFileCnt ANd document_ref like 'S%' order by stats_folder_cnt

INSERT INTO stats_detail 
(stats_folder_cnt,
stats_detail_id,
stats_detail_type,
risk_id,
risk_type_id,
risk_type_code,
peril_id,
peril_description,
peril_type_id,
peril_type_code,
policy_section_type_id,
policy_section_type_code,
class_of_business_id,
class_of_business_code,
tax_type_id,
tax_type_code,
tax_value,
ri_party_cnt,
ri_shortname,
ri_party_type,
ri_share_percent,
ri_agreement_code,
annual_premium,
currency_code,
currency_rate,
this_premium_original,
this_premium_home,
commission_percent,
lead_commission_value_home,
sub_commission_value_home,
sum_insured_home,
sum_insured_currency_code,
sum_insured_change,
transaction_ledger_id,
transaction_account_id,
account_type_code,
ceded_ref,
cover_share_percent,
sum_insured_total,
charges_total,
taxes_total,
recoveries_total,
commission_excluded,
withholding_tax_excluded,
purchase_order_no,
purchase_invoice_no,
stats_version,
this_premium_system,
lead_commission_value_system,
sub_commission_value_system,
sum_insured_system,
is_commission_modified,
original_flag,
cover_to_date,
Claim_RI_Only_Amendment,
Earning_Pattern_id,
ri_arrangement_line_Id)

SELECT @nNewStatsFolderCnt,
stats_detail_id,
stats_detail_type,
risk_id,
risk_type_id,
risk_type_code,
peril_id,
peril_description,
peril_type_id,
peril_type_code,
policy_section_type_id,
policy_section_type_code,
class_of_business_id,
class_of_business_code,
tax_type_id,
tax_type_code,
-1*tax_value,
ri_party_cnt,
ri_shortname,
ri_party_type,
ri_share_percent,
ri_agreement_code,
-1*annual_premium,
currency_code,
currency_rate,
-1*this_premium_original,
-1*this_premium_home,
commission_percent,
-1*lead_commission_value_home,
-1*sub_commission_value_home,
-1*sum_insured_home,
sum_insured_currency_code,
-1*sum_insured_change,
transaction_ledger_id,
transaction_account_id,
account_type_code,
ceded_ref,
cover_share_percent,
-1*sum_insured_total,
charges_total,
taxes_total,
recoveries_total,
commission_excluded,
withholding_tax_excluded,
purchase_order_no,
purchase_invoice_no,
stats_version,
-1*this_premium_system,
-1*lead_commission_value_system,
-1*sub_commission_value_system,
-1*sum_insured_system,
is_commission_modified,
original_flag,
cover_to_date,
Claim_RI_Only_Amendment,
Earning_Pattern_id,
ri_arrangement_line_Id FROM stats_detail WHERE stats_folder_cnt=@nOldStatsfolderCnt
END