'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iCLMRiskDetails.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Risk related details.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Peril Details.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Comments.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - General Details.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comments.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress status.
        '''</summary>
        Friend ReadOnly Property str1206() As String
            Get
                Return ResourceManager.GetString("str1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property str1207() As String
            Get
                Return ResourceManager.GetString("str1207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend ReadOnly Property str1208() As String
            Get
                Return ResourceManager.GetString("str1208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary cause.
        '''</summary>
        Friend ReadOnly Property str1209() As String
            Get
                Return ResourceManager.GetString("str1209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary cause.
        '''</summary>
        Friend ReadOnly Property str1210() As String
            Get
                Return ResourceManager.GetString("str1210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Covers/Perils.
        '''</summary>
        Friend ReadOnly Property str1211() As String
            Get
                Return ResourceManager.GetString("str1211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim type.
        '''</summary>
        Friend ReadOnly Property str1212() As String
            Get
                Return ResourceManager.GetString("str1212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend ReadOnly Property str1213() As String
            Get
                Return ResourceManager.GetString("str1213", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peril description.
        '''</summary>
        Friend ReadOnly Property str1214() As String
            Get
                Return ResourceManager.GetString("str1214", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum Insured.
        '''</summary>
        Friend ReadOnly Property str1215() As String
            Get
                Return ResourceManager.GetString("str1215", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current reserve.
        '''</summary>
        Friend ReadOnly Property str1216() As String
            Get
                Return ResourceManager.GetString("str1216", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Add.
        '''</summary>
        Friend ReadOnly Property str1217() As String
            Get
                Return ResourceManager.GetString("str1217", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit.
        '''</summary>
        Friend ReadOnly Property str1218() As String
            Get
                Return ResourceManager.GetString("str1218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property str1219() As String
            Get
                Return ResourceManager.GetString("str1219", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1220() As String
            Get
                Return ResourceManager.GetString("str1220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1221() As String
            Get
                Return ResourceManager.GetString("str1221", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1222() As String
            Get
                Return ResourceManager.GetString("str1222", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver.
        '''</summary>
        Friend ReadOnly Property str1223() As String
            Get
                Return ResourceManager.GetString("str1223", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third Party.
        '''</summary>
        Friend ReadOnly Property str1224() As String
            Get
                Return ResourceManager.GetString("str1224", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repairer.
        '''</summary>
        Friend ReadOnly Property str1225() As String
            Get
                Return ResourceManager.GetString("str1225", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Witness.
        '''</summary>
        Friend ReadOnly Property str1226() As String
            Get
                Return ResourceManager.GetString("str1226", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provisional open claim.
        '''</summary>
        Friend ReadOnly Property str1227() As String
            Get
                Return ResourceManager.GetString("str1227", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live open claim.
        '''</summary>
        Friend ReadOnly Property str1228() As String
            Get
                Return ResourceManager.GetString("str1228", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closed.
        '''</summary>
        Friend ReadOnly Property str1229() As String
            Get
                Return ResourceManager.GetString("str1229", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-opened.
        '''</summary>
        Friend ReadOnly Property str1230() As String
            Get
                Return ResourceManager.GetString("str1230", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-closed.
        '''</summary>
        Friend ReadOnly Property str1231() As String
            Get
                Return ResourceManager.GetString("str1231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy Currency.
        '''</summary>
        Friend ReadOnly Property str1232() As String
            Get
                Return ResourceManager.GetString("str1232", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss Currency.
        '''</summary>
        Friend ReadOnly Property str1233() As String
            Get
                Return ResourceManager.GetString("str1233", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Risk details cancel.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not save the changes made to risk details. 
        ''' Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business failed.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to create business component..
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter parties for .
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add peril.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All perils specific to the claim/policy are already defined..
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peril deletion.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete this peril. Payments/receipts/recoveries/parties for this peril are present..
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Financial details.
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event log.
        '''</summary>
        Friend ReadOnly Property str1310() As String
            Get
                Return ResourceManager.GetString("str1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Risk details.
        '''</summary>
        Friend ReadOnly Property str1311() As String
            Get
                Return ResourceManager.GetString("str1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter mandatory data for .
        '''</summary>
        Friend ReadOnly Property str1312() As String
            Get
                Return ResourceManager.GetString("str1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid date.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please add perils.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter values.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Claim.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Claim.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get current reserve.
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to close claim.
        '''</summary>
        Friend ReadOnly Property str1319() As String
            Get
                Return ResourceManager.GetString("str1319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Action.
        '''</summary>
        Friend ReadOnly Property str1320() As String
            Get
                Return ResourceManager.GetString("str1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General Details.
        '''</summary>
        Friend ReadOnly Property str1321() As String
            Get
                Return ResourceManager.GetString("str1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party Summary.
        '''</summary>
        Friend ReadOnly Property str1322() As String
            Get
                Return ResourceManager.GetString("str1322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy Summary.
        '''</summary>
        Friend ReadOnly Property str1323() As String
            Get
                Return ResourceManager.GetString("str1323", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to reopen the claim.
        '''</summary>
        Friend ReadOnly Property str1324() As String
            Get
                Return ResourceManager.GetString("str1324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reopen Claim?.
        '''</summary>
        Friend ReadOnly Property str1325() As String
            Get
                Return ResourceManager.GetString("str1325", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to reopen the claim?.
        '''</summary>
        Friend ReadOnly Property str1326() As String
            Get
                Return ResourceManager.GetString("str1326", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
