Option Strict Off
Option Explicit On
Imports Artinsoft.VB6.Utils
Imports Microsoft.VisualBasic
Imports System
'Developer Guide no.129
Imports SharedFiles
Module MainModule
	' ***************************************************************** '
	' Module Name: MainModule
	'
	' Date:  25/10/2002
	'
	' Description: Main Module.
	'
	' Edit History:
	' RAW 21/11/2002 : PS005 : Add export for party loyalty scheme
	' RAW 28/11/2002 : PS005 : Use constants to define those columns in DetailArray that HUB requires for all exports
	' ***************************************************************** '
	
	' Main public constant for all functions
	' to identify which application this is.
	Public Const ACApp As String = "bACTFinanceSpoke"
	
	' Constant for the functions to identify
	' which class this is.
	Private Const ACClass As String = "MainModule"
	
	'Commonly Used Strings
	Public Const conDot As String = "."
	Public Const conSemiColon As String = ";"
	Public Const conComma As String = ","
	Public Const conEmptyString As String = ""
	
	'Batch Export Status Codes
	Public Const conBECode As String = "BE"
	Public Const conBICode As String = "BI"
	Public Const conBCCode As String = "BC"
	
	' Status Codes
	Public Const conWaitingForCollectionCode As String = "W"
	Public Const conCollectedCode As String = "C"
	
	'Array Dimensions
	Public Const conColumns As Integer = 1
	Public Const conRows As Integer = 2
	
	'Transaction table Primary Key Array Elements
	Public Const conIDFieldName As Integer = 0
	Public Const conIDFieldValue As Integer = 1
	
	'Export Header Data Array Elements
	Public Const ehdBatchTypeCode As Integer = 9
	Public Const ehdBatchCode As Integer = 10
	Public Const ehdAccountsFilter As Integer = 11
	Public Const ehdTotalNoOfTransactions As Integer = 12
	Public Const ehdBatchAmount As Integer = 13
	Public Const ehdSourceList As Integer = 14
	Public Const ehdLeadDays As Integer = 15
	'sw 16-04-2003 changed this from media val code to media code
	Public Const ehdMediaTypeCode As Integer = 16
	Public Const ehdAutoClose As Integer = 17
	Public Const ehdBatchName As Integer = 18
	'DD 18/06/2003: Added for manual export
	Public Const ehdArrayOnly As Integer = 19
	
	'Import Header Data Array Elements
	Public Const ihdEFTSuspenseAccount As Integer = 0
	
	'Import Detail Data Array Elements
	'REJECTIONS
	'Import header
	Public Const ACREJTotalNoTrans As Integer = 9
	Public Const ACREJTotalAmount As Integer = 10
	Public Const ACREJBatchRef As Integer = 11
	
	'Import Detail Data Array Elements
	Public Const iddDetailId As Integer = 0
	Public Const iddRecordStatus As Integer = 1
	Public Const iddRecordMessage As Integer = 2
	Public Const iddCreditCardNumber As Integer = 3
	Public Const iddAccountNumber As Integer = 4
	Public Const iddAmount As Integer = 5
	Public Const iddAccountName As Integer = 6
	Public Const iddClientCode As Integer = 7
	Public Const iddTransactionId As Integer = 8
	Public Const iddFailureCode As Integer = 9
	
	'Updated these constants SW 04/04/2003
	'Recurring Transaction Data Array Elements
	Public Const rcpPFInstalmentsId As Integer = 0
	Public Const rcpPFInstalmentDueDate As Integer = 1
	Public Const rcpPartyShortName As Integer = 2
	Public Const rcpPFPremiumFinanceClientName As Integer = 3
	Public Const rcpPFPremiumFinanceCompanyName As Integer = 4
	Public Const rcpPFCCNumber As Integer = 5
	Public Const rcpPFPremiumFinanceBankAccountName As Integer = 6
	Public Const rcpPFPremiumFinanceBankAccountNo As Integer = 7
	Public Const rcpPFPremiumFinanceBankSortCode As Integer = 8
	Public Const rcpPFPremiumFinanceBankName As Integer = 9
	Public Const rcpPFIInstalmentAmount As Integer = 10
	Public Const rcpPartyAlternativeIdentifier As Integer = 11
	Public Const rcpPartyAgentCnt As Integer = 12
	Public Const rcpPFInstalmentsGroupID As Integer = 13
	Public Const rcpPFInstalmentStatusID As Integer = 14
	Public Const rcpPFInstalmentStatusDescription As Integer = 15
	Public Const rcpPFInstalmentTransStatusID As Integer = 16
	Public Const rcpPFAutoGeneratedPlanRef As Integer = 17
	Public Const rcpPFInstalmentNo As Integer = 18
	Public Const rcpPFCCExpiryDate As Integer = 19
	Public Const rcpPFCCStartDate As Integer = 20
	Public Const rcpPFCCIssueNumber As Integer = 21
	Public Const rcpPFCCPIN As Integer = 22
	
	'One Off Transaction Data Array Elements
	Public Const oopCashListItemCashListItemId As Integer = 0
	Public Const oopPartyShortName As Integer = 1
	Public Const oopPartyName As Integer = 2
	Public Const oopCashListItemPaymentName As Integer = 3
	Public Const oopCashListItemAmount As Integer = 4
	'sw issue 2866 added in extra constants
	Public Const oopCCNumber As Integer = 5
	Public Const oopCCExpiryDate As Integer = 6
	Public Const oopCCStartDate As Integer = 7
	Public Const oopCCIssue As Integer = 8
	Public Const oopCCPin As Integer = 9
	Public Const oopCashListItemTransDetailId As Integer = 10
	Public Const oopPartyAlternativeIdentifier As Integer = 11
	Public Const oopPartyAgentCnt As Integer = 12
	
	
	'Table Columns
	Public Const clnCashListItemID As String = "CASHLISTITEM_ID"
	Public Const clnCollectionAccountID As String = "COLLECTION_ACCOUNT_ID"
	Public Const clnAccountID As String = "ACCOUNT_ID"
	Public Const clnMediaTypeID As String = "MEDIATYPE_ID"
	Public Const clnAmount As String = "AMOUNT"
	Public Const clnSuspenseAccountId As String = "SUSPENSE_ACCOUNT_ID"
	Public Const clnClientAccountId As String = "CLIENT_ACCOUNT_ID"
	Public Const clnPFInstalmentsID As String = "PFINSTALMENTS_ID"
	'sw added 04/04/2003
	Public Const clnTransDetailID As String = "TRANSDETAIL_ID"
	
	
	Public Const conAccountId As Integer = 0
	Public Const conAmount As Integer = 1
	
	Public Const conName As Integer = 0
	Public Const conValue As Integer = 1
	
	'sw added for Electronic receipting
	'Electronic receipting HeaderData Array Constants
	Public Const ACERBatchIDSIR As Integer = 0
	Public Const ACERTotalNoOfTransactions As Integer = 9
	Public Const ACERControlTotal As Integer = 10
	Public Const ACERSourceCode As Integer = 11
	
	'SMJB 20/08/03: CQ 2144 Added for Import Rejections
	Public Const ACIRHeaderAmount As Integer = 2
	Public Const ACIRDetailAmount As Integer = 5
	Public Const ACIRTotalNoOfTransactions As Integer = 9
	Public Const ACIRControlTotal As Integer = 10
	
	
	'Electronic receipting r_vDetailData array constants
	Public Const ACERRecordStatus As Integer = 1
	Public Const ACERRecordMessage As Integer = 2
	Public Const ACERMediaTypeCode As Integer = 3
	Public Const ACERAmount As Integer = 4
	Public Const ACERDebtorNumber As Integer = 5
	Public Const ACERClaimDebtID As Integer = 6
	Public Const ACERClaimNo As Integer = 7
	Public Const ACERBankStatementCode As Integer = 8
	Public Const ACERBankStatementRef As Integer = 9
	Public Const ACERBankStatementParticulars As Integer = 10
	Public Const ACERBankStatementOtherPartyName As Integer = 11
	
	'end sw
	
	'Instalment details data array elements
	Public Const ACInstalmentID As Integer = 0
	Public Const ACTransactionID As Integer = 1
	Public Const ACInstalmentAmount As Integer = 2
	Public Const ACDueDate As Integer = 3
	Public Const ACNextDueDate As Integer = 4
	Public Const ACNextInstalmentID As Integer = 5
	Public Const ACRecollectOnNext As Integer = 6
	Public Const ACRecollectDays As Integer = 7
	Public Const ACPlanTransID As Integer = 8
	
	'############ Export Cheque reminder Constants ################
	
	Public Const ACCRMonths As Integer = 9
	Public Const ACCRMediaTypeCode As Integer = 10
	
	'payment details data array elements
	Public Const ACCRPaymentCashListItemID As Integer = 0
	Public Const ACCRPaymentAmount As Integer = 1
	Public Const ACCRPaymentAccountID As Integer = 2
	Public Const ACCRPaymentPartyCnt As Integer = 3
	
	Public Const ACCRChequeReminderTemplateCode As String = "UCR"
	Public Const ACCRStandardLetterTypeCode As String = "LETTER"
	Public Const ACCRDocumentProductionEvent As String = "DOCUMENT"
	
	Public Const ACCRSpoolDocMode As Integer = 4
	
	'############ End Export cheque reminder ######################
	
	'############## Stale Cheque Constants #################
	
	Public Const ACSCMonths As Integer = 9
	Public Const ACSCMediaTypeCode As Integer = 10
	
	'payment details data array elements
	Public Const ACSCPaymentCashListItemID As Integer = 0
	Public Const ACSCPaymentAmount As Integer = 1
	Public Const ACSCPaymentTransdetail As Integer = 2
	Public Const ACSCAccountID As Integer = 3
	Public Const ACSCCashListBankAccount As Integer = 4
	Public Const ACSCPaymentTypeCode As Integer = 5
	
	'############### End Stale Cheque  #######################
	
	
	'############### Sweep Balances ##########################
	
	Public Const ACSBBankStatementDetailID As Integer = 0
	Public Const ACSBCreditAmount As Integer = 1
	Public Const ACSBDebitAmount As Integer = 2
	Public Const ACSBBankAccountID As Integer = 3
	Public Const ACSBAccountID As Integer = 4
	'############### End Sweep Balances #######################
	
	
	'############ Export Credit Balance Constants ################
	'DD 21/02/2003
	'Credit Balance data array elements
	Public Const ACCBAccountID As Integer = 0
	Public Const ACCBAccountAccountCode As Integer = 1
	'############ Export Credit Balance Constants ################
	
	'sw 25/02/2003
	Public Const ACHubSpecificColumnCount As Integer = 3
	
	Sub Main_Renamed()
		
	End Sub
	
	Public Function AddHUBColumnsToDetailArray(ByVal v_sStatusCode As String, ByVal v_sStatusMsg As String, ByRef r_vResultArray As Array, ByVal v_sUsername As String) As Integer
		' ---------------------------------------------------------------------------
		' PROCEDURE NAME: GetPartyLoyaltyScheme
		' PURPOSE: Adds 3 columns to the start of the result array and populates
		'          with the passed parameter values
		' AUTHOR: Rob Wilson
		' DATE: 21 November 2002
		' RETURNS: PMTrue for success
		' CHANGES:
		' ---------------------------------------------------------------------------
		
		Dim result As Integer = 0
		Dim lLBound1, lUBound1, lLBound2, lUBound2 As Integer
		Dim vNewArray( ,  ) As Object
		
		
		Try
		
		result = gPMConstants.PMEReturnCode.PMFalse
		
		' add 3 new fields at the start of each row (row no, status code and status message)
		If Information.IsArray(r_vResultArray) Then
			' Bound 1 = columns, Bound 2 = rows
			lLBound1 = r_vResultArray.GetLowerBound(0)
			lUBound1 = r_vResultArray.GetUpperBound(0)
			lLBound2 = r_vResultArray.GetLowerBound(1)
			lUBound2 = r_vResultArray.GetUpperBound(1)
			
			' Insert 3 columns at the start by copying each column to another array
			' but in a position 3 greater than the original
			vNewArray = ArraysHelper.RedimPreserve(Of Object(, ))(vNewArray, New Integer(){lUBound1 + 3 - lLBound1 + 1, lUBound2 - lLBound2 + 1}, New Integer(){lLBound1, lLBound2})
			For i1 As Integer = lLBound1 To lUBound1
				For i2 As Integer = lLBound2 To lUBound2


                    vNewArray(i1 + 3, i2) = r_vResultArray(i1, i2)
				Next i2
			Next i1
			
			' Now load data into the first 3 columns
			For i2 As Integer = lLBound2 To lUBound2
				' RAW 28/11/2002 : PS005 : replace column numbers with constants

				vNewArray(gHUBSpokeConstants.klExportDetailColRecordNo, i2) = i2 + 1 ' record number

				vNewArray(gHUBSpokeConstants.klExportDetailColStatusCode, i2) = v_sStatusCode

				vNewArray(gHUBSpokeConstants.klExportDetailColStatusMsg, i2) = v_sStatusMsg
			Next i2
			
			r_vResultArray = vNewArray
			
		End If
		
		result = gPMConstants.PMEReturnCode.PMTrue
		
		
		'----------------------------------------------------------------------------------------
		'Only for Debugging, the code will never execute this line
		'----------------------------------------------------------------------------------------
		  
		
		Catch ex As Exception
		Select Case Information.Err().Number
			Case Else
				' Log Error.
				bPMFunc.LogMessage("", iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="", vApp:=ACApp, vClass:=ACClass, vMethod:="AddHUBColumnsToDetailArray", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description, excep:=ex)
				
				result = gPMConstants.PMEReturnCode.PMFalse
				
		End Select
		
		Finally
	
		
		End Try
			Return result
	End Function
	
    'Developer Guide No 101
    Public Function AddResultArrayToDetailArray(ByRef v_vDetailArray As Object, ByRef r_vResultArray As Object, ByRef v_sUsername As String) As Integer
        ' ---------------------------------------------------------------------------
        ' PROCEDURE NAME: AddResultArrayToDetailArray
        ' PURPOSE: Add a new element to the Detail array and populate with the result array
        ' AUTHOR: Paul Cunningham
        ' DATE: 28 November 2002, 12:59:49
        ' RETURNS: PMTrue for success
        ' CHANGES:
        ' ---------------------------------------------------------------------------

        Dim result As Integer = 0
        Dim lLowerId, lNewUpperId As Integer


        Try

            result = gPMConstants.PMEReturnCode.PMFalse

            If Information.IsArray(r_vResultArray) Then
                'Dynamically size array for flexibility
                If Information.IsArray(v_vDetailArray) Then
                    lLowerId = v_vDetailArray.GetLowerBound(0)
                    lNewUpperId = v_vDetailArray.GetUpperBound(0) + 1
                    v_vDetailArray = ArraysHelper.RedimPreserve(Of Object())(v_vDetailArray, New Integer() {lNewUpperId - lLowerId + 1}, New Integer() {lLowerId})
                Else
                    v_vDetailArray = Array.CreateInstance(GetType(Object), New Integer() {1}, New Integer() {0})
                End If

                'Populate the new element with the ResultArray

                v_vDetailArray(lNewUpperId) = r_vResultArray
            End If

            result = gPMConstants.PMEReturnCode.PMTrue


            '----------------------------------------------------------------------------------------
            'Only for Debugging, the code will never execute this line
            '----------------------------------------------------------------------------------------


        Catch ex As Exception
            Select Case Information.Err().Number
                Case Else
                    ' Log Error.
                    bPMFunc.LogMessage("", iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="", vApp:=ACApp, vClass:=ACClass, vMethod:="AddResultArrayToDetailArray", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description, excep:=ex)

                    result = gPMConstants.PMEReturnCode.PMError

            End Select

        Finally



        End Try
        Return result
    End Function
End Module
