Option Strict On
Option Explicit On

#Region " Imports "
Imports System
Imports System.Text
Imports System.Xml.Serialization
Imports SiriusFS.SAM.Structure
Imports Sirius.Architecture.ExceptionHandling
Imports System.Collections.Generic
Imports SiriusFS.SAM.Structure.BaseImplementationTypes


#End Region

Namespace BaseImplementationTypes
#Region "Base GetHeaderAndSummariesPFPlanByKeyRequest And GetHeaderAndSummariesPFPlanByKeyRequest"
    ''' <summary>
    ''' Class Name :BaseGetHeaderAndSummariesPFPlanByKeyRequestType
    ''' </summary>
    ''' <remarks>Base Class to be Inhereted by GetHeaderAndSummariesPFPlanByKeyRequestType</remarks>
    Public Class BaseGetHeaderAndSummariesPFPlanByKeyRequestType
        Inherits BaseRequestType

        Public Property PFPremiumFinanceKey() As Integer

        Public Property PFPremiumFinanceVersionKey() As Integer

        Public Property DocumentRef() As String

        Public Property UserID() As Integer
    End Class

    ''' <summary>
    ''' Class Name :BaseGetHeaderAndSummariesPFPlanByKeyResponseType
    ''' </summary>
    ''' <remarks></remarks>
    Public Class BaseGetHeaderAndSummariesPFPlanByKeyResponseType
        Inherits BaseResponseType

        Public Property PremiumFinanceDetails() As BasePremiumFinancePlanDetailsType

        Public Property Installements() As BasePremiumFinancePlanInstalmentsType()

        Public Property Transactions() As BasePremiumFinancePlanTransactionsType()

        Public Property PFHistory() As BasePremiumFinancePlanHistoryType()

        Public Property PFBankHistory() As BasePremiumFinancePlanBankHistoryType()

    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanDetailsType
    ''' This Collections is used to Hold the value for PremiumFinancePlanDetails 
    ''' </summary>
    ''' <remarks></remarks>
    '''  
    Partial Public Class BasePremiumFinancePlanDetailsType
        Public Property PFPremiumFinanceKey() As Integer

        Public Property PFPremiumFinanceVersionKey() As Integer

        Public Property PFSchemeName() As String

        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property StartDate() As Date

        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property EndDate() As Date

        Public Property ProductClass() As String

        Public Property TransType() As String

        Public Property FinanceAmount() As Double

        Public Property APR() As Double

        Public Property InterestRate() As Double

        Public Property DaysDelay() As Integer

        Public Property NoOfInstallments() As Integer

        Public Property FirstInstallment() As Double

        Public Property OtherInstallments() As Double

        Public Property CostOfProtection() As Double

        Public Property Deposit() As Double

        Public Property NetAmount() As Double

        Public Property TotalCost() As Double

        Public Property InterestCost() As Double

        Public Property MinFinanceChrge() As Double

        Public Property PayProtection() As String

        Public Property ClientName() As String

        Public Property ClientAddress1() As String

        Public Property ClientAddress2() As String

        Public Property ClientAddress3() As String

        Public Property ClientAddress4() As String

        Public Property ClientTown() As String

        Public Property ClientPcode() As String

        Public Property ClientCountry() As String

        Public Property ClientAreaCode() As String

        Public Property ClientPhoneNo() As String

        Public Property ClientExtension() As String

        Public Property ClientFaxAreaCode() As String

        Public Property ClientFaxNo() As String

        Public Property BankName() As String

        Public Property BankSortCode() As String

        Public Property BankAccountNo() As String

        Public Property BankAccountName() As String

        Public Property BankBranch() As String

        Public Property BankAddress1() As String

        Public Property BankAddress2() As String

        Public Property BankAddress3() As String

        Public Property BankTown() As String

        Public Property BankRegion() As String

        Public Property BankPostCode() As String

        Public Property BankCountry() As String

        Public Property BankAreaCode() As String

        Public Property BankPhoneNo() As String

        Public Property BankExtension() As String

        Public Property BankFaxAreaCode() As String

        Public Property BankFaxNo() As String

        Public Property StatusInd() As FinancePlanStatus

        Public Property ClientCode() As String

        Public Property AutoGeneratedPlanRef() As String

        Public Property FinanceCollatedPlanRef() As String

        Public Property InterestFree() As String

        Public Property IsQuote() As Boolean

        Public Property PlanTransactionKey() As Integer

        Public Property InsuranceFileKey() As Integer

        Public Property PFRFKEY() As Integer

        Public Property PFFrequencyCode() As String

        Public Property BankCountryKey() As Integer

        Public Property ClientCountryKey() As Integer

        Public Property FirstInstalmentDate() As Date

        Public Property NextInstalmentDate() As Date

        Public Property LastInstalmentDate() As Date

        Public Property TaxCost() As Double

        Public Property MediaTypeCode() As String

        Public Property CCNumber() As String

        Public Property CCExpiryDate() As String

        Public Property CCStartDate() As String

        Public Property CCIssue() As String

        Public Property CCPin() As String

        Public Property MediaTypeValidationCode() As String

        Public Property bank_name_mandatory() As Boolean

        Public Property IsBankAddressMandatory() As Boolean

        Public Property IsBranchNameMandatory() As Boolean

        Public Property IsBranchCodeMandatory() As Boolean

        Public Property CommissionTransdetailKey() As Integer

        Public Property PFFrequencyPeriod() As String

        Public Property PFFrequencyAmount() As Integer

        Public Property PFFrequencyKey() As Integer

        Public Property SourceKey() As Integer

        Public Property ProductKey() As Integer

        Public Property PFSchemeTypeCode() As String

        Public Property FinanceFee() As Double

        Public Property DayOfWeekOrMonth() As Integer

        Public Property PaymentMethod() As String

        Public Property PFFrequencyDesc() As String

        Public Property SchemePrintType() As String

        Public Property OriginalAmount() As Double

        Public Property LastInstalment() As Double

        Public Property ClaimDebtId() As Integer

        Public Property DateCreated() As Date

        Public Property DateModified() As Date

        Public Property DateConfirmed() As Date

        Public Property DateReview() As Date

        Public Property IsViaThirdParty() As Boolean

        Public Property IsDepositAsInstalment() As Boolean

        Public Property PFRFMnemonic() As String

        Public Property CoverStartDate() As Date

        Public Property ExpiryDate() As Date

        Public Property Terms() As Integer

        Public Property OriginalRate() As Double

        Public Property IsCardHolder() As Boolean

        Public Property CardHolderName() As String

        Public Property CardHolderAddress1() As String

        Public Property CardHolderAddress2() As String

        Public Property CardHolderAddress3() As String

        Public Property CardHolderAddress4() As String

        Public Property CardHolderPostCode() As String

        Public Property CardType() As String

        Public Property IsProviderCollectDeposit() As Boolean

        Public Property DateBankDetailsChanged() As Date

        Public Property IsDDCancelled() As Boolean

        Public Property IsCCCancelled() As Boolean

        Public Property IsPaperlessDD() As Boolean

        Public Property SchemeType() As String

        Public Property SchemeCode() As String

        Public Property PartyBankKey() As Integer

        '''<remarks/>
        Public Property PFPremiumFinanceCancelReason() As String

        '''<remarks/>
        Public Property IsCancelPolicyRun() As Boolean

        '''<remarks/>
        Public Property IsFinanceNetCommission() As Boolean

        '''<remarks/>
        Public Property IsDepositOnOtherMediaType() As Boolean

        Public Property SettlementAmount() As Double

        '''<remarks/>
        Public Property DepostiCCTrackingNumber() As String

        '''<remarks/>
        Public Property CanUserEditInstallmentStatusYN() As Boolean

        '''<remarks/>
        Public Property Receipt_Difference_Option() As Integer
    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanInstalmentsType
    ''' This Collections is used to Hold the value for PremiumFinancePlan Instalments 
    ''' </summary>
    ''' <remarks></remarks>
    Partial Public Class BasePremiumFinancePlanInstalmentsType

        Public Property PFInstalmentsKey() As Integer

        Public Property InstalmentNumber() As Integer

        Public Property DueDate() As Date

        Public Property Fee() As Double

        Public Property Amount() As Double

        Public Property TransactionDescription() As String

        Public Property StatusDescription() As String

        Public Property BatchRef() As String

        Public Property ExportDate() As Date

        Public Property PostedDate() As Date

        Public Property PFTransactionKey() As Integer

        Public Property Tax() As Double

        Public Property Commission() As Double

        Public Property History() As BasePremiumFinancePlanInstalmentsHistoryType()

        Public Property InstalmentReason() As String

        Public Property StatusCode() As String

        Public Property InstalmentReasonCode() As String

        Public Property CurrencyDesc() As String

    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanInstalmentsHistoryType
    ''' This Collections is used to Hold the nested value for Premium FinancePlan Instalments History  
    ''' </summary>
    ''' <remarks></remarks>
    Partial Public Class BasePremiumFinancePlanInstalmentsHistoryType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property PostedDate() As Date

        '''<remarks/>
        Public Property PFIStatusDescription() As String

        '''<remarks/>
        Public Property PFIResultDescription() As String

        '''<remarks/>
        Public Property PFIResultCode() As String

    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanTransactionsType
    ''' This Collections is used to Hold the  value for Premium FinancePlan Transactions 
    ''' </summary>
    ''' <remarks></remarks>
    Partial Public Class BasePremiumFinancePlanTransactionsType

        '''<remarks/>
        Public Property PFTransactionKey() As Integer

        '''<remarks/>
        Public Property InsuranceRefIndex() As Integer

        '''<remarks/>
        Public Property Amount() As Double

        '''<remarks/>
        Public Property InsuranceFileKey() As Integer

        Public Property TransDetailKey() As Integer

        Public Property DocRef() As String

        Public Property AltRef() As String

        Public Property EffectiveDate() As Date

        Public Property TransDate() As Date

        Public Property MediaType() As String

        Public Property OutstandingAmount() As Decimal

        Public Property MediaRef() As String

        Public Property Accountkey() As Integer

        Public Property AccountCode() As String

        Public Property Currency() As String

        Public Property TaxBand() As String

        Public Property TransactionCurrenciesAmount() As Decimal

        Public Property TransactionCurrency() As String

        Public Property TransactionCurrencyCode() As String

        Public Property CurrencyDiff() As Decimal

        Public Property SourceID() As Integer

        Public Property PeriodName() As String

        Public Property DocType() As String

        Public Property DoctypeGroup() As String

        Public Property PrimarySettled() As String

        Public Property InsuranceRef() As String

        Public Property Spare() As String

        Public Property DocTypeID() As Integer

    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanHistoryType
    ''' This Collections is used to Hold the  value for Premium FinancePlan History 
    ''' </summary>
    ''' <remarks></remarks>
    Partial Public Class BasePremiumFinancePlanHistoryType

        '''<remarks/>
        Public Property PFPremiumFinanceKey() As Integer

        '''<remarks/>
        Public Property PFPremiumFinanceVersionKey() As Integer

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property StartDate() As Date

        '''<remarks/>
        Public Property FinanceAmount() As Double

        '''<remarks/>
        Public Property TotalCost() As Double

        '''<remarks/>
        Public Property StatusInd() As FinancePlanStatus

        '''<remarks/>
        Public Property AutoGeneratedPlanRef() As String

    End Class

    ''' <summary>
    ''' Class Name :BasePremiumFinancePlanBankHistoryType
    ''' This Collections is used to Hold the  value for Bank History
    ''' </summary>
    ''' <remarks></remarks>
    Partial Public Class BasePremiumFinancePlanBankHistoryType

        Public Property MediatypeValidationCode() As String

        Public Property ActionCode() As String

        Public Property BankAccountName() As String

        Public Property BankSortCode() As String

        Public Property BankAccountNo() As String

        Public Property BankName() As String

        Public Property BankBranch() As String

        Public Property BankAddress1() As String

        Public Property BankAddress2() As String

        Public Property BankAddress3() As String

        Public Property BankTown() As String

        Public Property BankPostCode() As String

        Public Property BankRegion() As String

        Public Property BankCountry() As String

        Public Property BankAreaCode() As String

        Public Property BankPhoneNo() As String

        Public Property BankExtension() As String

        Public Property BankFaxAreaCode() As String

        Public Property BankFaxNo() As String

        Public Property CCNumber() As String

        Public Property CCExpiry_date() As String

        Public Property CCStartDate() As String

        Public Property CCIssue() As String

        Public Property CCPin() As String

        Public Property CardHolderName() As String

        Public Property CardHolderAddress1() As String

        Public Property CardHolderAddress2() As String

        Public Property CardHolderAddress3() As String

        Public Property CardHolderAddress4() As String

        Public Property CardHolderPostCode() As String

        Public Property DateModified() As Date

        Public Property UserName() As String

        Public Property PaperDD() As Boolean

        Public Property PaymentType() As String

        Public Property AccountType() As String

    End Class
#End Region
#Region "Base UpdateInstalmentStatus"
    ''' <summary>
    ''' Class Name :BaseUpdateInstalmentStatusRequestType
    ''' </summary>
    ''' <remarks>Base Class to be Inhereted by UpdateInstalmentStatusRequestType</remarks>
    Public Class BaseUpdateInstalmentStatusRequestType
        Inherits BaseRequestType

        '''<remarks/>
        Public Property PFInstalmentKey() As Integer

        '''<remarks/>
        Public Property PFIStatusCode() As String

    End Class
    ''' <summary>
    ''' Class Name :BaseUpdateInstalmentStatusResponseType
    ''' </summary>
    ''' <remarks></remarks>
    Public Class BaseUpdateInstalmentStatusResponseType
        Inherits BaseResponseType
    End Class
#End Region

    Public Enum CancelPFPlanType
        DeletePlan
        SettlePlan
        CancelPlan
    End Enum

    Public Enum ProcessPFPlanType
        NewPlan
        PlanMTA
    End Enum


    Public NotInheritable Class InstalmentPlanStatus
        Public Const Saved As String = "010"
        Public Const Updated As String = "011"
        Public Const QuotePrinted As String = "012"
        Public Const Live As String = "040"
        Public Const OnHold As String = "140"
        Public Const Completed As String = "900"
        Public Const Superceded As String = "990"
        Public Const Cancelled As String = "999"
    End Class

    Partial Public Class BaseCancelPremiumFinancePlanRequestType
        Inherits BaseRequestType

        Public Property PFPremiumFinanceKey() As Integer

        Public Property PFPremiumFinanceVersionKey() As Integer

        Public Property ReasonCode() As String

        Public Property RequestType() As CancelPFPlanType

        Public Sub Validate(ByRef oErrorCollection As Object)

            Dim oSAMErrorCollection As SAMErrorCollection = CType(oErrorCollection, SAMErrorCollection)

            If PFPremiumFinanceKey = 0 Then
                oSAMErrorCollection.AddInvalidData(SAMConstants.SAMInvalidData.MandatoryInputMissing, _
                                                                   SAMConstants.SAMInvalidData.MandatoryInputMissing.ToString, _
                                                                "PFPremiumFinanceKey")
            End If

            If PFPremiumFinanceVersionKey = 0 Then
                oSAMErrorCollection.AddInvalidData(SAMConstants.SAMInvalidData.MandatoryInputMissing, _
                                                   SAMConstants.SAMInvalidData.MandatoryInputMissing.ToString, _
                                                   "PFPremiumFinanceVersionKey")
            End If

        End Sub


    End Class

    Partial Public Class BaseCancelPremiumFinancePlanResponseType
        Inherits BaseResponseType

        Public Property DebitTransdetailKey() As Integer

        Public Property Warnings() As String

        Public Property PFPolicies() As BaseCancelPremiumFinancePlanResponseTypePolicies()


    End Class


    Partial Public Class BaseCancelPremiumFinancePlanResponseTypePolicies

        Public Property InsuranceFileKey() As Integer

        Public Property CalculatedLapsedDate() As Date

    End Class



    Partial Public Class BaseCancelPFPoliciesRequestType
        Inherits BaseRequestType

        Public Property PFPremiumFinanceKey() As Integer

        Public Property PFPremiumFinanceVersionKey() As Integer

        Public Property LapsedReasonCode() As String

        Public Property SpoolDoc() As Boolean

        Public Property WriteOff() As Boolean

        Public Property PolicyLapsedDate() As Date


        Public Sub Validate(ByRef oErrorCollection As Object)

            Dim oSAMErrorCollection As SAMErrorCollection = CType(oErrorCollection, SAMErrorCollection)

            If PFPremiumFinanceKey = 0 Then
                oSAMErrorCollection.AddInvalidData(SAMConstants.SAMInvalidData.MandatoryInputMissing, _
                                                                   SAMConstants.SAMInvalidData.MandatoryInputMissing.ToString, _
                                                                "PFPremiumFinanceKey")
            End If

            If PFPremiumFinanceVersionKey = 0 Then
                oSAMErrorCollection.AddInvalidData(SAMConstants.SAMInvalidData.MandatoryInputMissing, _
                                                   SAMConstants.SAMInvalidData.MandatoryInputMissing.ToString, _
                                                   "PFPremiumFinanceVersionKey")
            End If

        End Sub

    End Class

    Partial Public Class BaseCancelPFPoliciesResponseType
        Inherits BaseResponseType

        Public Property Warnings() As String


    End Class

    Partial Public Class BaseProcessPFPlanRequestType
        Inherits BaseRequestType

        Public Property PartyCode() As String

        Public Property PFQuote() As BasePremiumFinanceDetails

        Public Property PFTransaction() As BaseProcessPFPlanRequestTrans()

        Public Property TransType() As ProcessPFPlanType

        Public Property Type() As InstalmentType

        Public Property SaveOnly() As Boolean

        Public Property PFPremFinanceKey() As Integer

        Public Property PFPremFinanceVersion() As Integer

        Public Property PFCreditCardDetails() As BaseCreditCardType

        Public Property PFBankDetails() As BasePFBankDetails

    End Class

    Partial Public Class BaseProcessPFPlanResponseType
        Inherits BaseResponseType

        Public Property PFPremFinanceKey() As Integer

        Public Property PFPremFinanceVersion() As Integer

        Public Property DepositTransdetailKey() As Integer

        Public Property Warnings() As String

    End Class


    Partial Public Class BasePremiumFinanceDetails

        Public Property PFBankDetails() As BasePFBankDetails

        Public Property PFPremiumFinanceKey() As Integer

        Public Property PFPremiumFinanceVersionKey() As Integer

        Public Property PFSchemeName() As String

        Public Property QuoteDate() As Date

        Public Property StartDate() As Date

        Public Property EndDate() As Date

        Public Property ProductClass() As String

        Public Property TransType() As String

        Public Property FinanceAmount() As Double

        Public Property APR() As Double

        Public Property InterestRate() As Double

        Public Property DaysDelay() As Double

        Public Property NoOfInstallments() As Double

        Public Property FirstInstallment() As Double

        Public Property OtherInstallments() As Double

        Public Property CostOfProtection() As Double

        Public Property Deposit() As Double

        Public Property NetAmount() As Double

        Public Property TotalCost() As Double

        Public Property InterestCost() As Double

        Public Property MinFinanceChrge() As Double

        Public Property PaymentProtection() As Boolean

        Public Property ClientName() As String

        Public Property ClientAddress1() As String

        Public Property ClientAddress2() As String

        Public Property ClientAddress3() As String

        Public Property ClientAddress4() As String

        Public Property ClientTown() As String

        Public Property ClientPcode() As String

        Public Property ClientCountry() As String

        Public Property ClientAreaCode() As String

        Public Property ClientPhoneNo() As String

        Public Property ClientExtension() As String

        Public Property ClientFaxAreaCode() As String

        Public Property ClientFaxNo() As String

        Public Property BankName() As String

        Public Property BankSortCode() As String

        Public Property BankAccountNo() As String

        Public Property BankAccountName() As String

        Public Property BankBranch() As String

        Public Property BankAddress1() As String

        Public Property BankAddress2() As String

        Public Property BankAddress3() As String

        Public Property BankAddress4() As String

        Public Property BankTown() As String

        Public Property BankRegion() As String

        Public Property BankPostCode() As String

        Public Property BankCountry() As String

        Public Property BankAreaCode() As String

        Public Property BankPhoneNo() As String

        Public Property BankExtension() As String

        Public Property BankFaxAreaCode() As String

        Public Property BankFaxNo() As String

        Public Property StatusInd() As FinancePlanStatus

        Public Property ClientCode() As String

        Public Property AutoGeneratedPlanRef() As String

        Public Property FinanceCollatedPlanRef() As String

        Public Property InterestFree() As String

        Public Property IsQuote() As Boolean

        Public Property PlanTransactionKey() As Integer

        Public Property InsuranceFileKey() As Integer

        Public Property PFRFKEY() As Integer

        Public Property PFFrequencyCode() As String

        Public Property BankCountryKey() As Integer

        Public Property ClientCountryKey() As Integer

        Public Property FirstInstalmentDate() As Date

        Public Property NextInstalmentDate() As Date

        Public Property LastInstalmentDate() As Date

        Public Property TaxCost() As Double

        Public Property MediaTypeCode() As String

        Public Property CCNumber() As String

        Public Property CCExpiryDate() As String

        Public Property CCStartDate() As String

        Public Property CCIssue() As String

        Public Property CCPin() As String

        Public Property MediaTypeValidationCode() As String

        Public Property bank_name_mandatory() As Boolean

        Public Property IsBankAddressMandatory() As Boolean

        Public Property IsBranchNameMandatory() As Boolean

        Public Property IsBranchCodeMandatory() As Boolean

        Public Property CommissionTransdetailKey() As Integer

        Public Property PFFrequencyPeriod() As String

        Public Property PFFrequencyAmount() As Integer

        Public Property PFFrequencyKey() As Integer

        Public Property SourceKey() As Integer

        Public Property ProductKey() As Integer

        Public Property PFSchemeTypeCode() As String

        Public Property FinanceFee() As Double

        Public Property DayOfWeekOrMonth() As Integer

        Public Property PaymentMethod() As String

        Public Property PFFrequencyDesc() As String

        Public Property SchemePrintType() As String

        Public Property OriginalAmount() As Double

        Public Property LastInstalment() As Double

        Public Property ClaimDebtId() As Integer

        Public Property DateCreated() As Date

        Public Property DateModified() As Date

        Public Property DateConfirmed() As Date

        Public Property DateReview() As Date

        Public Property IsViaThirdParty() As Boolean

        Public Property IsDepositAsInstalment() As Boolean

        Public Property PFRFMnemonic() As String

        Public Property CoverStartDate() As Date

        Public Property ExpiryDate() As Date

        Public Property Terms() As Integer

        Public Property OriginalRate() As Double

        Public Property IsCardHolder() As Boolean

        Public Property CardHolderName() As String

        Public Property CardHolderAddress1() As String

        Public Property CardHolderAddress2() As String

        Public Property CardHolderAddress3() As String

        Public Property CardHolderAddress4() As String

        Public Property CardHolderPostCode() As String

        Public Property CardType() As String

        Public Property IsProviderCollectDeposit() As Boolean

        Public Property DateBankDetailsChanged() As Date

        Public Property IsDDCancelled() As Boolean

        Public Property IsCCCancelled() As Boolean

        Public Property IsPaperlessDD() As Boolean

        Public Property SchemeType() As String

        Public Property SchemeCode() As String

        Public Property PartyBankKey() As Integer

        Public Property PFPremiumFinanceCancelReason() As String

        Public Property IsCancelPolicyRun() As Boolean

        Public Property IsFinanceNetCommission() As Boolean

        Public Property IsDepositOnOtherMediaType() As Boolean

        Public Property PreferredDate() As Date

        Public Property OverrideInterestRate() As Double

        Public Property SelectedSchemeNo() As Integer

        Public Property SelectedSchemeVersion() As Integer

        Public Property OverrideCommission() As Boolean

        Public Property ProcessPFMode() As String

        Public Property DepositCCTrackingNumber() As String

    End Class


    Partial Public Class BasePFBankDetails

        Public Property PartyBankKey() As Integer

        Public Property BankName() As String

        Public Property BankSortCode() As String

        Public Property BankAccountNo() As String

        Public Property BankAccountName() As String

        Public Property BankBranch() As String

        Public Property BankAreaCode() As String

        Public Property BankPhone() As String

        Public Property BankExtn() As String

        Public Property BankFaxCode() As String

        Public Property BankFax() As String

        Public Property BankAddress() As BaseAddressType

    End Class


    Partial Public Class BaseProcessPFPlanRequestTrans

        Public Property TransdetailKey() As Integer

        Public Property PolicyRef() As String

        Public Property OutstandingAmount() As Decimal

        Public Property Spare() As String

        Public Property DocumentTypeId() As Integer

        Public Property InsuranceFileKey() As Integer

        Public Property AccountId() As Integer

    End Class


End Namespace