'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=1.1.4322.573.
'
Namespace PartiesAndPolicies
    
    '<remarks/>
    <Serializable(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.tempuri.org/"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.tempuri.org/", IsNullable:=False)> _
    Public Class FindParty

        '<remarks/>
        Public GisDataModelCode As String

        '<remarks/>
        Public GisBusinessTypeCode As String

        '<remarks/>
        Public UserId As String

        '<remarks/>
        Public PartyType As String

        '<remarks/>
        Public TelephoneNumber As String

        '<remarks/>
        Public Postcode As String

        '<remarks/>
        Public Shortname As String

        '<remarks/>
        Public PolicyNo As String

        '<remarks/>
        Public Address As String

        '<remarks/>
        Public ResolvedName As String

        '<remarks/>
        Public LeadAgentCount As Integer

        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public LeadAgentCountSpecified As Boolean

        '<remarks/>
        Public AdditionalData As FindPartyAdditionalData

        '<remarks/>
        Public Results As FindPartyResults

    End Class

    '<remarks/>
    <Serializable(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.tempuri.org/")> _
    Public Class FindPartyAdditionalData

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("add")> _
        Public add() As FindPartyAdditionalDataAdd
    End Class

    '<remarks/>
    <Serializable(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.tempuri.org/")> _
    Public Class FindPartyAdditionalDataAdd

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public key As String

        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public value As String
    End Class

    '<remarks/>
    <Serializable(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.tempuri.org/")> _
    Public Class FindPartyResultsParty

        '<remarks/>
        Public Shortname As String

        '<remarks/>
        Public ResolvedName As String

        '<remarks/>
        Public Address As String

        '<remarks/>
        Public PostCode As String

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public DOB As Date

        '<remarks/>
        Public PartyCount As Integer

        '<remarks/>
        Public AgentCount As Integer
    End Class

    '<remarks/>
    <Serializable(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.tempuri.org/")> _
    Public Class FindPartyResults

        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Party")> _
        Public Party() As FindPartyResultsParty
    End Class
End Namespace
