'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace DREProxy
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ExecutorServiceSoap", [Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class ExecutorService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ExecuteRuleSetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFilterDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Nexus.Dre.My.MySettings.Default.Nexus_Dre_DREProxy_ExecutorService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ExecuteRuleSetCompleted As ExecuteRuleSetCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFilterDataCompleted As GetFilterDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ssp-uk.com/DRE/ExecuteRuleSet", RequestNamespace:="http://ssp-uk.com/DRE/", ResponseNamespace:="http://ssp-uk.com/DRE/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteRuleSet(ByVal input As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal effective As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute("profileToken")> ByVal profileToken() As String, ByVal filterRulesetNames As String, ByVal excludeRulesetNames As String, ByVal useEffectiveDateInChildRuleset As Boolean) As RuleSetReturn
            Dim results() As Object = Me.Invoke("ExecuteRuleSet", New Object() {input, effective, profileToken, filterRulesetNames, excludeRulesetNames, useEffectiveDateInChildRuleset})
            Return CType(results(0),RuleSetReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuteRuleSetAsync(ByVal input As String, ByVal effective As System.Nullable(Of Date), ByVal profileToken() As String, ByVal filterRulesetNames As String, ByVal excludeRulesetNames As String, ByVal useEffectiveDateInChildRuleset As Boolean)
            Me.ExecuteRuleSetAsync(input, effective, profileToken, filterRulesetNames, excludeRulesetNames, useEffectiveDateInChildRuleset, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuteRuleSetAsync(ByVal input As String, ByVal effective As System.Nullable(Of Date), ByVal profileToken() As String, ByVal filterRulesetNames As String, ByVal excludeRulesetNames As String, ByVal useEffectiveDateInChildRuleset As Boolean, ByVal userState As Object)
            If (Me.ExecuteRuleSetOperationCompleted Is Nothing) Then
                Me.ExecuteRuleSetOperationCompleted = AddressOf Me.OnExecuteRuleSetOperationCompleted
            End If
            Me.InvokeAsync("ExecuteRuleSet", New Object() {input, effective, profileToken, filterRulesetNames, excludeRulesetNames, useEffectiveDateInChildRuleset}, Me.ExecuteRuleSetOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuteRuleSetOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuteRuleSetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuteRuleSetCompleted(Me, New ExecuteRuleSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ssp-uk.com/DRE/GetFilterData", RequestNamespace:="http://ssp-uk.com/DRE/", ResponseNamespace:="http://ssp-uk.com/DRE/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFilterData(ByVal request As GetFilterDataRequest) As GetFilterDataResponse
            Dim results() As Object = Me.Invoke("GetFilterData", New Object() {request})
            Return CType(results(0),GetFilterDataResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFilterDataAsync(ByVal request As GetFilterDataRequest)
            Me.GetFilterDataAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFilterDataAsync(ByVal request As GetFilterDataRequest, ByVal userState As Object)
            If (Me.GetFilterDataOperationCompleted Is Nothing) Then
                Me.GetFilterDataOperationCompleted = AddressOf Me.OnGetFilterDataOperationCompleted
            End If
            Me.InvokeAsync("GetFilterData", New Object() {request}, Me.GetFilterDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFilterDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFilterDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFilterDataCompleted(Me, New GetFilterDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class RuleSetReturn
        
        Private ruleSetIdField As Integer
        
        Private outputField() As EngineOutput
        
        Private executionTimeField As String
        
        '''<remarks/>
        Public Property RuleSetId() As Integer
            Get
                Return Me.ruleSetIdField
            End Get
            Set
                Me.ruleSetIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Output() As EngineOutput()
            Get
                Return Me.outputField
            End Get
            Set
                Me.outputField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExecutionTime() As String
            Get
                Return Me.executionTimeField
            End Get
            Set
                Me.executionTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class EngineOutput
        
        Private profileTokenField As String
        
        Private ruleSetField As String
        
        Private scriptWarningsField() As String
        
        Private engineMessagesField() As String
        
        Private outputField As String
        
        Private differencesField As String
        
        Private ruleSetTimeField As String
        
        Private executionTimeField As String
        
        Private serialisationTimeField As String
        
        '''<remarks/>
        Public Property ProfileToken() As String
            Get
                Return Me.profileTokenField
            End Get
            Set
                Me.profileTokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RuleSet() As String
            Get
                Return Me.ruleSetField
            End Get
            Set
                Me.ruleSetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ScriptWarnings() As String()
            Get
                Return Me.scriptWarningsField
            End Get
            Set
                Me.scriptWarningsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EngineMessages() As String()
            Get
                Return Me.engineMessagesField
            End Get
            Set
                Me.engineMessagesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Output() As String
            Get
                Return Me.outputField
            End Get
            Set
                Me.outputField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Differences() As String
            Get
                Return Me.differencesField
            End Get
            Set
                Me.differencesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RuleSetTime() As String
            Get
                Return Me.ruleSetTimeField
            End Get
            Set
                Me.ruleSetTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExecutionTime() As String
            Get
                Return Me.executionTimeField
            End Get
            Set
                Me.executionTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SerialisationTime() As String
            Get
                Return Me.serialisationTimeField
            End Get
            Set
                Me.serialisationTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class RangeCategory
        
        Private idField As System.Guid
        
        Private lowerBoundField As Decimal
        
        Private upperBoundField As Decimal
        
        '''<remarks/>
        Public Property Id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LowerBound() As Decimal
            Get
                Return Me.lowerBoundField
            End Get
            Set
                Me.lowerBoundField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpperBound() As Decimal
            Get
                Return Me.upperBoundField
            End Get
            Set
                Me.upperBoundField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class RangeMatchInstance
        
        Private idField As System.Guid
        
        Private rangeCategoryIdField As System.Guid
        
        Private dateTimeField As Date
        
        Private countField As Integer
        
        Private totalField As Decimal
        
        Private maxField As Decimal
        
        Private minField As Decimal
        
        '''<remarks/>
        Public Property Id() As System.Guid
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RangeCategoryId() As System.Guid
            Get
                Return Me.rangeCategoryIdField
            End Get
            Set
                Me.rangeCategoryIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateTime() As Date
            Get
                Return Me.dateTimeField
            End Get
            Set
                Me.dateTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Max() As Decimal
            Get
                Return Me.maxField
            End Get
            Set
                Me.maxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Min() As Decimal
            Get
                Return Me.minField
            End Get
            Set
                Me.minField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class GetFilterDataResponse
        
        Private instancesField() As RangeMatchInstance
        
        Private rangesField() As RangeCategory
        
        '''<remarks/>
        Public Property Instances() As RangeMatchInstance()
            Get
                Return Me.instancesField
            End Get
            Set
                Me.instancesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ranges() As RangeCategory()
            Get
                Return Me.rangesField
            End Get
            Set
                Me.rangesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ssp-uk.com/DRE/")>  _
    Partial Public Class GetFilterDataRequest
        
        Private filterIdField As System.Guid
        
        Private startDateField As System.Nullable(Of Date)
        
        Private endDateField As System.Nullable(Of Date)
        
        '''<remarks/>
        Public Property FilterId() As System.Guid
            Get
                Return Me.filterIdField
            End Get
            Set
                Me.filterIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StartDate() As System.Nullable(Of Date)
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EndDate() As System.Nullable(Of Date)
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")>  _
    Public Delegate Sub ExecuteRuleSetCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuteRuleSetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuteRuleSetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RuleSetReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RuleSetReturn)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")>  _
    Public Delegate Sub GetFilterDataCompletedEventHandler(ByVal sender As Object, ByVal e As GetFilterDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFilterDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GetFilterDataResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetFilterDataResponse)
            End Get
        End Property
    End Class
End Namespace
