'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iOpenClaim.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opening a Claim.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Claim Details.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Client Details.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Agent Details.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Comments.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim status:.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim status date:.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last modified date:.
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend ReadOnly Property str1113() As String
            Get
                Return ResourceManager.GetString("str1113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client name.
        '''</summary>
        Friend ReadOnly Property str1114() As String
            Get
                Return ResourceManager.GetString("str1114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Additional Details.
        '''</summary>
        Friend ReadOnly Property str1115() As String
            Get
                Return ResourceManager.GetString("str1115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Client Details.
        '''</summary>
        Friend ReadOnly Property str1116() As String
            Get
                Return ResourceManager.GetString("str1116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Insurer Details.
        '''</summary>
        Friend ReadOnly Property str1117() As String
            Get
                Return ResourceManager.GetString("str1117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5 - Comments.
        '''</summary>
        Friend ReadOnly Property str1118() As String
            Get
                Return ResourceManager.GetString("str1118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim &amp;handler:.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pro&amp;gress status:.
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Description:.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Primary cause:.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Secondary cause:.
        '''</summary>
        Friend ReadOnly Property str1124() As String
            Get
                Return ResourceManager.GetString("str1124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C&amp;atastrophe code:.
        '''</summary>
        Friend ReadOnly Property str1125() As String
            Get
                Return ResourceManager.GetString("str1125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locatio&amp;n:.
        '''</summary>
        Friend ReadOnly Property str1126() As String
            Get
                Return ResourceManager.GetString("str1126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Town:.
        '''</summary>
        Friend ReadOnly Property str1127() As String
            Get
                Return ResourceManager.GetString("str1127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Reported date:.
        '''</summary>
        Friend ReadOnly Property str1128() As String
            Get
                Return ResourceManager.GetString("str1128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Loss date:.
        '''</summary>
        Friend ReadOnly Property str1129() As String
            Get
                Return ResourceManager.GetString("str1129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss to dat&amp;e:.
        '''</summary>
        Friend ReadOnly Property str1130() As String
            Get
                Return ResourceManager.GetString("str1130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R&amp;eported to date:.
        '''</summary>
        Friend ReadOnly Property str1131() As String
            Get
                Return ResourceManager.GetString("str1131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C&amp;urrency:.
        '''</summary>
        Friend ReadOnly Property str1132() As String
            Get
                Return ResourceManager.GetString("str1132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Information:.
        '''</summary>
        Friend ReadOnly Property str1133() As String
            Get
                Return ResourceManager.GetString("str1133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Likely To clai&amp;m:.
        '''</summary>
        Friend ReadOnly Property str1134() As String
            Get
                Return ResourceManager.GetString("str1134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone number (&amp;H):.
        '''</summary>
        Friend ReadOnly Property str1135() As String
            Get
                Return ResourceManager.GetString("str1135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tele&amp;phone number (O):.
        '''</summary>
        Friend ReadOnly Property str1136() As String
            Get
                Return ResourceManager.GetString("str1136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Fax number:.
        '''</summary>
        Friend ReadOnly Property str1137() As String
            Get
                Return ResourceManager.GetString("str1137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Mobile number:.
        '''</summary>
        Friend ReadOnly Property str1138() As String
            Get
                Return ResourceManager.GetString("str1138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Email number:.
        '''</summary>
        Friend ReadOnly Property str1139() As String
            Get
                Return ResourceManager.GetString("str1139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;VAT registered:.
        '''</summary>
        Friend ReadOnly Property str1140() As String
            Get
                Return ResourceManager.GetString("str1140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VAT &amp;registration number:.
        '''</summary>
        Friend ReadOnly Property str1141() As String
            Get
                Return ResourceManager.GetString("str1141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client cl&amp;aim number:.
        '''</summary>
        Friend ReadOnly Property str1142() As String
            Get
                Return ResourceManager.GetString("str1142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Telephone number:.
        '''</summary>
        Friend ReadOnly Property str1143() As String
            Get
                Return ResourceManager.GetString("str1143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Fax number:.
        '''</summary>
        Friend ReadOnly Property str1144() As String
            Get
                Return ResourceManager.GetString("str1144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Co&amp;ntact:.
        '''</summary>
        Friend ReadOnly Property str1145() As String
            Get
                Return ResourceManager.GetString("str1145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Email address:.
        '''</summary>
        Friend ReadOnly Property str1146() As String
            Get
                Return ResourceManager.GetString("str1146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insurer claim number:.
        '''</summary>
        Friend ReadOnly Property str1147() As String
            Get
                Return ResourceManager.GetString("str1147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insurer name:.
        '''</summary>
        Friend ReadOnly Property str1148() As String
            Get
                Return ResourceManager.GetString("str1148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User defined field A:.
        '''</summary>
        Friend ReadOnly Property str1149() As String
            Get
                Return ResourceManager.GetString("str1149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User defined field B:.
        '''</summary>
        Friend ReadOnly Property str1150() As String
            Get
                Return ResourceManager.GetString("str1150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User defined field C:.
        '''</summary>
        Friend ReadOnly Property str1151() As String
            Get
                Return ResourceManager.GetString("str1151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User defined field D:.
        '''</summary>
        Friend ReadOnly Property str1152() As String
            Get
                Return ResourceManager.GetString("str1152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User defined field E:.
        '''</summary>
        Friend ReadOnly Property str1153() As String
            Get
                Return ResourceManager.GetString("str1153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent name:.
        '''</summary>
        Friend ReadOnly Property str1154() As String
            Get
                Return ResourceManager.GetString("str1154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Agent claim number:.
        '''</summary>
        Friend ReadOnly Property str1155() As String
            Get
                Return ResourceManager.GetString("str1155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Title:.
        '''</summary>
        Friend ReadOnly Property str1156() As String
            Get
                Return ResourceManager.GetString("str1156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forename:.
        '''</summary>
        Friend ReadOnly Property str1157() As String
            Get
                Return ResourceManager.GetString("str1157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last name:.
        '''</summary>
        Friend ReadOnly Property str1158() As String
            Get
                Return ResourceManager.GetString("str1158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date passed test:.
        '''</summary>
        Friend ReadOnly Property str1159() As String
            Get
                Return ResourceManager.GetString("str1159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee Details.
        '''</summary>
        Friend ReadOnly Property str1160() As String
            Get
                Return ResourceManager.GetString("str1160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length of Service:.
        '''</summary>
        Friend ReadOnly Property str1161() As String
            Get
                Return ResourceManager.GetString("str1161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Claim.
        '''</summary>
        Friend ReadOnly Property str1162() As String
            Get
                Return ResourceManager.GetString("str1162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Details:.
        '''</summary>
        Friend ReadOnly Property str1163() As String
            Get
                Return ResourceManager.GetString("str1163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninsured Loss Recovery Details.
        '''</summary>
        Friend ReadOnly Property str1164() As String
            Get
                Return ResourceManager.GetString("str1164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninsured Loss Recovery.
        '''</summary>
        Friend ReadOnly Property str1165() As String
            Get
                Return ResourceManager.GetString("str1165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recovery Agent:.
        '''</summary>
        Friend ReadOnly Property str1166() As String
            Get
                Return ResourceManager.GetString("str1166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solicitor Appointed.
        '''</summary>
        Friend ReadOnly Property str1167() As String
            Get
                Return ResourceManager.GetString("str1167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solicitor Name:.
        '''</summary>
        Friend ReadOnly Property str1168() As String
            Get
                Return ResourceManager.GetString("str1168", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NCD Details.
        '''</summary>
        Friend ReadOnly Property str1169() As String
            Get
                Return ResourceManager.GetString("str1169", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At fault:.
        '''</summary>
        Friend ReadOnly Property str1170() As String
            Get
                Return ResourceManager.GetString("str1170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bonus Affected.
        '''</summary>
        Friend ReadOnly Property str1171() As String
            Get
                Return ResourceManager.GetString("str1171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deductibles.
        '''</summary>
        Friend ReadOnly Property str1172() As String
            Get
                Return ResourceManager.GetString("str1172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard Excess:.
        '''</summary>
        Friend ReadOnly Property str1173() As String
            Get
                Return ResourceManager.GetString("str1173", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non-standard Excess:.
        '''</summary>
        Friend ReadOnly Property str1174() As String
            Get
                Return ResourceManager.GetString("str1174", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insured Driver Details.
        '''</summary>
        Friend ReadOnly Property str1175() As String
            Get
                Return ResourceManager.GetString("str1175", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Navigate.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F&amp;ind Now.
        '''</summary>
        Friend ReadOnly Property str1204() As String
            Get
                Return ResourceManager.GetString("str1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ne&amp;w Search.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Risk Type:.
        '''</summary>
        Friend ReadOnly Property str1206() As String
            Get
                Return ResourceManager.GetString("str1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address....
        '''</summary>
        Friend ReadOnly Property str1207() As String
            Get
                Return ResourceManager.GetString("str1207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insurer....
        '''</summary>
        Friend ReadOnly Property str1208() As String
            Get
                Return ResourceManager.GetString("str1208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not return any search details.
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Search.
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new search will clear all of your existing search details.
        '''Do you wish to continue?.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching, Please wait....
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) found.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid look up.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Lookup datum is not valid..
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is a Mandatory field. You must enter data in this field..
        '''</summary>
        Friend ReadOnly Property str1310() As String
            Get
                Return ResourceManager.GetString("str1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date entered.
        '''</summary>
        Friend ReadOnly Property str1311() As String
            Get
                Return ResourceManager.GetString("str1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid date. Cannot be earlier than Loss Date.
        '''</summary>
        Friend ReadOnly Property str1312() As String
            Get
                Return ResourceManager.GetString("str1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid time entered.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter only numbers.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter the VAT registration number.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The loss date and time should be less than or equal to current date &amp; time.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a date value which is greater than or equal to Policy commencement date.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a date value which is less than or equal to Policy expiry date.
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter Valid Time HH:MM.
        '''</summary>
        Friend ReadOnly Property str1319() As String
            Get
                Return ResourceManager.GetString("str1319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open a Claim.
        '''</summary>
        Friend ReadOnly Property str1320() As String
            Get
                Return ResourceManager.GetString("str1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date. Cannot be earlier than Reported Date.
        '''</summary>
        Friend ReadOnly Property str1321() As String
            Get
                Return ResourceManager.GetString("str1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;3-Lead Agent Details.
        '''</summary>
        Friend ReadOnly Property str1322() As String
            Get
                Return ResourceManager.GetString("str1322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Claim.
        '''</summary>
        Friend ReadOnly Property str1323() As String
            Get
                Return ResourceManager.GetString("str1323", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress Status is &apos;Closed&apos;. Do you wish to Close this Claim?.
        '''</summary>
        Friend ReadOnly Property str1324() As String
            Get
                Return ResourceManager.GetString("str1324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss Date must not be later than Reported Date.
        '''</summary>
        Friend ReadOnly Property str1325() As String
            Get
                Return ResourceManager.GetString("str1325", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss Date must not be later than Loss To Date.
        '''</summary>
        Friend ReadOnly Property str1326() As String
            Get
                Return ResourceManager.GetString("str1326", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss Date must not be later than the current date.
        '''</summary>
        Friend ReadOnly Property str1327() As String
            Get
                Return ResourceManager.GetString("str1327", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reported Date must not be later than the current date.
        '''</summary>
        Friend ReadOnly Property str1328() As String
            Get
                Return ResourceManager.GetString("str1328", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reported Date must not be later than Reported To Date.
        '''</summary>
        Friend ReadOnly Property str1329() As String
            Get
                Return ResourceManager.GetString("str1329", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current outstanding reserves do not equal zero.
        '''Do you wish to reset outstanding reserves to zero?.
        '''</summary>
        Friend ReadOnly Property str1330() As String
            Get
                Return ResourceManager.GetString("str1330", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot close claim - all outstanding reserves should be zero.
        '''Please amend reserve information..
        '''</summary>
        Friend ReadOnly Property str1331() As String
            Get
                Return ResourceManager.GetString("str1331", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim Handled:.
        '''</summary>
        Friend ReadOnly Property str1332() As String
            Get
                Return ResourceManager.GetString("str1332", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax registered:.
        '''</summary>
        Friend ReadOnly Property str1333() As String
            Get
                Return ResourceManager.GetString("str1333", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax registration number:.
        '''</summary>
        Friend ReadOnly Property str1334() As String
            Get
                Return ResourceManager.GetString("str1334", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot validate cover on a Retroactive Date basis as no such value is set on the Risk..
        '''</summary>
        Friend ReadOnly Property str1335() As String
            Get
                Return ResourceManager.GetString("str1335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Loss Date on the claim needs to be between the Retroactive Date of the Risk         '''and the Policy Expiry Date. Cannot continue..
        '''</summary>
        Friend ReadOnly Property str1336() As String
            Get
                Return ResourceManager.GetString("str1336", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Reported Date on the claim needs to be between the Policy Cover Start Date         '''and the Expiry Date. Cannot continue..
        '''</summary>
        Friend ReadOnly Property str1337() As String
            Get
                Return ResourceManager.GetString("str1337", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Loss Date on the claim needs to be between the Retroactive Date of the Risk         '''and the Risk Inception Date. Cannot continue..
        '''</summary>
        Friend ReadOnly Property str1338() As String
            Get
                Return ResourceManager.GetString("str1338", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No valid policy can be found for this loss date.
        '''</summary>
        Friend ReadOnly Property str1339() As String
            Get
                Return ResourceManager.GetString("str1339", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
