Option Strict Off
Option Explicit On
Imports Artinsoft.VB6.Utils
Imports Microsoft.VisualBasic
Imports Microsoft.VisualBasic.Compatibility.VB6
Imports System
Imports System.IO
Imports System.Windows.Forms
Imports SharedFiles
<System.Runtime.InteropServices.ProgId("Interface_Renamed_NET.Interface_Renamed")> _
Public NotInheritable Class Interface_Renamed
    Implements IDisposable
    Implements SSP.S4I.Interfaces.ILocalInterface
    ' ***************************************************************** '
    ' Class Name: Interface
    '
    ' Date: 10/05/1999
    '
    ' Description: Main public class to accompany the interface form.
    '
    ' Edit History:
    ' CLG 01/09/2004 : RFC71 Added product option to allow spool and archive of documents
    ' RKS 02/05/2005 : 354-Standard Wording Control Enhancements, Added DocumentFilter
    '                  property
    ' ***************************************************************** '


    ' Constant for the functions to identify
    ' which class this is.
    Private Const ACClass As String = "Interface"
   
    Private m_sCallingAppName As String = ""

    Private m_iTask As Integer
    Private m_lNavigate As Integer
    Private m_lProcessMode As Integer
    Private m_sTransactionType As String = ""
    Private m_dtEffectiveDate As Date
    Private m_sNavigatorTitle As String = ""

    Private m_lPMAuthorityLevel As Integer

    Private m_sStepStatus As String = ""

    Private m_sSpoolDesc As String = ""
    Private m_sDocName As String = ""

    Private m_lDocumentTemplateId As Integer
    Private m_sDocumentTemplateCode As String = ""
    Private m_sDocumentTemplateDescription As String = ""
    Private m_lDocumentTypeId As Integer
    Private m_sDocumentTypeCode As String = ""
    Private m_sDocumentTypeDescription As String = ""

    Private m_sDocumentFilter As String = ""

    Private m_lPartyCnt As Integer
    Private m_lInsuranceFolderCnt As Integer
    Private m_lInsuranceFileCnt As Integer
    Private m_lClaimCnt As Integer
    Private m_sDocumentRef As String = ""
    Private m_lEventCnt As Integer

    Private m_lFSAComplaintFolderCnt As Integer
    Private m_sFSAComplaintReference As String = ""
    Private m_lMode As Integer
    Private m_bFromBatchTrans As Boolean
    Private m_sWordVersion As String = ""
    Private m_bFishRequired As Boolean

    'DC170203 -ISS1405 -For processing of shared invoices
    Private m_vPolicySharesArray As Object
    ' Stores the exit status of the interface.
    Private m_lStatus As Integer

    ' Stores the return value for the a
    ' function call.
    Private m_lReturn As Integer
    Private m_bArchiveAfterPrinting As Boolean
    Private m_sDocumentDescription As String = ""

    Private m_bAutoGenerateDocumentTask As Boolean

    'CLG RFC71 2004-09-01
    Private m_lArchiveMode As Integer
    Private m_sParameterXML As String = ""
    Private m_lKeepOnTop As Integer
    Private m_lRiskCnt As Integer

    Private m_iIsClient As Integer
    Private m_iIsAgent As Integer
    Private m_iIsOffice As Integer
    Private m_iProductionOrder As Integer
    Private m_bArchiveWithNoPrint As Boolean
    Private m_bEmailAsBody As Boolean
    Private m_bSpoolDocument As Boolean
    Private m_bArchiveAsText As Boolean
    Private m_bArchiveAsXML As Boolean
    Private m_bCalledFromGetDocument As Boolean 'PN66227
    'Added by Sudhanshu Behera on 5/5/2010 11:39:46 AM refer developer guide no. 69(Guide)
    Dim frmInterface As Object
    Private m_bIsDocumentEdited As Boolean = False
    Private m_bFormlessDocument As Boolean
    Private m_bIsNonBatchProcess As Boolean
    Private m_bCCMDocProduction As Boolean
    Private m_sCCMWebServiceURL As String
    Private m_sCCMCustomer As String
    Private m_sCCMPartner As String
    Private m_sCCMContractTypeName As String
    Private m_sCCMRepositoryProject As String
    Private m_sCCMContractTypeVersion As String
    Private m_sCCMDocumentName As String
    Private m_sCCMRepStatus As String
    Private m_bView As Boolean

    Private Enum CCMStatusDesc
        Published = 1
        Current = 2
        Accepted = 3
    End Enum

    ' PUBLIC Property Procedures (Begin)
    Public Property CalledFromGetDocument() As Boolean
        Get
            Return m_bCalledFromGetDocument
        End Get
        Set(ByVal Value As Boolean)
            m_bCalledFromGetDocument = Value
        End Set
    End Property

    Public Property AutoGenerateDocumentTask() As Boolean
        Get
            Return m_bAutoGenerateDocumentTask
        End Get
        Set(ByVal Value As Boolean)
            m_bAutoGenerateDocumentTask = Value
        End Set
    End Property
    Public WriteOnly Property SpoolDesc() As String
        Set(ByVal Value As String)
            m_sSpoolDesc = Value
        End Set
    End Property

    Public WriteOnly Property DocName() As String
        Set(ByVal Value As String)
            m_sDocName = Value
        End Set
    End Property

    Public Property RiskCnt() As Integer
        Get
            Return m_lRiskCnt
        End Get
        Set(ByVal Value As Integer)
            m_lRiskCnt = Value
        End Set
    End Property

    Public WriteOnly Property ArchiveAfterPrinting() As Boolean
        Set(ByVal Value As Boolean)
            m_bArchiveAfterPrinting = Value
        End Set
    End Property
    Public WriteOnly Property DocumentDescription() As String
        Set(ByVal Value As String)
            m_sDocumentDescription = Value
        End Set
    End Property
    'MKW030903 END

    Public Property DocumentTemplateId() As Integer
        Get
            Return m_lDocumentTemplateId
        End Get
        Set(ByVal Value As Integer)
            m_lDocumentTemplateId = Value
        End Set
    End Property

    Public Property DocumentTemplateCode() As String
        Get
            Return m_sDocumentTemplateCode
        End Get
        Set(ByVal Value As String)
            m_sDocumentTemplateCode = Value
        End Set
    End Property

    Public Property DocumentTemplateDescription() As String
        Get
            Return m_sDocumentTemplateDescription
        End Get
        Set(ByVal Value As String)
            m_sDocumentTemplateDescription = Value
        End Set
    End Property


    Public Property DocumentFilter() As String
        Get
            Return m_sDocumentFilter
        End Get
        Set(ByVal Value As String)
            m_sDocumentFilter = Value
        End Set
    End Property

    Public Property DocumentTypeId() As Integer
        Get
            Return m_lDocumentTypeId
        End Get
        Set(ByVal Value As Integer)
            m_lDocumentTypeId = Value
        End Set
    End Property

    Public Property DocumentTypeCode() As String
        Get
            Return m_sDocumentTypeCode
        End Get
        Set(ByVal Value As String)
            m_sDocumentTypeCode = Value
        End Set
    End Property

    Public Property DocumentTypeDescription() As String
        Get
            Return m_sDocumentTypeDescription
        End Get
        Set(ByVal Value As String)
            m_sDocumentTypeDescription = Value
        End Set
    End Property

    Public Property Mode() As Integer
        Get
            Return m_lMode
        End Get
        Set(ByVal Value As Integer)
            m_lMode = Value
        End Set
    End Property

    'CLG RFC71 2004-09-01 start
    Public Property ArchiveMode() As Integer
        Get
            Mode = m_lArchiveMode
        End Get
        Set(ByVal Value As Integer)
            m_lArchiveMode = Value
        End Set
    End Property
    'CLG RFC71 2004-09-01 start end
    'eck050402

    Public Property FromBatchTrans() As Boolean
        Get

            Return m_bFromBatchTrans

        End Get
        Set(ByVal Value As Boolean)

            m_bFromBatchTrans = Value

        End Set
    End Property
    'eck050402 - end

    Public Property PartyCnt() As Integer
        Get
            Return m_lPartyCnt
        End Get
        Set(ByVal Value As Integer)
            m_lPartyCnt = Value
        End Set
    End Property

    Public Property InsuranceFolderCnt() As Integer
        Get
            Return m_lInsuranceFolderCnt
        End Get
        Set(ByVal Value As Integer)
            m_lInsuranceFolderCnt = Value
        End Set
    End Property

    Public Property InsuranceFileCnt() As Integer
        Get
            Return m_lInsuranceFileCnt
        End Get
        Set(ByVal Value As Integer)
            m_lInsuranceFileCnt = Value
        End Set
    End Property

    Public Property ClaimCnt() As Integer
        Get
            Return m_lClaimCnt
        End Get
        Set(ByVal Value As Integer)
            m_lClaimCnt = Value
        End Set
    End Property

    Public Property DocumentRef() As String
        Get
            Return m_sDocumentRef
        End Get
        Set(ByVal Value As String)
            m_sDocumentRef = Value
        End Set
    End Property

    Public Property EventCnt() As Integer
        Get
            Return m_lEventCnt
        End Get
        Set(ByVal Value As Integer)
            m_lEventCnt = Value
        End Set
    End Property

    Public ReadOnly Property PMProductFamily() As Integer
        Get
            Return gPMConstants.PMEProductFamily.pmePFSiriusSolutions
        End Get
    End Property

    Public WriteOnly Property PMAuthorityLevel() As Integer
        Set(ByVal Value As Integer)
            m_lPMAuthorityLevel = Value
        End Set
    End Property

    Public WriteOnly Property CallingAppName() As String
        Set(ByVal Value As String)
            ' Set the calling application name.
            m_sCallingAppName = Value
        End Set
    End Property

    Public ReadOnly Property Status() As Integer
        Get
            ' Return the interface exit status.
            Return m_lStatus
        End Get
    End Property

    'DC170203 -ISS1405 -start -For processing of shared invoices
    Public Property PolicySharesArray() As Object
        Get
            Return m_vPolicySharesArray
        End Get
        Set(ByVal Value As Object)


            m_vPolicySharesArray = Value
        End Set
    End Property
    'DC170203 -end
    'FSA Phase 3.2
    Public Property FSAComplaintFolderCnt() As Integer
        Get
            Return m_lFSAComplaintFolderCnt
        End Get
        Set(ByVal Value As Integer)
            m_lFSAComplaintFolderCnt = Value
        End Set
    End Property
    Public Property FSAComplaintReference() As String
        Get
            Return m_sFSAComplaintReference
        End Get
        Set(ByVal Value As String)
            m_sFSAComplaintReference = Value
        End Set
    End Property

    ' RAM20050117 - allow a parameter xml to be passed in
    Public WriteOnly Property ParameterXML() As String
        Set(ByVal Value As String)
            m_sParameterXML = Value
        End Set
    End Property

    Public Property IsClient() As Integer
        Get
            Return m_iIsClient
        End Get
        Set(ByVal Value As Integer)
            m_iIsClient = Value
        End Set
    End Property

    Public Property IsAgent() As Integer
        Get
            Return m_iIsAgent
        End Get
        Set(ByVal Value As Integer)
            m_iIsAgent = Value
        End Set
    End Property

    Public Property IsOffice() As Integer
        Get
            Return m_iIsOffice
        End Get
        Set(ByVal Value As Integer)
            m_iIsOffice = Value
        End Set
    End Property

    Public Property ProductionOrder() As Integer
        Get
            Return m_iProductionOrder
        End Get
        Set(ByVal Value As Integer)
            m_iProductionOrder = Value
        End Set
    End Property


    Public Property ArchiveWithNoPrint() As Boolean
        Get
            Return m_bArchiveWithNoPrint
        End Get
        Set(ByVal Value As Boolean)
            m_bArchiveWithNoPrint = Value
        End Set
    End Property


    Public Property EmailAsBody() As Boolean
        Get
            Return m_bEmailAsBody
        End Get
        Set(ByVal Value As Boolean)
            m_bEmailAsBody = Value
        End Set
    End Property

    Public Property SpoolDocument() As Boolean
        Get
            Return m_bSpoolDocument
        End Get
        Set(ByVal Value As Boolean)
            m_bSpoolDocument = Value
        End Set
    End Property

    Private Property ArchiveAsText() As Boolean
        Get
            Return m_bArchiveAsText
        End Get
        Set(ByVal Value As Boolean)
            m_bArchiveAsText = Value
        End Set
    End Property

    Public Property FormlessDocument() As Boolean
        Get
            Return m_bFormlessDocument
        End Get
        Set(ByVal value As Boolean)
            m_bFormlessDocument = value
        End Set
    End Property
    Private Property ArchiveAsXML() As Boolean
        Get
            Return m_bArchiveAsXML
        End Get
        Set(ByVal Value As Boolean)
            m_bArchiveAsXML = Value
        End Set
    End Property
    ''' <summary>
    ''' 
    ''' </summary>
    ''' <value></value>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Public Property IsDocumentEdited() As Boolean
        Get
            Return m_bIsDocumentEdited
        End Get
        Set(ByVal value As Boolean)
            m_bIsDocumentEdited = value
        End Set
    End Property

    Public Property ViewTask() As Boolean
        Get
            Return m_bView
        End Get
        Set(ByVal Value As Boolean)
            m_bView = Value
        End Set
    End Property

    Public WriteOnly Property IsNonBatchProcess() As Boolean
        Set(ByVal Value As Boolean)

            m_bIsNonBatchProcess = Value

        End Set
    End Property

    ' {* USER DEFINED CODE (Begin) *}
    ' {* USER DEFINED CODE (End) *}
    ' PUBLIC Property Procedures (End)

    ' PRIVATE Property Procedures (Begin)
    ' PRIVATE Property Procedures (End)

    ' PUBLIC Methods (Begin)

    ' ***************************************************************** '
    ' Name: Initialise (Standard Method)
    '
    ' Description: Entry point for any initialisation code for this
    '              object.
    '
    ' ***************************************************************** '
    Public Function Initialise() As Integer Implements SSP.S4I.Interfaces.ILocalInterface.Initialise

        Dim result As Integer = 0
        Try

            result = gPMConstants.PMEReturnCode.PMTrue

            ' Create an instance of the object manager.
            g_oObjectManager = New bObjectManager.ObjectManager()

            ' Call the initialise method.
            m_lReturn = g_oObjectManager.Initialise(sCallingAppName:=ACApp)



            ' Check for errors.
            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                ' Failed to call the initialise method.
                result = gPMConstants.PMEReturnCode.PMFalse

                ' Set the object manager to nothing.
                g_oObjectManager = Nothing

                ' Log Error.
                gPMFunctions.LogMessagePopup(iType:=gPMConstants.PMELogLevel.PMLogError, sMsg:="Failed to initialise the object manager", vApp:=ACApp, vClass:=ACClass, vMethod:="Initialise")

                Return result
            End If


            ' Store the language ID from the object manager
            ' to the public variables, to enable us to use
            ' them throughout the object.
            With g_oObjectManager
                g_iLanguageID = .LanguageID
                g_iSourceID = .SourceID
                g_iUserID = .UserID
            End With

            ' Initialise the process modes.
            m_iTask = gPMConstants.PMEComponentAction.PMView
            m_lNavigate = gPMConstants.PMENavigateButtonStatus.PMNavigateNotRequired
            m_lProcessMode = gPMConstants.PMEProcessMode.PMProcessModeGeneric
            m_sTransactionType = gPMConstants.PMTransactionTypeGeneric
            m_dtEffectiveDate = DateTime.Now

            m_bAutoGenerateDocumentTask = True 'MKW 281003 PN7287 1.8.5 to 1.8.6 Catchup

            Dim temp_g_oBusiness As Object
            m_lReturn = g_oObjectManager.GetInstance(temp_g_oBusiness, "bSIRDocTemplate.Business", vInstanceManager:="ClientManager")
            g_oBusiness = temp_g_oBusiness


            Return result

        Catch excep As System.Exception




            result = gPMConstants.PMEReturnCode.PMError

            ' Log Error.
            gPMFunctions.LogMessagePopup(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Failed to initialise the object", vApp:=ACApp, vClass:=ACClass, vMethod:="Initialise", excep:=excep)

            Return result

        End Try
    End Function

    ' ***************************************************************** '
    ' Name: Terminate (Standard Method)
    '
    ' Description: Entry point for any termination code for this
    '              object.
    '
    ' ***************************************************************** '
    Private disposedValue As Boolean
    Public Sub Dispose() Implements IDisposable.Dispose
        Dispose(True)
        GC.SuppressFinalize(Me)
    End Sub


    Protected Sub Dispose(disposing As Boolean)
        If Not Me.disposedValue Then
            Me.disposedValue = True
            If disposing Then
                If g_oObjectManager IsNot Nothing Then
                    g_oObjectManager.Dispose()
                    g_oObjectManager = Nothing
                End If
            End If
        End If
        Me.disposedValue = True
    End Sub


    ' ***************************************************************** '
    ' Name: SetKeys (Standard Method)
    '
    ' Description: Stores all of the parameter members with the key
    '              array.
    '
    ' ***************************************************************** '
    Public Function SetKeys(ByRef vKeyArray(,) As Object) As Integer

        Dim result As Integer = 0

        Try

            result = gPMConstants.PMEReturnCode.PMTrue

            ' If we're here, we're merging...
            'm_lMode = 1

            ' Check we have a vaild array.
            If Not Information.IsArray(vKeyArray) Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Step through the key array.
            For lRow As Integer = vKeyArray.GetLowerBound(1) To vKeyArray.GetUpperBound(1)
                ' Assign the parameter member with the
                ' correct key array item.

                ' {* USER DEFINED CODE (Begin) *}


                Select Case CStr(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyName, lRow)).Trim()
                    Case PMNavKeyConst.PMKeyNamePartyCnt

                        m_lPartyCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameInsFolderCnt

                        m_lInsuranceFolderCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameInsFileCnt

                        m_lInsuranceFileCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameEventCnt

                        m_lEventCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.ACTKeyNameDocumentRef

                        m_sDocumentRef = CStr(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameDocumentTemplateId

                        m_lDocumentTemplateId = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameDocumentTypeId

                        m_lDocumentTypeId = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameDocTemplateMode

                        m_lMode = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameFromBatchTrans

                        m_bFromBatchTrans = CBool(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                        ' SET 10/10/2003 - PS236
                    Case PMNavKeyConst.PMKeyNameArchiveAfterPrinting

                        m_bArchiveAfterPrinting = CBool(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameClaimCnt

                        m_lClaimCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                        'm_sDocumentDescription
                        'FSA Phase 3.2
                    Case PMNavKeyConst.PMKeyNameFSAComplaintFolderCnt

                        m_lFSAComplaintFolderCnt = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameFSAComplaintReference

                        m_sFSAComplaintReference = CStr(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                    Case PMNavKeyConst.PMKeyNameKeepWindowOnTop

                        m_lKeepOnTop = CInt(vKeyArray(gPMConstants.PMENavLetGetKeyColPosition.PMKeyValue, lRow))
                End Select

                ' {* USER DEFINED CODE (End) *}
            Next lRow

            Return result

        Catch excep As System.Exception




            result = gPMConstants.PMEReturnCode.PMError

            ' Log Error Message
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="SetKeys Failed", vApp:=ACApp, vClass:=ACClass, vMethod:="SetKeys", vErrNo:=Information.Err().Number, vErrDesc:=excep.Message, excep:=excep)

            Return result

        End Try
    End Function

    ' ***************************************************************** '
    ' Name: GetKeys (Standard Method)
    '
    ' Description: Stores all of the key array with the parameter
    '              members.
    '
    ' ***************************************************************** '
    Public Function GetKeys(ByRef vKeyArray(,) As Object) As Integer
        Dim result As Integer = 0

        Try

            result = gPMConstants.PMEReturnCode.PMTrue
            ReDim vKeyArray(1, 1)
            Return result

        Catch excep As System.Exception
            result = gPMConstants.PMEReturnCode.PMError
            ' Log Error Message
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="GetKeys Failed", vApp:=ACApp, vClass:=ACClass, vMethod:="GetKeys", vErrNo:=Information.Err().Number, vErrDesc:=excep.Message, excep:=excep)

            Return result
        End Try
    End Function

    ' ***************************************************************** '
    ' Name: GetSummary (Standard Method)
    '
    ' Description: Stores all of the summary array with the parameter
    '              members.
    '
    ' ***************************************************************** '
    Public Function GetSummary(ByRef vSummaryArray As Object) As Integer

        Dim result As Integer = 0


        Try


            ' {* USER DEFINED CODE (Begin) *}

            ' Initialise the summary array with the number of
            ' items needed to be returned.
            ' Note: Remember arrays are zero based.
            'eck050402
            '   ReDim vKeyArray(1, 0)
            ' Assign the key array with the parameter members.
            '    vSummaryArray(PMKeyName, 0) = PMKeyNameNavigatorTitle1
            '    vSummaryArray(PMKeyValue, 0) = m_sNavigatorTitle$
            'eck050402end

            ' {* USER DEFINED CODE (End) *}

            Return gPMConstants.PMEReturnCode.PMTrue

        Catch excep As System.Exception




            result = gPMConstants.PMEReturnCode.PMError

            ' Log Error Message
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="GetSummary Failed", vApp:=ACApp, vClass:=ACClass, vMethod:="GetSummary", vErrNo:=Information.Err().Number, vErrDesc:=excep.Message, excep:=excep)

            Return result

        End Try
    End Function

    ' ***************************************************************** '
    ' Name: SetProcessModes (Standard Method)
    '
    ' Description: Set the optional process modes.
    '
    ' ***************************************************************** '
    Public Function SetProcessModes(Optional ByRef vTask As Object = Nothing, Optional ByRef vNavigate As Object = Nothing, Optional ByRef vProcessMode As Object = Nothing, Optional ByRef vTransactionType As Object = Nothing, Optional ByRef vEffectiveDate As Object = Nothing) As Integer

        Dim result As Integer = 0
        Try

            result = gPMConstants.PMEReturnCode.PMTrue

            ' Assign the process modes to the property members.


            If Not Information.IsNothing(vTask) Then

                m_iTask = CInt(vTask)
            End If


            If Not Information.IsNothing(vNavigate) Then

                m_lNavigate = CInt(vNavigate)
            End If


            If Not Information.IsNothing(vProcessMode) Then

                m_lProcessMode = CInt(vProcessMode)
            End If


            If Not Information.IsNothing(vTransactionType) Then

                m_sTransactionType = CStr(vTransactionType)
            End If


            If Not Information.IsNothing(vEffectiveDate) Then

                m_dtEffectiveDate = CDate(vEffectiveDate)
            End If

            Return result

        Catch excep As System.Exception




            result = gPMConstants.PMEReturnCode.PMError

            ' Log Error Message
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="SetProcessModes Failed", vApp:=ACApp, vClass:=ACClass, vMethod:="SetProcessModes", vErrNo:=Information.Err().Number, vErrDesc:=excep.Message, excep:=excep)

            Return result

        End Try
    End Function

    ' ***************************************************************** '
    ' Name: Start (Standard Method)
    '
    ' Description: Entry point for the object to start its processing.
    '
    ' ***************************************************************** '
    Public Function Start() As Integer

        Dim result As Integer = 0
        Try

            result = gPMConstants.PMEReturnCode.PMTrue

            ' Starts the interface processing.
            m_lReturn = ProcessInterface()

            ' Check for errors.
            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                ' Failed to process the interface.
                result = gPMConstants.PMEReturnCode.PMFalse
            End If

            Return result

        Catch excep As System.Exception

            result = gPMConstants.PMEReturnCode.PMError

            ' Log Error.
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Failed to start the object", vApp:=ACApp, vClass:=ACClass, vMethod:="Start", vErrNo:=Information.Err().Number, vErrDesc:=excep.Message, excep:=excep)

            Return result

        End Try
    End Function
    ' PUBLIC Methods (End)

    ' PRIVATE Methods (Begin)

    ' ***************************************************************** '
    '
    ' Name: PrintDocument
    '
    ' Description: Calls the print document function in the interface
    '
    ' History: 13/06/2000 CTAF - Created.
    '        :      27/11/2003 SET - improved the error reporting for this
    '                                function.
    '
    ' ***************************************************************** '
    Private Function PrintDocument() As Integer

        Dim result As Integer = 0
        Const ARCHIVE_AS_PDF As Integer = 5009
        Dim msgReply As DialogResult
        Dim sArchiveAsPDF As String = ""



        result = gPMConstants.PMEReturnCode.PMTrue

        If m_bSpoolDocument Then
            m_lMode = gSIRLibrary.ACSpoolDocMode
        End If


        ' Get system option EmailDocsAsPDF
        m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=ARCHIVE_AS_PDF, r_sOptionValue:=sArchiveAsPDF, v_iSourceID:=g_iSourceID)

        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        'If m_bArchiveWithNoPrint = True Then
        '   If sArchiveAsPDF = "1" Then
        '       'Do Nothing : PN67439 (To avoid duplicate archive)
        '   Else
        '       m_lMode = ACArchiveSilentMode
        '   End If




        ' Silent or verbose?

        Select Case m_lMode
            Case gSIRLibrary.ACPrintMode
                ' Call PrintDocument on the form
                m_lReturn = frmInterface.PrintDocument()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Print document failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

                'AR20050201 - PN18424   Ask user if they want to Spool the document
                '                       (suppress deletion of dependency files in case need to archive)
                msgReply = MessageBox.Show("Do You Wish To Spool This Document?", "Spool", MessageBoxButtons.YesNo, MessageBoxIcon.Question)

                If msgReply = System.Windows.Forms.DialogResult.Yes Then
                    m_lReturn = frmInterface.SpoolDocument()
                    If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                        result = gPMConstants.PMEReturnCode.PMFalse
                        iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                        Return result
                    End If
                End If

                'PN 17576 Asking for confirmation to archieve
                msgReply = MessageBox.Show("Do You Wish To Archive This Document?", "Archive", MessageBoxButtons.YesNo, MessageBoxIcon.Question)

                If msgReply = System.Windows.Forms.DialogResult.Yes Then
                    m_lReturn = frmInterface.ArchiveDocument()
                    If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                        result = gPMConstants.PMEReturnCode.PMFalse
                        iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Archive document failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                        Return result
                    End If
                End If

            Case gSIRLibrary.ACPrintSilentMode
                ' Call PrintDocument on the form
                m_lReturn = frmInterface.PrintDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Print document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

                'KB 17/0/6/2003 PN 4264 1.8.5 -> 1.8.6 catchup

                'MKW 030303 PN2507.  Archieve documents on Navigator Roadmap.
                m_lReturn = frmInterface.ArchiveDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Archive document failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If


                'KB 17/0/6/2003 PN 4264 1.8.5 -> 1.8.6 catchup end

            Case gSIRLibrary.ACSpoolDocMode, gSIRLibrary.ACSpoolReportMode


                'CLG RFC71 2004-09-01 start
                'also archive document if option selected
                If m_lArchiveMode = 1 Then
                    frmInterface.ArchiveAfterPrinting = True
                End If
                'CLG RFC71 2004-09-01 end

                ' RS201101 - Call SpoolDocument on the form
                'If sArchiveAsPDF = "1" Or m_bArchiveWithNoPrint Then
                If m_bArchiveWithNoPrint Then
                    frmInterface.ArchiveAfterPrinting = True
                    m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                Else
                    m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                End If
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACArchiveSilentMode
                ' Call PrintDocument on the form
                m_lReturn = frmInterface.ArchiveDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Archive document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If


                If m_bEmailAsBody Then
                    m_lReturn = frmInterface.EmailDocumentSilent()
                    If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                        gPMFunctions.RaiseError("PrintDocument", "Email Document(Silent) Failed")
                    End If
                End If


                If m_bSpoolDocument Then
                    m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName, 1)
                    If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                        gPMFunctions.RaiseError("PrintDocument", "SpoolDocument Failed")
                    End If
                End If


            Case ACPrintOnlySilentMode
                ' Call PrintDocument on the form
                m_lReturn = frmInterface.PrintDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Print document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACPrintSpoolArchiveSilentMode
                ' Call PrintDocument on the form
                m_bArchiveAfterPrinting = True
                frmInterface.ArchiveAfterPrinting = True

                m_lReturn = frmInterface.PrintDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Print document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

                m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACPrintSpoolSilentMode
                ' Call PrintDocument on the form
                m_bArchiveAfterPrinting = False

                m_lReturn = frmInterface.PrintDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Print document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)
                    Return result

                End If
                m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACSpoolArchiveSilentMode

                m_bArchiveAfterPrinting = True
                frmInterface.ArchiveAfterPrinting = True

                m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACSpoolSilentMode
                m_bArchiveAfterPrinting = False

                'Call SpoolDocument on the form
                m_lReturn = frmInterface.SpoolDocument(m_sSpoolDesc, m_sDocName)
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    result = gPMConstants.PMEReturnCode.PMFalse
                    iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Spool document (silent) failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                    Return result
                End If

            Case ACEmailOnlySilent
                m_lReturn = frmInterface.EmailDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    gPMFunctions.RaiseError("PrintDocument", "Email Document(Silent) Failed")
                End If

            Case Else
                'Should be unreachable check the mode set.
                result = gPMConstants.PMEReturnCode.PMError
                iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="PrintDocument Failed unknown mode = " & m_lMode, vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)
                Return result

        End Select

        If m_bEmailAsBody Then
            If m_lMode = gSIRLibrary.ACPrintMode Or m_lMode = gSIRLibrary.ACPrintSilentMode Or m_lMode = gSIRLibrary.ACSpoolDocMode Or m_lMode = gSIRLibrary.ACSpoolReportMode Or m_lMode = ACPrintSpoolArchiveSilentMode Or m_lMode = ACPrintSpoolSilentMode Or m_lMode = ACSpoolArchiveSilentMode Then

                m_lReturn = frmInterface.EmailDocumentSilent()
                If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                    gPMFunctions.RaiseError("PrintDocument", "Email Document(Silent) Failed")
                End If

            End If
        End If


        'AK 110402 - check if there is a attached work manager task for this template
        '            if yes, create a workmanager task instance
        'MKW 281003 PN7287 1.8.5 to 1.8.6 Catchup START
        If m_bAutoGenerateDocumentTask Then
            m_lReturn = frmInterface.CreateTask()
            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                result = gPMConstants.PMEReturnCode.PMFalse
                iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Create task failed", vApp:=ACApp, vClass:=ACClass, vMethod:="PrintDocument", vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description)

                Return result
            End If
        End If
        'MKW 281003 PN7287 1.8.5 to 1.8.6 Catchup END


        Return result

    End Function


    ' ***************************************************************** '
    ' Name: ProcessInterface (Standard Method)
    '
    ' Description: Calls the appropriate methods to process the
    '              interface.
    '
    ' ***************************************************************** '
    Private Function ProcessInterface() As Integer

        Dim result As Integer = 0


        result = gPMConstants.PMEReturnCode.PMTrue

        'sj 23/10/2002 - start
        Dim vValue As String = ""
        'sj 23/10/2002 - end

        'RWH(18/10/2000) Check Word Versions.
        ' SET 18/10/2004 ISS13245 - use global function
        'm_lReturn = GetWordVersion(m_sWordVersion)

        'If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
        '    Return gPMConstants.PMEReturnCode.PMFalse
        'End If

        'sj 23/10/2002 - start
        'Check product option to see if we need to interface with "FISH"
        m_lReturn = iPMFunc.getProductOptionValue(v_vOptionNumber:=gPMConstants.SIRHiddenOptions.SIROPTFishInstalled, v_vBranch:=g_iSourceID, r_vUnderwriting:=vValue)
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="getProductOptionValue Failed for option " & gPMConstants.SIRHiddenOptions.SIROPTValidateAlternativeIdentifier, vApp:=ACApp, vClass:=ACClass, vMethod:="ProcessInterface")
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        m_bFishRequired = vValue = "1"
        'sj 23/10/2002 - end

        ' Load the interface into memory.
        m_lReturn = LoadInterface()

        ' Check for errors.
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            ' Failed to load the interface.
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        ' CTAF 130600
        ' Do we want to display the interface, or just print the document?
        ' rs201101 - or spool the document
        'DN 23/04/03 - Also Spool Report
        Select Case m_lMode
            Case gSIRLibrary.ACPrintMode, gSIRLibrary.ACPrintSilentMode, gSIRLibrary.ACSpoolDocMode, gSIRLibrary.ACSpoolReportMode, ACArchiveSilentMode, ACPrintOnlySilentMode, ACPrintSpoolArchiveSilentMode, ACPrintSpoolSilentMode, ACSpoolArchiveSilentMode, ACSpoolSilentMode

                ' Print it
                m_lReturn = PrintDocument()

                ' Default to OK click
                frmInterface.Status = gPMConstants.PMEReturnCode.PMOK

            Case Else
                If m_lKeepOnTop = 1 Then
                    m_lReturn = iPMFunc.SetWindowPlacement(frmInterface.Handle.ToInt32(), True)
                End If

                ' Display the interface.
                If Not m_bFormlessDocument Then
                    m_lReturn = ShowInterface(lDisplayState:=FormShowConstants.Modal)
                End If

        End Select

        ' Check for errors.
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            ' Failed to display the inteface.
            result = gPMConstants.PMEReturnCode.PMFalse
        End If

        ' Destroy the interface from memory.
        m_lReturn = UnLoadInterface()

        ' Check for errors.
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            ' Failed to unload the interface.
            result = gPMConstants.PMEReturnCode.PMFalse
        End If

        Return result

    End Function
    ' ***************************************************************** '
    '
    ' Name: SpoolAsHtml
    '
    ' Description:
    '
    ' History: 14/10/2002 sj - Created.
    '
    ' ***************************************************************** '
    Private Function SpoolAsHtml() As Boolean

        Dim result As Boolean = False



        Dim vValue As Object

        m_lReturn = iPMFunc.getProductOptionValue(v_vOptionNumber:=gPMConstants.SIRHiddenOptions.SIROPTSpoolAsHTML, v_vBranch:=g_iSourceID, r_vUnderwriting:=vValue)
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="getProductOptionValue Failed for option " & gPMConstants.SIRHiddenOptions.SIROPTSpoolAsHTML, vApp:=ACApp, vClass:=ACClass, vMethod:="SpoolAsHtml")
            Return result
        End If


        If gPMFunctions.ToSafeInteger(vValue) = 1 Then
            Return True
        Else
            Return False
        End If
    End Function
    ' ***************************************************************** '
    ' Name: LoadInterface (Standard Method)
    '
    ' Description: Loads the instance of the interface into memory and
    '              passes the parameters in.
    '
    ' ***************************************************************** '
    Private Function LoadInterface() As Integer

        ' RDC 27/09/2005
        Dim result As Integer = 0
        Dim sAutoArchive As String
        Dim sArchiveAsPDF As String
        Dim sEmailDocsAsPDF As String
        'PN68078
        Dim sDocumentDescription As String = ""

        Const AUTO_ARCHIVE_ENABLED As Integer = 5008
        Const ARCHIVE_AS_PDF As Integer = 5009
        Const EMAIL_DOCS_AS_PDF As Integer = 5010

        Dim sCCMDocProduction As String = ""
        Dim sCCMRepStatusID As String = ""

        result = gPMConstants.PMEReturnCode.PMTrue

        ' Get system option auto-archive
        m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=AUTO_ARCHIVE_ENABLED, r_sOptionValue:=sAutoArchive, v_iSourceID:=g_iSourceID)

        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        ' Get system option EmailDocsAsPDF
        m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=EMAIL_DOCS_AS_PDF, r_sOptionValue:=sEmailDocsAsPDF, v_iSourceID:=g_iSourceID)

        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        ' Get system option EmailDocsAsPDF
        m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=ARCHIVE_AS_PDF, r_sOptionValue:=sArchiveAsPDF, v_iSourceID:=g_iSourceID)

        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            Return gPMConstants.PMEReturnCode.PMFalse
        End If

        ' Get system option CCMDocProduction
        m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionDocumentProductionSystem, r_sOptionValue:=sCCMDocProduction, v_iSourceID:=g_iSourceID)

        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            Return gPMConstants.PMEReturnCode.PMFalse
        End If
        If sCCMDocProduction = "1" Then
            m_bCCMDocProduction = True

            ' Get system option CCMWebServiceURL
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMWebServiceURL, r_sOptionValue:=m_sCCMWebServiceURL, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option CCMCustomer
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMCustomer, r_sOptionValue:=m_sCCMCustomer, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option CCMPartner
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMPartner, r_sOptionValue:=m_sCCMPartner, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option CCMContractTypeName
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMContractTypeName, r_sOptionValue:=m_sCCMContractTypeName, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option RepositoryProj
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMRepositoryProject, r_sOptionValue:=m_sCCMRepositoryProject, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option CCMContractTypeVersion
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMContractTypeVersion, r_sOptionValue:=m_sCCMContractTypeVersion, v_iSourceID:=g_iSourceID)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            ' Get system option CCMRepStatus
            m_lReturn = iPMFunc.GetSystemOption(v_iOptionNumber:=kSystemOptionCCMStatus, r_sOptionValue:=sCCMRepStatusID, v_iSourceID:=g_iSourceID)
            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                Return gPMConstants.PMEReturnCode.PMFalse
            End If

            m_sCCMRepStatus = CType(ToSafeInteger(sCCMRepStatusID), CCMStatusDesc).ToString()
        Else
            m_bCCMDocProduction = False
        End If

        m_lReturn = g_oBusiness.GetFurtherDetails(v_lDocTemplateId:=m_lDocumentTemplateId, r_bArchiveWithNoPrint:=m_bArchiveWithNoPrint, _
                                                  r_bEmailAsBody:=m_bEmailAsBody, r_bSpoolDocument:=m_bSpoolDocument, r_bArchiveAsText:=m_bArchiveAsText, _
                                                  r_sDocumentDescription:=sDocumentDescription, r_bArchiveAsXML:=m_bArchiveAsXML, r_sCCMDocumentName:=m_sCCMDocumentName)
        If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
            gPMFunctions.RaiseError("LoadInterface", "GetFurtherDetails Failed", gPMConstants.PMELogLevel.PMLogError)
        End If

        If Not m_bFormlessDocument Then
            frmInterface = New frmInterface()
        Else
            frmInterface = New iPMBDocTemplateFormless
        End If

        ' Assign the parameters to the interface properties.
        With frmInterface
            .CallingAppName = m_sCallingAppName
            .Task = m_iTask
            .Navigate = m_lNavigate
            .ProcessMode = m_lProcessMode
            .TransactionType = m_sTransactionType
            .EffectiveDate = m_dtEffectiveDate

            ' {* USER DEFINED CODE (Begin) *}
            .DocumentTemplateId = m_lDocumentTemplateId
            .DocumentTypeId = m_lDocumentTypeId
            .Mode = m_lMode
            .PartyCnt = m_lPartyCnt
            .InsuranceFileCnt = m_lInsuranceFileCnt
            .InsuranceFolderCnt = m_lInsuranceFolderCnt
            .ClaimCnt = m_lClaimCnt
            .DocumentRef = m_sDocumentRef
            .EventCnt = m_lEventCnt
            .WordVersion = m_sWordVersion
            .FromBatchTrans = m_bFromBatchTrans
            .FishRequired = m_bFishRequired
            .SpoolAsHtml = SpoolAsHtml() Or (sArchiveAsPDF = "1")
            .PolicySharesArray = m_vPolicySharesArray
            .ArchiveAfterPrinting = m_bArchiveAfterPrinting            
            'PN68078
            If m_sDocumentDescription = "" Then
                m_sDocumentDescription = sDocumentDescription
            End If
            .DocumentDescription = m_sDocumentDescription
            .FSAComplaintFolderCnt = m_lFSAComplaintFolderCnt
            .FSAComplaintReference = m_sFSAComplaintReference
            .ParameterXML = m_sParameterXML
            .DocumentFilter = m_sDocumentFilter
            .AutoArchiveEnabled = (sAutoArchive = "1")
            .EmailDocsAsPDF = (sEmailDocsAsPDF = "1")
            .ArchiveAsPDF = (sArchiveAsPDF = "1")
            .RiskCnt = m_lRiskCnt
            'Renewal Printing
            .IsAgent = m_iIsAgent
            .IsClient = m_iIsClient
            .IsOffice = m_iIsOffice
            .ProductionOrder = m_iProductionOrder
            .ArchiveAsText = m_bArchiveAsText
            .ArchiveAsXML = m_bArchiveAsXML

            .CalledFromGetDocument = m_bCalledFromGetDocument ' PN66227

            .DocFileExtension = "XML"
            .FieldStartMarker = "&lt;@"
            .FieldEndMarker = "@&gt;"
            .WordVersion = 11
            If Not m_bFormlessDocument Then
                .IsCCMDocProduction = m_bCCMDocProduction
                .CCMCustomer = m_sCCMCustomer
                .CCMPartner = m_sCCMPartner
                .CCMContractTypeName = m_sCCMContractTypeName
                .CCMRepositoryProject = m_sCCMRepositoryProject
                .CCMContractTypeVersion = m_sCCMContractTypeVersion
                .CCMDocumentName = m_sCCMDocumentName
                .CCMWebServiceURL = m_sCCMWebServiceURL
                .CCMRepStatus = m_sCCMRepStatus
                .ViewTask = m_bView
                .IsNonBatchProcess = m_bIsNonBatchProcess
            End If
            .bformlessDocument = m_bFormlessDocument
            ' {* USER DEFINED CODE (End) *}
        End With

        ' Load the instance of the interface into memory.
        frmInterface.frmInterfaceLoad()

        ' Check if we have had an error so far.
        If frmInterface.ErrorNumber = gPMConstants.PMEReturnCode.PMFalse Then
            ' We have already encountered an error,
            ' so we MUST return the error.
            result = frmInterface.ErrorNumber
        End If

        Return result

    End Function
    ''' <summary>
    ''' Unloads the instance of the interface from memory
    ''' </summary>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Private Function UnLoadInterface() As Integer

        Dim result As Integer = 0


        result = gPMConstants.PMEReturnCode.PMTrue

        'make sure word is closed
        m_lReturn = frmInterface.ShutItDown()

        ' Assign the property members from the interface parameters.
        With frmInterface
            m_lStatus = .Status
            m_sStepStatus = .StepStatus

            ' {* USER DEFINED CODE (Begin) *}
            m_lDocumentTemplateId = .DocumentTemplateId
            m_sDocumentTemplateCode = .DocumentTemplateCode
            m_sDocumentTemplateDescription = .DocumentTemplateDescription
            m_lDocumentTypeId = .DocumentTypeId
            m_sDocumentTypeCode = .DocumentTypeCode
            m_sDocumentTypeDescription = .DocumentTypeDescription
            m_sDocumentFilter = .DocumentFilter
            m_bIsDocumentEdited = .IsDocumentEdited

            ' {* USER DEFINED CODE (End) *}

        End With

        ' Unload and destroy the instance of the interface
        ' from memory.
        frmInterface.Close()
        frmInterface.Dispose()
        frmInterface = Nothing

        Return result

    End Function

    ' ***************************************************************** '
    ' Name: ShowInterface (Standard Method)
    '
    ' Description: Displays the instance of the interface using the
    '              display state.
    '
    ' ***************************************************************** '
    Private Function ShowInterface(ByRef lDisplayState As Integer) As Integer

        Dim result As Integer = 0


        result = gPMConstants.PMEReturnCode.PMTrue

        ' Display the interface.
        VB6.ShowForm(frmInterface, lDisplayState)

        If lDisplayState = FormShowConstants.Modal Then
            ' Check for any form errors.
            If frmInterface.ErrorNumber <> 0 Then
                result = frmInterface.ErrorNumber
            End If
        End If

        Return result

    End Function
    'PRIVATE Methods (End)


    Public Sub New()
        MyBase.New()

        ' Class Initialise Event.

        'UPGRADE_NOTE: (7001) The following code block (empty try-catch) seems to be dead code More Information: http://www.vbtonet.com/ewis/ewi7001.aspx
        'Try 
        '
        'Catch excep As System.Exception
        '
        '
        '
        '
        ' Log Error Message
        'gPMFunctions.LogMessagePopup(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:="Failed to initialise the interface entry class", vApp:=ACApp, vClass:=ACClass, vMethod:="Class_Initialise", vErrNo:=CStr(Information.Err().Number), vErrDesc:=excep.Message)
        '
        'Exit Sub
        '


    End Sub

    Protected Overrides Sub Finalize()
        Dispose(False)
    End Sub



    ' ***************************************************************** '
    '
    ' Name: EstablishLocalWordVersion
    '
    ' Description: To deal with different versions of word which may
    '               behave very differently and store documents in
    '               differing formats.
    '
    ' History: 18/10/2000 RWH - Created.
    '
    ' ***************************************************************** '
    'Private Function EstablishLocalWordVersion() As Long
    'Dim oWord As Object
    '
    '    On Error GoTo Err_EstablishLocalWordVersion
    '
    '    EstablishLocalWordVersion = PMTrue
    '
    '    If (m_sWordVersion <> "") Then
    '        Exit Function
    '    End If
    '
    '    'Launch Word.
    '    Set oWord = CreateObject("word.application")
    '    m_sWordVersion = oWord.Version
    '    oWord.Quit
    '    Set oWord = Nothing
    '
    '    Exit Function
    '
    'Err_EstablishLocalWordVersion:
    '
    '    EstablishLocalWordVersion = PMError
    '
    '    ' Log Error Message
    '    LogMessage _
    ''        iType:=PMLogOnError, _
    ''        sMsg:="EstablishLocalWordVersion Failed", _
    ''        vApp:=ACApp, _
    ''        vClass:=ACClass, _
    ''        vMethod:="EstablishLocalWordVersion", _
    ''        vErrNo:=Err.Number, _
    ''        vErrDesc:=Err.Description
    '
    '    Exit Function
    '


    '' ***************************************************************** '
    ''
    '' Name: SetWordVersionDependentVariables
    ''
    '' Description: To deal with different versions of word which may
    ''               behave very differently and store documents in
    ''               differing formats.
    ''
    '' History: 18/10/2000 RWH - Created.
    ''
    '' ***************************************************************** '
    'Private Function SetWordVersionDependentVariables() As Long
    'Dim sTitle As String
    'Dim sMessage As String
    '
    '    On Error GoTo Err_SetWordVersionDependentVariables
    '
    '    SetWordVersionDependentVariables = PMTrue
    '
    '    Select Case Left$(m_sWordVersion, 1)
    '        Case "8"    'Word 97
    '            With frmInterface
    '                .DocFileExtension = "doc"
    '                .FieldStartMarker = "<@"
    '                .FieldEndMarker = "@>"
    '            End With
    '
    '        Case "9"    'Word 2000
    '            With frmInterface
    '                .DocFileExtension = "htm"
    '                .FieldStartMarker = "&lt;@"
    '                .FieldEndMarker = "@&gt;"
    '            End With
    '
    '        Case Else
    '            SetWordVersionDependentVariables = PMFalse
    '            ' Get description from the resource file.
    '            sTitle$ = GetResData( _
    ''                iLangID:=g_iLanguageID%, _
    ''                lID:=ACInterfaceTitle, _
    ''                iDataType:=PMResString)
    '
    '            sMessage$ = GetResData( _
    ''                iLangID:=g_iLanguageID%, _
    ''                lID:=ACUnsupportedWordVersion, _
    ''                iDataType:=PMResString)
    '
    '            ' Display message.
    '            MsgBox sMessage$, vbCritical, sTitle$
    '
    '            Exit Function
    '
    '    End Select
    '
    '    Exit Function
    '
    'Err_SetWordVersionDependentVariables:
    '
    '    SetWordVersionDependentVariables = PMError
    '
    '    ' Log Error Message
    '    LogMessage _
    ''        iType:=PMLogOnError, _
    ''        sMsg:="SetWordVersionDependentVariables Failed", _
    ''        vApp:=ACApp, _
    ''        vClass:=ACClass, _
    ''        vMethod:="SetWordVersionDependentVariables", _
    ''        vErrNo:=Err.Number, _
    ''        vErrDesc:=Err.Description
    '
    '    Exit Function
    '





    ''This Function is not a new function. It has been moved from bSIRRenewal

    Public Function SendEMail(ByVal v_sTo As String, ByVal v_sSubject As String, ByVal v_sMessagePath As String, ByVal v_sAttachment As String) As Integer

        Dim result As Integer = 0
        Dim sch As String = ""

        Dim cdoMail As CDO.Message
        Dim cdoConf As CDO.Configuration

        Dim sSMTPEmailServer, sSMTPEmailPort, sSMTPEmailFrom As String

        Dim sFailMsg As String = ""

        Const SMTP_Email_Server As Integer = 5045
        Const SMTP_Email_Port As Integer = 5046
        Const SMTP_Email_From As Integer = 5047

        Const kMethodName As String = "SendEMail"

        result = gPMConstants.PMEReturnCode.PMTrue

        Try

            cdoMail = New CDO.Message()
            cdoConf = New CDO.Configuration()

            cdoMail.Subject = v_sSubject

            ' Get System Option (SMTP Email From)
            m_lReturn = iPMFunc.GetSystemOption(v_iSourceID:=g_iSourceID, v_iOptionNumber:=SMTP_Email_From, r_sOptionValue:=sSMTPEmailFrom)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                sFailMsg = "Failed to get the System option SMTP_Email_From"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)
            End If

            If sSMTPEmailFrom = "" Then
                ' option not populated, no action
                sFailMsg = "Invalid SMTP"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)

            End If

            ' Get System Option (SMTP Email Server)
            m_lReturn = iPMFunc.GetSystemOption(v_iSourceID:=g_iSourceID, v_iOptionNumber:=SMTP_Email_Server, r_sOptionValue:=sSMTPEmailServer)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                sFailMsg = "Failed to get the System option SMTP_Email_Server"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)
            End If

            If sSMTPEmailServer = "" Then
                ' option not populated, no action
                sFailMsg = "Invalid SMTP"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)

            End If

            ' Get System Option (SMTP Email Port)
            m_lReturn = iPMFunc.GetSystemOption(v_iSourceID:=g_iSourceID, v_iOptionNumber:=SMTP_Email_Port, r_sOptionValue:=sSMTPEmailPort)

            If m_lReturn <> gPMConstants.PMEReturnCode.PMTrue Then
                sFailMsg = "Failed to get the System option SMTP_Email_Port"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)
            End If

            If sSMTPEmailPort = "" Then
                ' option not populated, no action
                sFailMsg = "Invalid SMTP"
                result = gPMConstants.PMEReturnCode.PMFalse
                Throw New Exception(sFailMsg)

            End If

            cdoMail.From = sSMTPEmailFrom
            cdoMail.To = v_sTo

            Dim fileInfo As FileInfo = New FileInfo(v_sMessagePath)
            fileInfo.Attributes = FileAttribute.Normal
            cdoMail.CreateMHTMLBody("file://" & v_sMessagePath)

            If v_sAttachment <> "" Then
                cdoMail.AddAttachment(v_sAttachment)
            End If

            sch = "http://schemas.microsoft.com/cdo/configuration/"

            'Modified by Sudhanshu Behera on 5/5/2010 1:16:32 PM refer developer guide no. 49 (no solution)
            'cdoConf.Fields(sch & "sendusing") = 2
            'cdoConf.Fields(sch & "sendusing") = 2
            'cdoConf.Fields(sch & "smtpserver") = sSMTPEmailServer
            'cdoConf.Fields(sch & "smtpserverport") = sSMTPEmailPort
            'cdoConf.Fields(sch & "smtpauthenticate") = 0
            'cdoConf.Fields.Update()

            cdoMail.Configuration = cdoConf

            cdoMail.Send()


            cdoMail = Nothing
            cdoConf = Nothing




        Catch ex As Exception

            iPMFunc.LogMessage(iType:=gPMConstants.PMELogLevel.PMLogOnError, sMsg:=sFailMsg, vApp:=ACApp, vClass:=ACClass, vMethod:=kMethodName, vErrNo:=Information.Err().Number, vErrDesc:=Information.Err().Description, excep:=ex)
        Finally


        End Try
        Return result
    End Function

End Class

