SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spu_Void_Risk_Tax_Fee_Copy'
GO

CREATE PROCEDURE spu_Void_Risk_Tax_Fee_Copy  
 @risk_cnt INT,  
 @insurance_File_Cnt INT,  
 @source_risk_cnt INT,  
 @source_insurance_file_cnt INT  
AS  
BEGIN  
  
 -- DELETE Current Risk Taxes if there are any  
 DELETE Tax_Calculation  
        WHERE risk_cnt = @risk_cnt AND insurance_file_cnt = @Insurance_File_Cnt AND transtype IN('TTR','TTIF','TTRITP','TTRIFP','TTF')
  
 -- Copy the taxes between two versions  
 INSERT INTO Tax_Calculation  
           (risk_cnt,  
           tax_band_id,  
           premium,  
           percentage,  
           value,  
           is_value,  
           is_manually_changed,  
           Calc_Basis,  
           Basis_Value,  
           Sum_Insured,  
           Sum_Insured_Rounded,  
           currency_id,  
           allow_tax_credit,  
           original_sum_insured,  
           country_id,  
           state_id,  
           class_of_business_id,  
           tax_group_id,  
           sequence,  
           insurance_file_cnt,  
           transtype,  
           policy_fee_u_id,  
           agent_commission_cnt,  
           ri_party_cnt,  
           ri_arrangement_line_id,  
           insurance_section_id,  
           policy_fee_id,  
           policy_agents_id,  
           insurer_party_cnt,  
           claim_peril_id,  
           claim_payment_id,  
           claim_receipt_id,  
           claim_payment_item_id,  
           claim_receipt_item_id,  
           is_not_applied_to_client,  
           include_tax_in_instalments,  
           spread_tax_across_instalments,  
           base_tax_calculation_cnt,  
           version_id,  
           pfprem_finance_cnt,  
           pfprem_finance_version,  
           policy_coinsurers_section_id,  
           is_commission_tax,  
           apply_tax_by,  
           tax_band_rate_id,  
           is_suspended)  
     SELECT @risk_cnt,  
           tax_band_id,  
           premium * -1,  
           percentage,  
           value * -1,  
           is_value,  
           is_manually_changed,  
           Calc_Basis,  
           Basis_Value,  
           Sum_Insured,  
           Sum_Insured_Rounded,  
           currency_id,  
           allow_tax_credit,  
           original_sum_insured,  
           country_id,  
           state_id,  
           class_of_business_id,  
           tax_group_id,  
           sequence,  
           @insurance_File_Cnt,  
           transtype,  
           policy_fee_u_id,  
           agent_commission_cnt,  
           ri_party_cnt,  
           ri_arrangement_line_id,  
           insurance_section_id,  
           policy_fee_id,  
           policy_agents_id,  
           insurer_party_cnt,  
           claim_peril_id,  
           claim_payment_id,  
           claim_receipt_id,  
           claim_payment_item_id,  
           claim_receipt_item_id,  
           is_not_applied_to_client,  
           include_tax_in_instalments,  
           spread_tax_across_instalments,  
           base_tax_calculation_cnt,  
           version_id,  
           pfprem_finance_cnt,  
           pfprem_finance_version,  
           policy_coinsurers_section_id,  
           is_commission_tax,  
           apply_tax_by,  
           tax_band_rate_id,  
           is_suspended  
   FROM    Tax_Calculation  WITH (NOLOCK)
   WHERE   risk_cnt = @source_risk_cnt  
   AND   insurance_file_cnt = @source_insurance_file_cnt  

   DELETE FROM policy_fee_u WHERE risk_cnt=@risk_cnt

   INSERT INTO policy_fee_u (
		insurance_file_cnt,
		party_cnt,
		fee_rate_percentage,
		fee_rate_amount,
		currency_id,
		transaction_type_id,
		product_id,
		branch_id,
		risk_cnt,
		base_currency_id,
		base_fee_amount,
		base_tax_amount,
		currency_amount,
		currency_tax_amount,
		risk_type_group_id,
		peril_group_id,
		tax_group_id,
		transaction_sub_type,
		is_fee_applied_to_cr,
		fee_rate_currency_id,
		Fee_Premium,
		include_fee_in_instalments,
		spread_fee_across_instalments,
		MakeLiveOptions_id,
		DoPaymentTerms_id,
		Calculation_Basis,
		Is_Prorated,
		Pro_rata_rate,
		Is_Override,
		FeeTypePercent)
    SELECT  @Insurance_File_Cnt,
			party_cnt,
			fee_rate_percentage,
			fee_rate_amount * -1,
			currency_id,
			transaction_type_id,
			product_id,
			branch_id,
			risk_cnt,
			base_currency_id,
			base_fee_amount * -1,
			base_tax_amount * -1,
			currency_amount * -1,
			currency_tax_amount * -1,
			risk_type_group_id,
			peril_group_id,
			tax_group_id,
			transaction_sub_type,
			is_fee_applied_to_cr,
			fee_rate_currency_id,
			Fee_Premium * -1,
			include_fee_in_instalments,
			spread_fee_across_instalments,
			MakeLiveOptions_id,
			DoPaymentTerms_id,
			Calculation_Basis,
			Is_Prorated,
			Pro_rata_rate,
			Is_Override,
			FeeTypePercent
    FROM    policy_fee_u WITH (NOLOCK)
    WHERE   risk_cnt = @source_risk_cnt 
	and insurance_file_cnt = @source_insurance_file_cnt

END  