SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_copy_event_to_file'
GO


CREATE PROCEDURE spu_copy_event_to_file
    @event_cnt INT,
    @insurance_file_cnt INT,
    @insurance_folder_cnt INT
AS

DECLARE
    @insurance_file_structure_id INT,
    @insurance_file_type_id INT,
    @insurance_file_status_id INT,
    @insurance_file_id INT,
    @source_id SMALLINT,
    @insurance_ref VARCHAR(30),
    @product_id INT,
    @lead_insurer_cnt INT,
    @lead_agent_cnt INT,
    @lead_agent_percent FLOAT,
    @account_handler_cnt INT,
    @insured_cnt INT,
    @business_type_id SMALLINT,
    @collect_type_id SMALLINT,
    @collection_from_cnt INT,
    @branch_id SMALLINT,
    @currency_id SMALLINT,
    @language_id SMALLINT,
    @date_issued DATETIME,
    @cover_start_date DATETIME,
    @expiry_date DATETIME,
    @renewal_date DATETIME,
    @renewal_method_id INT,
    @renewal_frequency_id SMALLINT,
    @is_referred_at_renewal TINYINT,
    @lapsed_reason_id INT,
    @lapsed_date DATETIME,
    @lapsed_description VARCHAR(255),
    @is_referred_on_mta TINYINT,
    @policy_version INT,
    @gemini_policy_status INT,
    @gemini_business_type INT,
    @deferred_ind INT,
    @policy_ignore INT,
    @broker_cnt INT,
    @risk_code_id INT,
    @Analysis_code_id INT,
    @proposal_date DATETIME,
    @diary_date DATETIME,
    @review_date DATETIME,
    @renewal_day_number INT,
    @Policy_type_id INT,
    @indicator CHAR(1),
    @clause CHAR(4),
    @cover CHAR(1),
    @area CHAR(1),
    @long_term_undertaking_date DATETIME,
    @renewal_stop_code_id INT,
    @vbs_type CHAR(2),
    @vbs_status CHAR(1),
    @is_insurer_rate_table TINYINT,
    @is_related_policies TINYINT,
    @is_retained_documents TINYINT,
    @schemes_postcode VARCHAR(8),
    @paid_direct CHAR(1),
    @scheme INT,
    @brokerage_amount MONEY,
    @is_minimum_brokerage_flag TINYINT,
    @annual_premium MONEY,
    @this_premium MONEY,
    @net_premium MONEY,
    @commission_amount MONEY,
    @iptable_amount MONEY,
    @ipt_percentage FLOAT,
    @is_ipt_overridden TINYINT,
    @tax_amount MONEY,
    @vatable_amount MONEY,
    @vat_percentage FLOAT,
    @vat_amount MONEY,
    @payment_method VARCHAR(60),
    @user_defined_data_id INT,
    @commission_percentage FLOAT,
    @invariant_key INT,
    @insured_name VARCHAR(100),
    @alternate_reference VARCHAR(80),
    @is_client_invoiced TINYINT,
    @old_policy_number VARCHAR(20),
    @quote_expiry_date DATETIME,
    @alternate_account_cnt INT,
    @account_executive_cnt INT,
    @anniversary_date DATETIME,
    @fsa_customer_category_id SMALLINT,
    @fsa_contract_location_id SMALLINT,
    @fsa_underwriter_cnt INT,
    @fsa_type_of_sale_id SMALLINT,
    @fsa_renewal_consent TINYINT,
    @policy_style_id INT,
    @underwriting_year_id INT,
    @policy_status_id INT,
    @edi_message_sent TINYINT,
    @return_premium_currency_id SMALLINT,
    @exchange_rate_override_reason_id INT,
    @base_currency_id SMALLINT,
    @currency_base_xrate FLOAT,
    @agent_account_currency_id SMALLINT,
    @agent_account_base_xrate FLOAT,
    @system_base_xrate FLOAT,
    @currency_base_date DATETIME,
    @account_base_date DATETIME,
    @system_base_date DATETIME,
    @inception_date_tpi DATETIME,
    @country_id smallint,
    @terms_agreed BIT,
    @terms_agreed_date DATETIME,
    @inception_Date DATETIME,
    @policy_documents_issued_date DATETIME,
    @policy_documents_correct BIT,
    @error_notification_date DATETIME,
    @risk_transfer_agreement BIT 

SELECT  
    @insurance_file_structure_id = insurance_file_structure_id,
    @insurance_file_type_id = insurance_file_type_id  ,
    @insurance_file_status_id = insurance_file_status_id,
    @insurance_file_id = insurance_file_id,
    @source_id = source_id,
    @insurance_ref = insurance_ref,
    @product_id = product_id,
    @lead_insurer_cnt = lead_insurer_cnt,
    @lead_agent_cnt = lead_agent_cnt,
    @lead_agent_percent = lead_agent_percent,
    @account_handler_cnt = account_handler_cnt,
    @insured_cnt = insured_cnt,
    @business_type_id = business_type_id,
    @collect_type_id = collect_type_id,
    @collection_from_cnt = collection_from_cnt,
    @branch_id = branch_id,
    @currency_id = currency_id,
    @language_id = language_id,
    @date_issued = date_issued,
    @cover_start_date = cover_start_date,
    @expiry_date = expiry_date,
    @renewal_date = renewal_date,
    @renewal_method_id = renewal_method_id,
    @renewal_frequency_id = renewal_frequency_id,
    @is_referred_at_renewal = is_referred_at_renewal,
    @lapsed_reason_id = lapsed_reason_id,
    @lapsed_date = lapsed_date,
    @lapsed_description = lapsed_description,
    @is_referred_on_mta = is_referred_on_mta,
    @policy_version = policy_version,
    @gemini_policy_status = gemini_policy_status,
    @gemini_business_type = gemini_business_type,
    @deferred_ind = deferred_ind,
    @policy_ignore = policy_ignore,
    @broker_cnt = broker_cnt,
    @risk_code_id = risk_code_id,
    @Analysis_code_id = Analysis_code_id,
    @proposal_date = proposal_date,
    @diary_date = diary_date,
    @review_date = review_date,
    @renewal_day_number = renewal_day_number,
    @Policy_type_id = Policy_type_id,
    @indicator = indicator,
    @clause = clause,
    @cover = cover,
    @area = area,
    @long_term_undertaking_date = long_term_undertaking_date,
    @renewal_stop_code_id = renewal_stop_code_id,
    @vbs_type = vbs_type,
    @vbs_status = vbs_status,
    @is_insurer_rate_table = is_insurer_rate_table,
    @is_related_policies = is_related_policies,
    @is_retained_documents = is_retained_documents,
    @schemes_postcode = schemes_postcode,
    @paid_direct = paid_direct,
    @scheme = scheme,
    @brokerage_amount = brokerage_amount,
    @is_minimum_brokerage_flag = is_minimum_brokerage_flag,
    @annual_premium = annual_premium,
    @this_premium = this_premium,
    @net_premium = net_premium,
    @commission_amount = commission_amount,
    @iptable_amount = iptable_amount,
    @ipt_percentage = ipt_percentage,
    @is_ipt_overridden = is_ipt_overridden,
    @tax_amount = tax_amount,
    @vatable_amount = vatable_amount,
    @vat_percentage = vat_percentage,
    @vat_amount = vat_amount,
    @payment_method = payment_method,
    @user_defined_data_id = user_defined_data_id,
    @commission_percentage = commission_percentage ,
    @invariant_key = invariant_key,
    @insured_name = insured_name,
    @alternate_reference = alternate_reference,
    @is_client_invoiced = is_client_invoiced,
    @old_policy_number = old_policy_number,
    @quote_expiry_date = quote_expiry_date,
    @alternate_account_cnt = alternate_account_cnt,
    @account_executive_cnt = account_executive_cnt,
    @anniversary_date = anniversary_date,
    @fsa_customer_category_id = fsa_customer_category_id,
    @fsa_contract_location_id = fsa_contract_location_id,
    @fsa_underwriter_cnt = fsa_underwriter_cnt,
    @fsa_type_of_sale_id = fsa_type_of_sale_id,
    @fsa_renewal_consent = fsa_renewal_consent,
    @policy_style_id = policy_style_id,
    @underwriting_year_id = underwriting_year_id,
    @policy_status_id = policy_status_id,
    @edi_message_sent = edi_message_sent,
    @return_premium_currency_id = return_premium_currency_id,
    @exchange_rate_override_reason_id = exchange_rate_override_reason_id,
    @base_currency_id = base_currency_id,
    @currency_base_xrate = currency_base_xrate,
    @agent_account_currency_id = agent_account_currency_id,
    @agent_account_base_xrate = agent_account_base_xrate,
    @system_base_xrate = system_base_xrate,
    @currency_base_date = currency_base_date,
    @account_base_date = account_base_date,
    @system_base_date = system_base_date,
    @inception_date_tpi = inception_date_tpi,
    @country_id= country_id,
    @terms_agreed = terms_agreed,
    @terms_agreed_date = terms_agreed_date,
    @inception_Date = inception_Date,
    @policy_documents_issued_date = policy_documents_issued_date,
    @policy_documents_correct = policy_documents_correct,
    @error_notification_date = error_notification_date,
    @risk_transfer_agreement = risk_transfer_agreement
FROM event_insurance_file
WHERE insurance_file_cnt = @event_cnt


UPDATE insurance_file
SET insurance_file_structure_id = @insurance_file_structure_id,
    insurance_file_type_id = @insurance_file_type_id,
    insurance_file_status_id = @insurance_file_status_id,
    insurance_file_id = @insurance_file_id,
    source_id = @source_id,
    insurance_folder_cnt = @insurance_folder_cnt,
    insurance_ref = @insurance_ref,
    product_id = @product_id,
    lead_insurer_cnt = @lead_insurer_cnt,
    lead_agent_cnt = @lead_agent_cnt,
    lead_agent_percent = @lead_agent_percent,
    account_handler_cnt = @account_handler_cnt,
    insured_cnt = @insured_cnt,
    business_type_id = @business_type_id,
    collect_type_id = @collect_type_id,
    collection_from_cnt = @collection_from_cnt,
    branch_id = @branch_id,
    currency_id = @currency_id,
    language_id = @language_id,
    date_issued = @date_issued,
    cover_start_date = @cover_start_date,
    expiry_date = @expiry_date,
    renewal_date = @renewal_date,
    renewal_method_id = @renewal_method_id,
    renewal_frequency_id = @renewal_frequency_id,
    is_referred_at_renewal = @is_referred_at_renewal,
    lapsed_reason_id = @lapsed_reason_id,
    lapsed_date = @lapsed_date,
    lapsed_description = @lapsed_description,
    is_referred_on_mta = @is_referred_on_mta,
    policy_version = @policy_version,
    gemini_policy_status = @gemini_policy_status,
    gemini_business_type = @gemini_business_type,
    deferred_ind = @deferred_ind,
    policy_ignore = @policy_ignore,
    broker_cnt = @broker_cnt,
    risk_code_id = @risk_code_id,
    Analysis_code_id = @analysis_code_id,
    proposal_date = @proposal_date,
    diary_date = @diary_date,
    review_date = @review_date,
    renewal_day_number = @renewal_day_number,
    Policy_type_id = @policy_type_id,
    indicator = @indicator,
    clause = @clause,
    cover = @cover,
    area = @area,
    long_term_undertaking_date = @long_term_undertaking_date,
    renewal_stop_code_id = @renewal_stop_code_id,
    vbs_type = @vbs_type,
    vbs_status = @vbs_status,
    is_insurer_rate_table = @is_insurer_rate_table,
    is_related_policies = @is_related_policies,
    is_retained_documents = @is_retained_documents,
    schemes_postcode = @schemes_postcode,
    paid_direct = @paid_direct,
    scheme = @scheme,
    brokerage_amount = @brokerage_amount,
    is_minimum_brokerage_flag = @is_minimum_brokerage_flag,
    annual_premium = @annual_premium,
    this_premium = @this_premium,
    net_premium = @net_premium,
    commission_amount = @commission_amount,
    iptable_amount = @iptable_amount,
    ipt_percentage = @ipt_percentage,
    is_ipt_overridden = @is_ipt_overridden,
    tax_amount = @tax_amount,
    vatable_amount = @vatable_amount,
    vat_percentage = @vat_percentage,
    vat_amount = @vat_amount,
    payment_method = @payment_method,
    user_defined_data_id = @user_defined_data_id,
    commission_percentage = @commission_percentage,
    invariant_key = @invariant_key,
    insured_name = @insured_name,
    alternate_reference = @alternate_reference,
    is_client_invoiced = @is_client_invoiced,
    old_policy_number = @old_policy_number,
    quote_expiry_date = @quote_expiry_date,
    alternate_account_cnt = @alternate_account_cnt,
    account_executive_cnt = @account_executive_cnt,
    anniversary_date = @anniversary_date,
    fsa_customer_category_id = @fsa_customer_category_id,
    fsa_contract_location_id = @fsa_contract_location_id,
    fsa_underwriter_cnt = @fsa_underwriter_cnt,
    fsa_type_of_sale_id = @fsa_type_of_sale_id,
    fsa_renewal_consent = @fsa_renewal_consent,
    policy_style_id = @policy_style_id,
    underwriting_year_id = @underwriting_year_id,
    policy_status_id = @policy_status_id,
    edi_message_sent = @edi_message_sent,
    return_premium_currency_id = @return_premium_currency_id,
    exchange_rate_override_reason_id = @exchange_rate_override_reason_id,
    base_currency_id = @base_currency_id,
    currency_base_xrate = @currency_base_xrate,
    agent_account_currency_id = @agent_account_currency_id,
    agent_account_base_xrate = @agent_account_base_xrate,
    system_base_xrate = @system_base_xrate,
    currency_base_date = @currency_base_date,
    account_base_date = @account_base_date,
    system_base_date = @system_base_date,
    inception_date_tpi = @inception_date_tpi,
    country_id=@country_id,
    terms_agreed = @terms_agreed,
    terms_agreed_date = @terms_agreed_date,
    inception_Date = @inception_Date,
    policy_documents_issued_date = @policy_documents_issued_date,
    policy_documents_correct = @policy_documents_correct,
    error_notification_date = @error_notification_date,
    risk_transfer_agreement = @risk_transfer_agreement
WHERE insurance_file_cnt = @insurance_file_cnt


GO


