Option Strict Off
Option Explicit On
Imports System
<System.Runtime.InteropServices.ProgId("GisSchemeConst_NET.GisSchemeConst")> _
 Public Module GisSchemeConst
	' ***************************************************************** '
	' Class Name: GisSchemeConst
	'
	' Date: 25/06/1999
	'
	' Description: Contains the Field Array positional constants for
	'              the GisScheme Interface and Business objects
	'
	' Edit History:JSB 27/07/01 - Added constants for insurer ABI numbers
	' ***************************************************************** '
	
	' {* GENERATED CODE (Begin) *}
	
	' Constant used to Dimension Field Array
	Public Const ACGisSchemeFieldArraySize As Integer = 31
	
	' Field Array positional constants
	Public Const ACGisScheme_GisSchemeID As Integer = 0
	Public Const ACGisScheme_GisQuoteEngineID As Integer = 1
	Public Const ACGisScheme_GisBusinessTypeID As Integer = 2
	Public Const ACGisScheme_GisInsurerID As Integer = 3
	Public Const ACGisScheme_SchemeNo As Integer = 4
	Public Const ACGisScheme_SchemeVer As Integer = 5
	Public Const ACGisScheme_SchemeStatus As Integer = 6
	Public Const ACGisScheme_StartDate As Integer = 7
	Public Const ACGisScheme_SchemeDesc As Integer = 8
	Public Const ACGisScheme_Priority As Integer = 9
	Public Const ACGisScheme_AgencyCode As Integer = 10
	Public Const ACGisScheme_ProductCode As Integer = 11
	Public Const ACGisScheme_ActivationLevel As Integer = 12
	Public Const ACGisScheme_PrintingPrivileges As Integer = 13
	Public Const ACGisScheme_BrokerGroup As Integer = 14
	Public Const ACGisScheme_CommisionPerc As Integer = 15
	Public Const ACGisScheme_QuoteDayNum As Integer = 16
	Public Const ACGisScheme_SelectionDayNum As Integer = 17
	Public Const ACGisScheme_InviteDayNum As Integer = 18
	Public Const ACGisScheme_ConfirmDayNum As Integer = 19
	Public Const ACGisScheme_LapseDayNum As Integer = 20
	Public Const ACGisScheme_MaxChangeNum As Integer = 21
	Public Const ACGisScheme_MinChangeNum As Integer = 22
	Public Const ACGisScheme_ExpiryDate As Integer = 23
	Public Const ACGisScheme_QmInsurerRef As Integer = 24
	Public Const ACGisScheme_SchemeTypeFlags As Integer = 25
	Public Const ACGisScheme_Filename As Integer = 26
	Public Const ACGisScheme_EdiMailBox As Integer = 27
	Public Const ACGisScheme_ReferEmailAddress As Integer = 28
	Public Const ACGisScheme_Refer_Fax_Number As Integer = 29
	Public Const ACGisScheme_Scheme_Type As Integer = 30
	Public Const ACGisScheme_SchemeVariant As Integer = 31
	'sj 24/05/2001 - start
	Public Const ACGisScheme_SchemeDictVer As Integer = 32
	Public Const ACGisScheme_SchemeClassOfBusiness As Integer = 33
	Public Const ACGisScheme_SchemeCountryId As Integer = 34
	'sj 24/05/2001 - end
	
	' JSB constants for getting scheme list ID with insurer
	Public Const ACGisSchemeWithIns_GisSchemeID As Integer = 0
	Public Const ACGisSchemeWithIns_BusinessType As Integer = 1
	Public Const ACGisSchemeWithIns_InsurerID As Integer = 2
	Public Const ACGisSchemeWithIns_SchemeNo As Integer = 3
	Public Const ACGisSchemeWithIns_SchemeVer As Integer = 4
	Public Const ACGisSchemeWithIns_SchemeDesc As Integer = 5
	Public Const ACGisSchemeWithIns_AgencyCode As Integer = 6
	Public Const ACGisSchemeWithIns_ActivationLevel As Integer = 7
	Public Const ACGisSchemeWithIns_Description As Integer = 8
	
	'JSB 27/07/01 - Insurer ABI No. Constants
	Public Const InsurerABINoAbbeyMotorPoliciesatLloyds As Integer = 1
	Public Const InsurerABINoAGF As Integer = 0
	Public Const InsurerABINoAlbion As Integer = 161
	Public Const InsurerABINoAllianzCornhillNI As Integer = 0
	Public Const InsurerABINoALSMotorPoliciesatLloyds As Integer = 5
	Public Const InsurerABINoAnsvarInsuranceCompanyLimited As Integer = 6
	Public Const InsurerABINoAUA As String = "991"
	Public Const InsurerABINoAvonInsurance As Integer = 121
	Public Const InsurerABINoAXA As Integer = 7
	Public Const InsurerABINoBell As Integer = 0
	Public Const InsurerABINoBishopsgateInsuranceLimited As Integer = 9
	Public Const InsurerABINoBradfordPennineInsuranceCompanyLimited As Integer = 11
	Public Const InsurerABINoBrokerDirect As Integer = 216
	Public Const InsurerABINoCEHeath As Integer = 990
	Public Const InsurerABINoCGUSCOTG As Integer = 93
	Public Const InsurerABINoCGUInsurance As Integer = 220
	Public Const InsurerABINoCloverleaf As Integer = 20
	Public Const InsurerABINoCommercialUnionAssuranceCompanyPlc As Integer = 22
	Public Const InsurerABINoCongregationalGen As Integer = 992
	Public Const InsurerABINoCorinthianMotorPoliciesatLloyds As Integer = 24
	Public Const InsurerABINoCornhillInsurancePlc As Integer = 25
	Public Const InsurerABINoCroweMotorPoliciesatLloyds As Integer = 26
	Public Const InsurerABINoDominionInsuranceCompanyLimited As Integer = 28
	Public Const InsurerABINoDoric As Integer = 29
	Public Const InsurerABINoDrakeInsuranceLimited As Integer = 30
	Public Const InsurerABINoEagleStarInsuranceCompanyPlc As Integer = 31
	Public Const InsurerABINoEcclesiastical As Integer = 33
	Public Const InsurerABINoEclipseMotorPoliciesatLloyds As Integer = 34
	Public Const InsurerABINoEnsignMotorPoliciesatLloyds As Integer = 36
	Public Const InsurerABINoEquityRedStarMotorPoliciesatLloyds As Integer = 38
	Public Const InsurerABINoFolgate As Integer = 41
	Public Const InsurerABINoFortisInsuranceLtd As Integer = 230
	Public Const InsurerABINoGanInsuranceCompany As Integer = 42
	Public Const InsurerABINoGuardianRoyalExchange As Integer = 48
	Public Const InsurerABINoHibernianInsuranceLimited As Integer = 51
	Public Const InsurerABINoHighwayMotorPoliciesatLloyds As Integer = 52
	Public Const InsurerABINoHoldsure As Integer = 53
	Public Const InsurerABINoIbexMotorPoliciesatLloyds As Integer = 54
	Public Const InsurerABINoIndependentInsuranceCompanyLimited As Integer = 55
	Public Const InsurerABINoInsuranceCorporationofChannelIslands As Integer = 57
	Public Const InsurerABINoIronTradesInsuranceGroup As Integer = 60
	Public Const InsurerABINoITTLondonEdinburgh As Integer = 61
	Public Const InsurerABINoKGMMotorPoliciesatLloyds As Integer = 64
	Public Const InsurerABINoLegalGeneralInsuranceLimited As Integer = 66
	Public Const InsurerABINoLibertyMotor As Integer = 229
	Public Const InsurerABINoLinkPoliciesAtLloyds As Integer = 67
	Public Const InsurerABINoLinkInsurance As Integer = 0
	Public Const InsurerABINoLombardContinentalInsuranceUKLimited As Integer = 69
	Public Const InsurerABINoMethodist As Integer = 0
	Public Const InsurerABINoNIG As Integer = 73
	Public Const InsurerABINoNormanInsuranceCompanyLimited As Integer = 74
	Public Const InsurerABINoNorthernStarInsuranceCompanyLimited As Integer = 75
	Public Const InsurerABINoNU As Integer = 218
	Public Const InsurerABINoPegasusMotorPoliciesatLloyds As Integer = 81
	Public Const InsurerABINoProvident As Integer = 84
	Public Const InsurerABINoRoyalSunAlliance As Integer = 200
	Public Const InsurerABINoSabreInsuranceCompanyLimited As Integer = 91
	Public Const InsurerABINoServiceMotorPoliciesatLloyds As Integer = 96
	Public Const InsurerABINoSheadMotorPoliciesatLloyds As Integer = 97
	Public Const InsurerABINoTorchMotorPoliciesatLloyds As Integer = 106
	Public Const InsurerABINoTowergate As Integer = 228
	Public Const InsurerABINoUAPProvincial As Integer = 382
	Public Const InsurerABINoWellingtonInsurance As Integer = 0
	Public Const InsurerABINoWellingtonInsuranceService As Integer = 109
	Public Const InsurerABINoWesleyan As Integer = 0
	Public Const InsurerABINoWrenMotorPoliciesatLloyds As Integer = 114
	Public Const InsurerABINoZenithInsurancePoliciesatLloyds As Integer = 115
	Public Const InsurerABINoZurichInsuranceCompanyLimited As Integer = 116
	
	' {* GENERATED CODE (End) *}
	
	'JSB - QM Insurer Ref constants
	Public Const InsQMRef_AbbeyMotorPoliciesatLloyds As String = "030"
	Public Const InsQMRef_AllianzNI1 As String = "005"
	Public Const InsQMRef_AllianzNI2 As String = "305"
	Public Const InsQMRef_ALSMotorPoliciesatLloyds1 As String = "001"
	Public Const InsQMRef_ALSMotorPoliciesatLloyds2 As String = "301"
	Public Const InsQMRef_AnsvarInsuranceCompanyLimited1 As String = "003"
	Public Const InsQMRef_AnsvarInsuranceCompanyLimited2 As String = "303"
	Public Const InsQMRef_AUA As String = "091"
	Public Const InsQMRef_AvonInsurance As String = "004"
	Public Const InsQMRef_AXAInsuranceCompanyLimited1 As String = "077"
	Public Const InsQMRef_AXAInsuranceCompanyLimited2 As String = "110"
	Public Const InsQMRef_AXAInsuranceCompanyLimited3 As String = "116"
	Public Const InsQMRef_AXAInsuranceCompanyLimited4 As String = "117"
	Public Const InsQMRef_AXAInsuranceCompanyLimited5 As String = "477"
	Public Const InsQMRef_Bell As String = "191"
	Public Const InsQMRef_BIIBA__UnlistedInsurer1 As String = "009"
	Public Const InsQMRef_BIIBA__UnlistedInsurer2 As String = "309"
	Public Const InsQMRef_BradfordPennineInsuranceCompanyLimited1 As String = "002"
	Public Const InsQMRef_BradfordPennineInsuranceCompanyLimited2 As String = "083"
	Public Const InsQMRef_BradfordPennineInsuranceCompanyLimited3 As String = "084"
	Public Const InsQMRef_BritInsuranceLimited1 As String = "094"
	Public Const InsQMRef_BritInsuranceLimited2 As String = "394"
	Public Const InsQMRef_BritInsuranceLimited3 As String = "494"
	Public Const InsQMRef_BrokerDirect_Trafalgar1 As String = "096"
	Public Const InsQMRef_BrokerDirect_Trafalgar2 As String = "126"
	Public Const InsQMRef_BrokerDirect_Trafalgar3 As String = "396"
	Public Const InsQMRef_CEHeath As String = "048"
	Public Const InsQMRef_CGU_SCOTG As String = "066"
	Public Const InsQMRef_CGUInsurance1 As String = "026"
	Public Const InsQMRef_CGUInsurance2 As String = "115"
	Public Const InsQMRef_CGUInsurance3 As String = "326"
	Public Const InsQMRef_ChaucerInsurance1 As String = "086"
	Public Const InsQMRef_ChaucerInsurance2 As String = "108"
	Public Const InsQMRef_ChaucerInsurance3 As String = "128"
	Public Const InsQMRef_ChaucerInsurance4 As String = "386"
	Public Const InsQMRef_Cloverleaf As String = "011"
	Public Const InsQMRef_CommercialUnionAssuranceCompanyPlc1 As String = "012"
	Public Const InsQMRef_CommercialUnionAssuranceCompanyPlc2 As String = "024"
	Public Const InsQMRef_Congregational_AND_Gen As String = "036"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds1 As String = "013"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds2 As String = "119"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds3 As String = "141"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds4 As String = "142"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds5 As String = "313"
	Public Const InsQMRef_CorinthianMotorPoliciesatLloyds6 As String = "319"
	Public Const InsQMRef_CornhillInsurancePlc1 As String = "014"
	Public Const InsQMRef_CornhillInsurancePlc2 As String = "020"
	Public Const InsQMRef_CornhillInsurancePlc3 As String = "047"
	Public Const InsQMRef_CornhillInsurancePlc4 As String = "095"
	Public Const InsQMRef_CornhillInsurancePlc5 As String = "105"
	Public Const InsQMRef_CornhillInsurancePlc6 As String = "111"
	Public Const InsQMRef_CroweMotorPoliciesatLloyds As String = "073"
	Public Const InsQMRef_DominionInsuranceCompanyLimited As String = "017"
	Public Const InsQMRef_Doric As String = "018"
	Public Const InsQMRef_DrakeInsuranceLimited1 As String = "006"
	Public Const InsQMRef_DrakeInsuranceLimited2 As String = "019"
	Public Const InsQMRef_DrakeInsuranceLimited3 As String = "053"
	Public Const InsQMRef_DrakeInsuranceLimited4 As String = "070"
	Public Const InsQMRef_DrakeInsuranceLimited5 As String = "072"
	Public Const InsQMRef_DrakeInsuranceLimited6 As String = "081"
	Public Const InsQMRef_E_AND_L As String = "192"
	Public Const InsQMRef_EagleStarInsuranceCompanyPlc1 As String = "015"
	Public Const InsQMRef_EagleStarInsuranceCompanyPlc2 As String = "032"
	Public Const InsQMRef_EagleStarInsuranceCompanyPlc3 As String = "059"
	Public Const InsQMRef_Ecclesiastical20 As String = "011"
	Public Const InsQMRef_EclipseMotorPoliciesatLloyds1 As String = "021"
	Public Const InsQMRef_EclipseMotorPoliciesatLloyds2 As String = "071"
	Public Const InsQMRef_EclipseMotorPoliciesatLloyds3 As String = "101"
	Public Const InsQMRef_EclipseMotorPoliciesatLloyds4 As String = "102"
	Public Const InsQMRef_EnsignMotorPoliciesatLloyds As String = "010"
	Public Const InsQMRef_EquityRedStarMotorPoliciesatLloyds1 As String = "017"
	Public Const InsQMRef_EquityRedStarMotorPoliciesatLloyds2 As String = "034"
	Public Const InsQMRef_EquityRedStarMotorPoliciesatLloyds3 As String = "062"
	Public Const InsQMRef_EquityRedStarMotorPoliciesatLloyds4 As String = "082"
	Public Const InsQMRef_EquityRedStarMotorPoliciesatLloyds5 As String = "123"
	Public Const InsQMRef_Folgate As String = "065"
	Public Const InsQMRef_FolgateInsuranceCompanyLimited As String = "065"
	Public Const InsQMRef_FortisInsuranceLtd1 As String = "007"
	Public Const InsQMRef_FortisInsuranceLtd2 As String = "039"
	Public Const InsQMRef_FortisInsuranceLtd3 As String = "339"
	Public Const InsQMRef_GanInsuranceCompany1 As String = "021"
	Public Const InsQMRef_GanInsuranceCompany2 As String = "042"
	Public Const InsQMRef_GanInsuranceCompany3 As String = "043"
	Public Const InsQMRef_GanInsuranceCompany4 As String = "442"
	Public Const InsQMRef_GuardianRoyalExchange As String = "027"
	Public Const InsQMRef_HibernianInsuranceLimited As String = "085"
	Public Const InsQMRef_HighwayMotorPoliciesatLloyds1 As String = "024"
	Public Const InsQMRef_HighwayMotorPoliciesatLloyds2 As String = "031"
	Public Const InsQMRef_HighwayMotorPoliciesatLloyds3 As String = "049"
	Public Const InsQMRef_HighwayMotorPoliciesatLloyds4 As String = "331"
	Public Const InsQMRef_HighwayMotorPoliciesatLloyds5 As String = "431"
	Public Const InsQMRef_HiscoxInsuranceCo As String = "193"
	Public Const InsQMRef_Holdsure1 As String = "023"
	Public Const InsQMRef_Holdsure2 As String = "093"
	Public Const InsQMRef_Holdsure3 As String = "393"
	Public Const InsQMRef_IndependentInsuranceCompanyLimited As String = "087"
	Public Const InsQMRef_InsuranceCorporationofChannelIslands1 As String = "008"
	Public Const InsQMRef_InsuranceCorporationofChannelIslands2 As String = "129"
	Public Const InsQMRef_IronTradesInsuranceGroup1 As String = "029"
	Public Const InsQMRef_IronTradesInsuranceGroup2 As String = "033"
	Public Const InsQMRef_ITTLondon_AND_Edinburgh1 As String = "041"
	Public Const InsQMRef_ITTLondon_AND_Edinburgh2 As String = "044"
	Public Const InsQMRef_KGMMotorPoliciesatLloyds As String = "035"
	Public Const InsQMRef_Legal_AND_GeneralInsuranceLimited1 As String = "037"
	Public Const InsQMRef_Legal_AND_GeneralInsuranceLimited2 As String = "080"
	Public Const InsQMRef_Legal_AND_GeneralInsuranceLimited3 As String = "088"
	Public Const InsQMRef_Legal_AND_GeneralInsuranceLimited4 As String = "337"
	Public Const InsQMRef_Legal_AND_GeneralInsuranceLimited5 As String = "380"
	Public Const InsQMRef_LibertyMotor As String = "092"
	Public Const InsQMRef_LinkatLloyds1 As String = "038"
	Public Const InsQMRef_LinkatLloyds2 As String = "138"
	Public Const InsQMRef_LinkInsurance As String = "038"
	Public Const InsQMRef_LombardContinentalInsurance_UKLimited As String = "040"
	Public Const InsQMRef_MARKS__UnlistedInsurer As String = "140"
	Public Const InsQMRef_Methodist As String = "194"
	Public Const InsQMRef_MMAInsuranceplc1 As String = "050"
	Public Const InsQMRef_MMAInsuranceplc2 As String = "097"
	Public Const InsQMRef_NIG1 As String = "045"
	Public Const InsQMRef_NIG2 As String = "048"
	Public Const InsQMRef_NIG3 As String = "085"
	Public Const InsQMRef_NIG4 As String = "195"
	Public Const InsQMRef_NIG5 As String = "445"
	Public Const InsQMRef_NorthernStarInsuranceCompanyLimited As String = "051"
	Public Const InsQMRef_NorwichUnionInsuranceLimited1 As String = "019"
	Public Const InsQMRef_NorwichUnionInsuranceLimited2 As String = "025"
	Public Const InsQMRef_NorwichUnionInsuranceLimited3 As String = "046"
	Public Const InsQMRef_NorwichUnionInsuranceLimited4 As String = "052"
	Public Const InsQMRef_NorwichUnionInsuranceLimited5 As String = "054"
	Public Const InsQMRef_NorwichUnionInsuranceLimited6 As String = "066"
	Public Const InsQMRef_NorwichUnionInsuranceLimited7 As String = "091"
	Public Const InsQMRef_NorwichUnionInsuranceLimited8 As String = "113"
	Public Const InsQMRef_NorwichUnionInsuranceLimited9 As String = "325"
	Public Const InsQMRef_NorwichUnionInsuranceLimited10 As String = "352"
	Public Const InsQMRef_NorwichUnionInsuranceLimited11 As String = "413"
	Public Const InsQMRef_NorwichUnionInsuranceLimited12 As String = "446"
	Public Const InsQMRef_NorwichUnionInsuranceLimited13 As String = "452"
	Public Const InsQMRef_NorwichUnionInsuranceLimited14 As String = "466"
	Public Const InsQMRef_PegasusMotorPoliciesatLloyds15 As String = "055"
	Public Const InsQMRef_ProvidentInsurancePlc As String = "028"
	Public Const InsQMRef_Royal_AND_SunAlliance1 As String = "016"
	Public Const InsQMRef_Royal_AND_SunAlliance2 As String = "022"
	Public Const InsQMRef_Royal_AND_SunAlliance3 As String = "058"
	Public Const InsQMRef_Royal_AND_SunAlliance4 As String = "060"
	Public Const InsQMRef_Royal_AND_SunAlliance5 As String = "062"
	Public Const InsQMRef_Royal_AND_SunAlliance6 As String = "098"
	Public Const InsQMRef_Royal_AND_SunAlliance7 As String = "099"
	Public Const InsQMRef_Royal_AND_SunAlliance8 As String = "135"
	Public Const InsQMRef_Royal_AND_SunAlliance9 As String = "322"
	Public Const InsQMRef_Royal_AND_SunAlliance10 As String = "358"
	Public Const InsQMRef_Royal_AND_SunAlliance11 As String = "360"
	Public Const InsQMRef_Royal_AND_SunAlliance12 As String = "398"
	Public Const InsQMRef_Royal_AND_SunAlliance13 As String = "399"
	Public Const InsQMRef_Royal_AND_SunAlliance14 As String = "462"
	Public Const InsQMRef_Royal_AND_SunAlliance15 As String = "499"
	Public Const InsQMRef_SabreInsuranceCompanyLimited1 As String = "063"
	Public Const InsQMRef_SabreInsuranceCompanyLimited2 As String = "090"
	Public Const InsQMRef_SabreInsuranceCompanyLimited3 As String = "363"
	Public Const InsQMRef_ServiceMotorPoliciesatLloyds As String = "061"
	Public Const InsQMRef_SheadMotorPoliciesatLloyds1 As String = "069"
	Public Const InsQMRef_SheadMotorPoliciesatLloyds2 As String = "075"
	Public Const InsQMRef_SterlingInsurance As String = "103"
	Public Const InsQMRef_TorchMotorPoliciesatLloyds As String = "074"
	Public Const InsQMRef_Towergate As String = "104"
	Public Const InsQMRef_TRADX__UnlistedInsurer1 As String = "005"
	Public Const InsQMRef_TRADX__UnlistedInsurer2 As String = "107"
	Public Const InsQMRef_UAPProvincial1 As String = "056"
	Public Const InsQMRef_UAPProvincial2 As String = "057"
	Public Const InsQMRef_VANL__UnlistedInsurer As String = "067"
	Public Const InsQMRef_WellingtonInsurance As String = "196"
	Public Const InsQMRef_WellingtonInsuranceService As String = "076"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds1 As String = "068"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds2 As String = "078"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds3 As String = "121"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds4 As String = "122"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds5 As String = "124"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds6 As String = "125"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds7 As String = "130"
	Public Const InsQMRef_ZenithInsurancePoliciesatLloyds8 As String = "131"
	Public Const InsQMRef_ZurichInsuranceCompanyLimited1 As String = "064"
	Public Const InsQMRef_ZurichInsuranceCompanyLimited2 As String = "079"
	Public Const InsQMRef_ZurichInsuranceCompanyLimited3 As String = "364"
End Module