'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("uctInstalmentsControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instalments.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Plans Available.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Details.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Override.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Other Details.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str1150() As String
            Get
                Return ResourceManager.GetString("str1150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cheque.
        '''</summary>
        Friend ReadOnly Property str1151() As String
            Get
                Return ResourceManager.GetString("str1151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Acount.
        '''</summary>
        Friend ReadOnly Property str1152() As String
            Get
                Return ResourceManager.GetString("str1152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card.
        '''</summary>
        Friend ReadOnly Property str1153() As String
            Get
                Return ResourceManager.GetString("str1153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weekday.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day in Month.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Payment.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Financed Amount.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transactions.
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rate:.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Payable.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instalments.
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APR:.
        '''</summary>
        Friend ReadOnly Property str1310() As String
            Get
                Return ResourceManager.GetString("str1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Breakdown.
        '''</summary>
        Friend ReadOnly Property str1311() As String
            Get
                Return ResourceManager.GetString("str1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deposit.
        '''</summary>
        Friend ReadOnly Property str1312() As String
            Get
                Return ResourceManager.GetString("str1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Protection Charge.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Instalment Date.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Instalment Date.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Instalment Date.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin Charge.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interest:.
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Instalment.
        '''</summary>
        Friend ReadOnly Property str1319() As String
            Get
                Return ResourceManager.GetString("str1319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Instalments.
        '''</summary>
        Friend ReadOnly Property str1320() As String
            Get
                Return ResourceManager.GetString("str1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taxes:.
        '''</summary>
        Friend ReadOnly Property str1321() As String
            Get
                Return ResourceManager.GetString("str1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Override Options.
        '''</summary>
        Friend ReadOnly Property str1322() As String
            Get
                Return ResourceManager.GetString("str1322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Additional Options.
        '''</summary>
        Friend ReadOnly Property str1323() As String
            Get
                Return ResourceManager.GetString("str1323", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Override Interest Rate?.
        '''</summary>
        Friend ReadOnly Property str1324() As String
            Get
                Return ResourceManager.GetString("str1324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Rate:.
        '''</summary>
        Friend ReadOnly Property str1325() As String
            Get
                Return ResourceManager.GetString("str1325", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission Override?.
        '''</summary>
        Friend ReadOnly Property str1326() As String
            Get
                Return ResourceManager.GetString("str1326", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference:.
        '''</summary>
        Friend ReadOnly Property str1327() As String
            Get
                Return ResourceManager.GetString("str1327", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not include Payment Protection.
        '''</summary>
        Friend ReadOnly Property str1328() As String
            Get
                Return ResourceManager.GetString("str1328", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str1329() As String
            Get
                Return ResourceManager.GetString("str1329", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferred Days.
        '''</summary>
        Friend ReadOnly Property str1330() As String
            Get
                Return ResourceManager.GetString("str1330", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MTA.
        '''</summary>
        Friend ReadOnly Property str1331() As String
            Get
                Return ResourceManager.GetString("str1331", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use Existing Plan Details.
        '''</summary>
        Friend ReadOnly Property str1332() As String
            Get
                Return ResourceManager.GetString("str1332", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spread over remaining plan.
        '''</summary>
        Friend ReadOnly Property str1333() As String
            Get
                Return ResourceManager.GetString("str1333", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Put MTA Amount in next instalment.
        '''</summary>
        Friend ReadOnly Property str1334() As String
            Get
                Return ResourceManager.GetString("str1334", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Put MTA Amount into new plan.
        '''</summary>
        Friend ReadOnly Property str1335() As String
            Get
                Return ResourceManager.GetString("str1335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1702() As String
            Get
                Return ResourceManager.GetString("str1702", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later..
        '''</summary>
        Friend ReadOnly Property str1703() As String
            Get
                Return ResourceManager.GetString("str1703", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monday.
        '''</summary>
        Friend ReadOnly Property str1704() As String
            Get
                Return ResourceManager.GetString("str1704", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuesday.
        '''</summary>
        Friend ReadOnly Property str1705() As String
            Get
                Return ResourceManager.GetString("str1705", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wednesday.
        '''</summary>
        Friend ReadOnly Property str1706() As String
            Get
                Return ResourceManager.GetString("str1706", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thursday.
        '''</summary>
        Friend ReadOnly Property str1707() As String
            Get
                Return ResourceManager.GetString("str1707", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Friday.
        '''</summary>
        Friend ReadOnly Property str1708() As String
            Get
                Return ResourceManager.GetString("str1708", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str1709() As String
            Get
                Return ResourceManager.GetString("str1709", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Details.
        '''</summary>
        Friend ReadOnly Property str1801() As String
            Get
                Return ResourceManager.GetString("str1801", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card Details.
        '''</summary>
        Friend ReadOnly Property str1802() As String
            Get
                Return ResourceManager.GetString("str1802", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information has been changed. Cancelling will lose your changes. Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1803() As String
            Get
                Return ResourceManager.GetString("str1803", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to These changes will replace the existing negociated Plan with a new version. Do you still want to go ahead?.
        '''</summary>
        Friend ReadOnly Property str1804() As String
            Get
                Return ResourceManager.GetString("str1804", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select weekday..
        '''</summary>
        Friend ReadOnly Property str1805() As String
            Get
                Return ResourceManager.GetString("str1805", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select day in month..
        '''</summary>
        Friend ReadOnly Property str1806() As String
            Get
                Return ResourceManager.GetString("str1806", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please specify a preferred date of first payment..
        '''</summary>
        Friend ReadOnly Property str1807() As String
            Get
                Return ResourceManager.GetString("str1807", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select media type..
        '''</summary>
        Friend ReadOnly Property str1808() As String
            Get
                Return ResourceManager.GetString("str1808", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select frequency..
        '''</summary>
        Friend ReadOnly Property str1809() As String
            Get
                Return ResourceManager.GetString("str1809", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please specify amount of instalments..
        '''</summary>
        Friend ReadOnly Property str1810() As String
            Get
                Return ResourceManager.GetString("str1810", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The address for this agent is insufficient. Please correct this prior to printing any documents.
        '''</summary>
        Friend ReadOnly Property str1811() As String
            Get
                Return ResourceManager.GetString("str1811", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no Frequency available for this Media Type. Please select another Media Type, or set up a rate for this Media Type and Frequency..
        '''</summary>
        Friend ReadOnly Property str1812() As String
            Get
                Return ResourceManager.GetString("str1812", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot save in View mode..
        '''</summary>
        Friend ReadOnly Property str1813() As String
            Get
                Return ResourceManager.GetString("str1813", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must quote before saving..
        '''</summary>
        Friend ReadOnly Property str1814() As String
            Get
                Return ResourceManager.GetString("str1814", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installments.
        '''</summary>
        Friend ReadOnly Property str2100() As String
            Get
                Return ResourceManager.GetString("str2100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Plans Available.
        '''</summary>
        Friend ReadOnly Property str2101() As String
            Get
                Return ResourceManager.GetString("str2101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Details.
        '''</summary>
        Friend ReadOnly Property str2102() As String
            Get
                Return ResourceManager.GetString("str2102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Override.
        '''</summary>
        Friend ReadOnly Property str2103() As String
            Get
                Return ResourceManager.GetString("str2103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Other Details.
        '''</summary>
        Friend ReadOnly Property str2104() As String
            Get
                Return ResourceManager.GetString("str2104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str2150() As String
            Get
                Return ResourceManager.GetString("str2150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cheque.
        '''</summary>
        Friend ReadOnly Property str2151() As String
            Get
                Return ResourceManager.GetString("str2151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Acount.
        '''</summary>
        Friend ReadOnly Property str2152() As String
            Get
                Return ResourceManager.GetString("str2152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card.
        '''</summary>
        Friend ReadOnly Property str2153() As String
            Get
                Return ResourceManager.GetString("str2153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weekday.
        '''</summary>
        Friend ReadOnly Property str2300() As String
            Get
                Return ResourceManager.GetString("str2300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day in Month.
        '''</summary>
        Friend ReadOnly Property str2301() As String
            Get
                Return ResourceManager.GetString("str2301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Payment.
        '''</summary>
        Friend ReadOnly Property str2302() As String
            Get
                Return ResourceManager.GetString("str2302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend ReadOnly Property str2304() As String
            Get
                Return ResourceManager.GetString("str2304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Financed Amount.
        '''</summary>
        Friend ReadOnly Property str2305() As String
            Get
                Return ResourceManager.GetString("str2305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transactions.
        '''</summary>
        Friend ReadOnly Property str2306() As String
            Get
                Return ResourceManager.GetString("str2306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rate:.
        '''</summary>
        Friend ReadOnly Property str2307() As String
            Get
                Return ResourceManager.GetString("str2307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Payable.
        '''</summary>
        Friend ReadOnly Property str2308() As String
            Get
                Return ResourceManager.GetString("str2308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installments.
        '''</summary>
        Friend ReadOnly Property str2309() As String
            Get
                Return ResourceManager.GetString("str2309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APR:.
        '''</summary>
        Friend ReadOnly Property str2310() As String
            Get
                Return ResourceManager.GetString("str2310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Breakdown.
        '''</summary>
        Friend ReadOnly Property str2311() As String
            Get
                Return ResourceManager.GetString("str2311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deposit.
        '''</summary>
        Friend ReadOnly Property str2312() As String
            Get
                Return ResourceManager.GetString("str2312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Protection Charge.
        '''</summary>
        Friend ReadOnly Property str2313() As String
            Get
                Return ResourceManager.GetString("str2313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Installment Date.
        '''</summary>
        Friend ReadOnly Property str2314() As String
            Get
                Return ResourceManager.GetString("str2314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Installment Date.
        '''</summary>
        Friend ReadOnly Property str2315() As String
            Get
                Return ResourceManager.GetString("str2315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Installment Date.
        '''</summary>
        Friend ReadOnly Property str2316() As String
            Get
                Return ResourceManager.GetString("str2316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin Charge.
        '''</summary>
        Friend ReadOnly Property str2317() As String
            Get
                Return ResourceManager.GetString("str2317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interest:.
        '''</summary>
        Friend ReadOnly Property str2318() As String
            Get
                Return ResourceManager.GetString("str2318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Installment.
        '''</summary>
        Friend ReadOnly Property str2319() As String
            Get
                Return ResourceManager.GetString("str2319", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Installments.
        '''</summary>
        Friend ReadOnly Property str2320() As String
            Get
                Return ResourceManager.GetString("str2320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taxes:.
        '''</summary>
        Friend ReadOnly Property str2321() As String
            Get
                Return ResourceManager.GetString("str2321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Override Options.
        '''</summary>
        Friend ReadOnly Property str2322() As String
            Get
                Return ResourceManager.GetString("str2322", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Additional Options.
        '''</summary>
        Friend ReadOnly Property str2323() As String
            Get
                Return ResourceManager.GetString("str2323", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Override Interest Rate?.
        '''</summary>
        Friend ReadOnly Property str2324() As String
            Get
                Return ResourceManager.GetString("str2324", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Rate:.
        '''</summary>
        Friend ReadOnly Property str2325() As String
            Get
                Return ResourceManager.GetString("str2325", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission Override?.
        '''</summary>
        Friend ReadOnly Property str2326() As String
            Get
                Return ResourceManager.GetString("str2326", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference:.
        '''</summary>
        Friend ReadOnly Property str2327() As String
            Get
                Return ResourceManager.GetString("str2327", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not include Payment Protection.
        '''</summary>
        Friend ReadOnly Property str2328() As String
            Get
                Return ResourceManager.GetString("str2328", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str2329() As String
            Get
                Return ResourceManager.GetString("str2329", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferred Days.
        '''</summary>
        Friend ReadOnly Property str2330() As String
            Get
                Return ResourceManager.GetString("str2330", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MTA.
        '''</summary>
        Friend ReadOnly Property str2331() As String
            Get
                Return ResourceManager.GetString("str2331", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use Existing Plan Details.
        '''</summary>
        Friend ReadOnly Property str2332() As String
            Get
                Return ResourceManager.GetString("str2332", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spread over remaining plan.
        '''</summary>
        Friend ReadOnly Property str2333() As String
            Get
                Return ResourceManager.GetString("str2333", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Put MTA Amount in next installment.
        '''</summary>
        Friend ReadOnly Property str2334() As String
            Get
                Return ResourceManager.GetString("str2334", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Put MTA Amount into new plan.
        '''</summary>
        Friend ReadOnly Property str2335() As String
            Get
                Return ResourceManager.GetString("str2335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str2702() As String
            Get
                Return ResourceManager.GetString("str2702", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later..
        '''</summary>
        Friend ReadOnly Property str2703() As String
            Get
                Return ResourceManager.GetString("str2703", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monday.
        '''</summary>
        Friend ReadOnly Property str2704() As String
            Get
                Return ResourceManager.GetString("str2704", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuesday.
        '''</summary>
        Friend ReadOnly Property str2705() As String
            Get
                Return ResourceManager.GetString("str2705", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wednesday.
        '''</summary>
        Friend ReadOnly Property str2706() As String
            Get
                Return ResourceManager.GetString("str2706", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thursday.
        '''</summary>
        Friend ReadOnly Property str2707() As String
            Get
                Return ResourceManager.GetString("str2707", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Friday.
        '''</summary>
        Friend ReadOnly Property str2708() As String
            Get
                Return ResourceManager.GetString("str2708", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Period.
        '''</summary>
        Friend ReadOnly Property str2709() As String
            Get
                Return ResourceManager.GetString("str2709", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank Details.
        '''</summary>
        Friend ReadOnly Property str2801() As String
            Get
                Return ResourceManager.GetString("str2801", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit Card Details.
        '''</summary>
        Friend ReadOnly Property str2802() As String
            Get
                Return ResourceManager.GetString("str2802", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information has been changed. Cancelling will lose your changes. Are you sure?.
        '''</summary>
        Friend ReadOnly Property str2803() As String
            Get
                Return ResourceManager.GetString("str2803", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to These changes will replace the existing negociated Plan with a new version. Do you still want to go ahead?.
        '''</summary>
        Friend ReadOnly Property str2804() As String
            Get
                Return ResourceManager.GetString("str2804", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select weekday..
        '''</summary>
        Friend ReadOnly Property str2805() As String
            Get
                Return ResourceManager.GetString("str2805", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select day in month..
        '''</summary>
        Friend ReadOnly Property str2806() As String
            Get
                Return ResourceManager.GetString("str2806", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please specify a preferred date of first payment..
        '''</summary>
        Friend ReadOnly Property str2807() As String
            Get
                Return ResourceManager.GetString("str2807", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select media type..
        '''</summary>
        Friend ReadOnly Property str2808() As String
            Get
                Return ResourceManager.GetString("str2808", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select frequency..
        '''</summary>
        Friend ReadOnly Property str2809() As String
            Get
                Return ResourceManager.GetString("str2809", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please specify amount of installments..
        '''</summary>
        Friend ReadOnly Property str2810() As String
            Get
                Return ResourceManager.GetString("str2810", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The address for this agent is insufficient. Please correct this prior to printing any documents.
        '''</summary>
        Friend ReadOnly Property str2811() As String
            Get
                Return ResourceManager.GetString("str2811", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no Frequency available for this Media Type. Please select another Media Type, or set up a rate for this Media Type and Frequency..
        '''</summary>
        Friend ReadOnly Property str2812() As String
            Get
                Return ResourceManager.GetString("str2812", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot save in View mode..
        '''</summary>
        Friend ReadOnly Property str2813() As String
            Get
                Return ResourceManager.GetString("str2813", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must quote before saving..
        '''</summary>
        Friend ReadOnly Property str2814() As String
            Get
                Return ResourceManager.GetString("str2814", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
