EXEC DDLDropProcedure spu_Report_Premium_Finance_Satement
GO

CREATE PROCEDURE spu_Report_Premium_Finance_Satement
	@branch_id INT, 
	@end_date DATETIME,
        @party_code VARCHAR(100)

AS

DECLARE
    @dEndDate DATETIME

SET NOCOUNT ON

SET ANSI_WARNINGS OFF

IF @party_code = 'ALL' OR @party_code = ''
BEGIN
    SELECT @party_code = NULL
END

IF @branch_id = 0
BEGIN
    SELECT @branch_id = NULL
END

SELECT @dEndDate = ISNULL(@end_date, GETDATE())

CREATE TABLE #Report_Transaction
(
    transdetail_id INT,
    document_id INT,
    account_id INT,
    documenttype_id INT,
    branch_id INT,
    ledger_id INT,
    account_code VARCHAR(30),
    account_name VARCHAR(255),
    document_ref VARCHAR(25),
    document_date DATETIME,
    effective_date DATETIME,
    account_address1 VARCHAR(60),
    account_address2 VARCHAR(60),
    account_address3 VARCHAR(60),
    account_address4 VARCHAR(60),
    account_postal_code VARCHAR(20),
    phone_area_code VARCHAR(10),
    phone_number VARCHAR(255),
    ledger_name VARCHAR(30),
    policy_number VARCHAR(30),
    transaction_type_code VARCHAR(10),
    transaction_type_description VARCHAR(255),
    policy_type_code VARCHAR(10),
    policy_type_description VARCHAR(255),
    gross_premium MONEY,
    base_match_amount MONEY,
    unallocated_amount MONEY,
    account_total MONEY,
    match_total MONEY,
    date_paid DATETIME,
    Branch_Name VARCHAR(255),
    Branch_address1 VARCHAR(40),
    Branch_address2 VARCHAR(40),
    Branch_address3 VARCHAR(40),
    Branch_address4 VARCHAR(40),
    Branch_postal_code VARCHAR(20),
    matched INT,
    client_code VARCHAR(20),
    client_name VARCHAR(255),
    client_premium MONEY,
    client_match_amt MONEY,
    client_matched INT,
    comment VARCHAR(255),
    number_of_days INT,
    reminder_type VARCHAR(100),
    transaction_reason VARCHAR(255),
    account_handler VARCHAR(255),
    renewal_date DATETIME,
    risk_code VARCHAR(10),
    report_indicator INT,
    order_code VARCHAR(30),
    latest_transaction_comment VARCHAR(500),
    has_comment BIT,
    spare VARCHAR(30),
    orig_document_ref VARCHAR(30),
    ledger_short_name VARCHAR(2)
)

-- Get the required transactions
INSERT INTO #Report_Transaction
(
    transdetail_id,
    account_id,
    account_code,
    document_id,
    document_ref,
    document_date,
    effective_date,
    ledger_name,
    policy_number,
    documenttype_id,
    gross_premium,
    branch_id,
    matched,
    match_total,
    ledger_id,
    comment,
--    transaction_reason,
    client_code,
    client_name,
    Branch_Name,
    Branch_address1,
    Branch_address2,
    Branch_address3,
    Branch_address4,
    Branch_postal_code,
    transaction_type_code,
    transaction_type_description,
 /*   renewal_date,
    risk_code,
    report_indicator,*/
    latest_transaction_comment,
    spare,
    orig_document_ref,
    ledger_short_name
)
SELECT
    td.transdetail_id,
    a.account_id,
    a.short_code,
    d.document_id,
    d.document_ref,
    d.document_date,
    td.ref_date,
    l.ledger_name,
    pf.autogeneratedplanref,
    d.documenttype_id,
    ROUND(td.Amount,2),
    d.company_id,
    0,
    (
        SELECT ISNULL(SUM(ROUND(TM.base_match_amount,2)),0)
        FROM TransMatch TM
        JOIN MatchGroup MG
            ON MG.match_id = TM.match_id
            AND MG.match_date <= @dEndDate
        WHERE TM.transdetail_id = TD.transdetail_id
        AND TM.allocationdetail_id IS NOT NULL
    ),
    A.ledger_id,
    TD.comment,
--    TEF.reason,
    P.shortname,
    p.resolved_name,
    c.description,
    c.address1,
    c.address2,
    c.address3,
    c.address4,
    c.postal_code,
    dt.code,
    dt.description,
/*  I.renewal_date,
    RC.code,
    PA.report_indicator*/
    (
        SELECT TOP 1
            tc.description
        FROM transaction_comment tc
        WHERE tc.transdetail_id = td.transdetail_id
        ORDER BY comment_date DESC
    ),
    TD.spare,
    '',
    l.ledger_short_name
FROM	Account a 
JOIN	Ledger l 
	ON a.ledger_id = l.ledger_id 
JOIN	TransDetail td 
	ON td.account_id = a.account_id 
JOIN	Document d 
	ON d.document_id = td.document_id 
JOIN	Company c 
	ON c.company_id = d.company_id 
JOIN	DocumentType dt
	ON dt.documenttype_id = d.documenttype_id 
LEFT JOIN PFPremiumFinance pf
	ON td.transdetail_id = pf.PlanTransaction_id 
LEFT JOIN Party p
	ON PF.ClientId = p.party_cnt
WHERE a.short_code = ISNULL(@party_code,a.short_code)
AND d.document_date <= @dEndDate
AND d.company_id = ISNULL(@branch_id,d.company_id)
AND l.ledger_short_name = 'RF'

    UPDATE rt
        SET client_code = p.shortname,
        client_name = p.name,
        client_premium = TD.amount,
        client_match_amt =
            (
                SELECT SUM(ROUND(TM.base_match_amount,2))
                FROM TransMatch TM
                JOIN MatchGroup MG
                    ON MG.match_id = TM.match_id
                WHERE TM.transdetail_id = TD.transdetail_id
                AND MG.match_date <= @dEndDate
            ),
        client_matched = 0
    FROM #Report_Transaction rt
    JOIN TransDetail td
        ON td.document_id = rt.document_id
        AND td.document_sequence = 1
    JOIN Account a
        ON a.account_id = td.account_id
    AND Left(RT.spare, 8) <> 'INT COMM'
    AND Left(RT.spare, 8) <> 'INT ADJ '
    AND Left(RT.spare, 8) <> 'Revsd IC'
    AND Left(RT.spare, 8) <> 'Revsl IC'
    AND Left(RT.spare, 8) <> 'Revd ICA'
    AND Left(RT.spare, 8) <> 'Revl ICA'
    JOIN Party p
        ON a.account_key = p.party_cnt
    /* DC270105 added this to obtain the client details from the relating transaction of the introducer journal */
    UPDATE RT
        SET client_code = p.shortname,
        client_name = p.name,
        client_premium = TD.amount,
        client_match_amt =
            (
                SELECT SUM(ROUND(TM.base_match_amount,2))
                FROM TransMatch TM
                JOIN MatchGroup MG
                    ON MG.match_id = TM.match_id
                WHERE TM.transdetail_id = TD.transdetail_id
                AND MG.match_date <= @dEndDate
            ),
            client_matched = 0,
        orig_document_ref = D.document_ref
    FROM #Report_Transaction RT
    JOIN document D
        ON rtrim(D.document_ref) = rtrim(substring(RT.spare, 10, 20))
        AND D.company_id = RT.branch_id
    JOIN TransDetail TD
        ON TD.document_id = D.document_id
        AND TD.document_sequence = 1
    JOIN Account A
        ON A.account_id = TD.account_id
        AND     (
        ((left(RT.spare, 8) = 'INT COMM' OR left(RT.spare, 8) = 'INT ADJ ') OR
            (left(RT.spare, 8) = 'Revsd IC' OR left(RT.spare, 8) = 'Revsl IC')) OR
        (left(RT.spare, 8) = 'Revd ICA' OR left(RT.spare, 8) = 'Revl ICA')
        )
    JOIN party p
        ON p.party_cnt=a.account_key 
UPDATE RT
SET account_address1 = AD.address1,
    account_address2 = AD.address2,
    account_address3 = AD.address3,
    account_address4 = AD.address4,
    account_postal_code = AD.postal_code,
    phone_area_code = A.phone_area_code,
    phone_number = A.phone_number
FROM #Report_Transaction RT
JOIN Account A
    ON A.account_id = RT.account_id
JOIN Party P
    ON P.party_cnt = A.account_key
JOIN Party_Address_Usage PAU
    ON PAU.party_cnt = P.party_cnt
JOIN Address AD
    ON AD.address_cnt = PAU.address_cnt
JOIN Address_Usage_Type AUT
    ON AUT.address_usage_type_id = PAU.address_usage_type_id
   AND AUT.code = '3131 XCO'

/*Identify matched amounts*/
UPDATE #Report_Transaction
SET matched = 1
WHERE match_total = gross_premium

/*Calculate the totals*/
UPDATE RT
SET account_total =
        (
            SELECT SUM(gross_premium)
            FROM #Report_Transaction
            WHERE account_id = RT.account_id
        ),
    account_name = P.resolved_name
FROM #Report_Transaction RT
JOIN Account A
    ON A.account_id = RT.account_id
JOIN Party P
    ON P.party_cnt = A.account_key

/*Set order_code for each account*/
UPDATE RT
SET order_code =
        (
            SELECT
                CASE RT.report_indicator
                    WHEN 0 THEN CONVERT(VARCHAR(30),RT.date_paid,20)
                    WHEN 1 THEN RT.policy_number
                    WHEN 2 THEN RT.client_code
                    WHEN 3 THEN CONVERT(VARCHAR(30),RT.renewal_date,20)
                    WHEN 4 THEN RT.risk_code
                    ELSE RT.document_ref
                END
        )
FROM #Report_Transaction RT

UPDATE RT
SET has_comment =
        CASE
            WHEN ISNULL(latest_transaction_comment,'') = '' THEN 0
            ELSE 1
        END
FROM #Report_Transaction RT

--If this transaction is not related to a finance plan then it will show as a hyphen
UPDATE #Report_Transaction   
SET policy_number ='-' where policy_number is null

/*Extract the data*/
SET NOCOUNT OFF
--SELECT * INTO Am FROM #Report_Transaction RT
SELECT
    transdetail_id,
    document_id,
    account_id,
    documenttype_id,
    branch_id,
    ledger_id,
    account_code,
    account_name,
    document_ref,
    document_date,
    effective_date,
    account_address1,
    account_address2,
    account_address3,
    account_address4,
    account_postal_code,
    phone_area_code,
    phone_number,
    ledger_name,
    policy_number,
    transaction_type_code,
    transaction_type_description,
    policy_type_code,
    policy_type_description,
    gross_premium,
    base_match_amount,
    unallocated_amount,
    account_total,
    match_total,
    date_paid,
    Branch_Name,
    Branch_address1,
    Branch_address2,
    Branch_address3,
    Branch_address4,
    Branch_postal_code,
    matched,
    client_code,
    client_name,
    client_premium,
    client_match_amt,
    client_matched,
    comment,
    number_of_days,
    reminder_type,
    transaction_reason,
    account_handler,
    order_code,
    latest_transaction_comment,
    has_comment,
    spare,
    orig_document_ref,
    ledger_short_name
FROM #Report_Transaction
ORDER BY
    account_code,
    order_code

SET NOCOUNT ON

/*Remove the working table*/
DROP TABLE #Report_Transaction

GO
