[SSCE User]
; =================================================
; DICTIONARY PATH - Change the Paths if you install Sirius in a different folder
; =================================================

MainLexPath=C:\Program Files\Pure\SpellChecker
UserLexPath=C:\Program Files\Pure\SpellChecker
HelpFile=C:\Program Files\Pure\SpellChecker

; =================================================
; DICTIONARIES - Remove the semi-colon from the required MainLexFiles line
; =================================================

; US English
;MainLexFiles=ssceam.tlx,ssceam2.clx

; US English + US Medical & Legal
MainLexFiles=ssceam.tlx,ssceam2.clx,sscema.tlx,sscema2.clx,sscela.tlx,sscela2.clx

; British English
;MainLexFiles=sscebr.tlx,scebr2.clx

; British English + British Medical & Legal
;MainLexFiles=sscebr.tlx,scebr2.clx,sscemb.tlx,sscemb2.clx,sscelb.tlx,sscelb2.clx

; Canadian English
;MainLexFiles=ssceca.tlx,sceca2.clx

; USER DICTIONARY
UserLexFiles=userdic.tlx,correct.tlx

; =================================================
; SETTINGS - customise the spelling options as required
; =================================================

IgnoreCappedWords=0
IgnoreAllCapsWords=0
IgnoreMixedDigits=0
IgnoreMixedCase=0
IgnoreDomainNames=1
ReportDoubledWords=1
AutoCorrect=1
LastSelectedLex=userdic.tlx
CaseSensitive=1
SuggestSplitWords=1
PhoneticSuggestions=0
TypographicalSuggestions=1
SplitContractedWords=0
SplitHyphenatedWords=1
SplitWords=0
MinSuggestDepth=30
AllowAccentedCaps=1
BackupLex=0
DialogOriginX=0
DialogOriginY=0
IgnoreHTMLMarkups=0
IgnoreNonAlphaWords=1
ReportMixedCaseWords=0
ReportUncappedWords=1
ReportWordsWithDigits=0
StripPossessives=1
