'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iACTFindCashList.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Cash List.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1 - Details.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Navigate.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not return any search details.
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Search.
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new search will clear all of your existing search details.
        '''Do you wish to continue?.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching, Please wait....
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) found.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
