'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PartyGCControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corporate Client.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Identity.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Address.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Contact.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Convictions.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5 - Additions.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group code:.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is agent ?.
        '''</summary>
        Friend ReadOnly Property str1107() As String
            Get
                Return ResourceManager.GetString("str1107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group name:.
        '''</summary>
        Friend ReadOnly Property str1108() As String
            Get
                Return ResourceManager.GetString("str1108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prospect Details.
        '''</summary>
        Friend ReadOnly Property str1109() As String
            Get
                Return ResourceManager.GetString("str1109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Charity details.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Charity:.
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. of members:.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group type:.
        '''</summary>
        Friend ReadOnly Property str1113() As String
            Get
                Return ResourceManager.GetString("str1113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. of employees:.
        '''</summary>
        Friend ReadOnly Property str1114() As String
            Get
                Return ResourceManager.GetString("str1114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Charity No.:.
        '''</summary>
        Friend ReadOnly Property str1116() As String
            Get
                Return ResourceManager.GetString("str1116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lead agent.
        '''</summary>
        Friend ReadOnly Property str1117() As String
            Get
                Return ResourceManager.GetString("str1117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code....
        '''</summary>
        Friend ReadOnly Property str1118() As String
            Get
                Return ResourceManager.GetString("str1118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code....
        '''</summary>
        Friend ReadOnly Property str1119() As String
            Get
                Return ResourceManager.GetString("str1119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property str1124() As String
            Get
                Return ResourceManager.GetString("str1124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to County Court Judgements:.
        '''</summary>
        Friend ReadOnly Property str1125() As String
            Get
                Return ResourceManager.GetString("str1125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency:.
        '''</summary>
        Friend ReadOnly Property str1126() As String
            Get
                Return ResourceManager.GetString("str1126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service level:.
        '''</summary>
        Friend ReadOnly Property str1127() As String
            Get
                Return ResourceManager.GetString("str1127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment method:.
        '''</summary>
        Friend ReadOnly Property str1128() As String
            Get
                Return ResourceManager.GetString("str1128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit card type:.
        '''</summary>
        Friend ReadOnly Property str1129() As String
            Get
                Return ResourceManager.GetString("str1129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminder type:.
        '''</summary>
        Friend ReadOnly Property str1130() As String
            Get
                Return ResourceManager.GetString("str1130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terms of payment:.
        '''</summary>
        Friend ReadOnly Property str1131() As String
            Get
                Return ResourceManager.GetString("str1131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Financial year:.
        '''</summary>
        Friend ReadOnly Property str1132() As String
            Get
                Return ResourceManager.GetString("str1132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Associates.
        '''</summary>
        Friend ReadOnly Property str1133() As String
            Get
                Return ResourceManager.GetString("str1133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area:.
        '''</summary>
        Friend ReadOnly Property str1134() As String
            Get
                Return ResourceManager.GetString("str1134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File code:.
        '''</summary>
        Friend ReadOnly Property str1135() As String
            Get
                Return ResourceManager.GetString("str1135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Executive.
        '''</summary>
        Friend ReadOnly Property str1136() As String
            Get
                Return ResourceManager.GetString("str1136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wage roll:.
        '''</summary>
        Friend ReadOnly Property str1137() As String
            Get
                Return ResourceManager.GetString("str1137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turnover:.
        '''</summary>
        Friend ReadOnly Property str1138() As String
            Get
                Return ResourceManager.GetString("str1138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vat code:.
        '''</summary>
        Friend ReadOnly Property str1139() As String
            Get
                Return ResourceManager.GetString("str1139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is prospect ?.
        '''</summary>
        Friend ReadOnly Property str1140() As String
            Get
                Return ResourceManager.GetString("str1140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferred Correspondence:.
        '''</summary>
        Friend ReadOnly Property str1141() As String
            Get
                Return ResourceManager.GetString("str1141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main contact:.
        '''</summary>
        Friend ReadOnly Property str1142() As String
            Get
                Return ResourceManager.GetString("str1142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Branch:.
        '''</summary>
        Friend ReadOnly Property str1143() As String
            Get
                Return ResourceManager.GetString("str1143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trading name:.
        '''</summary>
        Friend ReadOnly Property str1144() As String
            Get
                Return ResourceManager.GetString("str1144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub-branch:.
        '''</summary>
        Friend ReadOnly Property str1145() As String
            Get
                Return ResourceManager.GetString("str1145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alternative Identifier:.
        '''</summary>
        Friend ReadOnly Property str1146() As String
            Get
                Return ResourceManager.GetString("str1146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loyalty number:.
        '''</summary>
        Friend ReadOnly Property str1147() As String
            Get
                Return ResourceManager.GetString("str1147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loyalty Schemes.
        '''</summary>
        Friend ReadOnly Property str1155() As String
            Get
                Return ResourceManager.GetString("str1155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6 - Misc.
        '''</summary>
        Friend ReadOnly Property str1156() As String
            Get
                Return ResourceManager.GetString("str1156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Delete.
        '''</summary>
        Friend ReadOnly Property str1157() As String
            Get
                Return ResourceManager.GetString("str1157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the selected item?.
        '''</summary>
        Friend ReadOnly Property str1158() As String
            Get
                Return ResourceManager.GetString("str1158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third Party.
        '''</summary>
        Friend ReadOnly Property str1159() As String
            Get
                Return ResourceManager.GetString("str1159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7 - Tax.
        '''</summary>
        Friend ReadOnly Property str1160() As String
            Get
                Return ResourceManager.GetString("str1160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fee Client:.
        '''</summary>
        Friend ReadOnly Property str1161() As String
            Get
                Return ResourceManager.GetString("str1161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Navigate.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property str1204() As String
            Get
                Return ResourceManager.GetString("str1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property str1206() As String
            Get
                Return ResourceManager.GetString("str1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not add or update any details
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Agent you have selected does not exist.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The reference you have entered already exists.
        '''Please enter a new reference.
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Third Party you have selected does not exist.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
