'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPMBFindParty.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Client.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Company / Person.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Address &amp; Telephone.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Policy.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client code:.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type:.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status:.
        '''</summary>
        Friend ReadOnly Property str1107() As String
            Get
                Return ResourceManager.GetString("str1107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address line 1:.
        '''</summary>
        Friend ReadOnly Property str1108() As String
            Get
                Return ResourceManager.GetString("str1108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PostCode:.
        '''</summary>
        Friend ReadOnly Property str1109() As String
            Get
                Return ResourceManager.GetString("str1109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone:.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy number....
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Closed Branches.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Code.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 1.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PostCode.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Code.
        '''</summary>
        Friend ReadOnly Property str1124() As String
            Get
                Return ResourceManager.GetString("str1124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property str1125() As String
            Get
                Return ResourceManager.GetString("str1125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property str1126() As String
            Get
                Return ResourceManager.GetString("str1126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source.
        '''</summary>
        Friend ReadOnly Property str1127() As String
            Get
                Return ResourceManager.GetString("str1127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Finance Provider.
        '''</summary>
        Friend ReadOnly Property str1128() As String
            Get
                Return ResourceManager.GetString("str1128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Reinsurer.
        '''</summary>
        Friend ReadOnly Property str1129() As String
            Get
                Return ResourceManager.GetString("str1129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Agent.
        '''</summary>
        Friend ReadOnly Property str1130() As String
            Get
                Return ResourceManager.GetString("str1130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Account Executive.
        '''</summary>
        Friend ReadOnly Property str1131() As String
            Get
                Return ResourceManager.GetString("str1131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Account Handler.
        '''</summary>
        Friend ReadOnly Property str1132() As String
            Get
                Return ResourceManager.GetString("str1132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Insurer.
        '''</summary>
        Friend ReadOnly Property str1133() As String
            Get
                Return ResourceManager.GetString("str1133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Broker.
        '''</summary>
        Friend ReadOnly Property str1134() As String
            Get
                Return ResourceManager.GetString("str1134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Fee.
        '''</summary>
        Friend ReadOnly Property str1135() As String
            Get
                Return ResourceManager.GetString("str1135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Extra.
        '''</summary>
        Friend ReadOnly Property str1136() As String
            Get
                Return ResourceManager.GetString("str1136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Discount.
        '''</summary>
        Friend ReadOnly Property str1137() As String
            Get
                Return ResourceManager.GetString("str1137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Commission Account.
        '''</summary>
        Friend ReadOnly Property str1138() As String
            Get
                Return ResourceManager.GetString("str1138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finance Provider Code:.
        '''</summary>
        Friend ReadOnly Property str1139() As String
            Get
                Return ResourceManager.GetString("str1139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Code:.
        '''</summary>
        Friend ReadOnly Property str1140() As String
            Get
                Return ResourceManager.GetString("str1140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Executive Code:.
        '''</summary>
        Friend ReadOnly Property str1141() As String
            Get
                Return ResourceManager.GetString("str1141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Handler Code:.
        '''</summary>
        Friend ReadOnly Property str1142() As String
            Get
                Return ResourceManager.GetString("str1142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insurer Code:.
        '''</summary>
        Friend ReadOnly Property str1143() As String
            Get
                Return ResourceManager.GetString("str1143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Broker Code:.
        '''</summary>
        Friend ReadOnly Property str1144() As String
            Get
                Return ResourceManager.GetString("str1144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fee Code:.
        '''</summary>
        Friend ReadOnly Property str1145() As String
            Get
                Return ResourceManager.GetString("str1145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extra Code:.
        '''</summary>
        Friend ReadOnly Property str1146() As String
            Get
                Return ResourceManager.GetString("str1146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount Code:.
        '''</summary>
        Friend ReadOnly Property str1147() As String
            Get
                Return ResourceManager.GetString("str1147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission Account Code:.
        '''</summary>
        Friend ReadOnly Property str1148() As String
            Get
                Return ResourceManager.GetString("str1148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reinsurer Code:.
        '''</summary>
        Friend ReadOnly Property str1149() As String
            Get
                Return ResourceManager.GetString("str1149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Other Parties.
        '''</summary>
        Friend ReadOnly Property str1150() As String
            Get
                Return ResourceManager.GetString("str1150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party Code:.
        '''</summary>
        Friend ReadOnly Property str1151() As String
            Get
                Return ResourceManager.GetString("str1151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party Type:.
        '''</summary>
        Friend ReadOnly Property str1152() As String
            Get
                Return ResourceManager.GetString("str1152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Of Birth.
        '''</summary>
        Friend ReadOnly Property str1153() As String
            Get
                Return ResourceManager.GetString("str1153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swift Link.
        '''</summary>
        Friend ReadOnly Property str1154() As String
            Get
                Return ResourceManager.GetString("str1154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 2.
        '''</summary>
        Friend ReadOnly Property str1155() As String
            Get
                Return ResourceManager.GetString("str1155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Membership Id.
        '''</summary>
        Friend ReadOnly Property str1156() As String
            Get
                Return ResourceManager.GetString("str1156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Agent Group.
        '''</summary>
        Friend ReadOnly Property str1157() As String
            Get
                Return ResourceManager.GetString("str1157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Group Code:.
        '''</summary>
        Friend ReadOnly Property str1158() As String
            Get
                Return ResourceManager.GetString("str1158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Branch:.
        '''</summary>
        Friend ReadOnly Property str1159() As String
            Get
                Return ResourceManager.GetString("str1159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third Party:.
        '''</summary>
        Friend ReadOnly Property str1160() As String
            Get
                Return ResourceManager.GetString("str1160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Third Party.
        '''</summary>
        Friend ReadOnly Property str1161() As String
            Get
                Return ResourceManager.GetString("str1161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Intermediary.
        '''</summary>
        Friend ReadOnly Property str1162() As String
            Get
                Return ResourceManager.GetString("str1162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intermediary Code:.
        '''</summary>
        Friend ReadOnly Property str1163() As String
            Get
                Return ResourceManager.GetString("str1163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend ReadOnly Property str1164() As String
            Get
                Return ResourceManager.GetString("str1164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forename.
        '''</summary>
        Friend ReadOnly Property str1165() As String
            Get
                Return ResourceManager.GetString("str1165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 3.
        '''</summary>
        Friend ReadOnly Property str1166() As String
            Get
                Return ResourceManager.GetString("str1166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 4.
        '''</summary>
        Friend ReadOnly Property str1167() As String
            Get
                Return ResourceManager.GetString("str1167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigate.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F&amp;ind Now.
        '''</summary>
        Friend ReadOnly Property str1204() As String
            Get
                Return ResourceManager.GetString("str1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ne&amp;w Search.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N&amp;ew.
        '''</summary>
        Friend ReadOnly Property str1206() As String
            Get
                Return ResourceManager.GetString("str1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;dit.
        '''</summary>
        Friend ReadOnly Property str1207() As String
            Get
                Return ResourceManager.GetString("str1207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property str1208() As String
            Get
                Return ResourceManager.GetString("str1208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undelete.
        '''</summary>
        Friend ReadOnly Property str1209() As String
            Get
                Return ResourceManager.GetString("str1209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not return any search details.
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Search.
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new search will clear all of your existing search details.
        '''Do you wish to continue?.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching, Please wait....
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) found.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Management..
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning - No Agency Agreement exists..
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Client.
        '''</summary>
        Friend ReadOnly Property str1310() As String
            Get
                Return ResourceManager.GetString("str1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you wish to proceed and delete this client?.
        '''</summary>
        Friend ReadOnly Property str1311() As String
            Get
                Return ResourceManager.GetString("str1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to amend Client Details.
        '''</summary>
        Friend ReadOnly Property str1312() As String
            Get
                Return ResourceManager.GetString("str1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose an address:.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to House.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Street.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suburb.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Client.
        '''</summary>
        Friend ReadOnly Property str2100() As String
            Get
                Return ResourceManager.GetString("str2100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Company / Person.
        '''</summary>
        Friend ReadOnly Property str2101() As String
            Get
                Return ResourceManager.GetString("str2101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Address &amp; Telephone.
        '''</summary>
        Friend ReadOnly Property str2102() As String
            Get
                Return ResourceManager.GetString("str2102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Policy.
        '''</summary>
        Friend ReadOnly Property str2103() As String
            Get
                Return ResourceManager.GetString("str2103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client code:.
        '''</summary>
        Friend ReadOnly Property str2104() As String
            Get
                Return ResourceManager.GetString("str2104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property str2105() As String
            Get
                Return ResourceManager.GetString("str2105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type:.
        '''</summary>
        Friend ReadOnly Property str2106() As String
            Get
                Return ResourceManager.GetString("str2106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status:.
        '''</summary>
        Friend ReadOnly Property str2107() As String
            Get
                Return ResourceManager.GetString("str2107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address line 1:.
        '''</summary>
        Friend ReadOnly Property str2108() As String
            Get
                Return ResourceManager.GetString("str2108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZipCode:.
        '''</summary>
        Friend ReadOnly Property str2109() As String
            Get
                Return ResourceManager.GetString("str2109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone:.
        '''</summary>
        Friend ReadOnly Property str2110() As String
            Get
                Return ResourceManager.GetString("str2110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy number....
        '''</summary>
        Friend ReadOnly Property str2111() As String
            Get
                Return ResourceManager.GetString("str2111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Closed Branches.
        '''</summary>
        Friend ReadOnly Property str2112() As String
            Get
                Return ResourceManager.GetString("str2112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Code.
        '''</summary>
        Friend ReadOnly Property str2120() As String
            Get
                Return ResourceManager.GetString("str2120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property str2121() As String
            Get
                Return ResourceManager.GetString("str2121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 1.
        '''</summary>
        Friend ReadOnly Property str2122() As String
            Get
                Return ResourceManager.GetString("str2122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZipCode.
        '''</summary>
        Friend ReadOnly Property str2123() As String
            Get
                Return ResourceManager.GetString("str2123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Code.
        '''</summary>
        Friend ReadOnly Property str2124() As String
            Get
                Return ResourceManager.GetString("str2124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property str2125() As String
            Get
                Return ResourceManager.GetString("str2125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property str2126() As String
            Get
                Return ResourceManager.GetString("str2126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source.
        '''</summary>
        Friend ReadOnly Property str2127() As String
            Get
                Return ResourceManager.GetString("str2127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Finance Provider.
        '''</summary>
        Friend ReadOnly Property str2128() As String
            Get
                Return ResourceManager.GetString("str2128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Reinsurer.
        '''</summary>
        Friend ReadOnly Property str2129() As String
            Get
                Return ResourceManager.GetString("str2129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Agent.
        '''</summary>
        Friend ReadOnly Property str2130() As String
            Get
                Return ResourceManager.GetString("str2130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Account Executive.
        '''</summary>
        Friend ReadOnly Property str2131() As String
            Get
                Return ResourceManager.GetString("str2131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Account Handler.
        '''</summary>
        Friend ReadOnly Property str2132() As String
            Get
                Return ResourceManager.GetString("str2132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Insurer.
        '''</summary>
        Friend ReadOnly Property str2133() As String
            Get
                Return ResourceManager.GetString("str2133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Broker.
        '''</summary>
        Friend ReadOnly Property str2134() As String
            Get
                Return ResourceManager.GetString("str2134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Fee.
        '''</summary>
        Friend ReadOnly Property str2135() As String
            Get
                Return ResourceManager.GetString("str2135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Extra.
        '''</summary>
        Friend ReadOnly Property str2136() As String
            Get
                Return ResourceManager.GetString("str2136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Discount.
        '''</summary>
        Friend ReadOnly Property str2137() As String
            Get
                Return ResourceManager.GetString("str2137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Commission Account.
        '''</summary>
        Friend ReadOnly Property str2138() As String
            Get
                Return ResourceManager.GetString("str2138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finance Provider Code:.
        '''</summary>
        Friend ReadOnly Property str2139() As String
            Get
                Return ResourceManager.GetString("str2139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Code:.
        '''</summary>
        Friend ReadOnly Property str2140() As String
            Get
                Return ResourceManager.GetString("str2140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Executive Code:.
        '''</summary>
        Friend ReadOnly Property str2141() As String
            Get
                Return ResourceManager.GetString("str2141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Handler Code:.
        '''</summary>
        Friend ReadOnly Property str2142() As String
            Get
                Return ResourceManager.GetString("str2142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insurer Code:.
        '''</summary>
        Friend ReadOnly Property str2143() As String
            Get
                Return ResourceManager.GetString("str2143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Broker Code:.
        '''</summary>
        Friend ReadOnly Property str2144() As String
            Get
                Return ResourceManager.GetString("str2144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fee Code:.
        '''</summary>
        Friend ReadOnly Property str2145() As String
            Get
                Return ResourceManager.GetString("str2145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extra Code:.
        '''</summary>
        Friend ReadOnly Property str2146() As String
            Get
                Return ResourceManager.GetString("str2146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount Code:.
        '''</summary>
        Friend ReadOnly Property str2147() As String
            Get
                Return ResourceManager.GetString("str2147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commission Account Code:.
        '''</summary>
        Friend ReadOnly Property str2148() As String
            Get
                Return ResourceManager.GetString("str2148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reinsurer Code:.
        '''</summary>
        Friend ReadOnly Property str2149() As String
            Get
                Return ResourceManager.GetString("str2149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Other Parties.
        '''</summary>
        Friend ReadOnly Property str2150() As String
            Get
                Return ResourceManager.GetString("str2150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party Code:.
        '''</summary>
        Friend ReadOnly Property str2151() As String
            Get
                Return ResourceManager.GetString("str2151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party Type:.
        '''</summary>
        Friend ReadOnly Property str2152() As String
            Get
                Return ResourceManager.GetString("str2152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Of Birth.
        '''</summary>
        Friend ReadOnly Property str2153() As String
            Get
                Return ResourceManager.GetString("str2153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swift Link.
        '''</summary>
        Friend ReadOnly Property str2154() As String
            Get
                Return ResourceManager.GetString("str2154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 2.
        '''</summary>
        Friend ReadOnly Property str2155() As String
            Get
                Return ResourceManager.GetString("str2155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Membership Id.
        '''</summary>
        Friend ReadOnly Property str2156() As String
            Get
                Return ResourceManager.GetString("str2156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Agent Group.
        '''</summary>
        Friend ReadOnly Property str2157() As String
            Get
                Return ResourceManager.GetString("str2157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Group Code:.
        '''</summary>
        Friend ReadOnly Property str2158() As String
            Get
                Return ResourceManager.GetString("str2158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Branch:.
        '''</summary>
        Friend ReadOnly Property str2159() As String
            Get
                Return ResourceManager.GetString("str2159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third Party:.
        '''</summary>
        Friend ReadOnly Property str2160() As String
            Get
                Return ResourceManager.GetString("str2160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Third Party.
        '''</summary>
        Friend ReadOnly Property str2161() As String
            Get
                Return ResourceManager.GetString("str2161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find: Intermediary.
        '''</summary>
        Friend ReadOnly Property str2162() As String
            Get
                Return ResourceManager.GetString("str2162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intermediary Code:.
        '''</summary>
        Friend ReadOnly Property str2163() As String
            Get
                Return ResourceManager.GetString("str2163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend ReadOnly Property str2164() As String
            Get
                Return ResourceManager.GetString("str2164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forename.
        '''</summary>
        Friend ReadOnly Property str2165() As String
            Get
                Return ResourceManager.GetString("str2165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 3.
        '''</summary>
        Friend ReadOnly Property str2166() As String
            Get
                Return ResourceManager.GetString("str2166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 4.
        '''</summary>
        Friend ReadOnly Property str2167() As String
            Get
                Return ResourceManager.GetString("str2167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property str2200() As String
            Get
                Return ResourceManager.GetString("str2200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property str2201() As String
            Get
                Return ResourceManager.GetString("str2201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property str2202() As String
            Get
                Return ResourceManager.GetString("str2202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigate.
        '''</summary>
        Friend ReadOnly Property str2203() As String
            Get
                Return ResourceManager.GetString("str2203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find Now.
        '''</summary>
        Friend ReadOnly Property str2204() As String
            Get
                Return ResourceManager.GetString("str2204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Search.
        '''</summary>
        Friend ReadOnly Property str2205() As String
            Get
                Return ResourceManager.GetString("str2205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property str2206() As String
            Get
                Return ResourceManager.GetString("str2206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property str2207() As String
            Get
                Return ResourceManager.GetString("str2207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property str2208() As String
            Get
                Return ResourceManager.GetString("str2208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undelete.
        '''</summary>
        Friend ReadOnly Property str2209() As String
            Get
                Return ResourceManager.GetString("str2209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str2300() As String
            Get
                Return ResourceManager.GetString("str2300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not return any search details.
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str2301() As String
            Get
                Return ResourceManager.GetString("str2301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str2302() As String
            Get
                Return ResourceManager.GetString("str2302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str2303() As String
            Get
                Return ResourceManager.GetString("str2303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Search.
        '''</summary>
        Friend ReadOnly Property str2304() As String
            Get
                Return ResourceManager.GetString("str2304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new search will clear all of your existing search details.
        '''Do you wish to continue?.
        '''</summary>
        Friend ReadOnly Property str2305() As String
            Get
                Return ResourceManager.GetString("str2305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching, Please wait....
        '''</summary>
        Friend ReadOnly Property str2306() As String
            Get
                Return ResourceManager.GetString("str2306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) found.
        '''</summary>
        Friend ReadOnly Property str2307() As String
            Get
                Return ResourceManager.GetString("str2307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agent Management..
        '''</summary>
        Friend ReadOnly Property str2308() As String
            Get
                Return ResourceManager.GetString("str2308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning - No Agency Agreement exists..
        '''</summary>
        Friend ReadOnly Property str2309() As String
            Get
                Return ResourceManager.GetString("str2309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Client.
        '''</summary>
        Friend ReadOnly Property str2310() As String
            Get
                Return ResourceManager.GetString("str2310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you wish to proceed and delete this client?.
        '''</summary>
        Friend ReadOnly Property str2311() As String
            Get
                Return ResourceManager.GetString("str2311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to amend Client Details.
        '''</summary>
        Friend ReadOnly Property str2312() As String
            Get
                Return ResourceManager.GetString("str2312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose an address:.
        '''</summary>
        Friend ReadOnly Property str2313() As String
            Get
                Return ResourceManager.GetString("str2313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to House.
        '''</summary>
        Friend ReadOnly Property str2314() As String
            Get
                Return ResourceManager.GetString("str2314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Street.
        '''</summary>
        Friend ReadOnly Property str2315() As String
            Get
                Return ResourceManager.GetString("str2315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suburb.
        '''</summary>
        Friend ReadOnly Property str2316() As String
            Get
                Return ResourceManager.GetString("str2316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend ReadOnly Property str2317() As String
            Get
                Return ResourceManager.GetString("str2317", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
