SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

DDLDropProcedure 'spu_PFScheme_add'

GO
-- Object:  Stored Procedure dbo.spu_PFScheme_add    
-- Script Date: 10/15/2003 2:18:09 PM    
    
-- Added 4 New parameters to support Re-Insurance dripping    
CREATE PROCEDURE spu_PFScheme_add    
    @companyno int,  
    @schemeno int,  
    @schemeversion int,  
    @party_cnt int,  
    @datamodelcode varchar(10),  
    @startdate datetime,  
    @enddate datetime,  
    @paymentmethod_cnt int,  
    @systemtag char(1),  
    @schemename varchar(35),  
    @schemedescription varchar(255),  
    @quoteableind char(1),  
    @quotedocid int,  
    @bankdocid int,  
    @creditdocid int,  
    @insrmailboxno varchar(25),  
    @EDImessagecount numeric (18,0),  
    @immediatebankdetails tinyint,  
    @mediatype_id INT,  
    @currency_id INT,  
    @pfscheme_printtype_id INT,  
    @spread_commission TINYINT,  
    @suspense_account_id INT,  
    @interest_account_id INT,  
    @admin_account_id INT,  
    @protection_account_id INT,  
    @tax_group_id INT,  
    @tax_suspense_account_id INT,  
    @commission_suspense_account_id INT,  
    @pfscheme_type_id INT,  
    @bank_name_mandatory TINYINT,  
    @bank_address_mandatory TINYINT,  
    @branch_name_mandatory TINYINT,  
    @branch_code_mandatory TINYINT,  
    @bankaccount_id INT,  
    @confirmation_doc_id INT,  
    @Spread_ri TINYINT,  
    @Spread_taxes TINYINT,  
    @ri_Suspense_Account_ID INT,  
    @deposit_as_instalment TINYINT,  
    @deposit_on_other_media_type TINYINT,  
    @agent_ref_mandatory TINYINT,  
    @pf_message VARCHAR(255),  
    @business_code_mandatory TINYINT,  
	 @receipt_difference TINYINT,  
	 @provider_website VARCHAR(255),  
	 @provider_username VARCHAR(100),  
	 @provider_password VARCHAR(100),  
	 @provider_brokerid VARCHAR(100),  
	 @provider_timeout INT,  
	 @financial_institution_code VARCHAR(50),  
	 @direct_debit_supplier_name VARCHAR(50),  
	 @direct_debit_supplier_id VARCHAR(50),  
	 @remitter VARCHAR(50),  
	 @processing_days SMALLINT,  
	 @rates_are_for_information_only TINYINT ,--'(RC) PLICO 9-10  
	 @provider_plbrokerid VARCHAR(255),  
	 @provider_clbrokerid VARCHAR(255),  
	 @provider_prem_threshold INT,  
	 @allow_client_fees  INT,
	 @is_plan_reference_editable TINYINT,
	--Start(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
	 @ColNotDocID INT,
	 @nColNotNumDays INT = 0,
	--End(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
	@nspread_subagent_commission TINYINT,   
	@ncommission_subagent_suspense_account_id INT,
	@UserId INT = 0,
	@UniqueId VARCHAR(50),
	@ScreenHierarchy VARCHAR(500),
	@sBusinessIdentifierCodeMandatory TINYINT = 0,  
	@sInternationalBankAccountNumberMandatory TINYINT = 0,
	@SchemeType TINYINT = 1
AS  
BEGIN  
INSERT INTO PFScheme (  
    companyno,  
    schemeno,  
    schemeversion,  
    party_cnt,  
    datamodelcode,  
    startdate,  
    enddate,  
    paymentmethod_cnt,  
    systemtag,  
    schemename,  
    schemedescription,  
    quoteableind,  
    quotedocid,  
    bankdocid,  
    creditdocid,  
    insrmailboxno,  
    EDImessagecount,  
    immediatebankdetails,  
    mediatype_id,  
    currency_id,  
    pfscheme_printtype_id,  
    spread_commission,  
    suspense_account_id,  
    interest_account_id,  
    admin_account_id,  
    protection_account_id,  
    tax_group_id,  
    tax_suspense_account_id,  
    commission_suspense_account_id,  
    pfscheme_type_id,  
    bank_name_mandatory,  
    bank_address_mandatory,  
    branch_name_mandatory,  
    branch_code_mandatory,  
    bankaccount_id,  
    ConfirmationDocID,  
    spread_taxes,  
    spread_ri,  
    ri_suspense_account_id,  
    deposit_as_instalment,  
    deposit_on_other_media_type,  
    agent_ref_mandatory,  
    pf_message,  
	 business_code_mandatory,  
	 receipt_difference_option,  
	 provider_website,  
	 provider_username,  
	 provider_password,  
	 provider_brokerid,  
	 provider_timeout,  
	 financial_institution_code,  
	 direct_debit_supplier_name,  
	 direct_debit_supplier_id,  
	 remitter,  
	 processing_days,  
	 rates_are_for_information_only, --'(RC) PLICO 9-10  
	 plbrokerid,  
	 clbrokerid,  
	 provider_prem_threshold,  
	 allow_client_fees,
	is_plan_reference_editable,
	--Start(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
	ColNotdocID,
	ColNotNumDays,
	--End(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)  
	 spread_subagent_commission ,  
    commission_subagent_suspense_account_id,
	UserId ,
	UniqueId,
	ScreenHierarchy,
	business_identifier_code_mandatory,
    international_bank_account_number_mandatory,
	scheme_type
)  
VALUES (  
    @companyno,  
    @schemeno,  
    @schemeversion,  
    @party_cnt,  
    @datamodelcode,  
    @startdate,  
    @enddate,  
    @paymentmethod_cnt,  
    @systemtag,  
    @schemename,  
    @schemedescription,  
    @quoteableind,  
    @quotedocid,  
    @bankdocid,  
    @creditdocid,  
    @insrmailboxno,  
    @EDImessagecount,  
    @immediatebankdetails,  
    @mediatype_id,  
    @currency_id,  
    @pfscheme_printtype_id,  
    @spread_commission ,  
    @suspense_account_id,  
    @interest_account_id,  
    @admin_account_id,  
    @protection_account_id,  
    @tax_group_id,  
    @tax_suspense_account_id,  
    @commission_suspense_account_id,  
    @pfscheme_type_id,  
    @bank_name_mandatory,  
    @bank_address_mandatory,  
    @branch_name_mandatory,  
    @branch_code_mandatory,  
    @bankaccount_id,  
    @confirmation_doc_id,  
    @Spread_taxes,  
    @Spread_ri,  
    @ri_Suspense_Account_ID,  
    @deposit_as_instalment,  
    @deposit_on_other_media_type,  
	 @agent_ref_mandatory,  
	 @pf_message,  
	 @business_code_mandatory,  
	 @receipt_difference,  
	 @provider_website,  
	 @provider_username,  
	 @provider_password,  
	 @provider_brokerid,  
	 @provider_timeout,  
	 @financial_institution_code,  
	 @direct_debit_supplier_name,  
	 @direct_debit_supplier_id,  
	 @remitter,  
	 @processing_days,  
	 @rates_are_for_information_only,  --'(RC) PLICO 9-10  
	 @provider_plbrokerid,  
	 @provider_clbrokerid,  
	 @provider_prem_threshold,  
	 @allow_client_fees,
	 @is_plan_reference_editable,
	--Start(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
	 @ColNotDocID ,
	 @nColNotNumDays,
	--End(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)  
	 @nspread_subagent_commission ,   
    @ncommission_subagent_suspense_account_id,
	@UserId ,
	@UniqueId,
	@ScreenHierarchy,
	@sBusinessIdentifierCodeMandatory,  
	@sInternationalBankAccountNumberMandatory,
	@SchemeType
)  
  
END  
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

