EXECUTE DDLDropProcedure 'spu_PFInstalments_update_new_instalment_date'
GO

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO

CREATE  PROCEDURE spu_PFInstalments_update_new_instalment_date
   	@FinancePlanCnt int,
    	@FinancePlanVersion int

AS 
BEGIN

declare @new_status_id int, 
	@daysdelay int, 
	@delayedpaymentdate datetime,
        @datechanged datetime

	select @new_status_id = ( select pfinstalments_status_id from pfinstalments_status where code = 'U' )

	--if there is an existing instalment that is 'new', update next payment date, 
	--if before date bank details changed + mta days delay.
	--to be date bank details changed + mta days delay

	select @daysdelay = ISNULL(pfrf.daysdelay, 0)
	from pfrf pfrf
	join pfpremiumfinance pf on pf.schemeno = pfrf.schemeno and pf.schemeversion = pfrf.schemeversion
	where pf.pfprem_finance_cnt = @FinancePlanCnt
	and pf.pfprem_finance_version = @FinancePlanVersion
	and pfrf.productfamily = 'MTA'
	and pfrf.startdate <= GetDate() 
        and pfrf.enddate >= GetDate()

	select @datechanged = max(pfpf2.datebankdetailschanged)
	from pfpremiumfinance pfpf
	join pfpremiumfinance pfpf2 on pfpf.autogeneratedplanref = pfpf2.autogeneratedplanref
	where pfpf.pfprem_finance_cnt = @FinancePlanCnt
	and pfpf.pfprem_finance_version = @FinancePlanVersion

	if @datechanged is not null 
	begin
		select @delayedpaymentdate = dateadd(dd, @daysdelay, @datechanged)

		update pfinstalments 
		set duedate = @delayedpaymentdate 
		where pfprem_finance_cnt = @FinancePlanCnt
		and pfprem_finance_version = @FinancePlanVersion
		and duedate < @delayedpaymentdate
		and status = @new_status_id

	end

end
GO

SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO