
/* Created by : Vidya Rangdale
Creation Date : 26/02/2014
Description   : This is used to do some manipulation onn data
Test Code     : Exec spu_PFPremiumFinance_Generate_Unique_PlanRef
 */

SET QUOTED_IDENTIFIER OFF 
GO

Execute DDLDropProcedure 'spu_PFPremiumFinance_Generate_Unique_PlanRef'
GO

CREATE PROCEDURE spu_PFPremiumFinance_Generate_Unique_PlanRef
    @sPlanReference VARCHAR(20)
 
AS  

DECLARE @sNewPlanReference VARCHAR(20)         
DECLARE @nExists int 
 
SET @sNewPlanReference =  CONVERT(NUMERIC,@sPlanReference) + 1 

WHILE 1=1
BEGIN 
    SET @nExists = 0 
    IF EXISTS (SELECT 1 FROM PFMediaTypeHistory WHERE AutoGeneratedPlanRef = @sNewPlanReference)
        SET @sNewPlanReference =  CONVERT(NUMERIC,@sNewPlanReference) + 1 
    ELSE
       BREAK 
END

SELECT @sNewPlanReference