Execute DDLDropProcedure 'spu_PFPremiumFinance_Get_Exisiting_Plan_Details'
GO

CREATE PROCEDURE spu_PFPremiumFinance_Get_Exisiting_Plan_Details  
    @FinancePlanCnt INT,  
    @FinancePlanVersion INT  
AS  
  
SELECT  
    pf.bankname,  
    pf.banksortcode,  
    pf.bankaccountno,  
    pf.bankbranch,  
    pf.bankaddr1,  
    pf.bankaddr2,  
    pf.bankaddr3,  
    pf.bankregion,  
    pf.banktown,  
    pf.bankpcode,  
    pf.bankcountry,  
    pf.bankareacode,  
    pf.bankphoneno,  
    pf.bankextension,  
    pf.bankfaxareacode,  
    pf.bankfaxno,  
    pf.bankaccountname,  
    pf.cc_number,  
    pf.cc_expiry_date,  
    pf.cc_start_date,  
    pf.cc_issue,  
    pf.cc_pin,  
    cc.country_id 'client_country_id',  
    bc.country_id 'bank_country_id',  
    pf.insurance_file_cnt,  
    pf.source_id,  
    pf.sub_branch_id,  
    pf.batch_id,   --'(RC) PLICO 9-10 
    pf.autogeneratedplanref,
    pf.party_bank_id,
    pf.AmountToFinance,
	pf.business_identifier_code,
	pf.international_bank_account_number, 
	pf.card_type,
	pf.cardholder_name,
	pf.is_cardholder,
	pf.cardholder_address1,
	pf.cardholder_address2,
	pf.cardholder_address3,
	pf.cardholder_address4,
	Pf.cardholder_postcode,
	chc.country_id 'Card_Holder_country_id',
    Pf.auth_code	
FROM pfpremiumfinance pf  
LEFT JOIN country bc  
    ON bc.description = pf.bankcountry  
LEFT JOIN country cc  
    ON cc.description = pf.clientcountry  
LEFT JOIN country chc
	ON chc.description = pf.CardHolderCountry  
WHERE pfprem_finance_cnt = @FinancePlanCnt  
AND pfprem_finance_version = @FinancePlanVersion  



GO
