SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

DDLDropProcedure 'spu_PFScheme_upd'
GO

CREATE PROCEDURE spu_PFScheme_upd
    @companyno int,  
    @schemeno int,  
    @schemeversion int,  
    @party_cnt int,  
    @datamodelcode varchar(10),  
    @startdate datetime,  
    @enddate datetime,  
    @paymentmethod_cnt int,  
    @systemtag char(1),  
    @schemename varchar(35),  
    @schemedescription varchar(255),  
    @quoteableind char(1),  
    @quotedocid int,  
    @bankdocid int,  
    @creditdocid int,  
    @insrmailboxno varchar(25),  
    @EDImessagecount numeric (18,0),  
    @immediatebankdetails tinyint,  
    @mediatype_id INT,  
    @currency_id INT,  
    @pfscheme_printtype_id INT,  
    @spread_commission TINYINT,  
    @suspense_account_id INT,  
    @interest_account_id INT,  
    @admin_account_id INT,  
    @protection_account_id INT,  
    @tax_group_id INT,  
    @tax_suspense_account_id INT,  
    @commission_suspense_account_id INT,  
    @pfscheme_type_id INT,  
    @bank_name_mandatory TINYINT,  
    @bank_address_mandatory TINYINT,  
    @branch_name_mandatory TINYINT,  
    @branch_code_mandatory TINYINT,  
    @bankaccount_id INT,  
    @confirmation_doc_id INT,  
    @Spread_ri TINYINT,  
    @Spread_taxes TINYINT,  
    @ri_Suspense_Account_ID INT,  
    @deposit_as_instalment TINYINT,  
    @deposit_on_other_media_type TINYINT,  
	@agent_ref_mandatory TINYINT,  
	@pf_message VARCHAR(255),  
	@business_code_mandatory TINYINT,  
	@receipt_difference TINYINT,  
	@provider_website VARCHAR(255),  
	@provider_username VARCHAR(255),  
	@provider_password VARCHAR(255),  
	@provider_brokerid VARCHAR(255),  
	@provider_timeout VARCHAR(255),  
	@financial_institution_code VARCHAR(50),  
	@direct_debit_supplier_name VARCHAR(50),  
	@direct_debit_supplier_id VARCHAR(50),  
	@remitter VARCHAR(50),  
	@processing_days SMALLINT,  
	@rates_are_for_information_only TINYINT,--'(RC) PLICO 9-10  
	@provider_plbrokerid VARCHAR(255),  
	@provider_clbrokerid VARCHAR(255),  
	@provider_prem_threshold INT,  
	@allow_client_fees  INT ,
	@is_plan_reference_editable TINYINT, 
	@ColNotDocID INT,
	@nColNotNumDays INT = 0, 
	@sBusinessIdentifierCodeMandatory TINYINT = 0,
	@sInternationalBankAccountNumberMandatory TINYINT = 0,
	@nspread_subagent_commission TINYINT,  
	@ncommission_subagent_suspense_account_id INT,
	@UserId INT = 0,
	@UniqueId VARCHAR(50),
	@ScreenHierarchy VARCHAR(500) = NULL,
	@SchemeType TINYINT = 1
AS  
BEGIN  
UPDATE PFScheme SET  
    party_cnt = @party_cnt,  
    datamodelcode = @datamodelcode,  
    startdate = @startdate,  
    enddate = @enddate,  
    paymentmethod_cnt = @paymentmethod_cnt,  
    systemtag = @systemtag,  
    schemename = @schemename,  
    schemedescription = @schemedescription,  
    quoteableind = @quoteableind,  
    quotedocid = @quotedocid,  
    bankdocid = @bankdocid,  
    creditdocid = @creditdocid,  
    insrmailboxno = @insrmailboxno,  
    EDImessagecount = @EDImessagecount,  
    immediatebankdetails = @immediatebankdetails,  
    mediatype_id = @mediatype_id ,  
    currency_id = @currency_id,  
    pfscheme_printtype_id = @pfscheme_printtype_id,  
    spread_commission = @spread_commission,  
    suspense_account_id = @suspense_account_id,  
    interest_account_id = @interest_account_id,  
    admin_account_id = @admin_account_id,  
    protection_account_id = @protection_account_id,  
    tax_group_id = @tax_group_id,  
    tax_suspense_account_id = @tax_suspense_account_id,  
    commission_suspense_account_id = @commission_suspense_account_id,  
    pfscheme_type_id = @pfscheme_type_id,  
    bank_name_mandatory = @bank_name_mandatory,  
    bank_address_mandatory = @bank_address_mandatory,  
    branch_name_mandatory = @branch_name_mandatory,  
    branch_code_mandatory = @branch_code_mandatory,  
    bankaccount_id = @bankaccount_id,  
    ConfirmationDocID = @confirmation_doc_id,  
    spread_ri = @Spread_ri,  
    spread_taxes = @Spread_taxes,  
    ri_suspense_account_id = @ri_Suspense_Account_ID,  
    deposit_as_instalment =  @deposit_as_instalment,  
    deposit_on_other_media_type = @deposit_on_other_media_type,  
    agent_ref_mandatory = @agent_ref_mandatory,  
    pf_message = @pf_message,  
 business_code_mandatory = @business_code_mandatory,  
 receipt_difference_option = @receipt_difference,  
 provider_website = @provider_website,  
 provider_username = @provider_username,  
 provider_password = @provider_password,  
 provider_brokerid = @provider_brokerid,  
 provider_timeout = @provider_timeout,  
 financial_institution_code = @financial_institution_code,  
 direct_debit_supplier_name = @direct_debit_supplier_name,  
 direct_debit_supplier_id = @direct_debit_supplier_id,  
 remitter = @remitter,  
 processing_days = @processing_days,  
        rates_are_for_information_only = @rates_are_for_information_only,  --'(RC) PLICO 9-10  
        plbrokerid=  @provider_plbrokerid,  
 clbrokerid=  @provider_clbrokerid,  
 provider_prem_threshold =@provider_prem_threshold,  
 allow_client_fees =@allow_client_fees,
 is_plan_reference_editable=@is_plan_reference_editable,  
--Start(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
ColNotDocID = @ColNotDocID ,
ColNotNumDays = @nColNotNumDays ,
business_identifier_code_mandatory  = @sBusinessIdentifierCodeMandatory,
	international_bank_account_number_mandatory = @sInternationalBankAccountNumberMandatory,
  spread_subagent_commission=@nspread_subagent_commission,  
    commission_subagent_suspense_account_id =@ncommission_subagent_suspense_account_id,
	UserId=@UserId,
	UniqueId=@UniqueId,
    ScreenHierarchy=ISNULL(@ScreenHierarchy, ScreenHierarchy),
	scheme_type=@SchemeType
--End(Saurabh Agrawal) Tech Spec PGR 005 Automated Emails (6.2.2.2)
WHERE companyno = @companyno  
AND schemeno = @schemeno  
AND schemeversion = @schemeversion  
END  
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

