EXECUTE DDLDropProcedure 'spu_PFPremiumFinance_Sel_Single'
GO

CREATE PROCEDURE spu_PFPremiumFinance_Sel_Single  
    @financeplancnt int,  
    @financeplanversion int,  
    @insurancefilecnt int=NULL,
	@nUserID INT=NULL
	  
AS BEGIN  
    DECLARE @TransCount int  
	DECLARE @crSettleAmount NUMERIC(19,4) 
	DECLARE @crRefundFee NUMERIC(19,4)
	DECLARE @crRefundTax NUMERIC(19,4)
	DECLARE @dtNextInstalmentDate DATETIME
	DECLARE @dtNextInstalmentDatePlus1 DATETIME
	DECLARE @dtLastInstalmentDate DATETIME
	DECLARE @dtLastPaidInstalmentDate DATETIME
	DECLARE @bCan_update_instalment_status TINYINT

	EXEC spu_PFPremiumFinance_settlement @financeplancnt, @financeplanversion, @SettleAmount=@crSettleAmount OUTPUT, @RefundFee=@crRefundFee OUTPUT, @RefundTax=@crRefundTax OUTPUT,@NextInstalmentDate= @dtNextInstalmentDate OUTPUT, @NextInstalmentDatePlus1=@dtNextInstalmentDatePlus1 OUTPUT, @LastInstalmentDate=@dtLastInstalmentDate, @LastPaidInstalmentDate= @dtLastPaidInstalmentDate OUTPUT

    SELECT  
        @TransCount = Count(pFTransaction_id)  
    FROM pftransaction_id  
    WHERE pfprem_finance_cnt = @financeplancnt  
    AND  
        pfprem_finance_version = @financeplanversion
		SELECT @bCan_update_instalment_status=ISNull(can_update_instalment_status,0) FROM User_Authorities WHERE USER_ID=@nUserID

    SELECT  

		P.pfPrem_finance_cnt, 
		P.pfPrem_finance_version, 
		P.companyno, 
		P.companyname, 
		P.schemeno,
		P.schemename, 
		P.schemeversion, 
		P.startdate, 
		P.enddate, 
		P.productclass,
		P.transtype, 
		P.amounttofinance, 
		P.APR, 
		P.InterestRate, 
		P.DaysDelay,
		P.NoOfInstallments, 
		P.FirstInstallment, 
		P.OthInstallments, 
		P.CostOfProtection, 
		P.Deposit,
		P.NetAmount, 
		P.TotalCost, 
		P.InterestCost, 
		P.MinFinanceChrge, 
		P.PayProtection,
		S.QuoteDocID, 
		S.BankDocID, 
		S.CreditDocID, 
		P.ClientName, 
		P.ClientAddr1,
		P.ClientAddr2, 
		P.ClientAddr3, 
		P.ClientTown, 
		P.ClientAddr4, 
		P.ClientPcode,
		P.ClientCountry, 
		P.ClientAreaCode, 
		P.ClientPhoneNo, 
		P.ClientExtension, 
		P.ClientFaxAreaCode,
		P.ClientFaxNo, 
		P.BankName, 
		P.BankSortCode, 
		P.BankAccountNo, 
		P.BankAccountName,
		P.BankBranch, 
		P.BankAddr1, 
		P.BankAddr2, 
		P.BankAddr3, 
		P.BankTown,
		P.BankRegion, 
		P.BankPCode, 
		P.BankCountry, 
		P.BankAreaCode, 
		P.BankPhoneNo,
		P.BankExtension, 
		P.BankFaxAreaCode, 
		P.BankFaxNo, 
		NULL BrokerName, 
		NULL BrokerAddr1,
		NULL BrokerAddr2, 
		NULL BrokerAddr3, 
		NULL BrokerPCode, 
		NULL BrokerAddr4, 
		P.StatusInd,
		NULL NBInd, 
		NULL MTAInd, 
		NULL RNWLInd, 
		NULL CNCLInd, 
		NULL PPInd,
		P.ClientId, 
		P.ClientCode, 
		P.systemtag, 
		P.AutoGeneratedPlanRef, 
		P.FinanceCollatedPlanRef,
		NULL PolicyCnt, 
		P.InterestFree, 
		P.IsQuote, 
		P.IsParentPlan, 
		P.Parent_finance_cnt,
		P.Parent_finance_version, 
		P.PlanTransaction_id, 
		@TransCount TransCount, 
		S.ImmediateBankDetails,
		P.Insurance_File_Cnt, 
		P.PFRF_ID, 
		PFF.Code, 
		s.MediaType_ID, 
		s.PFScheme_type_id,
		bc.Country_id AS bank_country, 
		cc.Country_id AS client_country, 
		p.first_instalment_date, 
		p.next_instalment_date,
		p.last_instalment_date, 
		p.tax_cost, 
		m.code AS mediatype_code,
		p.cc_number,
		p.cc_expiry_date,
		p.cc_start_date,
		p.cc_issue,
		p.cc_pin, 
		mv.code AS MediaType_validation_code,
        ISNULL(s.bank_name_mandatory,0) AS bank_name_mandatory,  
        ISNULL(s.bank_address_mandatory,0) AS bank_address_mandatory,  
        ISNULL(s.branch_name_mandatory,0) AS branch_name_mandatory,  
		ISNULL(s.branch_code_mandatory,0) AS branch_code_mandatory,
		commission_transdetail_id,
		PFF.period, 
		PFF.amount, 
		PFF.pffrequency_id, 
		P.source_id, 
		INF.product_id, 
		pfs.code AS PFScheme_Type_Code,
		ISNULL(P.FinanceFee, 0) AS FinanceFee, 
		ISNULL(P.DayOfWeekOrMonth, 0) AS DayOfWeekOrMonth,
		m.Description AS PaymentMethod, 
		pff.Description AS Frequency, 
		PFSPT.code AS SchemePrintType,
		P.original_amount, 
		P.last_instalment, 
		P.claim_debt_id, 
		P.user_id, 
		P.agent_cnt, 
		P.agent_ref,
		P.date_created, 
		P.date_modified, 
		P.date_confirmed, 
		P.date_review, 
		P.date_laststatement, 
		P.date_lastgeneration,
		P.final_statement_set, 
		P.no_statements, 
		P.statement_pffrequency_id, 
		P.review_pmwrk_task_instance_id,
		ISNULL(m.is_via_third_party,0) AS is_via_third_party, 
		PF.review_pmuser_group_id, 
		S.ConfirmationDocID,
        ISNULL(s.Spread_Commission, 0) AS Spread_Commission,  
		ISNULL(s.spread_taxes, 0) AS Spread_Taxes,
		ISNULL(s.spread_ri, 0) AS Spread_RI,
		ISNULL(s.deposit_as_instalment, 0) AS Deposit_As_Instalment,
		ISNULL(P.auth_code,'') AS auth_code,
		ISNULL(PtyType.code,' ') AS PartyTypeCode,
		ISNULL(p.pfprem_business_code,'') AS pfprem_business_code, 
		isnull(pf.mnemonic,'') AS pfrf_mnemonic,
  ISNULL(s.provider_website, ''),  
  ISNULL(s.provider_timeout, ''),  
  ISNULL(s.provider_username, ''),  
  ISNULL(s.provider_password, ''),  
  ISNULL(s.provider_brokerid, ''),  
  INF.cover_start_date,  
  INF.expiry_date,  
        p.terms,  
        p.sgref,  
        p.sgdocurl,  
        p.originalrate,  
        p.sgrefundtype,  
        p.limitedcompany,  
  p.is_cardholder,  
  p.cardholder_name,  
  p.cardholder_address1,  
  p.cardholder_address2,  
  p.cardholder_address3,  
  p.cardholder_address4,  
  p.cardholder_postcode,  
  p.card_type,  
  p.provider_collect_deposit,  
      p.datebankdetailschanged,  
        p.tax_group_id,  
        PF.Align_to,  
        p.sub_branch_id,  
        p.batch_id,  
        p.dd_cancelled,  
        p.cc_cancelled,  
        p.paperdd ,  
 s.xsl_code,  
 p.scheme_type,  
 p.scheme_code,  
        p.Party_bank_id,  
        ISNULL(p.pfpremiumfinance_cancel_reason_id, 0),  
        ISNULL(p.is_cancel_policy_run, 0)  ,
		PF.finance_net_commission,
		P.business_identifier_code,
		P.international_bank_account_number,
		ISNULL(s.business_identifier_code_mandatory,0) AS business_identifier_code_mandatory,
		ISNULL(s.international_bank_account_number_mandatory,0) AS international_bank_account_number_mandatory,
        P.use_trans_Currency,  
		ISNULL(chc.country_id,2),
		ISNULL(s.Spread_subagent_Commission, 0) AS Spread_subagent_Commission,  
        ISNULL(INF.currency_base_xrate, 1)      AS CurrencyBaseXRate,
		s.deposit_on_other_media_type,
		can.code,
		ISNUll(can.Description,'') AS PFCancelReasondesc,
		ISNULL(p.is_cancel_policy_run, 0)  AS is_cancel_policy_run,
		ISNULL(@crSettleAmount,0) AS 'SettleAmount',
		p.deposit_cc_tracking_number,
        @bCan_update_instalment_status As can_update_instalment_status,
		s.receipt_difference_option
		FROM PFPremiumFinance P WITH(NOLOCK)  
		INNER JOIN PFScheme S WITH(NOLOCK) 
		ON S.companyno = P.companyno  
		AND S.schemeno = P.schemeno  
		AND S.schemeversion = P.schemeversion  
		INNER JOIN PFRF as PF WITH(NOLOCK)  
		ON PF.pfrf_id = P.pfrf_id  
		INNER JOIN PFFrequency PFF WITH(NOLOCK) 
		ON PFF.pffrequency_id = PF.pFfrequency_id  
		INNER JOIN mediatype m WITH(NOLOCK) 
		ON s.mediatype_id = m.mediatype_id  
		INNER JOIN mediatype_validation mv WITH(NOLOCK) 
		ON m.mediatype_validation_id = mv.mediatype_validation_id  
		INNER JOIN pfScheme_type pfs WITH(NOLOCK) 
		ON pfs.pfScheme_type_id = s.pfScheme_type_id  
		LEFT OUTER JOIN country bc WITH(NOLOCK) 
		ON bc.description = p.bankcountry  
		LEFT OUTER JOIN country cc WITH(NOLOCK) 
		ON cc.description = p.clientcountry  
		LEFT OUTER JOIN Insurance_File AS INF  
		ON P.Insurance_File_Cnt = INF.insurance_file_cnt  
		LEFT JOIN PFScheme_PrintType AS PFSPT WITH(NOLOCK) 
		ON S.pfscheme_printtype_id = PFSPT.pfscheme_printtype_id  
		JOIN Party as Pty WITH(NOLOCK) 
		ON pty.party_cnt = p.clientid  
		JOIN Party_type as PtyType WITH(NOLOCK)  
		ON PtyType.Party_Type_id = pty.party_type_id
		LEFT JOIN PFPremiumFinance_Cancel_Reason can ON can.pfpremiumfinance_cancel_reason_id = p.pfpremiumfinance_cancel_reason_id
		LEFT OUTER JOIN country chc WITH(NOLOCK) 
		ON chc.description = p.CardHolderCountry   
    
    WHERE  
				pfprem_finance_cnt = @financeplancnt
    AND  
				pfprem_finance_version = @financeplanversion	

		AND (p.insurance_file_cnt = @insurancefilecnt OR @insurancefilecnt IS NULL)

END  

GO