SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_PFRF_upd'
GO

CREATE PROCEDURE spu_PFRF_upd  
    @PFRF_ID int,  
    @CompanyNo int,  
    @SchemeNo int,  
    @SchemeVersion int,  
    @StartDate datetime,  
    @ProductFamily char(3),  
    @ArrangementFee numeric(19,4),  
    @Mnemonic char(35),  
    @EndDate datetime,  
    @Protect char(1),  
    @DaysDelay int,  
    @DepositReq char(1),  
    @DepositPC numeric(19,4),  
    @AllowProtection char(1),  
    @ProtectRate numeric(7,4),  
    @MinInterest numeric(19,6),  
    @Min1 numeric(19,4),  
    @Max1 numeric(19,4),  
    @Rate1 numeric(19,6),  
    @R1Com numeric(19,4),  
    @Min2 numeric(19,4),  
    @Max2 numeric(19,4),  
    @Rate2 numeric(19,6),  
    @R2Com numeric(19,4),  
    @Min3 numeric(19,4),  
    @Max3 numeric(19,4),  
    @Rate3 numeric(19,6),  
    @R3Com numeric(19,4),  
    @Min4 numeric(19,4),  
    @Max4 numeric(19,4),  
    @Rate4 numeric(19,6),  
    @R4Com numeric(19,4),  
    @Min5 numeric(19,4),  
    @Max5 numeric(19,4),  
    @Rate5 numeric(19,6),  
    @R5Com numeric(19,4),  
    @AlLowOveride char(1),  
    @MinMTA numeric(19,4),  
    @MinMTAInstalments INT,  
    @pffrequency_id INT,  
    @tax_charged_to TINYINT,  
    @fee_type TINYINT,  
    @fee_charged_to TINYINT,  
    @protection_type TINYINT,  
    @protection_charged_to TINYINT,  
    @deposit_type TINYINT,  
    @deposit_charged_to TINYINT,  
    @backdated_rollup_to TINYINT,  
    @align_to TINYINT,  
    @start_limit SMALLINT,  
    @recollect_on_next TINYINT,  
    @recollect_days SMALLINT,  
    @retry_limit SMALLINT,  
    @mta_on_next_instalment TINYINT,  
    @existing_days_delay INT,  
    @statement_frequency_id INT,  
    @statement_report_id INT,  
    @advance_instalments SMALLINT,  
    @review_pmuser_group_id INT,  
    @remainder_threshhold NUMERIC(19,4),  
    @remainder_at_end TINYINT,  
    @maximum_instalments SMALLINT, 
@finance_net_commission TINYINT,
@single_instalment_per_month TINYINT, 
@first_instalment_align_with_day_in_month TINYINT,
@is_deposit_override_allowed TINYINT,
@apply_fee_percentages_to_fees TINYINT,
@apply_fee_percentages_to_taxes TINYINT,
@transaction_type TINYINT = NULL,
@UserId INT=0,
@UniqueId VARCHAR(50)='',
@ScreenHierarchy VARCHAR(500)=''

AS BEGIN  
  
    UPDATE PFRF  
        SET  
        SchemeNo = @SchemeNo,  
        SchemeVersion = @SchemeVersion,  
        CompanyNo = @CompanyNo,  
        StartDate = @StartDate,  
        ProductFamily = @ProductFamily,  
        ArrangementFee = @ArrangementFee,  
        Mnemonic = @Mnemonic,  
        EndDate = @EndDate,  
        Protect = @Protect,  
        DaysDelay = @DaysDelay,  
        DepositReq = @DepositReq,  
        DepositPC = @DepositPC,  
        AllowProtection = @AllowProtection,  
        ProtectRate = @ProtectRate,  
        MinInterest = @MinInterest,  
        Min1 = @Min1,  
        Max1 = @Max1,  
        Rate1 = @Rate1,  
        R1Com = @R1Com,  
        Min2 = @Min2,  
        Max2 = @Max2,  
        Rate2 = @Rate2,  
        R2Com = @R2Com,  
        Min3 = @Min3,  
        Max3 = @Max3,  
        Rate3 = @Rate3,  
        R3Com = @R3Com,  
        Min4 = @Min4,  
        Max4 = @Max4,  
        R4Com = @R4Com,  
        Rate4 = @Rate4,  
        Min5 = @Min5,  
        Max5 = @Max5,  
        Rate5 = @Rate5,  
        R5Com = @R5Com,  
        AlLowOveride = @AlLowOveride,  
        MinMTA = @MinMTA,  
        MinMTAInstalments = @MinMTAInstalments,  
        pffrequency_id = @pffrequency_id,  
        tax_charged_to = @tax_charged_to,  
        fee_type = @fee_type,  
        fee_charged_to= @fee_charged_to,  
        protection_type= @protection_type,  
        protection_charged_to = @protection_charged_to,  
        deposit_type = @deposit_type,  
        deposit_charged_to = @deposit_charged_to,  
        backdated_rollup_to= @backdated_rollup_to,  
        align_to = @align_to,  
        start_limit = @start_limit,  
        recollect_on_next = @recollect_on_next,  
        recollect_days  = @recollect_days,  
        retry_limit = @retry_limit,  
        mta_on_next_instalment = @mta_on_next_instalment,  
     existing_days_delay = @existing_days_delay,  
 statement_pffrequency_id=@statement_frequency_id,  
 statement_report_id=@statement_report_id,  
 advance_instalments=@advance_instalments,  
 review_pmuser_group_id=@review_pmuser_group_id,  
 remainder_amount_threshhold=@remainder_threshhold,  
 remainder_amount_at_end=@remainder_at_end,  
 maximum_instalments=@maximum_instalments,
 
finance_net_commission=@finance_net_commission,
single_instalment_per_month = @single_instalment_per_month,
first_instalment_align_with_day_in_month=@first_instalment_align_with_day_in_month,
is_deposit_override_allowed = @is_deposit_override_allowed , 
 apply_fee_percentages_to_fees=@apply_fee_percentages_to_fees,
apply_fee_percentages_to_taxes=@apply_fee_percentages_to_taxes,
transaction_type=@transaction_type,
UserId=@UserId,
UniqueId=@UniqueId,
ScreenHierarchy=@ScreenHierarchy 
    WHERE  
        PFRF_ID = @PFRF_ID  
        IF @finance_net_commission=1   
 UPDATE PFScheme SET spread_commission=0 WHERE CompanyNo=@CompanyNo and SchemeNo=@SchemeNo and SchemeVersion=@SchemeVersion  
END
  
GO


SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO