SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_PFRF_add'
GO

CREATE PROCEDURE spu_PFRF_add  
    @PFRF_ID int OUTPUT,  
    @CompanyNo int,  
    @SchemeNo int,  
    @SchemeVersion int,  
    @StartDate datetime,  
    @ProductFamily char(3),  
    @ArrangementFee numeric(19,4),  
    @Mnemonic char(35),  
    @EndDate datetime,  
    @Protect char(1),  
    @DaysDelay int,  
    @DepositReq char(1),  
    @DepositPC numeric(19,4),  
    @AllowProtection char(1),  
    @ProtectRate numeric(7,4),  
    @MinInterest numeric(19,6),  
    @Min1 numeric(19,4),  
    @Max1 numeric(19,4),  
    @Rate1 numeric(19,6),  
    @R1Com numeric(19,4),  
    @Min2 numeric(19,4),  
    @Max2 numeric(19,4),  
    @Rate2 numeric(19,6),  
    @R2Com numeric(19,4),  
    @Min3 numeric(19,4),  
    @Max3 numeric(19,4),  
    @Rate3 numeric(19,6),  
    @R3Com numeric(19,4),  
    @Min4 numeric(19,4),  
    @Max4 numeric(19,4),  
    @Rate4 numeric(19,6),  
    @R4Com numeric(19,4),  
    @Min5 numeric(19,4),  
    @Max5 numeric(19,4),  
    @Rate5 numeric(19,6),  
    @R5Com numeric(19,4),  
    @AlLowOveride char(1),  
    @MinMTA numeric(19,4),  
    @MinMTAInstalments INT,  
    @pffrequency_id INT,  
    @tax_charged_to TINYINT,  
    @fee_type TINYINT,  
    @fee_charged_to TINYINT,  
    @protection_type TINYINT,  
    @protection_charged_to TINYINT,  
    @deposit_type TINYINT,  
    @deposit_charged_to TINYINT,  
    @backdated_rollup_to TINYINT,  
    @align_to TINYINT,  
    @start_limit SMALLINT,  
    @recollect_on_next TINYINT,  
    @recollect_days SMALLINT,  
    @retry_limit SMALLINT,  
    @mta_on_next_instalment TINYINT,  
    @existing_days_delay INT,  
    @statement_frequency_id INT,  
    @statement_report_id INT,  
    @advance_instalments SMALLINT,  
    @review_pmuser_group_id INT,  
    @remainder_threshhold NUMERIC(19,4),  
    @remainder_at_end TINYINT,  
    @maximum_instalments SMALLINT,
    @finance_net_commission TINYINT,
    @single_instalment_per_month TINYINT,
    @first_instalment_align_with_day_in_month TINYINT,
	@is_deposit_override_allowed TINYINT,
	@apply_fee_percentages_to_fees TINYINT,
	@apply_fee_percentages_to_taxes TINYINT,
	@transaction_type TINYINT = NULL,
	@UserId INT,
	@UniqueId VARCHAR(50),
	@ScreenHierarchy VARCHAR(500)
AS BEGIN  
    INSERT INTO PFRF (  
        CompanyNo,  
        SchemeNo,  
        SchemeVersion,  
        StartDate,  
        ProductFamily,  
        ArrangementFee,  
        Mnemonic,  
        EndDate,  
        Protect,  
        DaysDelay,  
        DepositReq,  
        DepositPC,  
        AllowProtection,  
        ProtectRate,  
        MinInterest,  
        Min1,  
        Max1,  
        Rate1,  
        R1Com,  
        Min2,  
        Max2,  
        Rate2,  
        R2Com,  
        Min3,  
        Max3,  
        Rate3,  
        R3Com,  
        Min4,  
        Max4,  
        Rate4,  
        R4Com,  
        Min5,  
        Max5,  
        Rate5,  
        R5Com,  
        AlLowOveride,  
        MinMTA,  
        MinMTAInstalments,  
        pffrequency_id,  
        tax_charged_to,  
        fee_type,  
        fee_charged_to,  
        protection_type,  
        protection_charged_to,  
        deposit_type,  
        deposit_charged_to,  
        backdated_rollup_to,  
        align_to,  
        start_limit,  
        recollect_on_next,  
        recollect_days,  
        retry_limit,  
        mta_on_next_instalment,  
        existing_days_delay,  
 	statement_pffrequency_id,  
 	statement_report_id,  
	 advance_instalments,  
 	review_pmuser_group_id,  
 	remainder_amount_threshhold,  
 	remainder_amount_at_end,  
 	maximum_instalments,
	finance_net_commission,
	single_instalment_per_month,
	first_instalment_align_with_day_in_month,
	is_deposit_override_allowed,
	apply_fee_percentages_to_fees,
	apply_fee_percentages_to_taxes,
	transaction_type,
	UserId ,
	UniqueId,
	ScreenHierarchy
 )  
    VALUES (  
        @CompanyNo,  
        @SchemeNo,  
        @SchemeVersion,  
        @StartDate,  
        @ProductFamily,  
        @ArrangementFee,  
        @Mnemonic,  
        @EndDate,  
        @Protect,  
        @DaysDelay,  
        @DepositReq,  
        @DepositPC,  
        @AllowProtection,  
        @ProtectRate,  
        @MinInterest,  
        @Min1,  
        @Max1,  
        @Rate1,  
        @R1Com,  
        @Min2,  
        @Max2,  
        @Rate2,  
        @R2Com,  
        @Min3,  
        @Max3,  
        @Rate3,  
        @R3Com,  
        @Min4,  
        @Max4,  
        @Rate4,  
        @R4Com,  
        @Min5,  
        @Max5,  
        @Rate5,  
        @R5Com,  
        @AlLowOveride,  
        @MinMTA,  
        @MinMTAInstalments,  
        @pffrequency_id,  
        @tax_charged_to,  
        @fee_type,  
        @fee_charged_to,  
        @protection_type,  
        @protection_charged_to,  
        @deposit_type,  
        @deposit_charged_to,  
        @backdated_rollup_to,  
        @align_to,  
        @start_limit,  
        @recollect_on_next,  
        @recollect_days,  
        @retry_limit,  
        @mta_on_next_instalment,  
        @existing_days_delay,  
 	@statement_frequency_id,  
 	@statement_report_id,  
	 @advance_instalments,  
 	@review_pmuser_group_id,  
 	@remainder_threshhold,  
 	@remainder_at_end,  
 	@maximum_instalments,  
	@finance_net_commission,@single_instalment_per_month,@first_instalment_align_with_day_in_month,
	@is_deposit_override_allowed
	,@apply_fee_percentages_to_fees,@apply_fee_percentages_to_taxes, 
	@transaction_type,
	@UserId ,
	@UniqueId,
	@ScreenHierarchy
    )  
  
SELECT @PFRF_ID = @@IDENTITY  


IF @finance_net_commission=1   
 UPDATE PFScheme SET spread_commission=0 WHERE CompanyNo=@CompanyNo and SchemeNo=@SchemeNo and SchemeVersion=@SchemeVersion  

  
END  
GO


SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

