SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON 
GO

DDLDropProcedure 'spu_PFPremiumFinance_sel_single_rec'
GO

-- Object:  Stored Procedure dbo.spu_PFPremiumFinance_sel_single_rec   
-- Script Date: 10/16/2003 10:54:00 AM 
-- AAB - Added the new ReInsuranceDrippig Flags
-- PN12594 Add business code
CREATE PROCEDURE spu_PFPremiumFinance_sel_single_rec
	@claim_debt_id int
AS BEGIN
    DECLARE @TransCount int
    DECLARE @financeplanversion int
    DECLARE @financeplancnt int
    SELECT
	@financeplancnt = pfPrem_finance_cnt,
	@financeplanversion = pfPrem_finance_version
    FROM
	PFPremiumFinance
    WHERE
	claim_debt_id = @claim_debt_id
    SELECT
        @TransCount = Count(pFTransaction_id)
    FROM
        pftransaction_id
    WHERE
        pfprem_finance_cnt = @financeplancnt
    AND
        pfprem_finance_version = @financeplanversion
    SELECT
        P.pfPrem_finance_cnt, P.pfPrem_finance_version, P.companyno, P.companyname, P.schemeno,
        P.schemename, P.schemeversion, P.startdate, P.enddate, P.productclass,
        P.transtype, P.amounttofinance, P.APR, P.InterestRate, P.DaysDelay,
        P.NoOfInstallments, P.FirstInstallment, P.OthInstallments, P.CostOfProtection, P.Deposit,
        P.NetAmount, P.TotalCost, P.InterestCost, P.MinFinanceChrge, P.PayProtection,
        S.QuoteDocID, S.BankDocID, S.CreditDocID, P.ClientName, P.ClientAddr1,
        P.ClientAddr2, P.ClientAddr3, P.ClientTown, P.ClientAddr4, P.ClientPcode,
        P.ClientCountry, P.ClientAreaCode, P.ClientPhoneNo, P.ClientExtension, P.ClientFaxAreaCode,
        P.ClientFaxNo, P.BankName, P.BankSortCode, P.BankAccountNo, P.BankAccountName,
        P.BankBranch, P.BankAddr1, P.BankAddr2, P.BankAddr3, P.BankTown,
        P.BankRegion, P.BankPCode, P.BankCountry, P.BankAreaCode, P.BankPhoneNo,
        P.BankExtension, P.BankFaxAreaCode, P.BankFaxNo, Null BrokerName, Null BrokerAddr1,
        Null BrokerAddr2, Null BrokerAddr3, Null BrokerPCode, Null BrokerAddr4, P.StatusInd,
        Null NBInd, Null MTAInd, Null RNWLInd, Null CNCLInd, Null PPInd,
        P.ClientId, P.ClientCode, P.systemtag, P.AutoGeneratedPlanRef, P.FinanceCollatedPlanRef,
        Null PolicyCnt, P.InterestFree, P.IsQuote, P.IsParentPlan, P.Parent_finance_cnt,
        P.Parent_finance_version, P.PlanTransaction_id, @TransCount TransCount, S.ImmediateBankDetails,
        P.Insurance_File_Cnt, P.PFRF_ID, PFF.Code, s.MediaType_ID, s.PFScheme_type_id,
        bc.Country_id as bank_country, cc.Country_id as client_country, p.first_instalment_date, p.next_instalment_date,
        p.last_instalment_date, p.tax_cost, m.code as mediatype_code,
        p.cc_number,p.cc_expiry_date,p.cc_start_date,p.cc_issue,p.cc_pin, mv.code as MediaType_validation_code,
        ISNULL(s.bank_name_mandatory,0) AS bank_name_mandatory,
        ISNULL(s.bank_address_mandatory,0) AS bank_address_mandatory,
        ISNULL(s.branch_name_mandatory,0) AS branch_name_mandatory,
        ISNULL(s.branch_code_mandatory,0) AS branch_code_mandatory,commission_transdetail_id,
        PFF.period, PFF.amount, PFF.pffrequency_id, P.source_id, INF.product_id, pfs.code as PFScheme_Type_Code,
        ISNULL(P.FinanceFee, 0) AS FinanceFee, ISNULL(P.DayOfWeekOrMonth, 0) AS DayOfWeekOrMonth,
        m.Description as PaymentMethod, pff.Description as Frequency, PFSPT.code AS SchemePrintType,
        P.original_amount, P.last_instalment, P.claim_debt_id, P.user_id, P.agent_cnt, P.agent_ref,
        P.date_created, P.date_modified, P.date_confirmed, P.date_review, P.date_laststatement, P.date_lastgeneration,
        P.final_statement_set, P.no_statements, P.statement_pffrequency_id, P.review_pmwrk_task_instance_id,
        ISNULL(m.is_via_third_party,0) AS is_via_third_party, PF.review_pmuser_group_id, S.ConfirmationDocID,
        ISNULL(s.Spread_Commission, 0) AS Spread_Commission,
        ISNULL(s.spread_taxes, 0) as Spread_Taxes, 
        ISNULL(s.spread_ri, 0) as Spread_RI, 
        ISNULL(s.deposit_as_instalment, 0) as Deposit_As_Instalment,
        ISNULL(P.auth_code,'') as auth_code,
	ISNULL(P.pfprem_business_code,'') as pfprem_business_code,
	p.terms,
	p.sgref,
        p.sgdocurl,
        p.originalrate,
        p.sgrefundtype,
        p.limitedcompany,
	p.is_cardholder,
	p.cardholder_name,
	p.cardholder_address1,
	p.cardholder_address2,
	p.cardholder_address3,
	p.cardholder_address4,
	p.cardholder_postcode,
	p.card_type,
	p.provider_collect_deposit,
        p.datebankdetailschanged,
	p.tax_group_id,
	p.batch_id,  --'(RC) PLICO 9-10
	s.xsl_code,
	p.scheme_type,
	p.scheme_code,
        ISNULL(p.pfpremiumfinance_cancel_reason_id, 0),    
 	ISNULL(p.is_cancel_policy_run, 0) 
    FROM
        PFPremiumFinance P
    INNER JOIN
        PFScheme S
    ON
        S.companyno = P.companyno
    AND
        S.schemeno = P.schemeno
    AND
        S.schemeversion = P.schemeversion
    INNER JOIN
    PFRF as PF
    ON
    PF.pfrf_id = P.pfrf_id
    INNER JOIN
    PFFrequency PFF
    ON
    PFF.pffrequency_id = PF.pFfrequency_id
    INNER JOIN
        mediatype m
    ON
        s.mediatype_id = m.mediatype_id
    INNER JOIN
        mediatype_validation mv
    ON
        m.mediatype_validation_id = mv.mediatype_validation_id
    INNER JOIN
        pfScheme_type pfs
    ON
        pfs.pfScheme_type_id = s.pfScheme_type_id
    LEFT OUTER JOIN
        country bc
    ON
        bc.description = p.bankcountry
    LEFT OUTER JOIN
        country cc
    ON
        cc.description = p.clientcountry
    LEFT OUTER JOIN
	Insurance_File AS INF
    ON
	P.Insurance_File_Cnt = INF.insurance_file_cnt
    LEFT JOIN
    	PFScheme_PrintType AS PFSPT
    ON
    S.pfscheme_printtype_id = PFSPT.pfscheme_printtype_id
    WHERE
	claim_debt_id = @claim_debt_id
END

GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

