SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_PFPremiumFinance_Sel_SingleFromInsuranceFileCount'
GO

CREATE PROCEDURE spu_PFPremiumFinance_Sel_SingleFromInsuranceFileCount  
    @insurancefilecnt INT = NULL  
AS  

DECLARE @kStatusIndCancelled CHAR(3) = '999'
DECLARE @kStatusIndSuperseded CHAR(3) = '990'

SELECT    
    P.pfPrem_finance_cnt,    
    P.pfPrem_finance_version,    
    P.companyno,    
    P.companyname,    
    P.schemeno,    
    P.schemename,    
    P.schemeversion,    
    P.startdate,    
    P.enddate,    
    P.productclass,    
    P.transtype,    
    P.amounttofinance,    
    P.APR,    
    P.InterestRate,    
    P.DaysDelay,    
    P.NoOfInstallments,    
    P.FirstInstallment,    
    P.OthInstallments,    
    P.CostOfProtection,    
    P.Deposit,    
    P.NetAmount,    
    P.TotalCost,    
    P.InterestCost,    
    P.MinFinanceChrge,    
    P.PayProtection,    
    S.QuoteDocID,    
    S.BankDocID,    
    S.CreditDocID,    
    P.ClientName,    
    P.ClientAddr1,    
    P.ClientAddr2,    
    P.ClientAddr3,    
    P.ClientTown,    
    P.ClientAddr4,    
    P.ClientPcode,    
    P.ClientCountry,    
    P.ClientAreaCode,    
    P.ClientPhoneNo,    
    P.ClientExtension,    
    P.ClientFaxAreaCode,    
    P.ClientFaxNo,    
    P.BankName,    
    P.BankSortCode,    
    P.BankAccountNo,    
    P.BankAccountName,    
    P.BankBranch,    
    P.BankAddr1,    
    P.BankAddr2,    
    P.BankAddr3,    
    P.BankTown,    
    P.BankRegion,    
    P.BankPCode,    
    P.BankCountry,    
    P.BankAreaCode,    
    P.BankPhoneNo,    
    P.BankExtension,    
    P.BankFaxAreaCode,    
    P.BankFaxNo,    
    NULL BrokerName,    
    NULL BrokerAddr1,    
    NULL BrokerAddr2,    
    NULL BrokerAddr3,    
    NULL BrokerPCode,    
    NULL BrokerAddr4,    
    P.StatusInd,    
    NULL NBInd,    
    NULL MTAInd,    
    NULL RNWLInd,    
    NULL CNCLInd,    
    NULL PPInd,    
    P.ClientId,    
    P.ClientCode,    
    P.systemtag,    
    P.AutoGeneratedPlanRef,    
    P.FinanceCollatedPlanRef,    
    NULL PolicyCnt,    
    P.InterestFree,    
    P.IsQuote,    
    P.IsParentPlan,    
    P.Parent_finance_cnt,    
    P.Parent_finance_version,    
    P.PlanTransaction_id,    
    NULL TransCount,    
    S.ImmediateBankDetails,    
    P.Insurance_File_Cnt,    
    P.PFRF_ID,    
    PFF.Code,    
    s.MediaType_ID,    
    s.PFScheme_type_id,    
    bc.Country_id 'bank_country',    
    cc.Country_id 'client_country',    
    p.first_instalment_date,    
    p.next_instalment_date,    
    p.last_instalment_date,    
    p.tax_cost,    
    m.code 'mediatype_code',    
    p.cc_number,    
    p.cc_expiry_date,    
    p.cc_start_date,    
    p.cc_issue,    
    p.cc_pin,    
    mv.code 'MediaType_validation_code',    
    ISNULL(s.bank_name_mandatory,0) 'bank_name_mandatory',    
    ISNULL(s.bank_address_mandatory,0) 'bank_address_mandatory',    
    ISNULL(s.branch_name_mandatory,0) 'branch_name_mandatory',    
    ISNULL(s.branch_code_mandatory,0) 'branch_code_mandatory',    
    commission_transdetail_id,    
    PFF.period,    
    PFF.amount,    
    PFF.pffrequency_id,    
    P.source_id,    
    INF.product_id,    
    pfs.code 'PFScheme_Type_Code',    
    ISNULL(P.FinanceFee, 0) 'FinanceFee',    
    ISNULL(P.DayOfWeekOrMonth, 0) 'DayOfWeekOrMonth',    
    m.Description 'PaymentMethod',    
    pff.Description 'Frequency',    
    PFSPT.code 'SchemePrintType',    
    p.original_amount,    
    p.last_instalment,    
    p.claim_debt_id,    
    p.user_id,    
    p.agent_cnt,    
    p.agent_ref,    
    p.date_created,    
    p.date_modified,    
    p.date_confirmed,    
    p.date_review,    
    p.date_laststatement,    
    p.date_lastgeneration,    
    p.final_statement_set,    
    p.no_statements,    
    p.statement_pffrequency_id,    
    p.review_pmwrk_task_instance_id,    
    ISNULL(m.is_via_third_party,0) 'is_via_third_party',    
    PF.review_pmuser_group_id,    
    S.ConfirmationDocID,    
    ISNULL(s.Spread_Commission, 0) 'Spread_Commission',    
    ISNULL(s.spread_taxes, 0) 'Spread_Taxes',    
    ISNULL(s.spread_ri, 0) 'Spread_RI',    
    ISNULL(s.deposit_as_instalment, 0) 'Deposit_As_Instalment',    
    ISNULL(P.auth_code,'') 'auth_code',    
    ISNULL(PtyType.code,' ') 'PartyTypeCode',    
    ISNULL(P.pfprem_business_code,'') 'pfprem_business_code',    
    ISNULL(pf.mnemonic,'') 'pfrf_mnemonic',    
    ISNULL(s.provider_website, '') 'provider_website',    
    ISNULL(s.provider_timeout, '') 'provider_timeout',    
    ISNULL(s.provider_username, '') 'provider_username',    
    ISNULL(s.provider_password, '') 'provider_password',    
    ISNULL(s.provider_brokerid, '') 'provider_brokerid',    
    INF.cover_start_date,    
    INF.expiry_date,    
    p.terms,    
    p.sgref,    
    p.sgdocurl,    
    p.originalrate,    
    p.sgrefundtype,    
    p.limitedcompany,    
    p.is_cardholder,    
    p.cardholder_name,    
    p.cardholder_address1,    
    p.cardholder_address2,    
    p.cardholder_address3,    
    p.cardholder_address4,    
    p.cardholder_postcode,    
    p.card_type,    
    p.provider_collect_deposit,    
    p.datebankdetailschanged,    
    p.tax_group_id,    
    pf.align_to,    
    p.sub_branch_id,    
    p.batch_id,    
    p.dd_cancelled,    
    p.cc_cancelled,    
    p.paperdd ,  
    s.xsl_code,    
    p.scheme_type,    
    p.scheme_code,    
    p.Party_bank_id,  
    ISNULL(p.pfpremiumfinance_cancel_reason_id, 0),    
    ISNULL(p.is_cancel_policy_run, 0),    
    PF.finance_net_commission,
	P.business_identifier_code,
	p.international_bank_account_number,
	ISNULL(s.business_identifier_code_mandatory,0) AS business_identifier_code_mandatory,
	ISNULL(s.international_bank_account_number_mandatory,0) AS international_bank_account_number_mandatory,
	p.use_trans_currency,	
    ISNULL(chc.country_id,2),
    Isnull(s.Spread_subagent_Commission, 0) AS Spread_subagent_Commission,  
    Isnull(INF.currency_base_xrate, 1)      AS CurrencyBaseXRate     
FROM PFPremiumFinance P WITH(NOLOCK)    
LEFT JOIN PFTransaction_id PFT WITH(NOLOCK)    
    ON PFT.pfprem_finance_cnt = P.pfprem_finance_cnt    
JOIN PFScheme S  WITH(NOLOCK)   
    ON S.companyno = P.companyno    
    AND S.schemeno = P.schemeno    
    AND S.schemeversion = P.schemeversion    
JOIN PFRF PF WITH(NOLOCK)   
    ON PF.pfrf_id = P.pfrf_id    
JOIN PFFrequency PFF WITH(NOLOCK)   
    ON PFF.pffrequency_id = PF.pFfrequency_id    
JOIN mediatype m WITH(NOLOCK)    
    ON s.mediatype_id = m.mediatype_id    
JOIN mediatype_validation mv WITH(NOLOCK)
    ON m.mediatype_validation_id = mv.mediatype_validation_id    
JOIN pfScheme_type pfs WITH(NOLOCK)
    ON pfs.pfScheme_type_id = s.pfScheme_type_id    
LEFT JOIN country bc WITH(NOLOCK)
    ON bc.description = p.bankcountry    
LEFT JOIN country cc WITH(NOLOCK)
    ON cc.description = p.clientcountry    
JOIN Insurance_File INF WITH(NOLOCK)
    ON P.Insurance_File_Cnt = INF.insurance_file_cnt    
LEFT JOIN PFScheme_PrintType PFSPT WITH(NOLOCK)
    ON S.pfscheme_printtype_id = PFSPT.pfscheme_printtype_id    
JOIN Party Pty WITH(NOLOCK)
    ON pty.party_cnt = p.clientid    
JOIN Party_type PtyType WITH(NOLOCK)
    ON PtyType.Party_Type_id = pty.party_type_id    
        
LEFT OUTER JOIN country chc WITH(NOLOCK) 
	 ON  chc.description = p.CardHolderCountry  
WHERE P.StatusInd <> @kStatusIndCancelled AND        
(    
    PFT.pfprem_finance_cnt IS NULL    
    AND    
    P.insurance_file_cnt = @insurancefilecnt
)    
UNION ALL    
SELECT    
    P.pfPrem_finance_cnt,    
    P.pfPrem_finance_version,    
    P.companyno,    
    P.companyname,    
    P.schemeno,    
    P.schemename,    
    P.schemeversion,    
    P.startdate,    
    P.enddate,    
    P.productclass,    
    P.transtype,    
    P.amounttofinance,    
    P.APR,    
    P.InterestRate,    
    P.DaysDelay,    
    P.NoOfInstallments,    
    P.FirstInstallment,    
    P.OthInstallments,    
    P.CostOfProtection,    
    P.Deposit,    
    P.NetAmount,    
    P.TotalCost,    
    P.InterestCost,    
    P.MinFinanceChrge,    
    P.PayProtection,    
    S.QuoteDocID,    
    S.BankDocID,    
    S.CreditDocID,    
    P.ClientName,    
    P.ClientAddr1,    
    P.ClientAddr2,    
    P.ClientAddr3,    
    P.ClientTown,    
    P.ClientAddr4,    
    P.ClientPcode,    
    P.ClientCountry,    
    P.ClientAreaCode,    
    P.ClientPhoneNo,    
    P.ClientExtension,    
    P.ClientFaxAreaCode,    
    P.ClientFaxNo,    
    P.BankName,    
    P.BankSortCode,    
    P.BankAccountNo,    
    P.BankAccountName,    
    P.BankBranch,    
    P.BankAddr1,    
    P.BankAddr2,    
    P.BankAddr3,    
    P.BankTown,    
    P.BankRegion,    
    P.BankPCode,    
    P.BankCountry,
	P.BankAreaCode,    
    P.BankPhoneNo,    
    P.BankExtension,    
    P.BankFaxAreaCode,    
    P.BankFaxNo,    
    NULL BrokerName,    
    NULL BrokerAddr1,    
    NULL BrokerAddr2,    
    NULL BrokerAddr3,    
    NULL BrokerPCode,    
    NULL BrokerAddr4,    
    P.StatusInd,    
    NULL NBInd,    
    NULL MTAInd,    
    NULL RNWLInd,    
    NULL CNCLInd,    
    NULL PPInd,    
    P.ClientId,    
    P.ClientCode,    
    P.systemtag,    
    P.AutoGeneratedPlanRef,    
    P.FinanceCollatedPlanRef,    
    NULL PolicyCnt,    
    P.InterestFree,    
    P.IsQuote,    
    P.IsParentPlan,    
    P.Parent_finance_cnt,    
    P.Parent_finance_version,    
    P.PlanTransaction_id,    
    NULL TransCount,    
    S.ImmediateBankDetails,    
    P.Insurance_File_Cnt,    
    P.PFRF_ID,    
    PFF.Code,    
    s.MediaType_ID,    
    s.PFScheme_type_id,    
    bc.Country_id 'bank_country',    
    cc.Country_id 'client_country',    
    p.first_instalment_date,    
    p.next_instalment_date,    
    p.last_instalment_date,    
    p.tax_cost,    
    m.code 'mediatype_code',    
    p.cc_number,    
    p.cc_expiry_date,    
    p.cc_start_date,    
    p.cc_issue,    
    p.cc_pin,    
    mv.code 'MediaType_validation_code',    
    ISNULL(s.bank_name_mandatory,0) 'bank_name_mandatory',    
    ISNULL(s.bank_address_mandatory,0) 'bank_address_mandatory',    
    ISNULL(s.branch_name_mandatory,0) 'branch_name_mandatory',    
    ISNULL(s.branch_code_mandatory,0) 'branch_code_mandatory',    
    commission_transdetail_id,    
    PFF.period,    
    PFF.amount,    
    PFF.pffrequency_id,    
    P.source_id,    
    INF.product_id,    
    pfs.code 'PFScheme_Type_Code',    
    ISNULL(P.FinanceFee, 0) 'FinanceFee',    
    ISNULL(P.DayOfWeekOrMonth, 0) 'DayOfWeekOrMonth',    
    m.Description 'PaymentMethod',    
    pff.Description 'Frequency',    
    PFSPT.code 'SchemePrintType',    
    p.original_amount,    
    p.last_instalment,    
    p.claim_debt_id,    
    p.user_id,    
    p.agent_cnt,    
    p.agent_ref,    
    p.date_created,    
    p.date_modified,    
    p.date_confirmed,    
    p.date_review,    
    p.date_laststatement,    
    p.date_lastgeneration,    
    p.final_statement_set,    
    p.no_statements,    
    p.statement_pffrequency_id,    
    p.review_pmwrk_task_instance_id,    
    ISNULL(m.is_via_third_party,0) 'is_via_third_party',    
    PF.review_pmuser_group_id,    
    S.ConfirmationDocID,    
    ISNULL(s.Spread_Commission, 0) 'Spread_Commission',    
    ISNULL(s.spread_taxes, 0) 'Spread_Taxes',    
    ISNULL(s.spread_ri, 0) 'Spread_RI',    
    ISNULL(s.deposit_as_instalment, 0) 'Deposit_As_Instalment',    
    ISNULL(P.auth_code,'') 'auth_code',    
    ISNULL(PtyType.code,' ') 'PartyTypeCode',    
    ISNULL(P.pfprem_business_code,'') 'pfprem_business_code',    
    ISNULL(pf.mnemonic,'') 'pfrf_mnemonic',    
    ISNULL(s.provider_website, '') 'provider_website',    
    ISNULL(s.provider_timeout, '') 'provider_timeout',    
    ISNULL(s.provider_username, '') 'provider_username',    
    ISNULL(s.provider_password, '') 'provider_password',    
    ISNULL(s.provider_brokerid, '') 'provider_brokerid',    
    INF.cover_start_date,    
    INF.expiry_date,    
    p.terms,    
    p.sgref,    
    p.sgdocurl,    
    p.originalrate,    
    p.sgrefundtype,    
    p.limitedcompany,    
    p.is_cardholder,    
    p.cardholder_name,    
    p.cardholder_address1,    
    p.cardholder_address2,    
    p.cardholder_address3,    
    p.cardholder_address4,    
    p.cardholder_postcode,    
    p.card_type,    
    p.provider_collect_deposit,    
    p.datebankdetailschanged,    
    p.tax_group_id,    
    pf.align_to,    
    p.sub_branch_id,    
    p.batch_id,    
    p.dd_cancelled,    
    p.cc_cancelled,    
    p.paperdd ,  
    s.xsl_code,    
    p.scheme_type,    
    p.scheme_code,    
    p.Party_bank_id,  
    ISNULL(p.pfpremiumfinance_cancel_reason_id, 0),    
    ISNULL(p.is_cancel_policy_run, 0) ,    
    PF.finance_net_commission,
	P.business_identifier_code,
	p.international_bank_account_number,  
	ISNULL(s.business_identifier_code_mandatory,0) AS business_identifier_code_mandatory,
	ISNULL(s.international_bank_account_number_mandatory,0) AS international_bank_account_number_mandatory,  
	p.use_trans_currency,	
	ISNULL(chc.country_id,2),
	Isnull(s.Spread_subagent_Commission, 0) AS Spread_subagent_Commission,  
    Isnull(INF.currency_base_xrate, 1)      AS CurrencyBaseXRate  
FROM PFPremiumFinance P WITH(NOLOCK)    
JOIN PFScheme S WITH(NOLOCK)    
    ON S.companyno = P.companyno    
    AND S.schemeno = P.schemeno    
    AND S.schemeversion = P.schemeversion    
JOIN PFRF PF WITH(NOLOCK)    
    ON PF.pfrf_id = P.pfrf_id    
JOIN PFFrequency PFF WITH(NOLOCK)    
    ON PFF.pffrequency_id = PF.pFfrequency_id    
JOIN mediatype m WITH(NOLOCK)    
    ON s.mediatype_id = m.mediatype_id    
JOIN mediatype_validation mv WITH(NOLOCK)    
    ON m.mediatype_validation_id = mv.mediatype_validation_id    
JOIN pfScheme_type pfs WITH(NOLOCK)    
    ON pfs.pfScheme_type_id = s.pfScheme_type_id    
LEFT JOIN country bc WITH(NOLOCK)    
    ON bc.description = p.bankcountry    
LEFT JOIN country cc WITH(NOLOCK)    
    ON cc.description = p.clientcountry    
JOIN Insurance_File INF WITH(NOLOCK)    
    ON P.Insurance_File_Cnt = INF.insurance_file_cnt    
LEFT JOIN PFScheme_PrintType PFSPT WITH(NOLOCK)    
    ON S.pfscheme_printtype_id = PFSPT.pfscheme_printtype_id    
JOIN Party Pty WITH(NOLOCK)    
    ON pty.party_cnt = p.clientid    
JOIN Party_type PtyType WITH(NOLOCK)    
    ON PtyType.Party_Type_id = pty.party_type_id    
LEFT OUTER JOIN country chc WITH(NOLOCK) 
	 ON  chc.description = p.CardHolderCountry  
   
WHERE  P.StatusInd NOT IN (@kStatusIndCancelled,@kStatusIndSuperseded) AND     
    P.insurance_file_cnt = @insurancefilecnt
    
ORDER BY    
    P.pfPrem_finance_cnt DESC,    
    P.pfPrem_finance_version DESC
GO


SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO