
SET QUOTED_IDENTIFIER ON SET ANSI_NULLS ON 
GO

EXECUTE DDLDropProcedure 'spu_PFPremiumFinance_Find'
GO
CREATE PROCEDURE spu_PFPremiumFinance_Find  
    @clientID int,  
    @Status int,
	@AgentKey INT=0  
AS  
DECLARE @StatusInd varchar(3)  
DECLARE @enumPFInstalments_StatusCollected INT = 3  
  
SELECT @StatusInd = RIGHT (REPLICATE('0',3) + CONVERT(VARCHAR(3),@Status),3)  
  
IF EXISTS(SELECT * FROM party_agent WITH(NOLOCK) WHERE party_cnt=@clientID)  
BEGIN  
SELECT  
    pf.pfPrem_finance_cnt,  
    pf.pfPrem_finance_version,  
    insF.insurance_Ref PolicyNumber,  
 CASE  M.Description  
  WHEN 'Credit card' THEN REPLICATE('#',6) + RIGHT(RTRIM(pf.cc_number),4)  
  ELSE  pf.BankAccountNo  
    END  AccountNo,  
 CASE  
  WHEN pf.OthInstallments=0 THEN pf.firstinstallment  
  ELSE pf.OthInstallments  
    END Amount,  
    freq.description Frequency,  
   -- pf.next_instalment_date NextPaymentDate,  
  
 CASE  
 WHEN pf.NoOfInstallments=1 THEN pf.next_instalment_date  
 ELSE  
  (SELECT MIN(DUEDATE)  FROM pfinstalments i  
   WHERE i.pfprem_finance_cnt = pf.pfprem_finance_cnt  
   AND i.pfprem_finance_version = pf.pfprem_finance_version  
   AND i.Status <> @enumPFInstalments_StatusCollected AND i.InstalmentNumber<>0 AND i.InstalmentNumber>1)  
 END NextPaymentDate,  
  
    (SELECT count(*) from pfinstalments i WITH(NOLOCK)  
        WHERE i.pfprem_finance_cnt = pf.pfprem_finance_cnt  
        AND i.pfprem_finance_version = pf.pfprem_finance_version  
        AND i.Status <> 3 and i.InstalmentNumber<>0)  RemainingInstalments,  
    PF.StatusInd,  
    insF.alternate_reference,  
    PF.AutoGeneratedPlanRef,  
    ISNULL(P.resolved_name, 'In House')  
FROM  
    PFPremiumFinance pf WITH(NOLOCK)  
    INNER JOIN Insurance_File insF WITH(NOLOCK) ON pf.insurance_file_cnt=insF.insurance_file_cnt  
    INNER JOIN PFRF rf WITH(NOLOCK) ON rf.companyno = pf.companyno  
                        AND rf.schemeno = pf.schemeno  
                        AND rf.schemeversion = pf.schemeversion  
                        AND rf.pfrf_id = pf.pfrf_id  
  
    INNER JOIN PFFrequency freq WITH(NOLOCK) ON freq.pffrequency_id = rf.pffrequency_id  
    INNER JOIN PFScheme PFS WITH(NOLOCK) ON PF.companyno = PFS.companyno AND PF.SchemeNo = PFS.SchemeNo AND PF.SchemeVersion = PFS.SchemeVersion  
    LEFT OUTER JOIN Party P WITH(NOLOCK) ON PFS.party_cnt = P.party_cnt  
 Join PFScheme S WITH(NOLOCK)  
 ON S.schemeno = PF.schemeno  and  S.companyno = PF.companyno   and S.SchemeVersion=PF.SchemeVersion  
 INNER JOIN  mediatype M WITH(NOLOCK)  
 ON S.mediatype_id = M.mediatype_id  
    WHERE (pf.StatusInd = @StatusInd OR @Status <= 0)  
AND pf.agent_cnt = @clientId  -- PN 5913  
  AND pf.StatusInd <> '000' 
  AND (insF.lead_agent_cnt=@AgentKey OR @AgentKey=0)
ORDER BY pf.next_instalment_date DESC  
END  
ELSE  
BEGIN  
SELECT  
    pf.pfPrem_finance_cnt,  
    pf.pfPrem_finance_version,  
    insF.insurance_Ref PolicyNumber,  
 CASE  M.Description  
  WHEN 'Credit card' THEN REPLICATE('#',6) + RIGHT(RTRIM(pf.cc_number),4)  
  ELSE  pf.BankAccountNo  
    END  AccountNo,  
  
 CASE  
  WHEN pf.OthInstallments=0 THEN pf.firstinstallment  
  ELSE pf.OthInstallments  
    END Amount,  
    freq.description Frequency,  
   -- pf.next_instalment_date NextPaymentDate,  
 CASE  
 WHEN pf.NoOfInstallments=1  
  THEN pf.next_instalment_date  
 ELSE  
  (SELECT MIN(DUEDATE)  FROM pfinstalments i  
  WHERE i.pfprem_finance_cnt = pf.pfprem_finance_cnt  
  AND i.pfprem_finance_version = pf.pfprem_finance_version  
  AND i.Status <> @enumPFInstalments_StatusCollected AND i.InstalmentNumber<>0 AND i.InstalmentNumber>1)  
 END NextPaymentDate,  
  
    (SELECT count('') from pfinstalments i  
        WHERE i.pfprem_finance_cnt = pf.pfprem_finance_cnt  
        AND i.pfprem_finance_version = pf.pfprem_finance_version  
        AND i.Status <> 3 and i.InstalmentNumber<>0)  RemainingInstalments,  
    PF.StatusInd,  
    insF.alternate_reference,  
    PF.AutoGeneratedPlanRef,  
    ISNULL(P.resolved_name, 'In House')  
FROM  
    PFPremiumFinance pf  
    INNER JOIN Insurance_File insF ON pf.insurance_file_cnt=insF.insurance_file_cnt  
  
    INNER JOIN PFRF rf ON rf.companyno = pf.companyno  
                        AND rf.schemeno = pf.schemeno  
                        AND rf.schemeversion = pf.schemeversion  
                        AND rf.pfrf_id = pf.pfrf_id  
  
    INNER JOIN PFFrequency freq ON freq.pffrequency_id = rf.pffrequency_id  
    INNER JOIN PFScheme PFS ON PF.companyno = PFS.companyno AND PF.SchemeNo = PFS.SchemeNo AND PF.SchemeVersion = PFS.SchemeVersion  
    LEFT OUTER JOIN Party P ON PFS.party_cnt = P.party_cnt  
  
 Join PFScheme S  
 ON S.schemeno = PF.schemeno  and  S.companyno = PF.companyno   and S.SchemeVersion=PF.SchemeVersion  
 INNER JOIN  mediatype M  
 ON S.mediatype_id = M.mediatype_id  
  
    WHERE (pf.StatusInd = @StatusInd OR @Status <= 0)  
      AND pf.clientId = @clientId  
   AND pf.StatusInd <> '000' 
   AND (insF.lead_agent_cnt=@AgentKey OR @AgentKey=0)
ORDER BY pf.next_instalment_date DESC  
END  
GO

