'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPMUProduct.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product.
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1-Product.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2-Claim.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code:.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effective date:.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Renewal period:.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scheme agency ref:.
        '''</summary>
        Friend ReadOnly Property str1107() As String
            Get
                Return ResourceManager.GetString("str1107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Block no.:.
        '''</summary>
        Friend ReadOnly Property str1108() As String
            Get
                Return ResourceManager.GetString("str1108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provisional claim auto numbering:.
        '''</summary>
        Friend ReadOnly Property str1109() As String
            Get
                Return ResourceManager.GetString("str1109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quote Numbering:.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy Numbering:.
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full claim auto numbering:.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Midnight renewal.
        '''</summary>
        Friend ReadOnly Property str1113() As String
            Get
                Return ResourceManager.GetString("str1113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto renewal.
        '''</summary>
        Friend ReadOnly Property str1114() As String
            Get
                Return ResourceManager.GetString("str1114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax suppressed.
        '''</summary>
        Friend ReadOnly Property str1115() As String
            Get
                Return ResourceManager.GetString("str1115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Short Period Rated.
        '''</summary>
        Friend ReadOnly Property str1116() As String
            Get
                Return ResourceManager.GetString("str1116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accumulation.
        '''</summary>
        Friend ReadOnly Property str1117() As String
            Get
                Return ResourceManager.GetString("str1117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R/I pointer:.
        '''</summary>
        Friend ReadOnly Property str1118() As String
            Get
                Return ResourceManager.GetString("str1118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document pointer:.
        '''</summary>
        Friend ReadOnly Property str1119() As String
            Get
                Return ResourceManager.GetString("str1119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claim Year :.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single Claim Value :.
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allowed Claims :.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Claims Value :.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NB Prorata.
        '''</summary>
        Friend ReadOnly Property str1124() As String
            Get
                Return ResourceManager.GetString("str1124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MTA Prorata.
        '''</summary>
        Friend ReadOnly Property str1125() As String
            Get
                Return ResourceManager.GetString("str1125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Round Premium.
        '''</summary>
        Friend ReadOnly Property str1126() As String
            Get
                Return ResourceManager.GetString("str1126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rating Section:.
        '''</summary>
        Friend ReadOnly Property str1127() As String
            Get
                Return ResourceManager.GetString("str1127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy Number at Quote.
        '''</summary>
        Friend ReadOnly Property str1128() As String
            Get
                Return ResourceManager.GetString("str1128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Follow Up Time Frame (days):.
        '''</summary>
        Friend ReadOnly Property str1129() As String
            Get
                Return ResourceManager.GetString("str1129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quote Expiry (days):.
        '''</summary>
        Friend ReadOnly Property str1130() As String
            Get
                Return ResourceManager.GetString("str1130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Standard Wording Edit.
        '''</summary>
        Friend ReadOnly Property str1131() As String
            Get
                Return ResourceManager.GetString("str1131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Claims Type Basis :.
        '''</summary>
        Friend ReadOnly Property str1132() As String
            Get
                Return ResourceManager.GetString("str1132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply mandatory Risk.
        '''</summary>
        Friend ReadOnly Property str1133() As String
            Get
                Return ResourceManager.GetString("str1133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cover.
        '''</summary>
        Friend ReadOnly Property str1134() As String
            Get
                Return ResourceManager.GetString("str1134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unified Renewal Date is Read Only.
        '''</summary>
        Friend ReadOnly Property str1135() As String
            Get
                Return ResourceManager.GetString("str1135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property str1201() As String
            Get
                Return ResourceManager.GetString("str1201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property str1202() As String
            Get
                Return ResourceManager.GetString("str1202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Navigate.
        '''</summary>
        Friend ReadOnly Property str1203() As String
            Get
                Return ResourceManager.GetString("str1203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Add.
        '''</summary>
        Friend ReadOnly Property str1204() As String
            Get
                Return ResourceManager.GetString("str1204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit.
        '''</summary>
        Friend ReadOnly Property str1205() As String
            Get
                Return ResourceManager.GetString("str1205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property str1206() As String
            Get
                Return ResourceManager.GetString("str1206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A&amp;pply.
        '''</summary>
        Friend ReadOnly Property str1207() As String
            Get
                Return ResourceManager.GetString("str1207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;RI Model.
        '''</summary>
        Friend ReadOnly Property str1208() As String
            Get
                Return ResourceManager.GetString("str1208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Short Period Rate.
        '''</summary>
        Friend ReadOnly Property str1209() As String
            Get
                Return ResourceManager.GetString("str1209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insurer Model.
        '''</summary>
        Friend ReadOnly Property str1210() As String
            Get
                Return ResourceManager.GetString("str1210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not add or update any details
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Head Office you have selected does not exist.
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The reference you have entered already exists.
        '''Please enter a new reference.
        '''</summary>
        Friend ReadOnly Property str1306() As String
            Get
                Return ResourceManager.GetString("str1306", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) found.
        '''</summary>
        Friend ReadOnly Property str1307() As String
            Get
                Return ResourceManager.GetString("str1307", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid look up.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Shortname is not valid.
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prevent Claim Payments on Cancelled Agents.
        '''</summary>
        Friend ReadOnly Property str1310() As String
            Get
                Return ResourceManager.GetString("str1310", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positive Values in Cancel Policy.
        '''</summary>
        Friend ReadOnly Property str1311() As String
            Get
                Return ResourceManager.GetString("str1311", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media Type Field Mandatory On Claim Payments.
        '''</summary>
        Friend ReadOnly Property str1312() As String
            Get
                Return ResourceManager.GetString("str1312", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Policy Style:.
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Policy Style Is Mandatory.
        '''</summary>
        Friend ReadOnly Property str1314() As String
            Get
                Return ResourceManager.GetString("str1314", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transaction Group.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3-True Monthly Policies.
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4-Additional Options.
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5-Events.
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
