SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_User_Authorities_upd'
GO

CREATE PROCEDURE spe_User_Authorities_upd  
 @user_id smallint,  
 @has_write_off_authority tinyint,  
 @write_off_amount numeric(19,4),  
 @has_unrestricted_enquiry tinyint,  
 @has_unrestricted_update tinyint,  
 @fee_discount numeric(19,4),  
 @has_transaction_write_off_authority tinyint,  
 @transaction_write_off_amount numeric(19,4),  
 @has_refund_authority tinyint,  
 @has_transfer_authority tinyint,  
 @has_Payments_authority tinyint,  
 @Payments_amount numeric(19,4),  
 @has_claim_payments_authority tinyint,  
 @claim_payments_amount numeric(19,4),  
 @write_off_currency_id smallint,  
 @transaction_write_off_currency_id smallint,  
 @payments_currency_id smallint,  
 @claims_payments_currency_id smallint,  
 @can_change_exchange_date tinyint,  
 @can_change_exchange_rate tinyint,  
 @can_change_prepolicy_exchange_date tinyint,  
 @can_change_prepolicy_exchange_rate tinyint,  
 @is_view_client tinyint,  
 @is_edit_client tinyint,  
 @is_edit_policy tinyint,  
 @is_edit_claim tinyint,  
 @is_edit_finance_plan tinyint,  
 @is_raise_debit tinyint,  
 @is_raise_credit tinyint,  
 @is_raise_fee tinyint,  
 @is_raise_cash tinyint,  
 @is_reverse_transactions tinyint,  
 @is_reverse_allocations tinyint,  
 @is_raise_manual_DID tinyint,  
 @is_delete_client tinyint,  
 @is_perform_allocations tinyint,  
 @can_perform_broker_transfer tinyint,  
 @can_override_duplicate_claims tinyint,  
 @is_delete_policy tinyint,  
 @is_edit_scheme_policy tinyint,  
 @can_make_live_invoice tinyint,  
 @can_make_live_instalments tinyint,  
 @can_make_live_paynow tinyint,  
 @has_paynow_write_off_authority tinyint,  
 @paynow_write_off_currency_id int,  
 @paynow_write_off_amount money,  
 @paynow_bankaccount_id integer,  
 @can_override_posting_period tinyint,  
 @can_change_reserves_on_claim_payments tinyint,  
 @allow_ratingsection_adddelete tinyint,  
 @allow_ratingsection_editing tinyint,  
 @is_view_only_client_manager tinyint,  
 @is_view_only_agents_maintenance tinyint,  
 @is_view_only_account_handler_maintenance tinyint,  
 @is_view_only_account_executive_maintenance tinyint,  
 @is_view_only_insurer_maintenance tinyint,  
 @is_view_only_other_party_maintenance tinyint,  
 @is_recommender tinyint,  
 @recommender_currency_id int,  
 @recommender_currency_amount money,  
 @allow_reverse_allocations tinyint,  
 @reverse_allocations_days smallint,  
 @can_reverse_and_replace_transactions tinyint,  
 @MTA_Authority tinyint,  
 @can_override_cheque_Numbers tinyint,  
 @display_reinsurance tinyint,  
 @display_claim_reinsurance tinyint,  
 @can_backdate_collection_date tinyint = 0,  
 @can_make_live_BankGuarantee  tinyint,  
  @Edit_Default_Commission tinyint,  
 @can_make_live_cashdeposit tinyint = 0,  
  @can_user_debug_dynamic_logic_scripts tinyint,  
 @user_server_scripts_run_in_debug tinyint,  
 @Edit_Default_Commission_NB_RN tinyint=0,  
 @Edit_Default_Commission_MTA tinyint=0,  
 @Edit_Default_Commission_MTC tinyint=0,  
 @Edit_Default_Commission_MTR tinyint=0,  
 @Agent_Editable_During_MTA_MTC tinyint=0,  
 @allow_receipt_reversal tinyint,  
 @has_ViewBatchProcessStatus TINYINT,  
 @can_change_instalment_default_currency tinyint,  
 @can_update_instalment_status tinyint =0,  
 @can_edit_instalment_date TINYINT = 0,  
 @edit_instalment_by_no_of_days INT,  
 @currency_loss_gain_limit numeric(19,4),  
 @loss_gain_currency_id smallint ,
 @has_ManualJournal_authority tinyint,  
 @ManualJournal_currency_amount numeric(19,4),  
 @ManualJournal_currency_id smallint,
 @modified_by int,
 @unique_id varchar(50),
 @screen_hierarchy varchar(500),
 @void_policy_version varchar(30),
@can_extract_client_data tinyint = null
AS  
BEGIN  
  
UPDATE User_Authorities  
SET has_write_off_authority=@has_write_off_authority,  
 write_off_amount=@write_off_amount,  
 has_unrestricted_enquiry=@has_unrestricted_enquiry,  
 has_unrestricted_update=@has_unrestricted_update,  
 has_ViewBatchProcessStatus=@has_ViewBatchProcessStatus,  
 fee_discount=@fee_discount,  
 has_transaction_write_off_authority = @has_transaction_write_off_authority,  
 transaction_write_off_amount = @transaction_write_off_amount,  
 has_refund_authority = @has_refund_authority,  
 has_transfer_authority = @has_transfer_authority,  
 has_Payments_authority = @has_Payments_authority,  
 Payments_amount = @Payments_amount,  
 has_claim_payments_authority  = @has_claim_payments_authority,  
 claim_payments_amount = @claim_payments_amount,  
 write_off_currency_id = @write_off_currency_id,  
 transaction_write_off_currency_id = @transaction_write_off_currency_id,  
 payments_currency_id = @payments_currency_id,  
 claims_payments_currency_id = @claims_payments_currency_id,  
 can_change_exchange_date = @can_change_exchange_date,  
 can_change_exchange_rate = @can_change_exchange_rate,  
 can_change_prepolicy_exchange_date = @can_change_prepolicy_exchange_date,  
 can_change_prepolicy_exchange_rate = @can_change_prepolicy_exchange_rate,  
 is_view_client = @is_view_client,  
 is_edit_client = @is_edit_client,  
 is_edit_policy = @is_edit_policy,  
 is_edit_claim = @is_edit_claim,  
 is_edit_finance_plan = @is_edit_finance_plan,  
 is_raise_debit = @is_raise_debit,  
 is_raise_credit = @is_raise_credit,  
 is_raise_fee = @is_raise_fee,  
 is_raise_cash = @is_raise_cash,  
 is_reverse_transactions = @is_reverse_transactions,  
 is_reverse_allocations = @is_reverse_allocations,  
 is_raise_manual_DID = @is_raise_manual_DID,  
 is_delete_client = @is_delete_client,  
 is_perform_allocations = @is_perform_allocations,  
 can_perform_broker_transfer = @can_perform_broker_transfer,  
 can_override_duplicate_claims = @can_override_duplicate_claims,  
 is_delete_policy = @is_delete_policy,  
 is_edit_scheme_policy = @is_edit_scheme_policy,  
 can_make_live_invoice=@can_make_live_invoice,  
 can_make_live_instalments=@can_make_live_instalments,  
 can_make_live_paynow=@can_make_live_paynow,  
 has_paynow_write_off_authority=@has_paynow_write_off_authority,  
 paynow_write_off_currency_id=@paynow_write_off_currency_id,  
 paynow_write_off_amount=@paynow_write_off_amount,  
 paynow_bankaccount_id=@paynow_bankaccount_id,  
 can_override_posting_period=@can_override_posting_period,  
 can_change_reserves_on_claim_payments=@can_change_reserves_on_claim_payments,  
 allow_ratingsection_adddelete=@allow_ratingsection_adddelete,  
 allow_ratingsection_editing=@allow_ratingsection_editing,  
 is_view_only_client_manager=@is_view_only_client_manager,  
 is_view_only_agents_maintenance=@is_view_only_agents_maintenance,  
 is_view_only_account_handler_maintenance=@is_view_only_account_handler_maintenance,  
 is_view_only_account_executive_maintenance=@is_view_only_account_executive_maintenance,  
 is_view_only_insurer_maintenance=@is_view_only_insurer_maintenance,  
 is_view_only_other_party_maintenance=@is_view_only_other_party_maintenance,  
 is_recommender = @is_recommender,  
 recommender_currency_id = @recommender_currency_id,  
 recommender_currency_amount = @recommender_currency_amount,  
 allow_reverse_allocations = @allow_reverse_allocations,  
 reverse_allocations_days = @reverse_allocations_days,  
 can_reverse_and_replace_transactions = @can_reverse_and_replace_transactions,  
 out_of_sequence_mta_authority = @MTA_Authority,  
 can_override_cheque_Numbers=@can_override_cheque_Numbers,  
 display_reinsurance = @display_reinsurance,  
 display_claim_reinsurance=@display_claim_reinsurance,  
 can_backdate_collection_date=@can_backdate_collection_date,  
 can_make_live_BankGuarantee =  @can_make_live_BankGuarantee,  
  Edit_Default_Commission=@Edit_Default_Commission,  
 can_make_live_cashdeposit =@can_make_live_cashdeposit,  
  can_user_debug_dynamic_logic_scripts=@can_user_debug_dynamic_logic_scripts,  
 user_server_scripts_run_in_debug=@user_server_scripts_run_in_debug,  
 Edit_Default_Commission_NB_RN=@Edit_Default_Commission_NB_RN ,  
 Edit_Default_Commission_MTA=@Edit_Default_Commission_MTA ,  
 Edit_Default_Commission_MTC=@Edit_Default_Commission_MTC ,  
 Edit_Default_Commission_MTR=@Edit_Default_Commission_MTR ,  
 Agent_Editable_During_MTA_MTC=@Agent_Editable_During_MTA_MTC,  
 allow_receipt_reversal= @allow_receipt_reversal,  
 can_change_instalment_default_currency=@can_change_instalment_default_currency,  
 can_update_instalment_status = @can_update_instalment_status,  
 can_edit_instalment_date = @can_edit_instalment_date,  
 edit_instalment_by_no_of_days = @edit_instalment_by_no_of_days,  
 Currency_Loss_Gain_Limit = @currency_loss_gain_limit,  
 loss_gain_currency_id = @loss_gain_currency_id ,
  has_ManualJournal_authority = @has_ManualJournal_authority,  
 ManualJournal_currency_id = @ManualJournal_currency_id,  
  ManualJournal_currency_amount = @ManualJournal_currency_amount,
  ModifiedBy = @modified_by,
  UniqueId = @unique_id,
  ScreenHierarchy = @screen_hierarchy,
 void_policy_version=@void_policy_version,
 can_extract_client_data=ISNULL(@can_extract_client_data, can_extract_client_data)
WHERE  
    user_id = @user_id  
END   
GO