SET QUOTED_IDENTIFIER ON SET ANSI_NULLS ON
GO

EXECUTE DDLDropProcedure 'spe_PFRF_upd'
GO
CREATE PROCEDURE spe_PFRF_upd
    @CompanyNo int,
    @SchemeNo int,
    @SchemeVersion int,
    @StartDate datetime,
    @ProductFamily char(1),
    @ArrangementFee numeric(19,4),
    @Mnemonic char(35),
    @EndDate datetime,
    @Protect char(1),
    @DaysDelay int,
    @DepositReq char(1),
    @DepositPC numeric(7,4),
    @AllowProtection char(1),
    @ProtectRate numeric(7,4),
    @MinInterest numeric(19,4),
    @Min1 numeric(19,4),
    @Max1 numeric(19,4),
    @Rate1 numeric(7,4),
    @APR1 numeric(7,4),
    @R1Com numeric(19,4),
    @APR1Com numeric(7,4),
    @Com1PC numeric(7,4),
    @Min2 numeric(19,4),
    @Max2 numeric(19,4),
    @Rate2 numeric(7,4),
    @APR2 numeric(7,4),
    @R2Com numeric(19,4),
    @APR2Com numeric(7,4),
    @Com2PC numeric(7,4),
    @Min3 numeric(19,4),
    @Max3 numeric(19,4),
    @Rate3 numeric(7,4),
    @APR3 numeric(7,4),
    @R3Com numeric(19,4),
    @APR3Com numeric(7,4),
    @Com3PC numeric(7,4),
    @Min4 numeric(19,4),
    @Max4 numeric(19,4),
    @Rate4 numeric(7,4),
    @APR4 numeric(7,4),
    @R4Com numeric(19,4),
    @APR4Com numeric(7,4),
    @Com4PC numeric(7,4),
    @Min5 numeric(19,4),
    @Max5 numeric(19,4),
    @Rate5 numeric(7,4),
    @APR5 numeric(7,4),
    @R5Com numeric(19,4),
    @APR5Com numeric(7,4),
    @Com5PC numeric(7,4),
    @AlLowOveride char(1),
    @MinMTA numeric(19,4),
    @MinMTAInstalments INT
AS
BEGIN
UPDATE PFRF
    SET
    StartDate = @StartDate,
    ProductFamily = @ProductFamily,
    ArrangementFee = @ArrangementFee,
    Mnemonic = @Mnemonic,
    EndDate = @EndDate,
    Protect = @Protect,
    DaysDelay = @DaysDelay,
    DepositReq = @DepositReq,
    DepositPC = @DepositPC,
    AllowProtection = @AllowProtection,
    ProtectRate = @ProtectRate,
    MinInterest = @MinInterest,
    Min1 = @Min1,
    Max1 = @Max1,
    Rate1 = @Rate1,
    APR1 = @APR1,
    R1Com = @R1Com,
    APR1Com = @APR1Com,
    Com1PC = @Com1PC,
    Min2 = @Min2,
    Max2 = @Max2,
    Rate2 = @Rate2,
    APR2 = @APR2,
    R2Com = @R2Com,
    APR2Com = @APR2Com,
    Com2PC = @Com2PC,
    Min3 = @Min3,
    Max3 = @Max3,
    Rate3 = @Rate3,
    APR3 = @APR3,
    R3Com = @R3Com,
    APR3Com = @APR3Com,
    Com3PC = @Com3PC,
    Min4 = @Min4,
    Max4 = @Max4,
    Rate4 = @Rate4,
    APR4 = @APR4,
    R4Com = @R4Com,
    APR4Com = @APR4Com,
    Com4PC = @Com4PC,
    Min5 = @Min5,
    Max5 = @Max5,
    Rate5 = @Rate5,
    APR5 = @APR5,
    R5Com = @R5Com,
    APR5Com = @APR5Com,
    Com5PC = @Com5PC,
    AlLowOveride = @AlLowOveride,
    MinMTA = @MinMTA,
    MinMTAInstalments = @MinMTAInstalments
WHERE
    CompanyNo = @CompanyNo
AND SchemeNo = @SchemeNo
AND SchemeVersion = @SchemeVersion
AND StartDate = @StartDate
AND ProductFamily = @ProductFamily

END
GO

