
EXECUTE DDLDropProcedure 'spe_Product_add'
GO

--********************************************************************************************************************************  
-- JMK  25/07/2001          add rounding indicator params  
--*********************************************************************************************************************************  
CREATE PROCEDURE spe_Product_add  
		@product_id                                          INT OUTPUT,
		@caption_id                                          INT,
		@code                                                CHAR(10),
		@description                                         VARCHAR(255),
		@effective_date                                      DATETIME,
		@is_deleted                                          TINYINT,
		@scheme_agency_ref                                   VARCHAR(255),
		@block_no                                            VARCHAR(255),
		@is_tax_suppressed                                   TINYINT,
		@quote_auto_numbering_id                             INT,
		@is_short_period_rated                               TINYINT,
		@is_midnight_renewal                                 TINYINT,
		@is_auto_renewable                                   TINYINT,
		@renewal_period                                      INT,
		@policy_auto_numbering_id                            INT,
		@prov_claim_auto_numbering_id                        INT,
		@full_claim_auto_numbering_id                        INT,
		@is_accumulation                                     TINYINT,
		@ri_pointer                                          INT,
		@report_pointer                                      INT,
		@claim_year_to_check                                 INT,
		@max_single_claim_value                              MONEY,
		@max_number_of_claim                                 INT,
		@max_total_claim_value                               MONEY,
		@nb_prorata                                          AS TINYINT,
		@mta_prorata                                         AS TINYINT,
		@round_prem_to_nearest_unit                          TINYINT,
		@rounding_section_id                                 INT,
		@is_policy_number_at_quote                           TINYINT,
		@follow_up_time_frame                                INT,
		@grace_period                                        INT,
		@prevent_cancelled_agents                            TINYINT,
		@allow_positive_cancellation                         TINYINT,
		@media_type_mandatory                                TINYINT,
		@policy_style_id                                     INT,
		@policy_style_mandatory                              BIT,
		@allow_currency_change                               TINYINT,
		@allow_loss_currency_change                          TINYINT,
		@ChangePolicyNumberAtRenewal                         TINYINT,
		@allow_standard_wording_edit                         TINYINT,
		@HideSummaryAtRenewalAcceptance                      TINYINT,
		@is_true_monthly_policy                              TINYINT,
		@anniversary_renewal_weeks                           INT,
		@suppress_reserves                                   INT,
		@suppress_payments                                   INT,
		@suppress_recoveries                                 INT,
		@unifiedrenewalday                                   TINYINT,
		@LeadAllowConsolidateComm                            TINYINT,
		@leadmonthincycle                                    TINYINT,
		@LeadSuspenseAcct                                    VARCHAR(50),
		@SubAllowConsolidateComm                             TINYINT,
		@Submonthincycle                                     TINYINT,
		@SubSuspenseAcct                                     VARCHAR(50),
		@can_make_live_invoice                               TINYINT,
		@can_make_live_instalments                           TINYINT,
		@can_make_live_paynow                                TINYINT,
		@produce_schedule                                    TINYINT,
		@produce_certificate                                 TINYINT,
		@produce_debit_note                                  TINYINT,
		@is_renewable                                        TINYINT,
		@is_renewal_selection_enabled                        TINYINT,
		@true_monthly_policy_renewal_communication           TINYINT,
		@renewal_selection_man_review_template_id            INT,
 @renewal_selection_man_review_attachment_template_id INT,  
		@renewal_selection_invite_template_id                INT,
		@renewal_selection_invite_attachment_template_id     INT,
		@renewal_selection_update_template_id                INT,
		@renewal_selection_update_attachment_template_id     INT,
		@is_renewal_invite_enabled                           TINYINT,
		@renewal_invite_man_review_template_id               INT,
		@renewal_invite_man_review_attachment_template_id    INT,
		@renewal_invite_invite_template_id                   INT,
		@renewal_invite_invite_attachment_template_id        INT,
		@renewal_invite_update_template_id                   INT,
		@renewal_invite_update_attachment_template_id        INT,
		@is_renewal_update_enabled                           TINYINT,
		@renewal_update_man_review_template_id               INT,
		@renewal_update_man_review_attachment_template_id    INT,
		@renewal_update_invite_template_id                   INT,
		@renewal_update_invite_attachment_template_id        INT,
		@renewal_update_update_template_id                   INT,
		@renewal_update_update_attachment_template_id        INT,
		@is_agent_renewal_selection_enabled                  TINYINT,
		@is_agent_renewal_invite_enabled                     TINYINT,
		@is_agent_renewal_update_enabled                     TINYINT,
		@agent_renewal_man_review_template_id                INT,
		@agent_renewal_man_review_report_id                  INT,
		@agent_renewal_invite_template_id                    INT,
		@agent_renewal_invite_report_id                      INT,
		@agent_renewal_update_template_id                    INT,
		@agent_renewal_update_report_id                      INT,
		@multiple_claims_payments                            TINYINT,
		@max_unauthorised_claim_value                        MONEY,
		@max_unAuthorised_no_claim_payments                  INT,
		@run_authorisation_scripts_claim_payments            TINYINT,
		@BankAccount_Id                                      INT,
		@Claim_Value_For_Large_Loss_Advice                   NUMERIC(19, 4),
		@Inclusion_of_CoInsurers_On_Claims                   TINYINT,
		@Allow_Negative_Reserve                              TINYINT,
		@Ext_Clm_Handler_Acknowledged_Task_Allowed_Time      NUMERIC(3),
		@Ext_Clm_Handler_Supply_Pre_Report_Task_Allowed_Time NUMERIC(3),
		@Valid_Policy_Version_At_Loss_Date                   TINYINT,
		@Is_Gross_Claim_Payment_Amount                       TINYINT,
		@Claim_Task_Group                                    INT,
		@Claim_User_Group                                    INT,
		@Claims_UDT_A                                        INT,
		@Claims_UDT_B                                        INT,
		@Claims_UDT_C                                        INT,
		@Claims_UDT_D                                        INT,
		@Claims_UDT_E                                        INT,
		@Is_Duplicate_Claim_Check_Enabled                    TINYINT,
		@Is_Advanced_Tax_Script_Enabled                      TINYINT,
		@Is_Payment_Ref_Check_Enabled                        TINYINT,
		@is_Recommend_Claim_Payments                         TINYINT,
		@MTA_Date_allowed                                    TINYINT,
		@MtA_Allocation                                      TINYINT,
		@default_renewal_Months                              INT,
		@Payment_Cannot_Exceed_Reserve                       TINYINT,
		@enable_mtc_rating_rule                              TINYINT,
		@can_make_live_bankguarantee                         TINYINT,
		@Cover_Note_Default_Period                           INT,
		@Cover_Note_reused_upto                              INT,
		@Cover_Note_doc_Template_id                          INT,
		@Cover_Note_numbering_id                             INT,
		@allow_backdated_mtas                                TINYINT,
		@out_of_sequence_mta_UserGroup                       INT,
		@out_of_sequence_mta_TaskGroup                       INT,
		@use_nb_payment_term_at_renselection                 INT,
		@is_roundoff_to_zero                                 TINYINT,
		@check_mediatype_status_at_claim_payment             TINYINT,
		@check_mediatype_status_at_policy_refund             TINYINT,
		@change_policy_number_at_renewal_auto                TINYINT,
		@can_make_live_cashdeposit                           TINYINT = 0,
		@ri_manual_premium_adjustment                        TINYINT,
		@allow_backdated_can                                 TINYINT,
		@tmpautrenfac                                        TINYINT,
		@allow_written_status                                TINYINT,
		@written_task_manager_days                           INT,
		@written_rem_user_group                              INT,
		@written_rem_task_group                              INT,
		@use_prior_term_scheme_at_ren                        INT,
		@bind_renewal_without_invitation                     TINYINT,
		@is_enable_PrePayment                                TINYINT,
		@Mandatory_Risk_Type_Id                              INT,  
		@nDo_Not_Delete_RenQuote_On_Mta						 INT,
	    @Default_Cover_to_Date_to_Last_Day					 INT,
		@nUnified_Renewal_Date_Is_Read_Only		             INT,
		@bIsReservesReadonly                                 TINYINT,
		@bIsRecoveriesReadonly 				     TINYINT,
		@bIsPaymentsReadonly 				     TINYINT,
		@Quote_all_risk_NB									 TINYINT,
		@Quote_all_risk_MTC									 TINYINT,
		@Quote_all_risk_MTA									 TINYINT,
		@Auto_Renew_BDMPolicy								 TINYINT,
		@nDelete_ren_quote_ReRun_on_MTA    				     TINYINT = 0,
		@nQuote_all_risk_RENEWAL					TINYINT,
		@is_retain_policy_number_on_copy TINYINT	 = 0,
		@Anniversary_Date_Editable							 TINYINT,
		@disable_cover_start_date_on_REN					 TINYINT,
		@use_policy_inception_date                           TINYINT,
		@Authorisation_Threshold                             NUMERIC(10, 6),
		@UserId INT = NULL,
		@UniqueId VARCHAR(50) = NULL,
		@ScreenHierarchy VARCHAR(500) = NULL,
		@void_policy_version TINYINT = 0,
		@is_quote_versioning                             TINYINT = 0,
		@delete_quote_after                              INT = 0
AS  
BEGIN  
	DECLARE @LeadSuspenseAcct1 INT
	DECLARE @SubSuspenseAcct1 INT

IF @Product_id = 0  
                SELECT @Product_id = NULL  

IF @Product_id IS NULL  
                SELECT @Product_id = MAX(Product_id) + 1  
		FROM   Product

IF @Product_id IS NULL  
    SELECT @Product_id = 1  

	SELECT @LeadSuspenseAcct1 = account_id
	FROM   ACCOUNT
	WHERE  short_code = @LeadSuspenseAcct

	SELECT @SubSuspenseAcct1 = account_id
	FROM   ACCOUNT
	WHERE  short_code = @SubSuspenseAcct
  
INSERT INTO Product  
				(product_id,
 caption_id,  
 code,  
				 DESCRIPTION,
 effective_date,  
 is_deleted,  
 scheme_agency_ref,  
 block_no,  
 is_tax_suppressed,  
 quote_auto_numbering_id,  
 is_short_period_rated,  
 is_midnight_renewal,  
 is_auto_renewable,  
 renewal_period,  
 policy_auto_numbering_id,  
 prov_claim_auto_numbering_id,  
 full_claim_auto_numbering_id,  
 is_accumulation,  
 ri_pointer,  
 report_pointer,  
 claim_year_to_check,  
 max_single_claim_value,  
 max_number_of_claim,  
 max_total_claim_value,  
 nb_prorata,  
 mta_prorata,  
 round_prem_to_nearest_unit,  
 rounding_section_id,  
 is_policy_number_at_quote,  
 follow_up_time_frame,  
 grace_period,  
 prevent_cancelled_agents,  
 allow_positive_cancellation,  
 media_type_mandatory,  
 policy_style_id,  
 policy_style_mandatory,  
 allow_currency_change,  
 allow_loss_currency_change,  
 change_policy_number_at_renewal,  
 allow_standard_wording_edit,  
 hide_summary_at_renewal_acceptance,  
 is_true_monthly_policy,  
 anniversary_renewal_weeks,  
 suppress_reserves,  
 suppress_payments,  
 suppress_recoveries,  
 unified_renewal_day,  
 lead_allow_consolidated_commission,  
				 lead_month_in_cycle,
 lead_suspense_account_id,  
 sub_allow_consolidated_commission,  
 sub_month_in_cycle,  
 sub_suspense_account_id,  
 can_make_live_invoice,  
 can_make_live_instalments,  
 can_make_live_paynow,  
 produce_schedule,  
 produce_certificate,  
 produce_debit_note,  
 is_renewable,  
 is_renewal_selection_enabled,  
 true_monthly_policy_renewal_communication,  
 renewal_selection_man_review_template_id,  
 renewal_selection_man_review_attachment_template_id,  
 renewal_selection_invite_template_id,  
 renewal_selection_invite_attachment_template_id,  
 renewal_selection_update_template_id,  
 renewal_selection_update_attachment_template_id,  
 is_renewal_invite_enabled,  
 renewal_invite_man_review_template_id,  
 renewal_invite_man_review_attachment_template_id,  
 renewal_invite_invite_template_id,  
 renewal_invite_invite_attachment_template_id,  
 renewal_invite_update_template_id,  
 renewal_invite_update_attachment_template_id,  
 is_renewal_update_enabled,  
 renewal_update_man_review_template_id,  
 renewal_update_man_review_attachment_template_id,  
 renewal_update_invite_template_id,  
 renewal_update_invite_attachment_template_id,  
 renewal_update_update_template_id,  
 renewal_update_update_attachment_template_id,  
 is_agent_renewal_selection_enabled,  
 is_agent_renewal_invite_enabled,  
 is_agent_renewal_update_enabled,  
 agent_renewal_man_review_template_id,  
 agent_renewal_man_review_report_id,  
 agent_renewal_invite_template_id,  
 agent_renewal_invite_report_id,  
 agent_renewal_update_template_id,  
 agent_renewal_update_report_id,  
 multiple_claims_payments,  
 max_unauthorised_claim_value,  
 max_unauthorised_no_claim_payments,  
 run_authorisation_scripts_claim_payments,  
 BankAccount_Id,  
 Claim_Value_For_Large_Loss_Advice,  
 Inclusion_of_CoInsurers_On_Claims,  
 Allow_Negative_Reserve,  
 Ext_Clm_Handler_Acknowledged_Task_Allowed_Time,  
 Ext_Clm_Handler_Supply_Pre_Report_Task_Allowed_Time,  
 Valid_Policy_Version_At_Loss_Date,  
 Is_Gross_Claim_Payment_Amount,  
 Claim_Task_Group,  
 Claim_User_Group,  
 Claims_UDT_A,  
 Claims_UDT_B,  
 Claims_UDT_C,  
 Claims_UDT_D,  
 Claims_UDT_E,  
 Is_Duplicate_Claim_Check_Enabled,  
 Is_Advanced_Tax_Script_Enabled,  
 Is_Payment_Ref_Check_Enabled,  
 is_Recommend_Claim_Payments,  
				 out_of_sequence_mta_dates,
 out_of_sequence_mta_allocation,  
 default_renewal_Months,  
 Payment_Cannot_Exceed_Reserve,  
 enable_mtc_rating_rule,  
        can_make_live_bankguarantee,  
 Cover_Note_Default_Period,  
 Cover_Note_reused_upto,  
 Cover_Note_doc_Template_id,  
				 Cover_Note_numbering_id,
 allow_backdated_mtas,  
				 out_of_sequence_mta_UserGroup,
out_of_sequence_mta_TaskGroup,  
use_nb_payment_term_at_renselection,
				 is_roundoff_to_zero,
check_mediatype_status_at_claim_payment,
check_mediatype_status_at_policy_refund,
change_ren_policy_no_auto,
				 can_make_live_cashDeposit,
				 ri_manual_premium_adjustment,
				 allow_backdated_can,
				 tmpautrenfac,
				 allow_written_status,
				 written_task_manager_days,
				 written_rem_user_group,
written_rem_task_group,
				 use_prior_term_scheme_at_ren,
				 bind_renewal_without_invitation,
				 is_enable_PrePayment,
				 Mandatory_Risk_Type_Id,  
				 do_not_delete_renQuote_on_mta,
				 default_cover_to_date_to_last_day,
				 unified_renewal_date_is_read_only,
				 is_reserves_read_only,
				 is_recoveries_read_only,
				 is_payments_read_only,
				 Quote_all_risk_NB,
				 Quote_all_risk_MTC,
				 Quote_all_risk_MTA,
				 Auto_Renew_BDMPolicy,
				 Delete_And_ReRun_RenQuote,
				 Quote_all_risk_RENEWAL,
				 is_retain_policy_number_on_copy,
				 Anniversary_Date_Editable,
				 disable_cover_start_date_on_REN,
				 use_policy_inception_date,
				 UserId,
				 UniqueId,
				 ScreenHierarchy,
				 void_policy_version,
				 is_quote_versioning,
				 delete_quote_after)
	VALUES      ( @product_id,
 @caption_id,  
 @code,  
 @description,  
 @effective_date,  
 @is_deleted,  
 @scheme_agency_ref,  
 @block_no,  
 @is_tax_suppressed,  
 @quote_auto_numbering_id,  
 @is_short_period_rated,  
 @is_midnight_renewal,  
 @is_auto_renewable,  
 @renewal_period,  
 @policy_auto_numbering_id,  
 @prov_claim_auto_numbering_id,  
 @full_claim_auto_numbering_id,  
 @is_accumulation,  
 @ri_pointer,  
 @report_pointer,  
 @claim_year_to_check,  
 @max_single_claim_value,  
 @max_number_of_claim,  
 @max_total_claim_value,  
 @nb_prorata,  
 @mta_prorata,  
 @round_prem_to_nearest_unit,  
 @rounding_section_id,  
 @is_policy_number_at_quote,  
 @follow_up_time_frame,  
 @grace_period,  
 @prevent_cancelled_agents,  
 @allow_positive_cancellation,  
 @media_type_mandatory,  
 @policy_style_id,  
 @policy_style_mandatory,  
 @allow_currency_change,  
 @allow_loss_currency_change,  
 @ChangePolicyNumberAtRenewal,  
 @allow_standard_wording_edit,  
 @HideSummaryAtRenewalAcceptance,  
 @is_true_monthly_policy,  
 @anniversary_renewal_weeks,  
 @suppress_reserves,  
 @suppress_payments,  
 @suppress_recoveries,  
 @unifiedrenewalday,  
 @LeadAllowConsolidateComm,  
 @leadmonthincycle,  
 @LeadSuspenseAcct1,  
 @SubAllowConsolidateComm,  
 @submonthincycle,  
 @SubSuspenseAcct1,  
 @can_make_live_invoice,  
 @can_make_live_instalments,  
 @can_make_live_paynow,  
 @produce_schedule,  
 @produce_certificate,  
 @produce_debit_note,  
 @is_renewable,  
 @is_renewal_selection_enabled,  
 @true_monthly_policy_renewal_communication,  
 @renewal_selection_man_review_template_id,  
 @renewal_selection_man_review_attachment_template_id,  
 @renewal_selection_invite_template_id,  
 @renewal_selection_invite_attachment_template_id,  
 @renewal_selection_update_template_id,  
 @renewal_selection_update_attachment_template_id,  
 @is_renewal_invite_enabled,  
 @renewal_invite_man_review_template_id,  
 @renewal_invite_man_review_attachment_template_id,  
 @renewal_invite_invite_template_id,  
 @renewal_invite_invite_attachment_template_id,  
 @renewal_invite_update_template_id,  
 @renewal_invite_update_attachment_template_id,  
 @is_renewal_update_enabled,  
 @renewal_update_man_review_template_id,  
 @renewal_update_man_review_attachment_template_id,  
 @renewal_update_invite_template_id,  
 @renewal_update_invite_attachment_template_id,  
 @renewal_update_update_template_id,  
 @renewal_update_update_attachment_template_id,  
 @is_agent_renewal_selection_enabled,  
 @is_agent_renewal_invite_enabled,  
 @is_agent_renewal_update_enabled,  
 @agent_renewal_man_review_template_id,  
 @agent_renewal_man_review_report_id,  
 @agent_renewal_invite_template_id,  
 @agent_renewal_invite_report_id,  
 @agent_renewal_update_template_id,  
 @agent_renewal_update_report_id,  
 @multiple_claims_payments,  
 @max_unauthorised_claim_value,  
 @max_unauthorised_no_claim_payments,  
 @run_authorisation_scripts_claim_payments,  
 @BankAccount_Id,  
 @Claim_Value_For_Large_Loss_Advice,  
 @Inclusion_of_CoInsurers_On_Claims,  
 @Allow_Negative_Reserve,  
 @Ext_Clm_Handler_Acknowledged_Task_Allowed_Time,  
 @Ext_Clm_Handler_Supply_Pre_Report_Task_Allowed_Time,  
 @Valid_Policy_Version_At_Loss_Date,  
 @Is_Gross_Claim_Payment_Amount,  
 @Claim_Task_Group,  
 @Claim_User_Group,  
 @Claims_UDT_A,  
 @Claims_UDT_B,  
 @Claims_UDT_C,  
 @Claims_UDT_D,  
 @Claims_UDT_E,  
 @Is_Duplicate_Claim_Check_Enabled,  
 @Is_Advanced_Tax_Script_Enabled,  
 @Is_Payment_Ref_Check_Enabled,  
 @is_Recommend_Claim_Payments,  
				  @MTA_Date_allowed,
				  @MTA_Allocation,
 @default_renewal_Months,  
 @Payment_Cannot_Exceed_Reserve,  
 @enable_mtc_rating_rule,  
@can_make_live_bankguarantee,  
@Cover_Note_Default_Period,  
@Cover_Note_reused_upto,  
@Cover_Note_doc_Template_id,  
@Cover_Note_numbering_id,  
 @allow_backdated_mtas,  
				  @out_of_sequence_mta_UserGroup,
@out_of_sequence_mta_TaskGroup,  
 @use_nb_payment_term_at_renselection,
				  @is_roundoff_to_zero,
@check_mediatype_status_at_claim_payment,
@check_mediatype_status_at_policy_refund,
@change_policy_number_at_renewal_auto,
				  @can_make_live_cashDeposit,
@ri_manual_premium_adjustment,
@allow_backdated_can,
@tmpautrenfac,
				  @allow_written_status,
				  @written_task_manager_days,
				  @written_rem_user_group,
@written_rem_task_group,
				  @use_prior_term_scheme_at_ren,
				  @bind_renewal_without_invitation,
				  @is_enable_PrePayment,
				  @Mandatory_Risk_Type_Id,  
				  @nDo_Not_Delete_RenQuote_On_Mta,
				  @Default_Cover_to_Date_to_Last_Day,
				  @nUnified_Renewal_Date_Is_Read_Only,
				  @bIsReservesReadonly,
				  @bIsRecoveriesReadonly,
				  @bIsPaymentsReadonly,
				  @Quote_all_risk_NB,
				  @Quote_all_risk_MTC,
				  @Quote_all_risk_MTA,
				@Auto_Renew_BDMPolicy,
				@nDelete_ren_quote_ReRun_on_MTA,
				@nQuote_all_risk_RENEWAL,
				@is_retain_policy_number_on_copy,
				@Anniversary_Date_Editable,
				@disable_cover_start_date_on_REN,
				@use_policy_inception_date,
				  @UserId,
				  @UniqueId,
				  @ScreenHierarchy,
				  @void_policy_version,
				  @is_quote_versioning,
				  @delete_quote_after)
END

BEGIN  
SELECT Product_id = @Product_id  
END  

GO
