SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_User_Authorities_sel'
GO


CREATE PROCEDURE spe_User_Authorities_sel
    @user_id smallint  
AS  
SELECT  
 user_id,  
 has_write_off_authority,  
 write_off_amount,  
 has_unrestricted_enquiry,  
 has_unrestricted_update,  
 fee_discount,  
 has_transaction_write_off_authority,  
 transaction_write_off_amount,  
 has_refund_authority,  
 has_transfer_authority,  
 has_payments_authority,  
 payments_amount,  
 has_claim_payments_authority,  
 claim_payments_amount,  
 write_off_currency_id,  
 transaction_write_off_currency_id,  
 payments_currency_id,  
 claims_payments_currency_id,  
 can_change_exchange_date,  
 can_change_exchange_rate,  
 can_change_prepolicy_exchange_date,  
 can_change_prepolicy_exchange_rate,  
 is_view_client,  
 is_edit_client,  
 is_edit_policy,  
 is_edit_claim,  
 is_edit_finance_plan,  
 is_raise_debit,  
 is_raise_credit,  
 is_raise_fee,  
 is_raise_cash,  
 is_reverse_transactions,  
 is_reverse_allocations,  
 is_raise_manual_DID,  
 is_delete_client,  
 is_perform_allocations,  
 can_perform_broker_transfer,  
 can_override_duplicate_claims,  
 is_delete_policy,  
 is_edit_scheme_policy,  
 can_make_live_invoice,  
 can_make_live_instalments,  
 can_make_live_paynow,  
 has_paynow_write_off_authority,  
 paynow_write_off_currency_id,  
 paynow_write_off_amount,  
 paynow_bankaccount_id,  
 can_override_posting_period,
 can_change_reserves_on_claim_payments,
 allow_ratingsection_adddelete ,
 allow_ratingsection_editing,
 is_view_only_client_manager,  
 is_view_only_agents_maintenance,  
 is_view_only_account_handler_maintenance,  
 is_view_only_account_executive_maintenance,  
 is_view_only_insurer_maintenance,  
 is_view_only_other_party_maintenance,  
 is_recommender,  
 recommender_currency_id,  
 recommender_currency_amount,  
 allow_reverse_allocations,  
 reverse_allocations_days,  
 can_reverse_and_replace_transactions,  
 out_of_sequence_mta_authority,  
 can_override_cheque_Numbers,
 display_reinsurance, 
 display_claim_reinsurance, 
 can_backdate_collection_date,  
 can_make_live_BankGuarantee,  
  Edit_Default_Commission,
 can_make_live_cashdeposit,
  can_user_debug_dynamic_logic_scripts,
 user_server_scripts_run_in_debug,
 Edit_Default_Commission_NB_RN,
 Edit_Default_Commission_MTA,
 Edit_Default_Commission_MTC,
 Edit_Default_Commission_MTR,
 Agent_Editable_During_MTA_MTC,
 allow_receipt_reversal,
 has_ViewBatchProcessStatus,
 can_change_instalment_default_currency,
 can_update_instalment_status,
 can_edit_instalment_date,
 edit_instalment_by_no_of_days,
 Currency_Loss_Gain_Limit,
 loss_gain_currency_id,
 has_ManualJournal_authority,  
 ManualJournal_currency_amount ,  
 ManualJournal_currency_id ,
 void_policy_version,
 can_extract_client_data 
FROM  
    User_Authorities  
WHERE  
    user_id = @user_id  

GO

