SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_Farm_add'
GO

CREATE PROCEDURE spe_Farm_add
    @insurance_file_cnt int,
    @address_cnt int,
    @is_property_damage tinyint,
    @pd_produce_sum_insured numeric(19,4),
    @pd_poultry_sum_insured numeric(19,4),
    @pd_buildings_sum_insured numeric(19,4),
    @pd_misc_sum_insured numeric(19,4),
    @pd_liability_sum_insured numeric(19,4),
    @is_business_interruption tinyint,
    @bi_description varchar(60),
    @bi_sum_insured numeric(19,4),
    @bi_indemnity_period int,
    @is_livestock tinyint,
    @l_sum_insured numeric(19,4),
    @l_in_transit_limit numeric(19,4),
    @l_disease_sum_insured numeric(19,4),
    @is_farm_liabilities tinyint,
    @fl_wages_estimate numeric(19,4),
    @fl_employers_liability_limit numeric(19,4),
    @fl_public_liability_limit numeric(19,4),
    @is_money_and_assault tinyint,
    @ma_money_in_transit numeric(19,4),
    @ma_money numeric(19,4),
    @ma_not_in_safe numeric(19,4),
    @ma_in_dwellings numeric(19,4),
    @ma_locked numeric(19,4),
    @ma_any_other numeric(19,4),
    @is_personal_accident tinyint,
    @pa_insured_person varchar(60),
    @pa_age int,
    @pa_duties varchar(70),
    @pa_compensation numeric(19,4),
    @is_engineering tinyint,
    @e_property_insured varchar(60),
    @e_cover numeric(19,4),
    @e_indemnity_limit numeric(19,4),
    @e_excess numeric(19,4),
    @is_uncollected_milk tinyint,
    @um_days_compensation int,
    @um_compensation numeric(19,4),
    @um_number_of_cows int,
    @is_farm_home tinyint,
    @fh_buildings_sum_insured numeric(19,4),
    @fh_contents_sum_insured numeric(19,4),
    @fh_possessions_sum_insured numeric(19,4),
    @fh_unspecified_sum_insured numeric(19,4),
    @fh_specified_sum_insured numeric(19,4),
    @fh_buildings_excess numeric(19,4),
    @fh_subsidence_excess numeric(19,4),
    @fh_contents_excess numeric(19,4),
    @is_farm_motor tinyint,
    @fm_year int,
    @fm_registration_number varchar(20),
    @fm_value numeric(19,4),
    @fm_cover numeric(19,4)
AS
BEGIN
INSERT INTO Farm (
    insurance_file_cnt ,
    address_cnt ,
    is_property_damage ,
    pd_produce_sum_insured ,
    pd_poultry_sum_insured ,
    pd_buildings_sum_insured ,
    pd_misc_sum_insured ,
    pd_liability_sum_insured ,
    is_business_interruption ,
    bi_description ,
    bi_sum_insured ,
    bi_indemnity_period ,
    is_livestock ,
    l_sum_insured ,
    l_in_transit_limit ,
    l_disease_sum_insured ,
    is_farm_liabilities ,
    fl_wages_estimate ,
    fl_employers_liability_limit ,
    fl_public_liability_limit ,
    is_money_and_assault ,
    ma_money_in_transit ,
    ma_money ,
    ma_not_in_safe ,
    ma_in_dwellings ,
    ma_locked ,
    ma_any_other ,
    is_personal_accident ,
    pa_insured_person ,

    pa_age ,
    pa_duties ,
    pa_compensation ,
    is_engineering ,
    e_property_insured ,
    e_cover ,
    e_indemnity_limit ,
    e_excess ,
    is_uncollected_milk ,
    um_days_compensation ,
    um_compensation ,
    um_number_of_cows ,
    is_farm_home ,
    fh_buildings_sum_insured ,
    fh_contents_sum_insured ,
    fh_possessions_sum_insured ,
    fh_unspecified_sum_insured ,
    fh_specified_sum_insured ,
    fh_buildings_excess ,
    fh_subsidence_excess ,
    fh_contents_excess ,
    is_farm_motor ,
    fm_year ,
    fm_registration_number ,
    fm_value ,
    fm_cover )
VALUES (
    @insurance_file_cnt,
    @address_cnt,
    @is_property_damage,
    @pd_produce_sum_insured,
    @pd_poultry_sum_insured,
    @pd_buildings_sum_insured,
    @pd_misc_sum_insured,
    @pd_liability_sum_insured,
    @is_business_interruption,
    @bi_description,
    @bi_sum_insured,
    @bi_indemnity_period,
    @is_livestock,
    @l_sum_insured,
    @l_in_transit_limit,
    @l_disease_sum_insured,
    @is_farm_liabilities,
    @fl_wages_estimate,
    @fl_employers_liability_limit,
    @fl_public_liability_limit,
    @is_money_and_assault,
    @ma_money_in_transit,
    @ma_money,
    @ma_not_in_safe,
    @ma_in_dwellings,
    @ma_locked,
    @ma_any_other,
    @is_personal_accident,
    @pa_insured_person,
    @pa_age,
    @pa_duties,
    @pa_compensation,
    @is_engineering,
    @e_property_insured,
    @e_cover,
    @e_indemnity_limit,
    @e_excess,
    @is_uncollected_milk,
    @um_days_compensation,
    @um_compensation,
    @um_number_of_cows,
    @is_farm_home,
    @fh_buildings_sum_insured,
    @fh_contents_sum_insured,
    @fh_possessions_sum_insured,
    @fh_unspecified_sum_insured,
    @fh_specified_sum_insured,
    @fh_buildings_excess,
    @fh_subsidence_excess,
    @fh_contents_excess,
    @is_farm_motor,
    @fm_year,
    @fm_registration_number,
    @fm_value,
    @fm_cover)
END

GO

