SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_commercial_combined_add'
GO

CREATE PROCEDURE spe_commercial_combined_add
    @insurance_file_cnt int,
    @is_fire_damage tinyint,
    @fd_buildings_sum numeric(19,4),
    @fd_stock_and_materials numeric(19,4),
    @is_all_risks tinyint,
    @ar_buildings_sum numeric(19,4),
    @landlord_f_and_f_sum numeric(19,4),
    @stock_in_trade_sum numeric(19,4),
    @property_sum_insured numeric(19,4),
    @is_burglary tinyint,
    @machinery_sum_insured numeric(19,4),
    @b_stock_and_materials numeric(19,4),
    @s_i_t_tobacco numeric(19,4),
    @s_i_t_alcohol numeric(19,4),
    @s_i_t_radio numeric(19,4),
    @s_i_t_non_ferrous numeric(19,4),
    @is_business_interruption tinyint,
    @gross_profit_sum numeric(19,4),
    @maximum_indemnity_period int,
    @is_glass tinyint,
    @glass_type int,
    @glass_cover_amount numeric(19,4),
    @is_employers_liability tinyint,
    @e_indemnity_limit numeric(19,4),
    @e_description varchar(60),
    @wages_and_salaries numeric(19,4),
    @is_public_liability tinyint,
    @pl_indemnity_limit numeric(19,4),
    @pl_description varchar(60),
    @pl_rating_basis varchar(20),
    @pl_excess numeric(19,4),
    @is_money_and_assault tinyint,
    @ma_cards_limit numeric(19,4),
    @ma_not_locked numeric(19,4),
    @ma_locked numeric(19,4),
    @ma_premises numeric(19,4),
    @ma_any_other numeric(19,4),
    @ma_insured_persons int,
    @ma_compensation_amount numeric(19,4),
    @is_goods_in_transit tinyint,
    @git_make_of_vehicle varchar(70),
    @git_registration_number varchar(20),
    @git_tools_limit numeric(19,4),
    @git_liability_limit numeric(19,4),
    @git_retained_liability numeric(19,4),
    @is_personal_accident tinyint,
    @pa_insured_person varchar(20),
    @pa_age int,
    @pa_duties varchar(60),
    @pa_compensation numeric(19,4),
    @is_supp_all_risks tinyint,
    @sar_property_insured varchar(60),
    @sar_sum_insured numeric(19,4),
    @sar_liability_limit numeric(19,4),
    @is_engineering tinyint,
    @e_property_insured varchar(60),
    @e_cover numeric(19,4),
    @e_liability_limit numeric(19,4),
    @e_excess numeric(19,4),
    @is_frozen_food tinyint,
    @ff_unit_description varchar(60),
    @ff_date_of_make datetime,
    @ff_sum_insured numeric(19,4),
    @ff_liability_limit numeric(19,4)
AS
BEGIN
INSERT INTO commercial_combined (
    insurance_file_cnt ,
    is_fire_damage ,
    fd_buildings_sum ,
    fd_stock_and_materials ,
    is_all_risks ,
    ar_buildings_sum ,
    landlord_f_and_f_sum ,
    stock_in_trade_sum ,
    property_sum_insured ,
    is_burglary ,
    machinery_sum_insured ,
    b_stock_and_materials ,
    s_i_t_tobacco ,
    s_i_t_alcohol ,
    s_i_t_radio ,
    s_i_t_non_ferrous ,
    is_business_interruption ,
    gross_profit_sum ,
    maximum_indemnity_period ,
    is_glass ,
    glass_type ,
    glass_cover_amount ,
    is_employers_liability ,
    e_indemnity_limit ,
    e_description ,
    wages_and_salaries ,
    is_public_liability ,
    pl_indemnity_limit ,
    pl_description ,
    pl_rating_basis ,
    pl_excess ,
    is_money_and_assault ,
    ma_cards_limit ,
    ma_not_locked ,
    ma_locked ,
    ma_premises ,
    ma_any_other ,
    ma_insured_persons ,
    ma_compensation_amount ,
    is_goods_in_transit ,
    git_make_of_vehicle ,
    git_registration_number ,
    git_tools_limit ,
    git_liability_limit ,
    git_retained_liability ,
    is_personal_accident ,
    pa_insured_person ,
    pa_age ,
    pa_duties ,
    pa_compensation ,
    is_supp_all_risks ,
    sar_property_insured ,
    sar_sum_insured ,
    sar_liability_limit ,
    is_engineering ,
    e_property_insured ,
    e_cover ,
    e_liability_limit ,
    e_excess ,
    is_frozen_food ,
    ff_unit_description ,
    ff_date_of_make ,
    ff_sum_insured ,
    ff_liability_limit )
VALUES (
    @insurance_file_cnt,
    @is_fire_damage,
    @fd_buildings_sum,
    @fd_stock_and_materials,
    @is_all_risks,
    @ar_buildings_sum,
    @landlord_f_and_f_sum,
    @stock_in_trade_sum,
    @property_sum_insured,
    @is_burglary,
    @machinery_sum_insured,
    @b_stock_and_materials,
    @s_i_t_tobacco,
    @s_i_t_alcohol,
    @s_i_t_radio,
    @s_i_t_non_ferrous,
    @is_business_interruption,
    @gross_profit_sum,
    @maximum_indemnity_period,
    @is_glass,
    @glass_type,
    @glass_cover_amount,
    @is_employers_liability,
    @e_indemnity_limit,
    @e_description,
    @wages_and_salaries,
    @is_public_liability,
    @pl_indemnity_limit,
    @pl_description,
    @pl_rating_basis,
    @pl_excess,
    @is_money_and_assault,
    @ma_cards_limit,
    @ma_not_locked,
    @ma_locked,
    @ma_premises,
    @ma_any_other,
    @ma_insured_persons,
    @ma_compensation_amount,
    @is_goods_in_transit,
    @git_make_of_vehicle,
    @git_registration_number,
    @git_tools_limit,
    @git_liability_limit,
    @git_retained_liability,
    @is_personal_accident,
    @pa_insured_person,
    @pa_age,
    @pa_duties,
    @pa_compensation,
    @is_supp_all_risks,
    @sar_property_insured,
    @sar_sum_insured,
    @sar_liability_limit,
    @is_engineering,
    @e_property_insured,
    @e_cover,
    @e_liability_limit,
    @e_excess,
    @is_frozen_food,
    @ff_unit_description,
    @ff_date_of_make,
    @ff_sum_insured,
    @ff_liability_limit)
END

GO

