SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spe_Risk_Type_add'
GO


CREATE PROCEDURE [dbo].[spe_Risk_Type_add]
	@risk_type_id INT OUTPUT ,
	@risk_folder_type_id INT ,
	@caption_id INT ,
	@code CHAR(10) ,
	@description VARCHAR(255) ,
	@effective_date DATETIME ,
	@is_deleted TINYINT ,
	@var_data_structure_id INT ,
	@interface_object_name CHAR(30) ,
	@interface_class_name CHAR(30) ,
	@override_peril_ri_band TINYINT ,
	@override_peril_xl_band TINYINT ,
	@nb_premium_pro_rata_type_id INT ,
	@mta_premium_pro_rata_type_id INT ,
	@rn_premium_pro_rata_type_id INT ,
	@is_share_with_co_insurers TINYINT ,
	@is_share_with_re_insurers TINYINT ,
	@is_suppress_public_text TINYINT ,
	@is_suppress_private_text TINYINT ,
	@is_suppress_taxes TINYINT ,
	@report_pointer INT ,
	@section_mask INT ,
	@stamp_duty_rate1 NUMERIC(7,4) ,
	@stamp_duty_rate2 NUMERIC(7,4) ,
	@primary_sort CHAR(10) ,
	@secondary_sort CHAR(10) ,
	@header_clause CHAR(10) ,
	@trailer_clause CHAR(10) ,
	@is_ri_at_risk_level TINYINT ,
	@is_auto_reinsured TINYINT ,
	@header_clause_id INT ,
	@trailer_clause_id INT,
	@accumulation_level INT,
	@gis_screen_id INT,
	@is_deferred_RI_permitted INT,
	@claims_is_post_taxes TINYINT,
	@Display_reinsurance_screen TINYINT,
	@allow_add_ratingsection TINYINT,
	@allow_edit_ratingsection TINYINT,
	@allow_delete_ratingsection TINYINT,
	@allow_edit_ratingsection_ratetype TINYINT,
	@allow_edit_ratingsection_rate TINYINT,
	@allow_edit_ratingsection_suminsured TINYINT,
	@allow_edit_ratingsection_thispremium TINYINT,
        @Display_Claims_reinsurance_screen TINYINT,
	@Claims_type_basis_ID INT,
	@Claims_Cover_basis_ID INT,
	@bAttach_Claim_Outside_Of_Policy_Period TINYINT,
	@UserId int = NULL,
	@UniqueId varchar(50) = NUll,
	@ScreenHierarchy varchar(500) = NUll

AS

IF ISNULL(@Risk_Type_id, 0) = 0
	SELECT  @Risk_Type_id = ISNULL(MAX(Risk_Type_id), 0) + 1
	FROM    Risk_Type

	INSERT INTO Risk_Type (
		risk_type_id ,
		risk_folder_type_id ,
		caption_id ,
		code ,
		description ,
		effective_date ,
		is_deleted ,
		var_data_structure_id ,
		interface_object_name ,
		interface_class_name ,
		override_peril_ri_band ,
		override_peril_xl_band ,
		nb_premium_pro_rata_type_id ,
		mta_premium_pro_rata_type_id ,
		rn_premium_pro_rata_type_id ,
		is_share_with_co_insurers ,
		is_share_with_re_insurers ,
		is_suppress_public_text ,
		is_suppress_private_text ,    
		is_suppress_taxes ,
		report_pointer ,
		section_mask ,
		stamp_duty_rate1 ,
		stamp_duty_rate2 ,
		primary_sort ,
		secondary_sort ,
		header_clause ,
		trailer_clause ,
		is_ri_at_risk_level ,
		is_auto_reinsured ,
		header_clause_id ,
		trailer_clause_id,
		accumulation_level,
		gis_screen_id,
		is_deferred_RI_permitted,
		claims_is_post_taxes,
		Display_reinsurance_screen,
		show_information_checklist,
		allow_add_ratingsection,
		allow_edit_ratingsection,
		allow_delete_ratingsection,
		allow_edit_ratingsection_ratetype,
		allow_edit_ratingsection_rate,
		allow_edit_ratingsection_suminsured,
		allow_edit_ratingsection_thispremium,
        	Display_Claims_reinsurance_screen,
			Claims_Cover_basis_ID ,
		Claims_type_basis_ID ,
		Attach_Claim_Outside_Of_Policy_Period,
		UserId,
		UniqueId,
		ScreenHierarchy)
	VALUES (
		@risk_type_id,
		@risk_folder_type_id,
		@caption_id,
		@code,
		@description,
		@effective_date,
		@is_deleted,
		@var_data_structure_id,
		@interface_object_name,
		@interface_class_name,
		@override_peril_ri_band,
		@override_peril_xl_band,
		@nb_premium_pro_rata_type_id,
		@mta_premium_pro_rata_type_id,
		@rn_premium_pro_rata_type_id,
		@is_share_with_co_insurers,
		@is_share_with_re_insurers,
		@is_suppress_public_text,
		@is_suppress_private_text,
		@is_suppress_taxes,
		@report_pointer,
		@section_mask,
		@stamp_duty_rate1,
		@stamp_duty_rate2,
		@primary_sort,
		@secondary_sort,
		@header_clause,
		@trailer_clause,
		1,
		@is_auto_reinsured,
		@header_clause_id,
		@trailer_clause_id,
		@accumulation_level,
		@gis_screen_id, 
		@is_deferred_RI_permitted,
		@claims_is_post_taxes,
		@Display_reinsurance_screen,		
		1,
		@allow_add_ratingsection,
		@allow_edit_ratingsection,
		@allow_delete_ratingsection,
		@allow_edit_ratingsection_ratetype,
		@allow_edit_ratingsection_rate,
		@allow_edit_ratingsection_suminsured,
		@allow_edit_ratingsection_thispremium,
        	@Display_Claims_reinsurance_screen,
				@Claims_Cover_basis_ID ,
		@Claims_type_basis_ID,
  		@bAttach_Claim_Outside_Of_Policy_Period,
		@UserId,
		@UniqueId,
		@ScreenHierarchy)
        
	SELECT Risk_Type_id = @Risk_Type_id

GO