SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_Event_Insurance_File_upd'
GO

CREATE PROCEDURE spe_Event_Insurance_File_upd
    @insurance_file_cnt int,
    @insurance_file_structure_id int,
    @insurance_file_type_id int,
    @insurance_file_status_id int,
    @insurance_file_id int,
    @source_id smallint,
    @insurance_folder_cnt int,
    @insurance_ref varchar(30),
    @product_id int,
    @lead_insurer_cnt int,
    @lead_agent_cnt int,
    @lead_agent_percent numeric(12,8),
    @account_handler_cnt int,
    @insured_cnt int,
    @business_type_id smallint,
    @collect_type_id smallint,
    @collection_from_cnt int,
    @branch_id smallint,
    @currency_id smallint,
    @language_id smallint,
    @date_issued datetime,
    @cover_start_date datetime,
    @expiry_date datetime,
    @renewal_date datetime,
    @renewal_method_id int,
    @renewal_frequency_id smallint,
    @is_referred_at_renewal tinyint,
    @lapsed_reason_id int,
    @lapsed_date datetime,
    @lapsed_description varchar(255),
    @is_referred_on_mta tinyint,
    @policy_version int,
    @gemini_policy_status int,
    @gemini_business_type int,
    @deferred_ind int,
    @policy_ignore int,
    @broker_cnt int,
    @risk_code_id int,
    @Analysis_code_id int,
    @proposal_date datetime,
    @diary_date datetime,
    @review_date datetime,
    @renewal_day_number int,
    @Policy_type_id int,
    @indicator char(1),
    @clause char(4),
    @cover char(1),
    @area char(1),
    @long_term_undertaking_date datetime,
    @renewal_stop_code_id int,
    @vbs_type char(2),
    @vbs_status char(1),
    @is_insurer_rate_table tinyint,
    @is_related_policies tinyint,
    @is_retained_documents tinyint,
    @schemes_postcode varchar(8),
    @paid_direct char(1),
    @scheme int,
    @brokerage_amount numeric(19,4),
    @is_minimum_brokerage_flag tinyint,
    @annual_premium numeric(19,4),
    @this_premium numeric(19,4),
    @net_premium numeric(19,4),
    @commission_amount numeric(19,4),
    @iptable_amount numeric(19,4),
    @ipt_percentage numeric(7,4),
    @is_ipt_overridden tinyint,
    @tax_amount numeric(19,4),
    @vatable_amount numeric(19,4),
    @vat_percentage numeric(7,4),
    @vat_amount numeric(19,4),
    @payment_method varchar(60),
    @user_defined_data_id int,
    @commission_percentage numeric(7,4),
    @invariant_key int,
    @insured_name varchar(100),
    @alternate_reference varchar(80),
    @is_client_invoiced tinyint,
    @old_policy_number varchar(30),
    @quote_expiry_date datetime,
    @alternate_account_cnt int,
    @account_executive_cnt int,
    @anniversary_date datetime,
    @policy_style_id int,
    @underwriting_year_id int,
    @policy_status_id int,
    @inception_date_tpi datetime,
    @fsa_customer_category_id smallint,
    @fsa_contract_location_id smallint,
    @fsa_underwriter_cnt int,
    @fsa_type_of_sale_id smallint,
    @fsa_renewal_consent tinyint,
    @base_currency_Id smallint,
    @country_id smallint,
    @discount_reason_id smallint,
    @discounted_premium numeric(19,4),
    @discount_percentage numeric(11,8),
    @match_discounted_premium_flag tinyint, 
    @put_on_next_instalment_renewal tinyint,
    @anniversary_copy tinyint,  
    @discount_recurring_type_id int = NULL,
    @lead_allow_consolidated_commission tinyint,
    @sub_allow_consolidated_commission tinyint,
    @terms_agreed bit,
    @terms_agreed_date datetime,
    @inception_date datetime,
    @policy_documents_issued_date datetime,
    @policy_documents_correct bit,
    @error_notification_date datetime,
    @risk_transfer_agreement bit,
    @renewal_premium numeric(19,4),  
	@risk_transfer_editable bit
   
AS
BEGIN

    UPDATE 
        Event_Insurance_File
    SET
        insurance_file_structure_id=@insurance_file_structure_id,
        insurance_file_type_id=@insurance_file_type_id,
        insurance_file_status_id=@insurance_file_status_id,
        insurance_file_id=@insurance_file_id,
        source_id=@source_id,
        insurance_folder_cnt=@insurance_folder_cnt,
        insurance_ref=@insurance_ref,
        product_id=@product_id,
        lead_insurer_cnt=@lead_insurer_cnt,
        lead_agent_cnt=@lead_agent_cnt,
        lead_agent_percent=@lead_agent_percent,
        account_handler_cnt=@account_handler_cnt,
        insured_cnt=@insured_cnt,
        business_type_id=@business_type_id,
        collect_type_id=@collect_type_id,
        collection_from_cnt=@collection_from_cnt,
        branch_id=@branch_id,
        currency_id=@currency_id,
        language_id=@language_id,
        date_issued=@date_issued,
        cover_start_date=@cover_start_date,
        expiry_date=@expiry_date,
        renewal_date=@renewal_date,
        renewal_method_id=@renewal_method_id,
        renewal_frequency_id=@renewal_frequency_id,
        is_referred_at_renewal=@is_referred_at_renewal,
        lapsed_reason_id=@lapsed_reason_id,
        lapsed_date=@lapsed_date,
        lapsed_description=@lapsed_description,
        is_referred_on_mta=@is_referred_on_mta,
        policy_version=@policy_version,
        gemini_policy_status=@gemini_policy_status,
        gemini_business_type=@gemini_business_type,
        deferred_ind=@deferred_ind,
        policy_ignore=@policy_ignore,
        broker_cnt=@broker_cnt,
        risk_code_id=@risk_code_id,
        Analysis_code_id=@Analysis_code_id,
        proposal_date=@proposal_date,
        diary_date=@diary_date,
        review_date=@review_date,
        renewal_day_number=@renewal_day_number,
        Policy_type_id=@Policy_type_id,
        indicator=@indicator,
        clause=@clause,
        cover=@cover,
        area=@area,
        long_term_undertaking_date=@long_term_undertaking_date,
        renewal_stop_code_id=@renewal_stop_code_id,
        vbs_type=@vbs_type,
        vbs_status=@vbs_status,
        is_insurer_rate_table=@is_insurer_rate_table,
        is_related_policies=@is_related_policies,
        is_retained_documents=@is_retained_documents,
        schemes_postcode=@schemes_postcode,
        paid_direct=@paid_direct,
        scheme=@scheme,
        brokerage_amount=@brokerage_amount,
        is_minimum_brokerage_flag=@is_minimum_brokerage_flag,
        annual_premium=@annual_premium,
        this_premium=@this_premium,
        net_premium=@net_premium,
        commission_amount=@commission_amount,
        iptable_amount=@iptable_amount,
        ipt_percentage=@ipt_percentage,
        is_ipt_overridden=@is_ipt_overridden,
        tax_amount=@tax_amount,
        vatable_amount=@vatable_amount,
        vat_percentage=@vat_percentage,
        vat_amount=@vat_amount,
        payment_method=@payment_method,
        user_defined_data_id=@user_defined_data_id,
        commission_percentage=@commission_percentage,
        invariant_key=@invariant_key,
        insured_name=@insured_name,
        alternate_reference=@alternate_reference,
        is_client_invoiced=@is_client_invoiced,
        old_policy_number=@old_policy_number,
        quote_expiry_date=@quote_expiry_date,
        alternate_account_cnt=@alternate_account_cnt,
        account_executive_cnt=@account_executive_cnt,
        anniversary_date=@anniversary_date,
        policy_style_id=@policy_style_id,
    underwriting_year_id=@underwriting_year_id,
    policy_status_id=@policy_status_id,
    inception_date_tpi=@inception_date_tpi,
        fsa_customer_category_id=@fsa_customer_category_id,
        fsa_contract_location_id=@fsa_contract_location_id,
        fsa_underwriter_cnt=@fsa_underwriter_cnt,
        fsa_type_of_sale_id=@fsa_type_of_sale_id,
        fsa_renewal_consent=@fsa_renewal_consent,
        base_currency_Id=@base_currency_Id,
        country_id=@country_id,
        discount_reason_id=@discount_reason_id,
        discounted_premium=@discounted_premium,
        discount_percentage=@discount_percentage,
        match_discounted_premium_flag=@match_discounted_premium_flag,
	put_on_next_instalment_renewal = @put_on_next_instalment_renewal,
	anniversary_copy  = @anniversary_copy,
        discount_recurring_type_id = @discount_recurring_type_id,
        @lead_allow_consolidated_commission=@lead_allow_consolidated_commission,
        @sub_allow_consolidated_commission=@sub_allow_consolidated_commission,
        terms_agreed=@terms_agreed,
        terms_agreed_date=@terms_agreed_date,
        inception_date=@inception_date,
        policy_documents_issued_date=@policy_documents_issued_date,
        policy_documents_correct=@policy_documents_correct,
        error_notification_date=@error_notification_date,
	risk_transfer_agreement=@risk_transfer_agreement,
        renewal_premium=@renewal_premium,  
		risk_transfer_editable =@risk_transfer_editable
    WHERE 
        insurance_file_cnt = @insurance_file_cnt

END

GO

