SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spe_PFPremiumFinance_addnew'
GO
CREATE PROCEDURE spe_PFPremiumFinance_addnew
    @FinancePlanCnt int OUTPUT,
    @FinancePlanVersion int OUTPUT,
    @ClientId int, 
    @CompanyNo int, 
    @SchemeNo int, 
    @SchemeVer int, 
    @StartDate datetime, 
    @EndDate datetime, 
    @CompanyName char(35), 
    @SchemeName char(20), 
    @ProductClass char(1), 
    @TransType char(1), 
    @AmtToFinance numeric(19,4),
    @APR numeric(7,4),
    @InterestRate numeric(19,4), 
    @DaysDelay int, 
    @NoOfInstallments int, 
    @FirstInstallment numeric(19,4),
    @OtherInstallments numeric(19,4),
    @CostOfProtection numeric(19,4), 
    @Deposit numeric(19,4), 
    @NetAmount numeric(19,4), 
    @TotalCost numeric(19,4), 
    @InterestCost numeric(19,4), 
    @MinFinanceCharge numeric(19,4), 
    @PayProtect char(1), 
    @ClientName char(30), 
    @ClientAddr1 char(25), 
    @ClientAddr2 char(25), 
    @ClientAddr3 char(20), 
    @ClientPCode char(8), 
    @ClientAddr4 char(20), 
    @StatusInd char(3), 
    @ClientCode char(12), 
    @SystemTag char(1), 
    @AutoGenPlanRef char(20), 
    @FinCollPlanRef char(20), 
    @InterestFree char(1),
    @IsQuote tinyint, 
    @IsParentPlan tinyint, 
    @Parent_Finance_cnt int, 
    @Parent_Finance_version int, 
    @PlanTransaction_id int,
    @InsuranceFileCnt int
AS
    /* Generate the cnt value here to reduce likelihood of duplicates */
    SELECT @FinancePlanCnt = NEXT VALUE FOR SEQ_PremiumFinanceCnt 
    SET @FinancePlanVersion = 1  

    /* Insert new record */
    INSERT INTO PFPremiumFinance
       (pfprem_finance_cnt, pfPrem_finance_version, clientid, companyno, schemeno, schemeversion,
        startdate, enddate, companyname, schemename, productclass, transtype, amounttofinance, 
        apr, interestrate, daysdelay, noofInstallments, firstInstallment, othInstallments,    
        costofprotection, deposit, netamount, totalcost, interestcost, minfinancechrge, payprotection, 
        clientname, clientaddr1, clientaddr2, clientaddr3, clientpcode, clientaddr4,
        statusind, clientcode, systemtag, autogeneratedplanref, financecollatedplanref, interestfree,
        isquote, isparentplan, parent_finance_cnt, parent_finance_version, plantransaction_id, Insurance_File_Cnt)
    VALUES
       (@FinancePlanCnt, @FinancePlanVersion, @ClientId, @CompanyNo, @SchemeNo, @SchemeVer, 
        @StartDate, @EndDate, @CompanyName, @SchemeName, @ProductClass, @TransType, @AmtToFinance, 
        @APR, @InterestRate, @DaysDelay, @NoOfInstallments, @FirstInstallment, @OtherInstallments,
        @CostOfProtection, @Deposit, @NetAmount, @TotalCost, @InterestCost, @MinFinanceCharge, @PayProtect, 
        @ClientName, @ClientAddr1, @ClientAddr2, @ClientAddr3, @ClientPCode, @ClientAddr4, 
        @StatusInd, @ClientCode, @SystemTag, @AutoGenPlanRef, @FinCollPlanRef, @InterestFree,
        @IsQuote, @IsParentPlan, @Parent_Finance_cnt, @Parent_Finance_version, @PlanTransaction_id, @InsuranceFileCnt)


GO
SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS ON
GO

