
Execute DDLDropProcedure 'spe_Insurance_File_Add'
GO
CREATE PROCEDURE spe_Insurance_File_Add @insurance_file_cnt                 INT OUTPUT,
                                        @insurance_file_structure_id        INT,
                                        @insurance_file_type_id             INT,
                                        @insurance_file_status_id           INT,
                                        @insurance_file_id                  INT,
                                        @source_id                          SMALLINT,
                                        @insurance_folder_cnt               INT,
                                        @insurance_ref                      VARCHAR(30),
                                        @product_id                         INT,
                                        @lead_insurer_cnt                   INT,
                                        @lead_agent_cnt                     INT,
                                        @lead_agent_percent                 NUMERIC(12, 8),
                                        @account_handler_cnt                INT,
                                        @insured_cnt                        INT,
                                        @business_type_id                   SMALLINT,
                                        @collect_type_id                    SMALLINT,
                                        @collection_from_cnt                INT,
                                        @branch_id                          SMALLINT,
                                        @currency_id                        SMALLINT,
                                        @language_id                        SMALLINT,
                                        @date_issued                        DATETIME,
                                        @cover_start_date                   DATETIME,
                                        @expiry_date                        DATETIME,
                                        @renewal_date                       DATETIME,
                                        @renewal_method_id                  INT,
                                        @renewal_frequency_id               SMALLINT,
                                        @is_referred_at_renewal             TINYINT,
                                        @lapsed_reason_id                   INT,
                                        @lapsed_date                        DATETIME,
                                        @lapsed_description                 VARCHAR(255),
                                        @is_referred_on_mta                 TINYINT,
                                        @policy_version                     INT,
                                        @gemini_policy_status               INT,
                                        @gemini_business_type               INT,
                                        @deferred_ind                       INT,
                                        @policy_ignore                      INT,
                                        @broker_cnt                         INT,
                                        @risk_code_id                       INT,
                                        @Analysis_code_id                   INT,
                                        @proposal_date                      DATETIME,
                                        @diary_date                         DATETIME,
                                        @review_date                        DATETIME,
                                        @renewal_day_number                 INT,
                                        @Policy_type_id                     INT,
                                        @indicator                          CHAR(1),
                                        @clause                             CHAR(4),
                                        @cover                              CHAR(1),
                                        @area                               CHAR(1),
                                        @long_term_undertaking_date         DATETIME,
                                        @renewal_stop_code_id               INT,
                                        @vbs_type                           CHAR(2),
                                        @vbs_status                         CHAR(1),
                                        @is_insurer_rate_table              TINYINT,
                                        @is_related_policies                TINYINT,
                                        @is_retained_documents              TINYINT,
                                        @schemes_postcode                   VARCHAR(8),
                                        @paid_direct                        CHAR(1),
                                        @scheme                             INT,
                                        @brokerage_amount                   NUMERIC(19, 4),
                                        @is_minimum_brokerage_flag          TINYINT,
                                        @annual_premium                     NUMERIC(19, 4),
                                        @this_premium                       NUMERIC(19, 4),
                                        @net_premium                        NUMERIC(19, 4),
                                        @commission_amount                  NUMERIC(19, 4),
                                        @iptable_amount                     NUMERIC(19, 4),
                                        @ipt_percentage                     NUMERIC(7, 4),
                                        @is_ipt_overridden                  TINYINT,
                                        @tax_amount                         NUMERIC(19, 4),
                                        @vatable_amount                     NUMERIC(19, 4),
                                        @vat_percentage                     NUMERIC(7, 4),
                                        @vat_amount                         NUMERIC(19, 4),
                                        @payment_method                     VARCHAR(60),
                                        @user_defined_data_id               INT,
                                        @commission_percentage              NUMERIC(7, 4),
                                        @invariant_key                      INT,
                                        @insured_name                       VARCHAR(255),
                                        @alternate_reference                VARCHAR(80),
                                        @is_client_invoiced                 TINYINT,
                                        @old_policy_number                  VARCHAR(30),
                                        @quote_expiry_date                  DATETIME,
                                        @alternate_account_cnt              INT,
                                        @account_executive_cnt              INT = NULL,
                                        @anniversary_date                   DATETIME,
                                        @policy_style_id                    INT,
                                        @underwriting_year_id               INT,
                                        @policy_status_id                   INT,
                                        @inception_date_tpi                 DATETIME,
                                        @fsa_customer_category_id           SMALLINT,
                                        @fsa_contract_location_id           SMALLINT,
                                        @fsa_underwriter_cnt                INT,
                                        @fsa_type_of_sale_id                SMALLINT,
                                        @fsa_renewal_consent                TINYINT,
                                        @base_currency_Id                   SMALLINT,
                                        @country_id                         SMALLINT,
                                        @discount_reason_id                 SMALLINT,
                                        @discounted_premium                 NUMERIC(19, 4),
                                        @discount_percentage                NUMERIC(11, 8),
                                        @match_discounted_premium_flag      TINYINT,
                                        @put_on_next_instalment_renewal     INT,
                                        @anniversary_copy                   INT,
                                        @discount_recurring_type_id         INT = NULL,
                                        @lead_allow_consolidated_commission TINYINT,
                                        @sub_allow_consolidated_commission  TINYINT,
                                        @terms_agreed                       BIT,
                                        @terms_agreed_date                  DATETIME,
                                        @inception_date                     DATETIME,
                                        @policy_documents_issued_date       DATETIME,
                                        @policy_documents_correct           BIT,
                                        @error_notification_date            DATETIME,
                                        @policy_deductibles_id              INT,
                                        @policy_limits_id                   INT,
                                        @risk_transfer_agreement            BIT,
                                        @renewal_premium                    NUMERIC(19, 4),
                                        @renewal_product_id                 INT = NULL,
                                        @original_product_id                INT = NULL,
                                        @risk_transfer_editable             BIT,
                                        @manual_discount_percentage         NUMERIC(11, 8)=NULL,
                                        @base_insurance_folder_cnt          INT = NULL,
                                        @quote_version                      INT = NULL,
                                        @quote_status_id                    INT = NULL,
                                        @Contact_user_id                    INT =NULL,
                                        @MTA_reason_id                      SMALLINT =NULL,
                                        @bIs_Marketplace_Policy             TINYINT = 0,
									    @nCollectionFrequency_id INT = NULL,
										@nDOPaymentTerms_id INT = NULL,
										@coins_placement varchar(10)= NULL    ,										
										@Correspondence_Type	INT = NULL,
										@Default_Preferred_Correspondence	INT = NULL,
										@Is_Agent_Correspondence TINYINT = 0,
										@Sender_Email						VARCHAR(255) = NULL,
										@Receiver_Email						VARCHAR(255) = NULL,
										@original_insurance_file_type_id	INT = NULL
AS  
BEGIN  
IF ISNULL(@source_id, 0) = 0  
    SELECT @source_id = 1  

IF ISNULL(@branch_id, 0) = 0  
        EXEC SPU_SUB_BRANCH_DEFAULT
          @source_id,
          @branch_id OUTPUT
  
      IF ISNULL(@quote_version, 0) = 0
BEGIN  
 SELECT @quote_version = 1  
END  
  
      IF ISNULL(@quote_status_id, 0) = 0
BEGIN  
 SELECT @quote_status_id = 1  
END  
  
      IF ISNULL(@base_insurance_folder_cnt, 0) = 0
BEGIN  
 SELECT @base_insurance_folder_cnt = @insurance_folder_cnt  
END  
  
      SELECT @quote_status_id = CASE
                                  WHEN ISNULL(@lead_agent_cnt, 0) <> 0
                                       AND @insurance_file_type_id = 1 THEN 2
                                  ELSE 1
 END  
  
IF @Contact_user_id = 0  
        BEGIN
            SELECT @Contact_user_id = NULL
        END
  
      SELECT @Insurance_File_id = 1  
  
INSERT INTO Insurance_File  
                  (insurance_file_structure_id,
    insurance_file_type_id,  
    insurance_file_status_id,  
    insurance_file_id,  
    source_id,  
    insurance_folder_cnt,  
    insurance_ref,  
    product_id,  
    lead_insurer_cnt,  
    lead_agent_cnt,  
    lead_agent_percent,  
    account_handler_cnt,  
    insured_cnt,  
    business_type_id,  
    collect_type_id,  
    collection_from_cnt,  
    branch_id,  
    currency_id,  
    language_id,  
    date_issued,  
    cover_start_date,  
    expiry_date,  
    renewal_date,  
    renewal_method_id,  
    renewal_frequency_id,  
    is_referred_at_renewal,  
    lapsed_reason_id,  
    lapsed_date,  
    lapsed_description,  
    is_referred_on_mta,  
    policy_version,  
    gemini_policy_status,  
    gemini_business_type,  
    deferred_ind,  
    policy_ignore,  
    broker_cnt,  
    risk_code_id,  
    Analysis_code_id,  
    proposal_date,  
    diary_date,  
    review_date,  
    renewal_day_number,  
    Policy_type_id,  
    indicator,  
    clause,  
    cover,  
    area,  
    long_term_undertaking_date,  
    renewal_stop_code_id,  
    vbs_type,  
    vbs_status,  
    is_insurer_rate_table,  
    is_related_policies,  
    is_retained_documents,  
    schemes_postcode,  
    paid_direct,  
    scheme,  
    brokerage_amount,  
    is_minimum_brokerage_flag,  
    annual_premium,  
    this_premium,  
    net_premium,  
    commission_amount,  
    iptable_amount,  
    ipt_percentage,  
    is_ipt_overridden,  
    tax_amount,  
    vatable_amount,  
    vat_percentage,  
    vat_amount,  
    payment_method,  
    user_defined_data_id,  
    commission_percentage,  
    invariant_key,  
    insured_name,  
    alternate_reference,  
    is_client_invoiced,  
    old_policy_number,  
    quote_expiry_date,  
    alternate_account_cnt,  
    account_executive_cnt,  
    anniversary_date,  
    policy_style_id,  
    underwriting_year_id,  
    policy_status_id,  
    inception_date_tpi,  
    fsa_customer_category_id,  
    fsa_contract_location_id,  
    fsa_underwriter_cnt,  
    fsa_type_of_sale_id,  
    fsa_renewal_consent,  
    base_currency_Id,  
    country_id,  
    discount_reason_id,  
    discounted_premium,  
    discount_percentage,  
    match_discounted_premium_flag,  
    put_on_next_instalment_renewal,  
                   anniversary_copy,
    discount_recurring_type_id,  
    lead_allow_consolidated_commission,  
    sub_allow_consolidated_commission,  
    terms_agreed,  
    terms_agreed_date,  
    inception_date,  
    policy_documents_issued_date,  
    policy_documents_correct,  
    error_notification_date,  
    policy_deductibles_id,  
    policy_limits_id,  
    risk_transfer_agreement,  
    renewal_premium,  
    renewal_product_id,  
    original_product_id,  
    risk_transfer_editable,  
    manual_discount_percentage,  
    base_insurance_folder_cnt,  
    quote_version,  
    quote_status_id,  
    Contact_user_id,
                   MTA_reason_id,
                   is_marketplace_policy,
				   CollectionFrequency_id,
	               DOPaymentTerms_id,                   
				   coins_placement,
				   system_base_date,                   			   
				   Correspondence_Type,
				   Default_Preferred_Correspondence,
				   Is_Agent_Correspondence,
				   Sender_Email,
				   Receiver_Email,
				   original_insurance_file_type_id)
      VALUES      ( @insurance_file_structure_id,
    @insurance_file_type_id,  
    @insurance_file_status_id,  
    @insurance_file_id,  
    @source_id,  
    @insurance_folder_cnt,  
    @insurance_ref,  
    @product_id,  
    @lead_insurer_cnt,  
    @lead_agent_cnt,  
    @lead_agent_percent,  
    @account_handler_cnt,  
    @insured_cnt,  
    @business_type_id,  
    @collect_type_id,  
    @collection_from_cnt,  
    @branch_id,  
    @currency_id,  
    @language_id,  
    @date_issued,  
    @cover_start_date,  
    @expiry_date,  
    @renewal_date,  
    @renewal_method_id,  
    @renewal_frequency_id,  
    @is_referred_at_renewal,  
    @lapsed_reason_id,  
    @lapsed_date,  
    @lapsed_description,  
    @is_referred_on_mta,  
    @policy_version,  
    @gemini_policy_status,  
    @gemini_business_type,  
    @deferred_ind,  
    @policy_ignore,  
    @broker_cnt,  
    @risk_code_id,  
    @Analysis_code_id,  
    @proposal_date,  
    @diary_date,  
    @review_date,  
    @renewal_day_number,  
    @Policy_type_id,  
    @indicator,  
    @clause,  
    @cover,  
    @area,  
    @long_term_undertaking_date,  
    @renewal_stop_code_id,  
    @vbs_type,  
    @vbs_status,  
    @is_insurer_rate_table,  
    @is_related_policies,  
    @is_retained_documents,  
    @schemes_postcode,  
    @paid_direct,  
    @scheme,  
    @brokerage_amount,  
    @is_minimum_brokerage_flag,  
    @annual_premium,  
    @this_premium,  
    @net_premium,  
    @commission_amount,  
    @iptable_amount,  
    @ipt_percentage,  
    @is_ipt_overridden,  
    @tax_amount,  
    @vatable_amount,  
    @vat_percentage,  
    @vat_amount,  
    @payment_method,  
    @user_defined_data_id,  
    @commission_percentage,  
    @invariant_key,  
    @insured_name,  
    @alternate_reference,  
    @is_client_invoiced,  
    @old_policy_number,  
    @quote_expiry_date,  
    @alternate_account_cnt,  
    @account_executive_cnt,  
    @anniversary_date,  
    @policy_style_id,  
    @underwriting_year_id,  
    @policy_status_id,  
    @inception_date_tpi,  
    @fsa_customer_category_id,  
    @fsa_contract_location_id,  
    @fsa_underwriter_cnt,  
    @fsa_type_of_sale_id,  
    @fsa_renewal_consent,  
    @base_currency_Id,  
    @country_id,  
    @discount_reason_id,  
    @discounted_premium,  
    @discount_percentage,  
    @match_discounted_premium_flag,  
    @put_on_next_instalment_renewal,  
    @anniversary_copy,  
    @discount_recurring_type_id,  
    @lead_allow_consolidated_commission,  
    @sub_allow_consolidated_commission,  
    @terms_agreed,  
    @terms_agreed_date,  
    @inception_date,  
    @policy_documents_issued_date,  
    @policy_documents_correct,  
    @error_notification_date,  
    @policy_deductibles_id,  
    @policy_limits_id,  
    @risk_transfer_agreement,  
    @renewal_premium,  
    @renewal_product_id,  
    @original_product_id,  
    @risk_transfer_editable,  
    @manual_discount_percentage,  
    @base_insurance_folder_cnt,  
    @quote_version,  
    @quote_status_id,  
    @Contact_user_id,
    @MTA_reason_id,
    @bIs_Marketplace_Policy,
	@nCollectionFrequency_id,
	@nDOPaymentTerms_id,
	@coins_placement,
	getdate(),                   
	@Correspondence_Type,
	@Default_Preferred_Correspondence,
	@Is_Agent_Correspondence,
	@Sender_Email,
	@Receiver_Email,
	@original_insurance_file_type_id)
END  
BEGIN  
SELECT @insurance_file_cnt = @@IDENTITY  
END  
