SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
Execute DDLDropProcedure 'spe_Party_Agent_add'
GO

CREATE PROCEDURE spe_Party_Agent_add    
    @party_cnt int,    
    @party_agent_type_id int,    
    @party_agent_origin_id int,    
    @agency_agreement_date datetime,    
    @agency_next_review_date datetime,    
    @agency_account_number varchar(255),    
    @is_branch tinyint,    
    @is_head_office tinyint,    
    @default_commission_percent numeric(19,4),    
    @trading_name varchar(255),    
    @binder_indicator int,    
    @report_indicator int,    
    @linked_account_executive_id int,    
    @linked_account_group int,    
    @payment_method int,    
    @payment_frequency int,    
    @address_on_notice int,    
    @type_of_statement int,    
    @source int,    
    @title varchar(70),    
    @multipac tinyint,    
    @contact_person varchar(255),    
    @first_name varchar(255),    
    @bank_account varchar(30) = NULL,    
    @date_cancelled datetime,    
    @agent_status_id int,    
    @fsa_registration_number varchar(255),    
    @broker_abi_id varchar(20),    
    @expense_account_id int,    
    @is_in_transfer_mode tinyint,    
    @transfer_to_business_type_id smallint,    
    @transfer_to_party_cnt int,    
    @use_override_commission_rate tinyint,    
    @domiciled_for_tax tinyint,    
    @allow_consolidated_commission tinyint,    
    @can_make_live_invoice tinyint,    
    @can_make_live_instalments tinyint,    
    @can_make_live_paynow tinyint,    
    @is_standard_account tinyint,    
    @is_float_balance_account tinyint,    
    @is_overdraft_account tinyint,    
    @is_prepayment_account tinyint,    
    @expected_daily_premium money,    
    @days_allowed smallint,    
    @float_balance_limit money,    
    @overdraft_limit money,    
    @overdraft_expiry datetime,    
    @alternate_reference_mandatory tinyint,    
    @alternate_reference_for_each_transaction tinyint,  --(RC) QBENZ014    
    @commission_posting_type int,  --(RC) PLICO 9-10    
    @is_single_instalment_plan tinyint= NULL,    
    @common_renewal_date datetime=NULL,    
    @produce_agent_renewal_list tinyint=NULL,    
    @can_make_live_bankguarantee int = 0,  --(RC) PLICO 9-10    
 @can_make_live_cashdeposit tinyint =0, --Sankar - (UIIC_WPR85_Cash_Deposit_Process) - Paralleling    
 @commission_level_id int = NULL,    
    @is_gross_agent tinyint =0,    
    @bankaccount_id int =Null,    
 @receives_client_correspondence TINYINT=0,
 @user_id int,
 @unique_id varchar(50),
 @screen_hierarchy varchar(500),
 @use_override_commission_renewal tinyint=0
AS    
BEGIN    
INSERT INTO Party_Agent (    
    party_cnt ,    
    party_agent_type_id,    
    party_agent_origin_id ,    
    agency_agreement_date ,    
    agency_next_review_date ,    
    agency_account_number ,    
    is_branch ,    
    is_head_office ,    
    default_commission_percent,    
    trading_name,    
    binder_indicator,    
    report_indicator,    
    linked_account_executive_id,    
    linked_account_group,    
    payment_method,    
    payment_frequency,    
    address_on_notice,    
    type_of_statement,    
    source,    
    title,    
    multipac,    
    contact_person,    
    first_name,    
    bank_account,    
    date_cancelled,    
    agent_status_id,    
    fsa_registration_number,    
    broker_abi_id,    
    expense_account_id,    
    is_in_transfer_mode,    
    transfer_to_business_type_id,    
    transfer_to_party_cnt,    
    use_override_commission_rate,    
    domiciled_for_tax,    
    allow_consolidated_commission,    
    can_make_live_invoice,    
    can_make_live_instalments,    
    can_make_live_paynow,    
    is_standard_account,    
    is_float_balance_account,    
    is_overdraft_account,    
    is_prepayment_account,    
    expected_daily_premium,    
    days_allowed,    
    float_balance_limit,    
    overdraft_limit,    
    overdraft_expiry,    
    alternate_reference_mandatory,    
    alternate_reference_for_each_transaction, --(RC) QBENZ014    
    commission_posting_type_id,  --(RC) PLICO 9-10    
    is_single_instalment_plan,    
    common_renewal_date,    
    produce_agent_renewal_list,    
    can_make_live_bankguarantee,    
 can_make_live_cashdeposit ,--Sankar - (UIIC_WPR85_Cash_Deposit_Process) - Paralleling    
    commission_level_id,    
    is_gross_agent,    
    bankaccount_id,    
 Receives_Client_Correspondence,
 UserId,
 UniqueId,
 ScreenHierarchy,
 use_override_commission_renewal
    )    
VALUES (    
    @party_cnt,    
    @party_agent_type_id,    
    @party_agent_origin_id,    
    @agency_agreement_date,    
    @agency_next_review_date,    
    @agency_account_number,    
    @is_branch,    
    @is_head_office,    
    @default_commission_percent,    
    @trading_name,    
    @binder_indicator,    
    @report_indicator,    
    @linked_account_executive_id,    
    @linked_account_group,    
    @payment_method,    
    @payment_frequency,    
    @address_on_notice,    
    @type_of_statement,    
    @source,    
    @title,    
    @multipac,    
    @contact_person,    
    @first_name,    
    @bank_account,    
    @date_cancelled,    
    @agent_status_id,    
    @fsa_registration_number,    
    @broker_abi_id,    
    @expense_account_id,    
    @is_in_transfer_mode,    
    @transfer_to_business_type_id,    
    @transfer_to_party_cnt,    
    @use_override_commission_rate,    
    @domiciled_for_tax,    
    @allow_consolidated_commission,    
    @can_make_live_invoice,    
    @can_make_live_instalments,    
    @can_make_live_paynow,    
    @is_standard_account,    
    @is_float_balance_account,    
    @is_overdraft_account,    
    @is_prepayment_account,    
    @expected_daily_premium,    
    @days_allowed,    
    @float_balance_limit,    
    @overdraft_limit,    
    @overdraft_expiry,    
    @alternate_reference_mandatory,    
    @alternate_reference_for_each_transaction, --(RC) QBENZ014    
    @commission_posting_type, --(RC) PLICO 9-10    
    @is_single_instalment_plan,    
    @common_renewal_date,    
    @produce_agent_renewal_list,    
    @can_make_live_bankguarantee,    
 @can_make_live_cashdeposit, --Sankar - (UIIC_WPR85_Cash_Deposit_Process) - Paralleling    
 @commission_level_id,    
    @is_gross_agent,    
    @bankaccount_id,    
 @receives_client_correspondence,
 @user_id,
 @unique_id,
 @screen_hierarchy,
 @use_override_commission_renewal
    )    
END 


GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
