<Serializable()> Public Class FinancePlanDetails
    Private PFBankDetailsField As PFBankDetails
    Private nPFPremiumFinanceKeyField As Integer
    Private nPFPremiumFinanceVersionKeyField As Integer
    Private sPFSchemeNameField As String
    Private dtStartDateField As Date
    Private dtEndDateField As Date
    Private sProductClassField As String
    Private sTransTypeField As String
    Private dFinanceAmountField As Double
    Private dAPRField As Double
    Private dInterestRateField As Double
    Private dDaysDelayField As Integer
    Private nNoofInstallmentsField As Integer
    Private dFirstInstallmentField As Double
    Private dOtherInstallmentsField As Double
    Private dCostOfProtectionField As Double
    Private dDepositField As Double
    Private nNetAmountField As Double
    Private dTotalCostField As Double
    Private dInterestCostField As Double
    Private dMinFinanceChrgeField As Double
    Private sPayProtectionField As String
    Private bPaymentProtectionField As Boolean
    Private sClientNameField As String
    Private sClientAddress1Field As String
    Private sClientAddress2Field As String
    Private sClientAddress3Field As String
    Private sClientAddress4Field As String
    Private sClientTownField As String
    Private sClientPcodeField As String
    Private sClientCountryField As String
    Private sClientAreaCodeField As String
    Private sClientPhoneNoField As String
    Private sClientExtensionField As String
    Private sClientFaxAreaCodeField As String
    Private sClientFaxNoField As String
    Private sBankNameField As String
    Private sBankSortCodeField As String
    Private sBankAccountNoField As String
    Private sBankAccountNameField As String
    Private sBankBranchField As String
    Private sBankAddress1Field As String
    Private sBankAddress2Field As String
    Private sBankAddress3Field As String
    Private sBankTownField As String
    Private sBankRegionField As String
    Private sBankPostCodeField As String
    Private sBankCountryField As String
    Private sBankAreaCodeField As String
    Private sBankPhoneNoField As String
    Private sBankExtensionField As String
    Private sBankFaxAreaCodeField As String
    Private sBankFaxNoField As String
    Private sCardHolderNameField As String
    Private sStatusIndField As FinancePlanStatus
    Private sClientCodeField As String
    Private sAutoGeneratedPlanRefField As String
    Private sFinanceCollatedPlanRefField As String
    Private sInterestFreeField As String
    Private bIsQuoteField As Boolean
    Private nPlanTransactionKeyField As Integer
    Private nInsuranceFileKeyField As Integer
    Private nPFRFKEYField As Integer
    Private sPFFrequencyCodeField As String
    Private nBankCountryKeyField As Integer
    Private nClientCountryKeyField As Integer
    Private sDepositCCTrackingNumber As String
    Private dtFirstInstalmentDateField As Date
    Private dtNextInstalmentDateField As Date
    Private dtLastInstalmentDateField As Date
    Private dTaxCostField As Double
    Private sMediaTypeCodeField As String
    Private sCCNumberField As String
    Private sCCExpiryDateField As String
    Private sCCStartDateField As String
    Private sCCIssueField As String
    Private sCCPinField As String
    Private sMediaTypeValidationCodeField As String
    Private bBankNameMandatory As Boolean
    Private bIsBankAddressMandatoryField As Boolean
    Private bIsBranchNameMandatoryField As Boolean
    Private bIsBranchCodeMandatoryField As Boolean
    Private nCommissionTransdetailKeyField As Integer
    Private sPFFrequencyPeriodField As String
    Private nPFFrequencyAmountField As Integer
    Private nPFFrequencyKeyField As Integer
    Private nSourceKeyField As Integer
    Private nProductKeyField As Integer
    Private sPFSchemeTypeCodeField As String
    Private dFinanceFeeField As Double
    Private nDayOfWeekOrMonthField As Integer
    Private sPaymentMethodField As String
    Private sPFFrequencyDescField As String
    Private sSchemePrintTypeField As String
    Private dOriginalAmountField As Double
    Private dLastInstalmentField As Double
    Private nClaimDebtIdField As Integer
    Private dtDateCreatedField As Date
    Private dtDateModifiedField As Date
    Private dtDateConfirmedField As Date
    Private dtDateReviewField As Date
    Private bIsViaThirdPartyField As Boolean
    Private bIsDepositAsInstalmentField As Boolean
    Private sPFRFMnemonicField As String
    Private dtCoverStartDateField As Date
    Private dtExpiryDateField As Date
    Private nTermsField As Integer
    Private dOriginalRateField As Double
    Private bIsCardHolderField As Boolean
    Private sCardHolderAddress1Field As String
    Private sCardHolderAddress2Field As String
    Private sCardHolderAddress3Field As String
    Private sCardHolderAddress4Field As String
    Private sCardHolderPostCodeField As String
    Private sCardTypeField As String
    Private bIsProviderCollectDepositField As Boolean
    Private dtDateBankDetailsChangedField As Date
    Private bIsDDCancelledField As Boolean
    Private bIsCCCancelledField As Boolean
    Private bIsPaperlessDDField As Boolean
    Private sSchemeTypeField As String
    Private sSchemeCodeField As String
    Private dSettlementAmount As Double
    Private nPartyBankKeyField As Integer
    Private sPFPremiumFinanceCancelReasonField As String
    Private bIsCancelPolicyRunField As Boolean
    Private bIsFinanceNetCommissionField As Boolean
    Private bIsDepositOnOtherMediaTypeField As Boolean
    Private dtPreferredDateField As Date
    Private dOverrideInterestRateField As Double
    Private nSelectedSchemeNoField As Integer
    Private nSelectedSchemeVersionField As Integer
    Private bOverrideCommission As Boolean
    Private sProcessPFMode As String
    Private sAuthCode As String

    Public Property PFBankDetails() As PFBankDetails
        Get
            Return Me.PFBankDetailsField
        End Get
        Set(ByVal value As PFBankDetails)
            Me.PFBankDetailsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFPremiumFinanceKey() As Integer
        Get
            Return Me.nPFPremiumFinanceKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nPFPremiumFinanceKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFPremiumFinanceVersionKey() As Integer
        Get
            Return Me.nPFPremiumFinanceVersionKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nPFPremiumFinanceVersionKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFSchemeName() As String
        Get
            Return Me.sPFSchemeNameField
        End Get
        Set(ByVal value As String)
            Me.sPFSchemeNameField = value
        End Set
    End Property

    '''<remarks/>

    Public Property StartDate() As Date
        Get
            Return Me.dtStartDateField
        End Get
        Set(ByVal value As Date)
            Me.dtStartDateField = value
        End Set
    End Property

    '''<remarks/>

    Public Property EndDate() As Date
        Get
            Return Me.dtEndDateField
        End Get
        Set(ByVal value As Date)
            Me.dtEndDateField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ProductClass() As String
        Get
            Return Me.sProductClassField
        End Get
        Set(ByVal value As String)
            Me.sProductClassField = value
        End Set
    End Property

    '''<remarks/>
    Public Property TransType() As String
        Get
            Return Me.sTransTypeField
        End Get
        Set(ByVal value As String)
            Me.sTransTypeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property FinanceAmount() As Double
        Get
            Return Me.dFinanceAmountField
        End Get
        Set(ByVal value As Double)
            Me.dFinanceAmountField = value
        End Set
    End Property

    '''<remarks/>
    Public Property APR() As Double
        Get
            Return Me.dAPRField
        End Get
        Set(ByVal value As Double)
            Me.dAPRField = value
        End Set
    End Property

    '''<remarks/>
    Public Property InterestRate() As Double
        Get
            Return Me.dInterestRateField
        End Get
        Set(ByVal value As Double)
            Me.dInterestRateField = value
        End Set
    End Property

    '''<remarks/>
    Public Property DaysDelay() As Integer
        Get
            Return Me.dDaysDelayField
        End Get
        Set(ByVal value As Integer)
            Me.dDaysDelayField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NoOfInstallments() As Integer
        Get
            Return Me.nNoofInstallmentsField
        End Get
        Set(ByVal value As Integer)
            Me.nNoofInstallmentsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property FirstInstallment() As Double
        Get
            Return Me.dFirstInstallmentField
        End Get
        Set(ByVal value As Double)
            Me.dFirstInstallmentField = value
        End Set
    End Property

    '''<remarks/>
    Public Property OtherInstallments() As Double
        Get
            Return Me.dOtherInstallmentsField
        End Get
        Set(ByVal value As Double)
            Me.dOtherInstallmentsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CostOfProtection() As Double
        Get
            Return Me.dCostOfProtectionField
        End Get
        Set(ByVal value As Double)
            Me.dCostOfProtectionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Deposit() As Double
        Get
            Return Me.dDepositField
        End Get
        Set(ByVal value As Double)
            Me.dDepositField = value
        End Set
    End Property

    '''<remarks/>
    Public Property NetAmount() As Double
        Get
            Return Me.nNetAmountField
        End Get
        Set(ByVal value As Double)
            Me.nNetAmountField = value
        End Set
    End Property


    '''<remarks/>
    Public Property TotalCost() As Double
        Get
            Return Me.dTotalCostField
        End Get
        Set(ByVal value As Double)
            Me.dTotalCostField = value
        End Set
    End Property

    '''<remarks/>
    Public Property InterestCost() As Double
        Get
            Return Me.dInterestCostField
        End Get
        Set(ByVal value As Double)
            Me.dInterestCostField = value
        End Set
    End Property

    '''<remarks/>
    Public Property MinFinanceChrge() As Double
        Get
            Return Me.dMinFinanceChrgeField
        End Get
        Set(ByVal value As Double)
            Me.dMinFinanceChrgeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PayProtection() As String
        Get
            Return Me.sPayProtectionField
        End Get
        Set(ByVal value As String)
            Me.sPayProtectionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PaymentProtection() As Boolean
        Get
            Return Me.bPaymentProtectionField
        End Get
        Set(ByVal value As Boolean)
            Me.bPaymentProtectionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientName() As String
        Get
            Return Me.sClientNameField
        End Get
        Set(ByVal value As String)
            Me.sClientNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientAddress1() As String
        Get
            Return Me.sClientAddress1Field
        End Get
        Set(ByVal value As String)
            Me.sClientAddress1Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientAddress2() As String
        Get
            Return Me.sClientAddress2Field
        End Get
        Set(ByVal value As String)
            Me.sClientAddress2Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientAddress3() As String
        Get
            Return Me.sClientAddress3Field
        End Get
        Set(ByVal value As String)
            Me.sClientAddress3Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientAddress4() As String
        Get
            Return Me.sClientAddress4Field
        End Get
        Set(ByVal value As String)
            Me.sClientAddress4Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientTown() As String
        Get
            Return Me.sClientTownField
        End Get
        Set(ByVal value As String)
            Me.sClientTownField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientPcode() As String
        Get
            Return Me.sClientPcodeField
        End Get
        Set(ByVal value As String)
            Me.sClientPcodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientCountry() As String
        Get
            Return Me.sClientCountryField
        End Get
        Set(ByVal value As String)
            Me.sClientCountryField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientAreaCode() As String
        Get
            Return Me.sClientAreaCodeField
        End Get
        Set(ByVal value As String)
            Me.sClientAreaCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientPhoneNo() As String
        Get
            Return Me.sClientPhoneNoField
        End Get
        Set(ByVal value As String)
            Me.sClientPhoneNoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientExtension() As String
        Get
            Return Me.sClientExtensionField
        End Get
        Set(ByVal value As String)
            Me.sClientExtensionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientFaxAreaCode() As String
        Get
            Return Me.sClientFaxAreaCodeField
        End Get
        Set(ByVal value As String)
            Me.sClientFaxAreaCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientFaxNo() As String
        Get
            Return Me.sClientFaxNoField
        End Get
        Set(ByVal value As String)
            Me.sClientFaxNoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankName() As String
        Get
            Return Me.sBankNameField
        End Get
        Set(ByVal value As String)
            Me.sBankNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankSortCode() As String
        Get
            Return Me.sBankSortCodeField
        End Get
        Set(ByVal value As String)
            Me.sBankSortCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAccountNo() As String
        Get
            Return Me.sBankAccountNoField
        End Get
        Set(ByVal value As String)
            Me.sBankAccountNoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAccountName() As String
        Get
            Return Me.sBankAccountNameField
        End Get
        Set(ByVal value As String)
            Me.sBankAccountNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankBranch() As String
        Get
            Return Me.sBankBranchField
        End Get
        Set(ByVal value As String)
            Me.sBankBranchField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAddress1() As String
        Get
            Return Me.sBankAddress1Field
        End Get
        Set(ByVal value As String)
            Me.sBankAddress1Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAddress2() As String
        Get
            Return Me.sBankAddress2Field
        End Get
        Set(ByVal value As String)
            Me.sBankAddress2Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAddress3() As String
        Get
            Return Me.sBankAddress3Field
        End Get
        Set(ByVal value As String)
            Me.sBankAddress3Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankTown() As String
        Get
            Return Me.sBankTownField
        End Get
        Set(ByVal value As String)
            Me.sBankTownField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankRegion() As String
        Get
            Return Me.sBankRegionField
        End Get
        Set(ByVal value As String)
            Me.sBankRegionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankPostCode() As String
        Get
            Return Me.sBankPostCodeField
        End Get
        Set(ByVal value As String)
            Me.sBankPostCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankCountry() As String
        Get
            Return Me.sBankCountryField
        End Get
        Set(ByVal value As String)
            Me.sBankCountryField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankAreaCode() As String
        Get
            Return Me.sBankAreaCodeField
        End Get
        Set(ByVal value As String)
            Me.sBankAreaCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankPhoneNo() As String
        Get
            Return Me.sBankPhoneNoField
        End Get
        Set(ByVal value As String)
            Me.sBankPhoneNoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankExtension() As String
        Get
            Return Me.sBankExtensionField
        End Get
        Set(ByVal value As String)
            Me.sBankExtensionField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankFaxAreaCode() As String
        Get
            Return Me.sBankFaxAreaCodeField
        End Get
        Set(ByVal value As String)
            Me.sBankFaxAreaCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankFaxNo() As String
        Get
            Return Me.sBankFaxNoField
        End Get
        Set(ByVal value As String)
            Me.sBankFaxNoField = value
        End Set
    End Property

    '''<remarks/>
    Public Property StatusInd() As FinancePlanStatus
        Get
            Return Me.sStatusIndField
        End Get
        Set(ByVal value As FinancePlanStatus)
            Me.sStatusIndField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientCode() As String
        Get
            Return Me.sClientCodeField
        End Get
        Set(ByVal value As String)
            Me.sClientCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property AutoGeneratedPlanRef() As String
        Get
            Return Me.sAutoGeneratedPlanRefField
        End Get
        Set(ByVal value As String)
            Me.sAutoGeneratedPlanRefField = value
        End Set
    End Property

    '''<remarks/>
    Public Property FinanceCollatedPlanRef() As String
        Get
            Return Me.sFinanceCollatedPlanRefField
        End Get
        Set(ByVal value As String)
            Me.sFinanceCollatedPlanRefField = value
        End Set
    End Property

    '''<remarks/>
    Public Property InterestFree() As String
        Get
            Return Me.sInterestFreeField
        End Get
        Set(ByVal value As String)
            Me.sInterestFreeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IsQuote() As Boolean
        Get
            Return Me.bIsQuoteField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsQuoteField = value
        End Set
    End Property


    '''<remarks/>
    Public Property PlanTransactionKey() As Integer
        Get
            Return Me.nPlanTransactionKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nPlanTransactionKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property InsuranceFileKey() As Integer
        Get
            Return Me.nInsuranceFileKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nInsuranceFileKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFRFKEY() As Integer
        Get
            Return Me.nPFRFKEYField
        End Get
        Set(ByVal value As Integer)
            Me.nPFRFKEYField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFFrequencyCode() As String
        Get
            Return Me.sPFFrequencyCodeField
        End Get
        Set(ByVal value As String)
            Me.sPFFrequencyCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property BankCountryKey() As Integer
        Get
            Return Me.nBankCountryKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nBankCountryKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property ClientCountryKey() As Integer
        Get
            Return Me.nClientCountryKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nClientCountryKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property DepositCCTrackingNumber() As String
        Get
            Return Me.sDepositCCTrackingNumber
        End Get
        Set(ByVal value As String)
            Me.sDepositCCTrackingNumber = value
        End Set
    End Property

    '''<remarks/>
    Public Property Authcode() As String
        Get
            Return Me.sAuthCode
        End Get
        Set(ByVal value As String)
            Me.sAuthCode = value
        End Set
    End Property

    '''<remarks/>
    Public Property FirstInstalmentDate() As Date
        Get
            Return Me.dtFirstInstalmentDateField
        End Get
        Set(ByVal value As Date)
            Me.dtFirstInstalmentDateField = value
        End Set
    End Property

    '''<remarks/>

    Public Property NextInstalmentDate() As Date
        Get
            Return Me.dtNextInstalmentDateField
        End Get
        Set(ByVal value As Date)
            Me.dtNextInstalmentDateField = value
        End Set
    End Property

    '''<remarks/>

    Public Property LastInstalmentDate() As Date
        Get
            Return Me.dtLastInstalmentDateField
        End Get
        Set(ByVal value As Date)
            Me.dtLastInstalmentDateField = value
        End Set
    End Property
    '''<remarks/>
    Public Property TaxCost() As Double
        Get
            Return Me.dTaxCostField
        End Get
        Set(ByVal value As Double)
            Me.dTaxCostField = value
        End Set
    End Property
    '''<remarks/>
    Public Property MediaTypeCode() As String
        Get
            Return Me.sMediaTypeCodeField
        End Get
        Set(ByVal value As String)
            Me.sMediaTypeCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CCNumber() As String
        Get
            Return Me.sCCNumberField
        End Get
        Set(ByVal value As String)
            Me.sCCNumberField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CCExpiryDate() As String
        Get
            Return Me.sCCExpiryDateField
        End Get
        Set(ByVal value As String)
            Me.sCCExpiryDateField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CCStartDate() As String
        Get
            Return Me.sCCStartDateField
        End Get
        Set(ByVal value As String)
            Me.sCCStartDateField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CCIssue() As String
        Get
            Return Me.sCCIssueField
        End Get
        Set(ByVal value As String)
            Me.sCCIssueField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CCPin() As String
        Get
            Return Me.sCCPinField
        End Get
        Set(ByVal value As String)
            Me.sCCPinField = value
        End Set
    End Property

    '''<remarks/>
    Public Property MediaTypeValidationCode() As String
        Get
            Return Me.sMediaTypeValidationCodeField
        End Get
        Set(ByVal value As String)
            Me.sMediaTypeValidationCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property bank_name_mandatory() As Boolean
        Get
            Return Me.bBankNameMandatory
        End Get
        Set(ByVal value As Boolean)
            Me.bBankNameMandatory = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsBankAddressMandatory() As Boolean
        Get
            Return Me.bIsBankAddressMandatoryField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsBankAddressMandatoryField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsBranchNameMandatory() As Boolean
        Get
            Return Me.bIsBranchNameMandatoryField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsBranchNameMandatoryField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsBranchCodeMandatory() As Boolean
        Get
            Return Me.bIsBranchCodeMandatoryField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsBranchCodeMandatoryField = value
        End Set
    End Property
    '''<remarks/>
    Public Property CommissionTransdetailKey() As Integer
        Get
            Return Me.nCommissionTransdetailKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nCommissionTransdetailKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFFrequencyPeriod() As String
        Get
            Return Me.sPFFrequencyPeriodField
        End Get
        Set(ByVal value As String)
            Me.sPFFrequencyPeriodField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFFrequencyAmount() As Integer
        Get
            Return Me.nPFFrequencyAmountField
        End Get
        Set(ByVal value As Integer)
            Me.nPFFrequencyAmountField = value
        End Set
    End Property
    '''<remarks/>
    Public Property PFFrequencyKey() As Integer
        Get
            Return Me.nPFFrequencyKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nPFFrequencyKeyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property SourceKey() As Integer
        Get
            Return Me.nSourceKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nSourceKeyField = value
        End Set
    End Property
    '''<remarks/>
    Public Property ProductKey() As Integer
        Get
            Return Me.nProductKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nProductKeyField = value
        End Set
    End Property
    '''<remarks/>
    Public Property PFSchemeTypeCode() As String
        Get
            Return Me.sPFSchemeTypeCodeField
        End Get
        Set(ByVal value As String)
            Me.sPFSchemeTypeCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property FinanceFee() As Double
        Get
            Return Me.dFinanceFeeField
        End Get
        Set(ByVal value As Double)
            Me.dFinanceFeeField = value
        End Set
    End Property
    '''<remarks/>
    Public Property DayOfWeekOrMonth() As Integer
        Get
            Return Me.nDayOfWeekOrMonthField
        End Get
        Set(ByVal value As Integer)
            Me.nDayOfWeekOrMonthField = value
        End Set
    End Property
    '''<remarks/>
    Public Property PaymentMethod() As String
        Get
            Return Me.sPaymentMethodField
        End Get
        Set(ByVal value As String)
            Me.sPaymentMethodField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFFrequencyDesc() As String
        Get
            Return Me.sPFFrequencyDescField
        End Get
        Set(ByVal value As String)
            Me.sPFFrequencyDescField = value
        End Set
    End Property

    '''<remarks/>
    Public Property SchemePrintType() As String
        Get
            Return Me.sSchemePrintTypeField
        End Get
        Set(ByVal value As String)
            Me.sSchemePrintTypeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property OriginalAmount() As Double
        Get
            Return Me.dOriginalAmountField
        End Get
        Set(ByVal value As Double)
            Me.dOriginalAmountField = value
        End Set
    End Property
    '''<remarks/>
    Public Property LastInstalment() As Double
        Get
            Return Me.dLastInstalmentField
        End Get
        Set(ByVal value As Double)
            Me.dLastInstalmentField = value
        End Set
    End Property
    '''<remarks/>
    Public Property ClaimDebtId() As Integer
        Get
            Return Me.nClaimDebtIdField
        End Get
        Set(ByVal value As Integer)
            Me.nClaimDebtIdField = value
        End Set
    End Property
    '''<remarks/>

    Public Property DateCreated() As Date
        Get
            Return Me.dtDateCreatedField
        End Get
        Set(ByVal value As Date)
            Me.dtDateCreatedField = value
        End Set
    End Property
    '''<remarks/>
    Public Property DateModified() As Date
        Get
            Return Me.dtDateModifiedField
        End Get
        Set(ByVal value As Date)
            Me.dtDateModifiedField = value
        End Set
    End Property

    '''<remarks/>

    Public Property DateConfirmed() As Date
        Get
            Return Me.dtDateConfirmedField
        End Get
        Set(ByVal value As Date)
            Me.dtDateConfirmedField = value
        End Set
    End Property
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property DateReview() As Date
        Get
            Return Me.dtDateReviewField
        End Get
        Set(ByVal value As Date)
            Me.dtDateReviewField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IsViaThirdParty() As Boolean
        Get
            Return Me.bIsViaThirdPartyField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsViaThirdPartyField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsDepositAsInstalment() As Boolean
        Get
            Return Me.bIsDepositAsInstalmentField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsDepositAsInstalmentField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PFRFMnemonic() As String
        Get
            Return Me.sPFRFMnemonicField
        End Get
        Set(ByVal value As String)
            Me.sPFRFMnemonicField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property CoverStartDate() As Date
        Get
            Return Me.dtCoverStartDateField
        End Get
        Set(ByVal value As Date)
            Me.dtCoverStartDateField = value
        End Set
    End Property
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property ExpiryDate() As Date
        Get
            Return Me.dtExpiryDateField
        End Get
        Set(ByVal value As Date)
            Me.dtExpiryDateField = value
        End Set
    End Property

    '''<remarks/>
    Public Property Terms() As Integer
        Get
            Return Me.nTermsField
        End Get
        Set(ByVal value As Integer)
            Me.nTermsField = value
        End Set
    End Property
    '''<remarks/>
    Public Property OriginalRate() As Double
        Get
            Return Me.dOriginalRateField
        End Get
        Set(ByVal value As Double)
            Me.dOriginalRateField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsCardHolder() As Boolean
        Get
            Return Me.bIsCardHolderField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsCardHolderField = value
        End Set
    End Property
    '''<remarks/>
    Public Property CardHolderName() As String
        Get
            Return Me.sCardHolderNameField
        End Get
        Set(ByVal value As String)
            Me.sCardHolderNameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardHolderAddress1() As String
        Get
            Return Me.sCardHolderAddress1Field
        End Get
        Set(ByVal value As String)
            Me.sCardHolderAddress1Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardHolderAddress2() As String
        Get
            Return Me.sCardHolderAddress2Field
        End Get
        Set(ByVal value As String)
            Me.sCardHolderAddress2Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardHolderAddress3() As String
        Get
            Return Me.sCardHolderAddress3Field
        End Get
        Set(ByVal value As String)
            Me.sCardHolderAddress3Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardHolderAddress4() As String
        Get
            Return Me.sCardHolderAddress4Field
        End Get
        Set(ByVal value As String)
            Me.sCardHolderAddress4Field = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardHolderPostCode() As String
        Get
            Return Me.sCardHolderPostCodeField
        End Get
        Set(ByVal value As String)
            Me.sCardHolderPostCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property CardType() As String
        Get
            Return Me.sCardTypeField
        End Get
        Set(ByVal value As String)
            Me.sCardTypeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IsProviderCollectDeposit() As Boolean
        Get
            Return Me.bIsProviderCollectDepositField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsProviderCollectDepositField = value
        End Set
    End Property
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property DateBankDetailsChanged() As Date
        Get
            Return Me.dtDateBankDetailsChangedField
        End Get
        Set(ByVal value As Date)
            Me.dtDateBankDetailsChangedField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsDDCancelled() As Boolean
        Get
            Return Me.bIsDDCancelledField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsDDCancelledField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsCCCancelled() As Boolean
        Get
            Return Me.bIsCCCancelledField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsCCCancelledField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsPaperlessDD() As Boolean
        Get
            Return Me.bIsPaperlessDDField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsPaperlessDDField = value
        End Set
    End Property
    '''<remarks/>
    Public Property SchemeType() As String
        Get
            Return Me.sSchemeTypeField
        End Get
        Set(ByVal value As String)
            Me.sSchemeTypeField = value
        End Set
    End Property

    Public Property SettlementAmount() As String
        Get
            Return Me.dSettlementAmount
        End Get
        Set(ByVal value As String)
            Me.dSettlementAmount = value
        End Set
    End Property

    '''<remarks/>
    Public Property SchemeCode() As String
        Get
            Return Me.sSchemeCodeField
        End Get
        Set(ByVal value As String)
            Me.sSchemeCodeField = value
        End Set
    End Property

    '''<remarks/>
    Public Property PartyBankKey() As Integer
        Get
            Return Me.nPartyBankKeyField
        End Get
        Set(ByVal value As Integer)
            Me.nPartyBankKeyField = value
        End Set
    End Property
    '''<remarks/>
    Public Property PFPremiumFinanceCancelReason() As String
        Get
            Return Me.sPFPremiumFinanceCancelReasonField
        End Get
        Set(ByVal value As String)
            Me.sPFPremiumFinanceCancelReasonField = value
        End Set
    End Property

    '''<remarks/>
    Public Property IsCancelPolicyRun() As Boolean
        Get
            Return Me.bIsCancelPolicyRunField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsCancelPolicyRunField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsFinanceNetCommission() As Boolean
        Get
            Return Me.bIsFinanceNetCommissionField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsFinanceNetCommissionField = value
        End Set
    End Property
    '''<remarks/>
    Public Property IsDepositOnOtherMediaType() As Boolean
        Get
            Return Me.bIsDepositOnOtherMediaTypeField
        End Get
        Set(ByVal value As Boolean)
            Me.bIsDepositOnOtherMediaTypeField = value
        End Set
    End Property

    Public Property PreferredDate() As Date
        Get
            Return Me.dtPreferredDateField
        End Get
        Set(ByVal value As Date)
            Me.dtPreferredDateField = value
        End Set
    End Property


    Public Property OverrideInterestRate() As Double
        Get
            Return Me.dOverrideInterestRateField
        End Get
        Set(ByVal value As Double)
            Me.dOverrideInterestRateField = value
        End Set
    End Property

    Public Property SelectedSchemeNo() As Integer
        Get
            Return Me.nSelectedSchemeNoField
        End Get
        Set(ByVal value As Integer)
            Me.nSelectedSchemeNoField = value
        End Set
    End Property


    Public Property SelectedSchemeVersion() As Integer
        Get
            Return Me.nSelectedSchemeVersionField
        End Get
        Set(ByVal value As Integer)
            Me.nSelectedSchemeVersionField = value
        End Set
    End Property

    Public Property OverrideCommission() As Boolean
        Get
            Return Me.bOverrideCommission
        End Get
        Set(ByVal value As Boolean)
            Me.bOverrideCommission = value
        End Set
    End Property

    Public Property ProcessPFMode() As String
        Get
            Return Me.sProcessPFMode
        End Get
        Set(ByVal value As String)
            Me.sProcessPFMode = value
        End Set
    End Property

    Public Property Receipt_Difference_Option() As Integer
End Class

<Serializable()> Public Class FinancePlanDetailsCollection : Inherits CollectionBase

    Public Function Print() As String

        Dim sbPrint As New Text.StringBuilder()

        For Each oFinancePlanDetail As FinancePlanDetails In List
            'sbPrint.AppendLine(oInstalments.Print())
            sbPrint.AppendLine("<br />")
        Next

        Return sbPrint.ToString()

    End Function

    Public Function Add(ByVal v_oFinancePlanDetail As FinancePlanDetails) As Integer
        Return List.Add(v_oFinancePlanDetail)
    End Function

    Public Sub Remove(ByVal v_oFinancePlanDetail As FinancePlanDetails)
        List.Remove(v_oFinancePlanDetail)
    End Sub

    Public Sub Remove(ByVal index As Integer)
        List.RemoveAt(index)
    End Sub

    Default Public Property Item(ByVal i As Integer) As FinancePlanDetails
        Get
            Return List(i)
        End Get
        Set(ByVal value As FinancePlanDetails)
            List(i) = value
        End Set
    End Property

End Class
