'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PMAddressControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No./Name Street:.
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locality:.
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Town:.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to County:.
        '''</summary>
        Friend ReadOnly Property str1104() As String
            Get
                Return ResourceManager.GetString("str1104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Code:.
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country:.
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Street Address:.
        '''</summary>
        Friend ReadOnly Property str2101() As String
            Get
                Return ResourceManager.GetString("str2101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City:.
        '''</summary>
        Friend ReadOnly Property str2102() As String
            Get
                Return ResourceManager.GetString("str2102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to County:.
        '''</summary>
        Friend ReadOnly Property str2103() As String
            Get
                Return ResourceManager.GetString("str2103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State:.
        '''</summary>
        Friend ReadOnly Property str2104() As String
            Get
                Return ResourceManager.GetString("str2104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip Code:.
        '''</summary>
        Friend ReadOnly Property str2105() As String
            Get
                Return ResourceManager.GetString("str2105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country:.
        '''</summary>
        Friend ReadOnly Property str2106() As String
            Get
                Return ResourceManager.GetString("str2106", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
