'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPMUDeferredRIAuto.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Search.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelling will not add or update any details
        '''Do you really wish to cancel?.
        '''</summary>
        Friend ReadOnly Property str1301() As String
            Get
                Return ResourceManager.GetString("str1301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Business Object.
        '''</summary>
        Friend ReadOnly Property str1302() As String
            Get
                Return ResourceManager.GetString("str1302", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to gain access to the business object.
        '''Please try later.
        '''</summary>
        Friend ReadOnly Property str1303() As String
            Get
                Return ResourceManager.GetString("str1303", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching, Please wait....
        '''</summary>
        Friend ReadOnly Property str1304() As String
            Get
                Return ResourceManager.GetString("str1304", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to risks found for processing..
        '''</summary>
        Friend ReadOnly Property str1305() As String
            Get
                Return ResourceManager.GetString("str1305", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The renewal you have selected is currently awaiting update. Do you wish to amend it anyway?.
        '''</summary>
        Friend ReadOnly Property str1308() As String
            Get
                Return ResourceManager.GetString("str1308", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation.
        '''</summary>
        Friend ReadOnly Property str1309() As String
            Get
                Return ResourceManager.GetString("str1309", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amend Renewal.
        '''</summary>
        Friend ReadOnly Property str1315() As String
            Get
                Return ResourceManager.GetString("str1315", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to launch process .
        '''</summary>
        Friend ReadOnly Property str1316() As String
            Get
                Return ResourceManager.GetString("str1316", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to set keys for .
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to set process modes .
        '''</summary>
        Friend ReadOnly Property str1318() As String
            Get
                Return ResourceManager.GetString("str1318", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed process .
        '''</summary>
        Friend ReadOnly Property str1319() As String
            Get
                Return ResourceManager.GetString("str1319", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
