SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO


EXECUTE DDLDropProcedure 'spu_ACT_Add_CashListItem'
GO


CREATE PROCEDURE spu_ACT_Add_CashListItem  
    @cashlistitem_id int OUTPUT,  
    @allocationstatus_id int,  
    @mediatype_id int,  
    @cashlist_id int,  
    @account_id int,  
    @media_ref varchar(100),  
    @our_ref varchar(255),  
    @their_ref varchar(100),  
    @amount numeric(19,4),  
    @transdetail_id int,  
    @contact_name varchar(60),  
    @address1 varchar(40),  
    @address2 varchar(40),  
    @address3 varchar(40),  
    @address4 varchar(40),  
    @postal_code varchar(20),  
    @address_country smallint,  
    @payment_name varchar(60),  
    @payment_account_code varchar(60),  
    @payment_branch_code varchar(30),  
    @payment_expiry_date datetime,  
    @payment_reference1 varchar(30),  
    @payment_reference2 varchar(30),  
    @letter tinyint,  
    @batch_id int,  
    @pmuser_id int,  
    @transaction_date datetime,  
    @original_amount numeric(19, 4),  
    @amount_tendered numeric(19, 4),  
    @change numeric(19, 4),  
    @cashlistitem_receipt_type_id int,  
    @cashlistitem_receipt_status_id int,  
    @cashlistitem_bank_id int,  
    @cheque_date datetime,  
    @cc_number varchar (30),  
    @cc_expiry_date varchar (10),  
    @cc_start_date varchar (10),  
    @cc_issue varchar (2),  
    @cc_pin varchar (20),  
    @cc_auth_code varchar (50),  
    @receipt_details varchar (500),  
    @cashlistitem_reverse_pmuser_id smallint,  
    @cashlistitem_reverse_reason_id int,  
    @cashlistitem_payment_type_id int,  
    @cashlistitem_payment_status_id int,  
    @date_presented datetime,  
    @cheque_in_possession tinyint,  
    @stop_requested_date datetime,  
    @stop_printed_date datetime,  
    @stop_confirmation_date datetime,  
    @reason varchar (500),  
    @replaces_cashlistitem_id int,  
    @xml_object varchar (4000),  
    @underwriting_year_id int,  
    @currency_base_date datetime,  
    @currency_base_xrate float,  
    @account_base_date datetime,  
    @account_base_xrate float,  
    @system_base_date datetime,  
    @system_base_xrate float,  
    @exchange_rate_override_reason_id int,  
    @mediatype_issuer_id int,  
    @cc_name VARCHAR(50),  
    @cc_customer VARCHAR(50),  
    @cc_manual_auth_code VARCHAR(50),  
    @cc_transaction_code VARCHAR(255),  
    @Party_Bank_ID INT = NULL,  
    @collection_date datetime,  
    @comments VARCHAR(100),  
    @bank_location Varchar(100),  
    @bank_branch Varchar(50),  
    @chequetype_id int,  
    @Cheque_clearing_type_id int,  
    @cc_bank_id int,  
    @type_of_card_id int,  
    @cc_trans_slip_no Varchar(50),
    @is_lead TINYINT = NULL,
    @split_total NUMERIC(19,4) = NULL,
    @tax_band_id INT = NULL, 
    @TaxAmount  NUMERIC(19,4)=0,
    @sBusinessIdentifierCode VARCHAR(50)=NULL,
    @sInternationalBankAccountNumber VARCHAR(50)=NULL,
	@Insurance_ref VARCHAR(30)=NULL	
  
AS  
  

/*************************************************************************/  
/* ERWIN generated add record and return MAX ID column                   */  
/*************************************************************************/  
/*************************************************************************/  
/* 1.0 07/07/97 SP Original                                              */  
/*************************************************************************/  
  
IF (@underwriting_year_id=0)  
    SELECT @underwriting_year_id=NULL  
--Start - Sankar - (WPRvb64 Media Type Status) - Paralleling  
DECLARE @MediaType_Status_Id AS INT  
 --Check the cashlist is of type receipt  
 IF EXISTS(SELECT 1 FROM CashList cl INNER JOIN CashlistType clt ON clt.CashlistType_id=cl.CashlistType_Id AND clt.CODE='R'  
     WHERE cl.CashList_Id=@cashlist_id)  
 BEGIN  
  -- receipt item, get the media type status  
  SELECT  
   @MediaType_Status_Id=MediaType_Status_Id  
  FROM  
    MediaType  
  WHERE  
   MediaType_Id=@mediatype_id  
 END  
--End - Sankar - (WPRvb64 Media Type Status) - Paralleling  
  
INSERT INTO CashListItem  
(  
    allocationstatus_id ,  
    mediatype_id ,  
    cashlist_id ,  
    account_id ,  
    media_ref ,  
    our_ref ,  
    their_ref ,  
    amount ,  
    transdetail_id ,  
    contact_name ,  
    address1 ,  
    address2 ,  
    address3 ,  
    address4 ,  
    postal_code ,  
    address_country ,  
    Party_Bank_Id ,  
    payment_name ,  
    payment_account_code ,  
    payment_branch_code ,  
    payment_expiry_date ,  
    payment_reference1 ,  
    payment_reference2,  
    letter,  
    batch_id,  
    pmuser_id,  
    transaction_date,  
    original_amount,  
    amount_tendered,  
    change,  
    cashlistitem_receipt_type_id,  
    cashlistitem_receipt_status_id,  
    cashlistitem_bank_id,  
    cheque_date,  
    cc_number,  
    cc_expiry_date,  
    cc_start_date,  
    cc_issue,  
    cc_pin,  
    cc_auth_code,  
    receipt_details,  
    cashlistitem_reverse_pmuser_id,  
    cashlistitem_reverse_reason_id,  
    cashlistitem_payment_type_id,  
    cashlistitem_payment_status_id,  
    date_presented,  
    cheque_in_possession,  
    stop_requested_date,  
    stop_printed_date,  
    stop_confirmation_date,  
    reason,  
    replaces_cashlistitem_id,  
    xml_object,  
    underwriting_year_id,  
    currency_base_date,  
    currency_base_xrate,  
    account_base_date,  
    account_base_xrate,  
    system_base_date,  
    system_base_xrate,  
    exchange_rate_override_reason_id,  
    mediatype_issuer_id,  
    cc_name,  
    cc_customer,  
    cc_manual_auth_code,  
    cc_transaction_code,  
    collection_date,  
    comments,   
    MediaType_Status_id,  
    bank_location,  
    bank_branch,  
    chequetype_id,  
    Cheque_clearing_type_id,  
    cc_bank_id,  
    type_of_card_id,  
    cc_trans_slip_no,
    is_lead,
    split_total,
    tax_band_id,
    TaxAmount,
    business_identifier_code,
    international_bank_account_number,
	insurance_ref	 
)  
VALUES  
(  
    @allocationstatus_id,  
    @mediatype_id,  
    @cashlist_id,  
    @account_id,  
    @media_ref,  
    @our_ref,  
    @their_ref,  
    @amount,  
    @transdetail_id,  
    @contact_name,  
    @address1,  
    @address2,  
    @address3,  
    @address4,  
    @postal_code,  
    @address_country,  
    @Party_Bank_Id ,  
    @payment_name,  
    @payment_account_code,  
    @payment_branch_code,  
    @payment_expiry_date,  
    @payment_reference1,  
    @payment_reference2,  
    @letter,  
    @batch_id,  
    @pmuser_id,  
    @transaction_date,  
    @original_amount,  
    @amount_tendered,  
    @change,  
    @cashlistitem_receipt_type_id,  
    @cashlistitem_receipt_status_id,  
    @cashlistitem_bank_id,  
    @cheque_date,  
    @cc_number,  
    @cc_expiry_date,  
    @cc_start_date,  
    @cc_issue,  
    @cc_pin,  
    @cc_auth_code,  
    @receipt_details,  
    @cashlistitem_reverse_pmuser_id,  
    @cashlistitem_reverse_reason_id,  
    @cashlistitem_payment_type_id,  
    @cashlistitem_payment_status_id,  
    @date_presented,  
    @cheque_in_possession,  
    @stop_requested_date,  
    @stop_printed_date,  
    @stop_confirmation_date,  
    @reason,  
    @replaces_cashlistitem_id,  
    @xml_object,  
    @underwriting_year_id,  
    @currency_base_date,  
    @currency_base_xrate,  
    @account_base_date,  
    @account_base_xrate,  
    @system_base_date,  
    @system_base_xrate,  
    @exchange_rate_override_reason_id,  
    @mediatype_issuer_id,  
    @cc_name,  
    @cc_customer,  
    @cc_manual_auth_code,  
    @cc_transaction_code,  
    @collection_date,  
    @comments,   
    @MediaType_Status_id,  
    @bank_location,  
    @bank_branch,  
    @chequetype_id,  
    @Cheque_clearing_type_id,  
    @cc_bank_id,  
    @type_of_card_id,  
    @cc_trans_slip_no,   
    @is_lead,
    @split_total,
    @tax_band_id,
    @TaxAmount,
    @sBusinessIdentifierCode,
    @sInternationalBankAccountNumber,
	@Insurance_ref  
)  
SELECT @cashlistitem_id=@@IDENTITY  
GO


