if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spu_ACT_Select_Instalments_For_Account]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spu_ACT_Select_Instalments_For_Account]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE PROCEDURE spu_ACT_Select_Instalments_For_Account
@account_id int
AS
select
pfi.pfinstalments_id,
pfi.pfprem_finance_cnt, pfi.pfprem_finance_version,
pfi.instalmentnumber, pfi.duedate,
pfi.fee, pfi.amount,
pfp.autogeneratedplanref, convert(tinyint,0) as SelectedFlag, 0 as PartialPay
from
account a, pfpremiumfinance pfp, pfinstalments pfi, pfinstalments_status pfis
where
a.account_id = @account_id
and
a.account_key = pfp.clientid
and
pfp.StatusInd = '040'
and
pfi.Status = pfis.pfinstalments_status_id
and
(pfis.code = 'U' or pfis.code = 'R')
and
pfp.pfprem_finance_cnt = pfi.pfprem_finance_cnt
and
pfp.pfprem_finance_version = pfi.pfprem_finance_version
and
(select count(*) from cashlistitem_instalments cli where
pfi.pfinstalments_id = cli.pfinstalments_id) = 0
--AAB - Aug-21-2003 added order to support partial payments
ORDER BY pfi.pfprem_finance_cnt, pfi.pfprem_finance_version, pfi.InstalmentNumber
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

