SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

EXECUTE DDLDropProcedure 'spu_ACT_InstalmentExport_XML_Select'
GO

CREATE PROCEDURE spu_ACT_InstalmentExport_XML_Select  
 @media_type_code varchar(50),  
 @lead_days int,  
 @bank_account_name varchar(60) = '',  
 @batch_id int,  
 @status int  OUTPUT,  
 @newbatch int,  
 @due_day INT  
AS  
  
BEGIN  
  
IF (SELECT export_date FROM batch WHERE batch_id = @batch_id) Is Null  
 BEGIN  
        UPDATE  batch  
        SET     export_date = GetDate()  
        WHERE   batch_id = @batch_id  
 END  
ELSE  
 BEGIN  
        UPDATE  batch  
        SET     reexport_date = GetDate()  
        WHERE   batch_id = @batch_id  
END  
  
DECLARE @parameters varchar (300)  
DECLARE @batch_ref varchar(20)  
DECLARE @due_date datetime  
DECLARE @temp int  
DECLARE @total_amount_all_instalments numeric (19,4)  
DECLARE @total_amount_grouped_instalments numeric (19,4)  
DECLARE @total_transactions int  
  
--  
DECLARE @BatchStatus_Batch_In_Progress int  
DECLARE @BatchStatus_Batch_Exported int  
DECLARE @BatchStatus_Batch_Closed int  
DECLARE @media_type_id int  
DECLARE @batch_type_id int  
DECLARE @PFInstalments_Result_Waiting_For_Collection int  
  
-- instalment export fields  
DECLARE @instalment_pfinstalments_id int  
DECLARE @instalment_duedate datetime  
DECLARE @party_shortname char(20)  
DECLARE @plan_clientname varchar(30)  
DECLARE @plan_companyname varchar(35)  
DECLARE @plan_cc_number varchar(30)  
DECLARE @plan_bankaccountname varchar(30)  
DECLARE @plan_bankaccountno varchar(30)  
DECLARE @plan_business_identifier_code VARCHAR(50)  
DECLARE @plan_international_bank_account_number VARCHAR(50)  
DECLARE @plan_banksortcode varchar(8)  
DECLARE @plan_bankname varchar(60)  
DECLARE @instalment_amount numeric (19,4)  
DECLARE @party_alternative_identifier varchar(15)  
DECLARE @party_agent_cnt int  
DECLARE @instalments_group_id int  
DECLARE @instalment_status_id int  
DECLARE @instalment_status_description varchar(255)  
DECLARE @instalment_transaction_code char(10)  
DECLARE @plan_autogeneratedplanref varchar(20)  
DECLARE @instalment_instalmentnumber int  
DECLARE @plan_cc_expiry_date varchar(10)  
DECLARE @plan_cc_start_date varchar(10)  
DECLARE @plan_cc_issue varchar(2)  
DECLARE @plan_cc_pin varchar(20)  
DECLARE @sysOptionCollectINSFailedStatus varchar(1)  
  
-- get required id constants  
SELECT @batchstatus_batch_in_progress = batchstatus_id FROM BatchStatus WHere code = 'BI'  
SELECT @BatchStatus_Batch_Exported = batchstatus_id FROM BatchStatus WHere code = 'BE'  
SELECT @BatchStatus_Batch_Closed = batchstatus_id FROM BatchStatus WHere code = 'BC'  
SELECT @media_type_id = mediatype_id from mediatype where code = @media_type_code  
SELECT @batch_type_id = batch_type_id from batch_type where code ='BAC'  
SELECT @batch_ref = batch_ref from batch where batch_id = @batch_id  
  
-- initialisation  
SET @total_amount_all_instalments = 0  
SET @total_amount_grouped_instalments = 0  
SET @total_transactions = 0  
  
SET @parameters = 'media_type_code=' + @media_type_code + ' lead_days=' + Cast(@lead_days as varchar(10)) + ' bank_account_name=' + @bank_account_name + ' batch_id=' + Cast(@batch_id as varchar(10))  
  
-- initialise to ok  
SET @status =0  
  
SELECT @sysOptionCollectINSFailedStatus = ISNULL(value,'0') from System_Options where option_number = 5208  
  
IF @newbatch=-1 BEGIN  
 SET @due_date = DATEADD(dd,ISNULL(@lead_days,0), GETDATE())  
  
 -- create temp table  
 CREATE TABLE #temp_pfinstalments_id  
  (pfinstalments_id int)  
  
 -- get the instalments to export  
 DECLARE Instalment_Export CURSOR FAST_FORWARD FOR  
 SELECT  
  [PFI].pfinstalments_id,  
  [PFI].duedate,  
  [PTY].shortname,  
  [PLN].clientname,  
  [PLN].companyname,  
  [PLN].cc_number,  
  [PLN].bankaccountname,  
  [PLN].BankAccountNo,  
  [PLN].business_identifier_code,  
  [PLN].international_bank_account_number,  
  [PLN].BankSortCode,  
  [PLN].BankName,  
  [PFI].amount,  
  [PTY].alternative_identifier,  
  [PTY].agent_cnt,  
  0,  
  PFI.Status,  
  PFIS.Description,  
  PFIT.Code,  
  PLN.AutoGeneratedPlanRef,  
  PFI.InstalmentNumber,  
  [PLN].cc_expiry_date,  
  [PLN].cc_start_date,  
  [PLN].cc_issue,  
  [PLN].cc_pin  
  
 FROM PFInstalments [PFI]  
  
  JOIN PFInstalments_Status [PFIS] ON  
   [PFIS].PFInstalments_Status_id=PFI.Status  
  
  JOIN PFInstalments_Transaction [PFIT] ON  
   [PFIT].PFInstalments_Transaction_id=PFI.TransactionCode  
  
  JOIN PFPremiumFinance[PLN] ON  
   [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
      AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
   JOIN PFScheme[SCH] on  
   [SCH].schemeversion = [PLN].schemeversion  
      AND [SCH].schemeno = [PLN].schemeno  
      AND [SCH].companyno = [PLN].companyno  
  
   JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
  JOIN PFRF on  
   [PFRF].pfrf_id=[PLN].pfrf_id  
  
  JOIN MediaType[MTP] ON  
   [MTP].mediatype_id = [SCH].mediatype_id  
  
  JOIN Party[PTY] ON  
   [PTY].party_cnt = [PLN].clientid  
  
  LEFT JOIN pfpaymentmethod [PFPM] on  
   [PFPM].PFPaymentMethod_cnt = sch.PaymentMethod_cnt  
  
 WHERE [PFI].duedate <= @due_date  
 AND ([PFI].Batch_ID is Null OR [PFI].Status = 5 OR [PFI].Status = 7)  
 AND [MTP].code = @media_type_code  
 AND ([PLN].StatusInd='040'  OR pfit.code IN ('0N','0C'))  
 AND ([PFI].Status=1 OR [PFI].Status=5)  
 AND (ISNULL([PFI].failure_count,0)<=PFRF.retry_limit OR [PFRF].retry_limit = 0)  
 AND (([PFIT].code <> '0N' and [PFI].instalmentNumber <> 0 and [PFPM].excludeaudis=1) or (isnull([PFPM].excludeaudis,0) <> 1))  
 AND ((@bank_account_name ='') OR ([SCHBNK].description = @bank_account_name))  
 AND ((@sysOptionCollectINSFailedStatus = '1') OR (@sysOptionCollectINSFailedStatus = '0' AND CONVERT(VARCHAR(12),[PFI].pfprem_finance_cnt)+'-'+ CONVERT(VARCHAR(12),[PFI].pfprem_finance_version)  
   NOT IN  (SELECT CONVERT(VARCHAR(12),pfprem_finance_cnt)+'-'+ CONVERT(VARCHAR(12),pfprem_finance_version) FROM PFInstalments WITH(NOLOCK)  
   WHERE PFInstalments.Status=6 AND PFInstalments.pfprem_finance_cnt=[PFI].pfprem_finance_cnt  
   AND PFInstalments.pfprem_finance_version=[PFI].pfprem_finance_version))  
  )  
  
 ORDER BY [PFI].duedate  
  
 OPEN Instalment_Export  
  
 FETCH NEXT FROM Instalment_Export  
 INTO  
  @instalment_pfinstalments_id,  
  @instalment_duedate,  
  @party_shortname,  
  @plan_clientname,  
  @plan_companyname,  
  @plan_cc_number,  
  @plan_bankaccountname,  
  @plan_bankaccountno,  
  @plan_business_identifier_code,  
  @plan_international_bank_account_number,  
  @plan_banksortcode,  
  @plan_bankname,  
  @instalment_amount,  
  @party_alternative_identifier,  
  @party_agent_cnt,  
  @instalments_group_id,  
  @instalment_status_id,  
  @instalment_status_description,  
  @instalment_transaction_code,  
  @plan_autogeneratedplanref,  
  @instalment_instalmentnumber,  
  @plan_cc_expiry_date,  
  @plan_cc_start_date,  
  @plan_cc_issue,  
  @plan_cc_pin  
  
 WHILE @@FETCH_STATUS = 0  
 BEGIN  
  
  -- calculate the total of all instalments to be exported  
  SET @total_amount_all_instalments = @total_amount_all_instalments + ISNULL( @instalment_amount,0)  
  
  SET @total_transactions=@total_transactions+1  
  
  -- get grouping id for each instalment  
  SET @temp = 0  
  
  INSERT INTO #temp_pfinstalments_id  
  SELECT Min([PFI].pfinstalments_id)  
  FROM PFInstalments [PFI] with (nolock)  
  
   JOIN PFInstalments_Transaction [PFIT] with (nolock) ON  
    [PFIT].PFInstalments_Transaction_id=PFI.TransactionCode  
  
   LEFT JOIN PFPremiumFinance[PLN] with (nolock) ON  
    [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
       AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
   LEFT JOIN PFScheme[SCH] with (nolock) on  
    [SCH].schemeversion = [PLN].schemeversion  
       AND [SCH].schemeno = [PLN].schemeno  
       AND [SCH].companyno = [PLN].companyno  
  
    LEFT JOIN bankaccount [SCHBNK] ON  
     [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
   LEFT JOIN MediaType[MTP] with (nolock) ON  
  [MTP].mediatype_id = [SCH].mediatype_id  
  
   LEFT JOIN MediaType_Validation[MTV] with (nolock) ON  
    [MTV].mediatype_validation_id = [MTP].mediatype_validation_id  
  
   LEFT JOIN Party[PTY] with (nolock)  ON  
    [PTY].party_cnt = [PLN].clientid  
  
   LEFT JOIN pfpaymentmethod pfpm with (nolock) ON  
    pfpm.PFPaymentMethod_cnt = sch.PaymentMethod_cnt  
  
   LEFT JOIN PFRF with (nolock) on  
    PFRF.pfrf_id=[PLN].pfrf_id  
  
  WHERE [PFI].duedate <= @due_date  
  AND Day([PFI].duedate) >= CASE WHEN @due_day > 0 THEN @due_day ELSE 1  END  
  AND Day([PFI].duedate) <= CASE WHEN @due_day > 0 THEN @due_day ELSE 31  END  
  AND ([PFI].Batch_ID is Null OR [PFI].Status = 5 OR [PFI].Status = 7)  
  AND ((@bank_account_name ='') OR ([SCHBNK].description = @bank_account_name))  
  AND [MTP].code = @media_type_code  
  AND ([PLN].StatusInd='040'  OR (pfit.code  IN ('0N','0C') and [pln].StatusInd <> '999'))  
  AND [PLN].autogeneratedplanref = @plan_autogeneratedplanref  
  AND ([PFI].Status = 1 OR [PFI].Status = 5)  
  AND (ISNULL([PFI].failure_count,0)<=PFRF.retry_limit OR PFRF.retry_limit = 0)  
  AND ((pfit.code <> '0N' and pfi.instalmentNumber <> 0 and pfpm.excludeaudis = 1) or (isnull(pfpm.excludeaudis,0) <> 1))  
  AND [PTY].shortname = @party_shortname  
  AND (  
  ((@plan_cc_number IS NOT NULL) AND ([PLN].cc_number = @plan_cc_number))  
   OR (([PLN].BankAccountNo = @plan_bankaccountno) AND ([PLN].BankSortCode = @plan_banksortcode))  
   OR (([PLN].business_identifier_code = @plan_business_identifier_code)   AND ([PLN].international_bank_account_number) = @plan_international_bank_account_number )  
   )  
  AND ((@sysOptionCollectINSFailedStatus = '1') OR (@sysOptionCollectINSFailedStatus = '0' AND CONVERT(VARCHAR(12),[PFI].pfprem_finance_cnt)+'-'+ CONVERT(VARCHAR(12),[PFI].pfprem_finance_version)  
   NOT IN  (SELECT CONVERT(VARCHAR(12),pfprem_finance_cnt)+'-'+ CONVERT(VARCHAR(12),pfprem_finance_version) FROM PFInstalments WITH(NOLOCK)  
   WHERE PFInstalments.Status=6 AND PFInstalments.pfprem_finance_cnt=[PFI].pfprem_finance_cnt  
   AND PFInstalments.pfprem_finance_version=[PFI].pfprem_finance_version))  
  )  
  
  GROUP BY  
   [PFI].group_id,  
   [PFI].duedate,  
   [PTY].shortname,  
   [PLN].BankAccountNo,  
   [PLN].business_identifier_code,  
   [PLN].international_bank_account_number,  
   [PLN].BankSortCode,  
   [PLN].cc_number,  
   [PLN].clientname,  
   [PLN].companyname,  
   [PLN].bankaccountname,  
    [PLN].BankName,  
   [PTY].alternative_identifier,  
   [PLN].autogeneratedplanref  
  
  Select @temp = Min(pfinstalments_id) from #temp_pfinstalments_id  
  
  delete from #temp_pfinstalments_id  
  
  -- update instalment with grouping item id  
  UPDATE PFInstalments SET Group_ID = @temp WHERE PFInstalments_ID = @instalment_pfinstalments_id  
  
  -- Get the next instalment to export  
  FETCH NEXT FROM Instalment_Export  
  INTO  
   @instalment_pfinstalments_id,  
   @instalment_duedate,  
   @party_shortname,  
   @plan_clientname,  
   @plan_companyname,  
   @plan_cc_number,  
   @plan_bankaccountname,  
   @plan_bankaccountno,  
   @plan_business_identifier_code,  
   @plan_international_bank_account_number,  
   @plan_banksortcode,  
   @plan_bankname,  
   @instalment_amount,  
   @party_alternative_identifier,  
   @party_agent_cnt,  
   @instalments_group_id,  
   @instalment_status_id,  
   @instalment_status_description,  
   @instalment_transaction_code,  
   @plan_autogeneratedplanref,  
   @instalment_instalmentnumber,  
   @plan_cc_expiry_date,  
   @plan_cc_start_date,  
   @plan_cc_issue,  
   @plan_cc_pin  
  
 END  
  
 CLOSE Instalment_Export  
 OPEN Instalment_Export  
  
 DROP TABLE #temp_pfinstalments_id  
  
 FETCH NEXT FROM Instalment_Export  
 INTO  
  @instalment_pfinstalments_id,  
  @instalment_duedate,  
  @party_shortname,  
  @plan_clientname,  
  @plan_companyname,  
  @plan_cc_number,  
  @plan_bankaccountname,  
  @plan_bankaccountno,  
  @plan_business_identifier_code,  
  @plan_international_bank_account_number,  
  @plan_banksortcode,  
  @plan_bankname,  
  @instalment_amount,  
  @party_alternative_identifier,  
  @party_agent_cnt,  
  @instalments_group_id,  
  @instalment_status_id,  
  @instalment_status_description,  
  @instalment_transaction_code,  
  @plan_autogeneratedplanref,  
  @instalment_instalmentnumber,  
  @plan_cc_expiry_date,  
  @plan_cc_start_date,  
  @plan_cc_issue,  
  @plan_cc_pin  
  
 WHILE @@FETCH_STATUS = 0  
 BEGIN  
  -- update each instalment that is being exported with the batch reference  
  -- to mark them as being part of this batch - do this after the grouping has  
  -- taken place as throws out the existing grouping code  
  UPDATE PFInstalments  
  SET batch_id = @batch_id,  
  Status = 2  
  WHERE pfinstalments_id = @instalment_pfinstalments_id  
  
  -- Get the next instalment to export  
  FETCH NEXT FROM Instalment_Export  
  INTO  
   @instalment_pfinstalments_id,  
   @instalment_duedate,  
   @party_shortname,  
   @plan_clientname,  
   @plan_companyname,  
   @plan_cc_number,  
   @plan_bankaccountname,  
   @plan_bankaccountno,  
   @plan_business_identifier_code,  
   @plan_international_bank_account_number,  
   @plan_banksortcode,  
   @plan_bankname,  
   @instalment_amount,  
   @party_alternative_identifier,  
   @party_agent_cnt,  
   @instalments_group_id,  
   @instalment_status_id,  
   @instalment_status_description,  
   @instalment_transaction_code,  
   @plan_autogeneratedplanref,  
   @instalment_instalmentnumber,  
   @plan_cc_expiry_date,  
   @plan_cc_start_date,  
   @plan_cc_issue,  
   @plan_cc_pin  
  
 END  
  
 DEALLOCATE Instalment_Export  
  
 -- open cursor on the group records  
 DECLARE Instalment_Export CURSOR FAST_FORWARD FOR  
 SELECT  
  MIN([PFI].pfinstalments_id),  
  MAX([PFI].duedate),  
  [PTY].shortname,  
  [PLN].clientname,  
  [PLN].companyname,  
         [PLN].cc_number,  
  [PLN].bankaccountname,  
  [PLN].BankAccountNo,  
  [PLN].business_identifier_code,  
  [PLN].international_bank_account_number,  
  [PLN].BankSortCode,  
  [PLN].BankName,  
         SUM([PFI].amount),  
  [PTY].alternative_identifier,  
  [PTY].agent_cnt,  
  [PFI].group_id,  
  0,  
  '',  
  MIN([PFIT].Code),  
  PLN.AutoGeneratedPlanRef,  
  0,  
  [PLN].cc_expiry_date,  
  [PLN].cc_start_date,  
  [PLN].cc_issue,  
  [PLN].cc_pin  
  
 FROM PFInstalments [PFI]  
  JOIN PFInstalments_Status [PFIS] ON  
   [PFIS].PFInstalments_Status_id=PFI.Status  
  
  JOIN PFInstalments_Transaction [PFIT] ON  
   [PFIT].PFInstalments_Transaction_id=[PFI].TransactionCode  
  
  JOIN PFPremiumFinance[PLN] ON  
   [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
    AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
  JOIN PFScheme[SCH] ON  
   [SCH].schemeversion = [PLN].schemeversion  
  
      AND [SCH].schemeno = [PLN].schemeno  
      AND [SCH].companyno = [PLN].companyno  
  
  JOIN PFRF ON  
   PFRF.pfrf_id=[PLN].pfrf_id  
  
  JOIN MediaType[MTP] ON  
   [MTP].mediatype_id = [SCH].mediatype_id  
  
  JOIN Party[PTY] ON  
   [PTY].party_cnt = [PLN].clientid  
  
  left join pfpaymentmethod [PFPM] ON  
   [PFPM].PFPaymentMethod_cnt = [SCH].PaymentMethod_cnt  
  
 WHERE [PFI].batch_id =  @batch_id  
 AND [PFI].InstalmentNumber <> 0  
  
 GROUP BY  
  [PFI].group_id,  
  [PTY].shortname,  
  [PLN].BankAccountNo,  
  [PLN].business_identifier_code,  
  [PLN].international_bank_account_number,  
  [PLN].BankSortCode,  
  [PLN].AutoGeneratedPlanRef,  
  [PLN].cc_number,  
  [PLN].clientname,  
  [PLN].companyname,  
  [PLN].bankaccountname,  
  [PLN].BankName ,  
  [PTY].alternative_identifier,  
  [PTY].agent_cnt,  
  [PLN].cc_expiry_date,  
  [PLN].cc_start_date,  
  [PLN].cc_issue,  
  [PLN].cc_pin  
  
 UNION  
  
 SELECT  
  [PFI].pfinstalments_id,  
  [PFI].duedate,  
  [PTY].shortname,  
  [PLN].clientname,  
  [PLN].companyname,  
  [PLN].cc_number,  
  [PLN].bankaccountname,  
  [PLN].BankAccountNo,  
  [PLN].business_identifier_code,  
  [PLN].international_bank_account_number,  
  [PLN].BankSortCode,  
  [PLN].BankName,  
  [PFI].amount,  
  [PTY].alternative_identifier,  
  [PTY].agent_cnt,  
  0,  
  [PFI].Status,  
  [PFIS].Description,  
  [PFIT].Code,  
  [PLN].AutoGeneratedPlanRef,  
  [PFI].InstalmentNumber,  
  [PLN].cc_expiry_date,  
  [PLN].cc_start_date,  
  [PLN].cc_issue,  
  [PLN].cc_pin  
  
 FROM PFInstalments [PFI]  
  
    JOIN PFInstalments_Status [PFIS] ON  
    [PFIS].PFInstalments_Status_id=[PFI].Status  
  
    JOIN PFInstalments_Transaction [PFIT] ON  
    [PFIT].PFInstalments_Transaction_id=[PFI].TransactionCode  
  
    JOIN PFPremiumFinance[PLN] ON  
    [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
    AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
    JOIN PFScheme[SCH] on  
    [SCH].schemeversion = [PLN].schemeversion  
    AND [SCH].schemeno = [PLN].schemeno  
    AND [SCH].companyno = [PLN].companyno  
  
    LEFT JOIN pfpaymentmethod [PFPM] ON  
    [PFPM].PFPaymentMethod_cnt = [SCH].PaymentMethod_cnt  
  
    JOIN PFRF on  
    PFRF.pfrf_id=[PLN].pfrf_id  
  
    JOIN MediaType[MTP] ON  
    [MTP].mediatype_id = [SCH].mediatype_id  
  
    JOIN Party[PTY] ON  
    [PTY].party_cnt = [PLN].clientid  
  
 WHERE [PFI].batch_id = @batch_id  
 AND [PFI].InstalmentNumber = 0  
 ORDER BY Max([PFI].duedate)  
  
 OPEN Instalment_Export  
  
 FETCH NEXT FROM Instalment_Export  
 INTO  
  @instalment_pfinstalments_id,  
  @instalment_duedate,  
  @party_shortname,  
  @plan_clientname,  
  @plan_companyname,  
  @plan_cc_number,  
  @plan_bankaccountname,  
  @plan_bankaccountno,  
  @plan_business_identifier_code,  
  @plan_international_bank_account_number,  
  @plan_banksortcode,  
  @plan_bankname,  
  @instalment_amount,  
  @party_alternative_identifier,  
  @party_agent_cnt,  
  @instalments_group_id,  
  @instalment_status_id,  
  @instalment_status_description,  
  @instalment_transaction_code,  
  @plan_autogeneratedplanref,  
  @instalment_instalmentnumber,  
  @plan_cc_expiry_date,  
  @plan_cc_start_date,  
  @plan_cc_issue,  
  @plan_cc_pin  
  
 WHILE @@FETCH_STATUS = 0  
 BEGIN  
  
  SET @total_amount_grouped_instalments = @total_amount_grouped_instalments + @instalment_amount  
  
  -- Moved the logic for calculating the total transactions from here to first cursor.  
  -- The input to this cursor is the result of a group by query which means it is not a right place to count individual transactions  
  -- SET @total_transactions = @total_transactions + 1  
  
  -- Get the next instalment to export  
  FETCH NEXT FROM Instalment_Export  
  INTO  
    @instalment_pfinstalments_id,  
    @instalment_duedate,  
    @party_shortname,  
    @plan_clientname,  
    @plan_companyname,  
    @plan_cc_number,  
    @plan_bankaccountname,  
    @plan_bankaccountno,  
    @plan_business_identifier_code,  
    @plan_international_bank_account_number,  
    @plan_banksortcode,  
    @plan_bankname,  
    @instalment_amount,  
    @party_alternative_identifier,  
    @party_agent_cnt,  
    @instalments_group_id,  
    @instalment_status_id,  
    @instalment_status_description,  
    @instalment_transaction_code,  
    @plan_autogeneratedplanref,  
    @instalment_instalmentnumber,  
    @plan_cc_expiry_date,  
    @plan_cc_start_date,  
    @plan_cc_issue,  
    @plan_cc_pin  
  
 END  
  
 IF @total_amount_grouped_instalments <> @total_amount_all_instalments  
 BEGIN  
  SET @status =1  
  RETURN  
 END  
 ELSE  
 BEGIN  
  -- totals match so grouping update has been successful  
  -- update batch with relevant details  
  UPDATE Batch  
  SET batchstatus_id = @BatchStatus_Batch_Exported,  
  total_amount = @total_amount_all_instalments,  
  total_transactions = @total_transactions  
  WHERE batch_id = @batch_id  
 END  
  
 CLOSE Instalment_Export  
 DEALLOCATE Instalment_Export  
END  
ELSE  
BEGIN  
 SELECT @total_amount_grouped_instalments = total_amount, @total_transactions = total_transactions from Batch WHERE batch_id = @Batch_id  
END  
  
SELECT  
 1                                       As Tag,  
  Null                                    As Parent,  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id                               As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                             As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
    NULL          AS [SCHEME_HEADER!2!record_type],  
    NULL          AS [SCHEME_HEADER!2!scheme_number],  
    NULL          AS [SCHEME_HEADER!2!scheme_version],  
    NULL          AS [SCHEME_HEADER!2!financial_institution_code],  
    NULL          AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
    NULL          AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
    NULL          AS [SCHEME_HEADER!2!scheme_description],  
    NULL          AS [SCHEME_HEADER!2!processing_date],  
    NULL          AS [SCHEME_HEADER!2!scheme_bank_code],  
    NULL          AS [SCHEME_HEADER!2!scheme_bank_number],  
    NULL          AS [SCHEME_HEADER!2!remitter],  
    NULL          AS [SCHEME_HEADER!2!merchant_id],  
 NULL    AS [SCHEME_HEADER!2!sepa_scheme_bic],  
 NULL       AS [SCHEME_HEADER!2!sepa_scheme_iban],  
    NULL          AS [SCHEME_TRANSACTION!3!record_type],  
    NULL           AS [SCHEME_TRANSACTION!3!plan_bank_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
 NULL          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
 NULL          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
    NULL           AS [SCHEME_TRANSACTION!3!transaction_code],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_amount],  
    NULL          AS [SCHEME_TRANSACTION!3!client_name],  
 NULL          AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent businesss  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_reference],  
    NULL          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    NULL     as [SCHEME_TRANSACTION!3!instalment_group_id],  
    NULL          as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_company_name],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 NULL    AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 NULL    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    NULL   AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 NULL   AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
UNION ALL  
  
SELECT  
 2                                       As Tag,  
  1          As Parent,  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id                               As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                             As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
  0          AS [SCHEME_HEADER!2!record_type],  
    [SCH].schemeno         AS [SCHEME_HEADER!2!scheme_number],  
    [SCH].schemeversion        AS [SCHEME_HEADER!2!scheme_version],  
    MIN([SCH].financial_institution_code)      AS [SCHEME_HEADER!2!financial_institution_code],  
    MIN([SCH].direct_debit_supplier_name)      AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
    MIN([SCH].direct_debit_supplier_id)      AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
    MIN([SCH].schemedescription)       AS [SCHEME_HEADER!2!scheme_description],  
    DATEADD(dd,ISNULL(MIN([SCH].processing_days),0),GetDate())   AS [SCHEME_HEADER!2!processing_date],  
    MIN([SCHBNK].code)        AS [SCHEME_HEADER!2!scheme_bank_code],  
    MIN([SCHBNK].bank_account_no)       AS [SCHEME_HEADER!2!scheme_bank_number],  
    MIN([SCH].remitter)        AS [SCHEME_HEADER!2!remitter],  
    MIN([AC].merchant_id)      AS [SCHEME_HEADER!2!merchant_id],  
    ISNULL(MIN([SCHBNK].business_identifier_code),'')      AS [SCHEME_HEADER!2!sepa_scheme_bic],  
    ISNULL(MIN([SCHBNK].international_bank_account_number),'')      AS [SCHEME_HEADER!2!sepa_scheme_iban],  
    NULL          AS [SCHEME_TRANSACTION!3!record_type],  
    NULL           AS [SCHEME_TRANSACTION!3!plan_bank_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
 NULL          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
 NULL          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
    NULL           AS [SCHEME_TRANSACTION!3!transaction_code],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_amount],  
    NULL          AS [SCHEME_TRANSACTION!3!client_name],  
 NULL          AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent businesss  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_reference],  
    NULL          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    NULL          as [SCHEME_TRANSACTION!3!instalment_group_id],  
    NULL          as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    NULL          AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_company_name],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 NULL    AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 NULL    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    NULL          AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
  NULL          AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    NULL   AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 NULL   AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
FROM PFScheme [SCH]  
  
    LEFT JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
    INNER JOIN account [AC] ON  
    [SCHBNK].account_id = [AC].account_id  
  
    INNER JOIN (SELECT distinct schemeno, schemeversion, pfprem_finance_cnt, pfprem_finance_version , insurance_file_cnt  
    FROM pfpremiumfinance) [PLN] ON  
    [SCH].schemeno = [PLN].schemeno  
    and  [SCH].schemeversion = [PLN].schemeversion  
  
    INNER JOIN (SELECT distinct pfprem_finance_cnt as pfprem_finance_cnt, pfprem_finance_version as pfprem_finance_version, pfmediatype_history_id  
    FROM pfinstalments  
    WHERE batch_id = @batch_id) [PFI] ON  
    [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
    AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
    LEFT OUTER JOIN PFMediaTypeHistory [PMH] ON  
    [PMH].PfMediaTypeHistory_id = [PFI].pfmediatype_history_id  
  
    INNER JOIN Insurance_file [IFILE]     ON  
    [IFILE].insurance_file_cnt = [PLN].insurance_file_cnt  
  
WHERE  (SELECT count(*) FROM insurance_file [INSFILE]  
 WHERE Insurance_folder_Cnt IN  
 (Select insurance_folder_cnt From insurance_file where insurance_file_cnt =[IFILE].insurance_file_cnt)  
 AND lapsed_reason_id = (Select lapsed_reason_id from lapsed_reason where code ='CCNTRL'))=0  
  
GROUP BY [SCH].schemeno,  
  [SCH].schemeversion  
  
UNION ALL  
((  
SELECT  
 3                                       As Tag,  
  2                                     As Parent,  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id                               As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                             As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
  0          AS [SCHEME_HEADER!2!record_type],  
  [SCH].schemeno         AS [SCHEME_HEADER!2!scheme_number],  
  [SCH].schemeversion        AS [SCHEME_HEADER!2!scheme_version],  
  [SCH].financial_institution_code      AS [SCHEME_HEADER!2!financial_institution_code],  
  [SCH].direct_debit_supplier_name      AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
  [SCH].direct_debit_supplier_id       AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
  [SCH].schemedescription        AS [SCHEME_HEADER!2!scheme_description],  
  DATEADD(dd,ISNULL([SCH].processing_days,0),GetDate())    AS [SCHEME_HEADER!2!processing_date],  
  [SCHBNK].code         AS [SCHEME_HEADER!2!scheme_bank_code],  
  [SCHBNK].bank_account_no       AS [SCHEME_HEADER!2!scheme_bank_number],  
  [SCH].remitter         AS [SCHEME_HEADER!2!remitter],  
  [AC].merchant_id          AS [SCHEME_HEADER!2!merchant_id],  
  ISNULL([SCHBNK].business_identifier_code,'')      AS [SCHEME_HEADER!2!sepa_scheme_bic],  
  ISNULL([SCHBNK].international_bank_account_number,'')      AS [SCHEME_HEADER!2!sepa_scheme_iban],  
  1            AS [SCHEME_TRANSACTION!3!record_type],  
  ISNULL([PMH].banksortcode,'')        AS [SCHEME_TRANSACTION!3!plan_bank_code],  
  [PMH].bankaccountno        AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
  ISNULL([PMH].business_identifier_code,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
  ISNULL([PMH].international_bank_account_number,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
  13           AS [SCHEME_TRANSACTION!3!transaction_code],  
  [PFIT].code         AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
  [PFI].amount         AS [SCHEME_TRANSACTION!3!grouped_amount],  --(Prakash Varghese)-PN 60610-Removed rounding off  
Case  
  WHEN [PLN].Agent_Cnt IS NULL THEN [PLN].clientname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!client_name],  
Case  
 WHEN UPPER([PAG].resolved_name) LIKE '%ONLINE%' THEN 1  
 ELSE 0  
 END AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent business  
    [PMH].AutoGeneratedPlanRef       AS [SCHEME_TRANSACTION!3!grouped_reference],  
    0          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    0          AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    0          as [SCHEME_TRANSACTION!3!instalment_group_id],  
    [PFI].duedate         as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    [PFI].status         AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    [PFIS].description        AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    [PLN].companyname        AS [SCHEME_TRANSACTION!3!plan_company_name],  
    [PMH].bankaccountname        AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    ISNULL([PMH].banksortcode,'')        AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    [PMH].Bankname         AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 [PB].account_type  AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 Cty.[code]    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    [PMH].cc_number         AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    [PMH].cc_expiry_date        AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    [PMH].cc_start_date        AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    [PMH].cc_issue         AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    [PMH].cc_pin         AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
    [PLN].auth_code          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    Case  
 WHEN [PLN].Agent_Cnt IS NULL THEN [PTY].shortname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
    [PTY].alternative_identifier AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    Case  
 WHEN [PFI].InstalmentNumber = 0 THEN [PLN].deposit_cc_tracking_number  
 ELSE NULL  
 END AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 NULL   AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
FROM PFInstalments [PFI]  
  
    JOIN PFInstalments_Status [PFIS] ON  
    [PFIS].PFInstalments_Status_id=PFI.Status  
  
    INNER JOIN PFPremiumFinance [PLN] ON  
    [PFI].pfprem_finance_cnt = [PLN].pfprem_finance_cnt  
    AND  [PFI].pfprem_finance_version = [PLN].pfprem_finance_version  
  
 LEFT JOIN Party_Bank [PB] ON   --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 [PB].party_bank_id = [PLN].party_bank_id  
  
 LEFT JOIN Country Cty  --(Derick de Klerk) Joining Country to retrieve Bank Country  
 ON Cty.country_id = PB.bank_country  
  
    INNER JOIN PFMediaTypeHistory [PMH] ON  
    [PMH].PfMediaTypeHistory_id = [PFI].pfmediatype_history_id  
  
    JOIN Party[PTY] ON  
    [PTY].party_cnt = [PLN].clientid  
  
    INNER JOIN PfScheme [SCH] ON  
    [SCH].schemeno = [PLN].schemeno  
    and  [SCH].schemeversion = [PLN].schemeversion  
  
    LEFT JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
    INNER JOIN account [AC] ON  
    [SCHBNK].account_id = [AC].account_id  
  
    INNER JOIN PFInstalments_Transaction [PFIT] ON  
    [PFIT].PFInstalments_Transaction_id = [PFI].TransactionCode  
  
INNER JOIN Insurance_file [IFILE]     ON  
[IFILE].insurance_file_cnt = [PLN].insurance_file_cnt  
  
    LEFT JOIN PArty_Agent PA  
    ON PA.Party_cnt = [PLN].Agent_cnt  
  
 LEFT JOIN Party [PAG]     --(Derick de Klerk) Joining Party again for Agent Groups to determine if online broker  
 ON PA.linked_account_group = [PAG].party_cnt  
  
WHERE [PFI].batch_id = @batch_id  
AND [PFI].instalmentnumber = 0  
AND (SELECT count(*) FROM insurance_file [INSFILE]  
 WHERE Insurance_folder_Cnt IN  
 (Select insurance_folder_cnt From insurance_file where insurance_file_cnt =[IFILE].insurance_file_cnt)  
 AND lapsed_reason_id = (Select lapsed_reason_id from lapsed_reason where code ='CCNTRL'))=0)  
  
UNION  
  
(SELECT  
 3                                       As Tag,  
  2                                     As Parent,  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id    As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                             As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
  0          AS [SCHEME_HEADER!2!record_type],  
  [SCH].schemeno         AS [SCHEME_HEADER!2!scheme_number],  
  [SCH].schemeversion        AS [SCHEME_HEADER!2!scheme_version],  
  [SCH].financial_institution_code      AS [SCHEME_HEADER!2!financial_institution_code],  
  [SCH].direct_debit_supplier_name      AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
  [SCH].direct_debit_supplier_id       AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
  [SCH].schemedescription        AS [SCHEME_HEADER!2!scheme_description],  
  DATEADD(dd,ISNULL([SCH].processing_days,0),GetDate())    AS [SCHEME_HEADER!2!processing_date],  
  [SCHBNK].code         AS [SCHEME_HEADER!2!scheme_bank_code],  
  [SCHBNK].bank_account_no       AS [SCHEME_HEADER!2!scheme_bank_number],  
  [SCH].remitter         AS [SCHEME_HEADER!2!remitter],  
  [AC].merchant_id          AS [SCHEME_HEADER!2!merchant_id],  
  ISNULL([SCHBNK].business_identifier_code,'')      AS [SCHEME_HEADER!2!sepa_scheme_bic],  
  ISNULL([SCHBNK].international_bank_account_number,'')      AS [SCHEME_HEADER!2!sepa_scheme_iban],  
  1          AS [SCHEME_TRANSACTION!3!record_type],  
  [PLN].banksortcode        AS [SCHEME_TRANSACTION!3!plan_bank_code],  
  [PLN].bankaccountno        AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
  ISNULL([PLN].business_identifier_code,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
  ISNULL([PLN].international_bank_account_number,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
  13           AS [SCHEME_TRANSACTION!3!transaction_code],  
  MIN([PFIT].code)        AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
  SUM([PFI].amount)        AS [SCHEME_TRANSACTION!3!grouped_amount], --(Prakash Varghese)-PN 60610-Removed rounding off  
  
  Case  
    WHEN [PLN].Agent_Cnt IS NULL THEN [PLN].clientname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!client_name],  
  Case  
 WHEN UPPER([PAG].resolved_name) LIKE '%ONLINE%' THEN 1  
 ELSE 0  
 END AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent business  
    MIN([PLN].AutoGeneratedPlanRef)       AS [SCHEME_TRANSACTION!3!grouped_reference],  
    0          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    MIN([PFI].instalmentnumber)       AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    [PFI].group_id         as [SCHEME_TRANSACTION!3!instalment_group_id],  
    MIN([PFI].duedate)        as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    MIN([PFI].status)        AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    MIN([PFIS].description)        AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    [PLN].companyname        AS [SCHEME_TRANSACTION!3!plan_company_name],  
    [PLN].bankaccountname        AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    [PLN].BankSortCode        AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    [PLN].Bankname         AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 [PB].account_type  AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 Cty.[code]    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    [PLN].cc_number         AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    [PLN].cc_expiry_date        AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    [PLN].cc_start_date        AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    [PLN].cc_issue         AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    [PLN].cc_pin         AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
    [PLN].auth_code          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    Case  
     WHEN [PLN].Agent_Cnt IS NULL THEN [PTY].shortname  
     ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
    [PTY].alternative_identifier       AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    Case  
 WHEN [PFI].InstalmentNumber = 0 THEN [PLN].deposit_cc_tracking_number  
 ELSE NULL  
    END AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    NULL   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 NULL   AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
FROM PFInstalments [PFI]  
  
    JOIN PFInstalments_Status [PFIS] ON  
    [PFIS].PFInstalments_Status_id=PFI.Status  
  
    JOIN PFInstalments_Transaction [PFIT] ON  
    [PFIT].PFInstalments_Transaction_id=[PFI].TransactionCode  
  
    JOIN PFPremiumFinance[PLN] ON  
    [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
    AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
 LEFT JOIN Party_Bank [PB] ON   --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 [PB].party_bank_id = [PLN].party_bank_id  
  
 LEFT JOIN Country Cty  --(Derick de Klerk) Joining Country to retrieve Bank Country  
 ON Cty.country_id = PB.bank_country  
  
    JOIN PFScheme[SCH] ON  
    [SCH].schemeversion = [PLN].schemeversion  
    AND [SCH].schemeno = [PLN].schemeno  
    AND [SCH].companyno = [PLN].companyno  
  
    JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
    INNER JOIN account [AC] ON  
    [SCHBNK].account_id = [AC].account_id  
  
    JOIN Party[PTY] ON  
    [PTY].party_cnt = [PLN].clientid  
    LEFT JOIN PArty_Agent PA  
    ON PA.Party_cnt = [PLN].Agent_cnt  
  
 LEFT JOIN Party [PAG]     --(Derick de Klerk) Joining Party again for Agent Groups to determine if online broker  
 ON PA.linked_account_group = [PAG].party_cnt  
  
WHERE [PFI].batch_id = @batch_id  
AND [PFI].InstalmentNumber <> 0  
  
GROUP BY  
    [SCH].schemeno,  
    [SCH].schemeversion,  
    [SCH].financial_institution_code,  
    [SCH].direct_debit_supplier_name,  
    [SCH].direct_debit_supplier_id,  
    [SCH].schemedescription,  
    [SCH].processing_days,  
    [SCHBNK].code,  
    [SCHBNK].bank_account_no,  
    [SCH].remitter,  
    [AC].merchant_id,  
    [SCHBNK].business_identifier_code,  
    [SCHBNK].international_bank_account_number,  
    [PLN].banksortcode,  
    [PLN].bankaccountno,  
 [PLN].business_identifier_code,  
 [PLN].international_bank_account_number,  
    [PLN].clientname,  
    [PLN].companyname,  
    [PLN].bankaccountname,  
    [PLN].BankSortCode,  
    [PLN].Bankname,  
 [PB].account_type,  
    [PLN].cc_number,  
    [PLN].cc_expiry_date,  
    [PLN].cc_start_date,  
    [PLN].cc_issue,  
    [PLN].cc_pin,  
 [PLN].auth_code,  
    [PTY].shortname,  
    [PTY].alternative_identifier,  
    [PFI].group_id,  
    [PFI].transactioncode,  
    [PLN].Agent_Cnt,  
    [PA].Trading_Name,  
    [PFI].InstalmentNumber,  
    [PLN].deposit_cc_tracking_number,  
 [PAG].resolved_name,  
 Cty.[code]  
)  
)  
UNION ALL  
  
(  
(  
SELECT  
 4                                       As Tag,  
  3                                     As Parent,  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id                               As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                             As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
  0          AS [SCHEME_HEADER!2!record_type],  
  [SCH].schemeno         AS [SCHEME_HEADER!2!scheme_number],  
  [SCH].schemeversion        AS [SCHEME_HEADER!2!scheme_version],  
  [SCH].financial_institution_code      AS [SCHEME_HEADER!2!financial_institution_code],  
  [SCH].direct_debit_supplier_name      AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
  [SCH].direct_debit_supplier_id       AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
  [SCH].schemedescription        AS [SCHEME_HEADER!2!scheme_description],  
  DATEADD(dd,ISNULL([SCH].processing_days,0),GetDate())    AS [SCHEME_HEADER!2!processing_date],  
  [SCHBNK].code         AS [SCHEME_HEADER!2!scheme_bank_code],  
  [SCHBNK].bank_account_no       AS [SCHEME_HEADER!2!scheme_bank_number],  
  [SCH].remitter         AS [SCHEME_HEADER!2!remitter],  
  [AC].merchant_id          AS [SCHEME_HEADER!2!merchant_id],  
  ISNULL([SCHBNK].business_identifier_code,'')      AS [SCHEME_HEADER!2!sepa_scheme_bic],  
  ISNULL([SCHBNK].international_bank_account_number,'')      AS [SCHEME_HEADER!2!sepa_scheme_iban],  
  1          AS [SCHEME_TRANSACTION!3!record_type],  
  ISNULL([PMH].banksortcode,'')        AS [SCHEME_TRANSACTION!3!plan_bank_code],  
  [PMH].bankaccountno        AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
  ISNULL([PMH].business_identifier_code,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
  ISNULL([PMH].international_bank_account_number,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
  13           AS [SCHEME_TRANSACTION!3!transaction_code],  
  [PFIT].code         AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
  [PFI].amount         AS [SCHEME_TRANSACTION!3!grouped_amount],  --(Prakash Varghese)-PN 60610-Removed rounding off  
Case  
    WHEN [PLN].Agent_Cnt IS NULL THEN [PLN].clientname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!client_name],  
Case  
 WHEN UPPER([PAG].resolved_name) LIKE '%ONLINE%' THEN 1  
 ELSE 0  
 END AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent business  
    [PMH].AutoGeneratedPlanRef       AS [SCHEME_TRANSACTION!3!grouped_reference],  
    0          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    0          AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    0          as [SCHEME_TRANSACTION!3!instalment_group_id],  
    [PFI].duedate         as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    [PFI].status         AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    [PFIS].description        AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    [PLN].companyname        AS [SCHEME_TRANSACTION!3!plan_company_name],  
    [PMH].bankaccountname        AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    ISNULL([PMH].banksortcode,'')        AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    [PMH].Bankname         AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 [PB].account_type  AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 Cty.[code]    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    [PMH].cc_number         AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    [PMH].cc_expiry_date        AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    [PMH].cc_start_date        AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    [PMH].cc_issue         AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    [PMH].cc_pin         AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
    [PLN].auth_code          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    Case  
 WHEN [PLN].Agent_Cnt IS NULL THEN [PTY].shortname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
    [PTY].alternative_identifier AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    Case  
 WHEN [PFI].InstalmentNumber = 0 THEN [PLN].deposit_cc_tracking_number  
 ELSE NULL  
 END AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    [PLN].insurance_file_cnt   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    [IFILE].insurance_ref   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 (  
  SELECT LTRIM(RTRIM(iso_code))  
  FROM Currency  
  WHERE currency_id =  
      (CASE  
       WHEN ISNULL([PLN].use_trans_currency,0) = 1  
        THEN [IFILE].currency_id  
       ELSE [IFILE].base_currency_id  
      END)  
 ) AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
FROM PFInstalments [PFI]  
  
    JOIN PFInstalments_Status [PFIS] ON  
    [PFIS].PFInstalments_Status_id=PFI.Status  
  
    INNER JOIN PFPremiumFinance [PLN] ON  
    [PFI].pfprem_finance_cnt = [PLN].pfprem_finance_cnt  
    AND  [PFI].pfprem_finance_version = [PLN].pfprem_finance_version  
  
 LEFT JOIN Party_Bank [PB] ON   --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 [PB].party_bank_id = [PLN].party_bank_id  
  
 LEFT JOIN Country Cty  --(Derick de Klerk) Joining Country to retrieve Bank Country  
 ON Cty.country_id = PB.bank_country  
  
    INNER JOIN PFMediaTypeHistory [PMH] ON  
    [PMH].PfMediaTypeHistory_id = [PFI].pfmediatype_history_id  
  
    JOIN Party[PTY] ON  
    [PTY].party_cnt = [PLN].clientid  
  
    INNER JOIN PfScheme [SCH] ON  
    [SCH].schemeno = [PLN].schemeno  
    and  [SCH].schemeversion = [PLN].schemeversion  
  
    LEFT JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
    INNER JOIN account [AC] ON  
    [SCHBNK].account_id = [AC].account_id  
  
    INNER JOIN PFInstalments_Transaction [PFIT] ON  
    [PFIT].PFInstalments_Transaction_id = [PFI].TransactionCode  
  
    INNER JOIN Insurance_file [IFILE]     ON  
    [IFILE].insurance_file_cnt = [PLN].insurance_file_cnt  
  
    LEFT JOIN PArty_Agent PA  
    ON PA.Party_cnt = [PLN].Agent_cnt  
  
 LEFT JOIN Party [PAG]     --(Derick de Klerk) Joining Party again for Agent Groups to determine if online broker  
 ON PA.linked_account_group = [PAG].party_cnt  
  
WHERE [PFI].batch_id = @batch_id  
AND [PFI].instalmentnumber = 0  
AND (SELECT count(*) FROM insurance_file [INSFILE]  
 WHERE Insurance_folder_Cnt IN  
 (Select insurance_folder_cnt From insurance_file where insurance_file_cnt =[IFILE].insurance_file_cnt)  
 AND lapsed_reason_id = (Select lapsed_reason_id from lapsed_reason where code ='CCNTRL'))=0)  
  
UNION  
(  
SELECT  
 4                                       As Tag,  
  3                                     As Parent,  
      'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321'   As [EXPORT_HEADER!1!xmlns],  
        'http://www.w3.org/2001/XMLSchema-instance'            As [EXPORT_HEADER!1!xmlns:xsi],  
        'http://www.siriusfs.com/SFI/Export/Instalment_Export/20060321 Instalment_Export.xsd'   As [EXPORT_HEADER!1!xsi:schemaLocation],  
        GetDate()                               As [EXPORT_HEADER!1!date_exported],  
        'Instalment_Export'                            As [EXPORT_HEADER!1!interface_name],  
        @batch_id                               As [EXPORT_HEADER!1!batch_id],  
        @batch_ref                     As [EXPORT_HEADER!1!batch_reference],  
        @total_transactions                    As [EXPORT_HEADER!1!total_transactions],  
        @total_amount_grouped_instalments       As [EXPORT_HEADER!1!total_amount],  
        @parameters          As [EXPORT_HEADER!1!parameters_used],  
  0          AS [SCHEME_HEADER!2!record_type],  
  [SCH].schemeno         AS [SCHEME_HEADER!2!scheme_number],  
  [SCH].schemeversion        AS [SCHEME_HEADER!2!scheme_version],  
  [SCH].financial_institution_code      AS [SCHEME_HEADER!2!financial_institution_code],  
  [SCH].direct_debit_supplier_name      AS [SCHEME_HEADER!2!direct_debit_supplier_name],  
  [SCH].direct_debit_supplier_id       AS [SCHEME_HEADER!2!direct_debit_supplier_id],  
  [SCH].schemedescription        AS [SCHEME_HEADER!2!scheme_description],  
  DATEADD(dd,ISNULL([SCH].processing_days,0),GetDate())    AS [SCHEME_HEADER!2!processing_date],  
  [SCHBNK].code         AS [SCHEME_HEADER!2!scheme_bank_code],  
  [SCHBNK].bank_account_no       AS [SCHEME_HEADER!2!scheme_bank_number],  
  [SCH].remitter         AS [SCHEME_HEADER!2!remitter],  
  [AC].merchant_id          AS [SCHEME_HEADER!2!merchant_id],  
  ISNULL([SCHBNK].business_identifier_code,'')      AS [SCHEME_HEADER!2!sepa_scheme_bic],  
  ISNULL([SCHBNK].international_bank_account_number,'')      AS [SCHEME_HEADER!2!sepa_scheme_iban],  
  1          AS [SCHEME_TRANSACTION!3!record_type],  
  [PLN].banksortcode        AS [SCHEME_TRANSACTION!3!plan_bank_code],  
  [PLN].bankaccountno        AS [SCHEME_TRANSACTION!3!plan_bank_account_number],  
  ISNULL([PLN].business_identifier_code,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_bic],  
  ISNULL([PLN].international_bank_account_number,'')          AS [SCHEME_TRANSACTION!3!sepa_plan_iban],  
  13           AS [SCHEME_TRANSACTION!3!transaction_code],  
  MIN([PFIT].code)        AS [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
  SUM([PFI].amount)        AS [SCHEME_TRANSACTION!3!grouped_amount], --(Prakash Varghese)-PN 60610-Removed rounding off  
  
  Case  
    WHEN [PLN].Agent_Cnt IS NULL THEN [PLN].clientname  
    ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!client_name],  
  Case  
 WHEN UPPER([PAG].resolved_name) LIKE '%ONLINE%' THEN 1  
 ELSE 0  
 END AS [SCHEME_TRANSACTION!3!is_online_agent], --(Derick de Klerk) Adding is_online_agent to identify if online agent business  
    MIN([PLN].AutoGeneratedPlanRef)       AS [SCHEME_TRANSACTION!3!grouped_reference],  
    0          AS [SCHEME_TRANSACTION!3!total_withholding_tax],  
    MIN([PFI].instalmentnumber)       AS [SCHEME_TRANSACTION!3!grouped_instalment_number],  
    [PFI].group_id         as [SCHEME_TRANSACTION!3!instalment_group_id],  
    MIN([PFI].duedate)        as [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
    MIN([PFI].status)        AS [SCHEME_TRANSACTION!3!grouped_instalment_status],  
    MIN([PFIS].description)        AS [SCHEME_TRANSACTION!3!grouped_instalment_status_description],  
    [PLN].companyname        AS [SCHEME_TRANSACTION!3!plan_company_name],  
    [PLN].bankaccountname        AS [SCHEME_TRANSACTION!3!plan_bank_account_name],  
    [PLN].BankSortCode        AS [SCHEME_TRANSACTION!3!plan_bank_sort_code],  
    [PLN].Bankname         AS [SCHEME_TRANSACTION!3!plan_bank_name],  
 [PB].account_type  AS [SCHEME_TRANSACTION!3!plan_bank_account_type], --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 Cty.[code]    As [SCHEME_TRANSACTION!3!plan_bank_country],  --(Derick de Klerk) Adding Client Bank Country  
    [PLN].cc_number         AS [SCHEME_TRANSACTION!3!plan_cc_number],  
    [PLN].cc_expiry_date        AS [SCHEME_TRANSACTION!3!plan_cc_expiry_date],  
    [PLN].cc_start_date        AS [SCHEME_TRANSACTION!3!plan_cc_start_date],  
    [PLN].cc_issue         AS [SCHEME_TRANSACTION!3!plan_cc_issue],  
    [PLN].cc_pin         AS [SCHEME_TRANSACTION!3!plan_cc_pin],  
 [PLN].auth_code          AS [SCHEME_TRANSACTION!3!plan_cc_auth_code],  
    Case  
     WHEN [PLN].Agent_Cnt IS NULL THEN [PTY].shortname  
     ELSE PA.Trading_Name  
    END AS [SCHEME_TRANSACTION!3!plan_party_client_name],  
    [PTY].alternative_identifier       AS [SCHEME_TRANSACTION!3!plan_party_client_alternative_identifier],  
    Case  
 WHEN [PFI].InstalmentNumber = 0 THEN [PLN].deposit_cc_tracking_number  
 ELSE NULL  
    END AS [SCHEME_TRANSACTION!3!cc_tracking_number],  
    [PLN].insurance_file_cnt   AS [SCHEME_TRANSACTION_POLICY!4!policy_id],  
    [IFILE].insurance_ref   AS [SCHEME_TRANSACTION_POLICY!4!insurance_ref],  
 (  
  SELECT LTRIM(RTRIM(iso_code))  
  FROM Currency  
  WHERE currency_id =  
      (CASE  
       WHEN ISNULL([PLN].use_trans_currency,0) = 1  
        THEN [IFILE].currency_id  
       ELSE [IFILE].base_currency_id  
      END)  
 ) AS [SCHEME_TRANSACTION_POLICY!4!currency_code]  
FROM PFInstalments [PFI]  
  
    JOIN PFInstalments_Status [PFIS] ON  
    [PFIS].PFInstalments_Status_id=PFI.Status  
  
    JOIN PFInstalments_Transaction [PFIT] ON  
    [PFIT].PFInstalments_Transaction_id=[PFI].TransactionCode  
  
    JOIN PFPremiumFinance[PLN] ON  
    [PLN].pfprem_finance_cnt = [PFI].pfprem_finance_cnt  
    AND [PLN].pfprem_finance_version = [PFI].pfprem_finance_version  
  
 LEFT JOIN Party_Bank [PB] ON   --(Derick de Klerk) Joining Party_Bank to include 'Bank Account Type'  
 [PB].party_bank_id = [PLN].party_bank_id  
  
 LEFT JOIN Country Cty  --(Derick de Klerk) Joining Country to retrieve Bank Country  
 ON Cty.country_id = PB.bank_country  
  
    JOIN PFScheme[SCH] ON  
    [SCH].schemeversion = [PLN].schemeversion  
    AND [SCH].schemeno = [PLN].schemeno  
    AND [SCH].companyno = [PLN].companyno  
  
    JOIN bankaccount [SCHBNK] ON  
    [SCH].bankaccount_id = [SCHBNK].bankaccount_id  
  
    INNER JOIN account [AC] ON  
    [SCHBNK].account_id = [AC].account_id  
  
    JOIN Party[PTY] ON  
    [PTY].party_cnt = [PLN].clientid  
    LEFT JOIN PArty_Agent PA  
    ON PA.Party_cnt = [PLN].Agent_cnt  
 LEFT JOIN Party [PAG]     --(Derick de Klerk) Joining Party again for Agent Groups to determine if online broker  
 ON PA.linked_account_group = [PAG].party_cnt  
    JOIN Insurance_File [IFILE] ON  
    [PLN].insurance_file_cnt = [IFILE].insurance_file_cnt  
  
WHERE [PFI].batch_id = @batch_id  
AND [PFI].InstalmentNumber <> 0  
  
GROUP BY  
    [SCH].schemeno,  
    [SCH].schemeversion,  
    [SCH].financial_institution_code,  
    [SCH].direct_debit_supplier_name,  
    [SCH].direct_debit_supplier_id,  
    [SCH].schemedescription,  
    [SCH].processing_days,  
    [SCHBNK].code,  
    [SCHBNK].bank_account_no,  
    [SCH].remitter,  
    [AC].merchant_id,  
    [SCHBNK].business_identifier_code,  
    [SCHBNK].international_bank_account_number,  
    [PLN].banksortcode,  
    [PLN].bankaccountno,  
 [PLN].business_identifier_code,  
 [PLN].international_bank_account_number,  
    [PLN].clientname,  
    [PLN].companyname,  
    [PLN].bankaccountname,  
    [PLN].BankSortCode,  
    [PLN].Bankname,  
 [PB].account_type,  
    [PLN].cc_number,  
    [PLN].cc_expiry_date,  
    [PLN].cc_start_date,  
    [PLN].cc_issue,  
    [PLN].cc_pin,  
 [PLN].auth_code,  
    [PTY].shortname,  
    [PTY].alternative_identifier,  
    [PFI].group_id,  
    [PFI].transactioncode,  
    [PLN].Agent_Cnt,  
    [PA].Trading_Name,  
    [PFI].InstalmentNumber,  
    [PLN].deposit_cc_tracking_number,  
    [PLN].insurance_file_cnt,  
    [IFILE].insurance_ref,  
 [IFILE].currency_id,  
 [IFILE].base_currency_id,  
 [PLN].use_trans_currency,  
 [PAG].resolved_name,  
 Cty.[code]  
)  
  
)  
  
ORDER BY  
 [EXPORT_HEADER!1!interface_name],  
 [SCHEME_HEADER!2!scheme_number],  
 [SCHEME_HEADER!2!scheme_version],  
 [SCHEME_TRANSACTION!3!grouped_instalment_duedate],  
 [SCHEME_TRANSACTION!3!grouped_instalment_number],  
 [SCHEME_TRANSACTION!3!grouped_reference],  
 [SCHEME_TRANSACTION!3!grouped_instalment_transaction_code],  
 [SCHEME_TRANSACTION_POLICY!4!policy_id]  
  
FOR XML EXPLICIT  
  
END  


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

