SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
EXECUTE DDLDropProcedure 'spu_BankGuarantee_PLDBranch'
GO

CREATE  PROCEDURE spu_BankGuarantee_PLDBranch
@BG_Id  INT
AS
DELETE FROM
    Bg_Branch_Link WHERE Bg_Id =@bg_id

SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
