SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS ON
GO

EXECUTE DDLDropProcedure 'spu_ACT_Add_Account'
GO

CREATE PROCEDURE spu_ACT_Add_Account
    @account_id int OUTPUT,
    @company_id smallint,
    @purgefrequency_id smallint,
    @accounttype_id smallint,
    @paymenttype_id smallint,
    @currency_id smallint,
    @ledger_id smallint,
    @account_name varchar(60),
    @short_code char(30), -- Sankar - (WPR85_Cash_Deposit_Process) - Paralleling - 20 to 30
    @restrict_enquiry bit,
    @restrict_update bit,
    @delete_at_purge bit,
    @contact_name varchar(60),
    @address1 varchar(40),
    @address2 varchar(40),
    @address3 varchar(40),
    @address4 varchar(40),
    @postal_code varchar(20),
    @address_country smallint,
    @phone_area_code varchar(10),
    @phone_number varchar(15),
    @phone_extension varchar(6),
    @fax_area_code varchar(10),
    @fax_number varchar(15),
    @fax_extension varchar(6),
    @payment_name varchar(60),
    @payment_account_code varchar(60),
    @payment_branch_code varchar(30),
    @payment_expiry_date datetime,
    @payment_reference1 varchar(30),
    @payment_reference2 varchar(30),
    @prooflist_report_id integer,
    @bordereau_report_id integer,
    @credit_limit numeric(19,4),
    @discount_percentage float,
    @settlement_period smallint,
    @bank_name varchar(60),
    @bank_address1 varchar(40),
    @bank_address2 varchar(40),
    @bank_address3 varchar(40),
    @bank_address4 varchar(40),
    @bank_postal_code varchar(20),
    @bank_country smallint,
    @bank_phone_area_code varchar(10),
    @bank_phone_number varchar(15),
    @bank_phone_extension varchar(6),
    @bank_fax_area_code varchar(10),
    @bank_fax_number varchar(15),
    @bank_fax_extension varchar(6),
    @comments varchar(255),
    @account_key int,
    @nominal_account_id int,
    @accountstatus_id smallint,
    @sub_branch_id int = NULL,
    @allow_electronic_payment smallint = 0,
    @client_money_calc_account_type smallint=0,
    @client_bank_account_type smallint,
    @merchant_id varchar(20) = Null
AS
IF ISNULL(@sub_branch_id, 0) = 0
    SELECT @sub_branch_id = sub_branch_id
    FROM   party WITH(NOLOCK)
    WHERE  party_cnt = @account_key
    AND    source_id = @company_id
IF ISNULL(@sub_branch_id, 0) = 0
    EXEC spu_sub_branch_default @source_id=@company_id, @sub_branch_id=@sub_branch_id OUTPUT
INSERT INTO Account (
    company_id,
    sub_branch_id,
    purgefrequency_id,
    accounttype_id,
    paymenttype_id,
    currency_id,
    ledger_id,
    account_name,
    short_code,
    restrict_enquiry,
    restrict_update,
    delete_at_purge,
    contact_name,
    address1,
    address2,
    address3,
    address4,
    postal_code,
    address_country,
    phone_area_code,
    phone_number,
    phone_extension,
    fax_area_code,
    fax_number,
    fax_extension,
    payment_name,
    payment_account_code,
    payment_branch_code,
    payment_expiry_date,
    payment_reference1,
    payment_reference2,
    prooflist_report_id,
    bordereau_report_id,
    credit_limit,
    discount_percentage,
    settlement_period,
    bank_name,
    bank_address1,
    bank_address2,
    bank_address3,
    bank_address4,
    bank_postal_code,
    bank_country,
    bank_phone_area_code,
    bank_phone_number,
    bank_phone_extension,
    bank_fax_area_code,
    bank_fax_number,
    bank_fax_extension,
    comments,
    account_key,
    nominal_account_id,
    accountstatus_id,
    allow_electronic_payment,
    client_money_calc_account_type,
    client_bank_account_type,
    merchant_id)
VALUES (
    @company_id,
    @sub_branch_id,
    @purgefrequency_id,
    @accounttype_id,
    @paymenttype_id,
    @currency_id,
    @ledger_id,
    @account_name,
    @short_code,
    @restrict_enquiry,
    @restrict_update,
    @delete_at_purge,
    @contact_name,
    @address1,
    @address2,
    @address3,
    @address4,
    @postal_code,
    @address_country,
    @phone_area_code,
    @phone_number,
    @phone_extension,
    @fax_area_code,
    @fax_number,
    @fax_extension,
    @payment_name,
    @payment_account_code,
    @payment_branch_code,
    @payment_expiry_date,
    @payment_reference1,
    @payment_reference2,
    @prooflist_report_id,
    @bordereau_report_id,
    @credit_limit,
    @discount_percentage,
    @settlement_period,
    @bank_name,
    @bank_address1,
    @bank_address2,
    @bank_address3,
    @bank_address4,
    @bank_postal_code,
    @bank_country,
    @bank_phone_area_code,
    @bank_phone_number,
    @bank_phone_extension,
    @bank_fax_area_code,
    @bank_fax_number,
    @bank_fax_extension,
    @comments,
    @account_key,
    @nominal_account_id,
    @accountstatus_id,
    @allow_electronic_payment,
    @client_money_calc_account_type,
    @client_bank_account_type,
    @merchant_id)
SELECT @account_id = @@IDENTITY
GO
