SET QUOTED_IDENTIFIER OFF SET ANSI_NULLS OFF
GO

EXECUTE DDLDropProcedure 'spu_ACT_Check_Currency_Rate'
GO

CREATE PROCEDURE spu_ACT_Check_Currency_Rate
    @CURRENCY_ID INT,@CurrencyExist INT OUTPUT
AS

IF EXISTS ( SELECT NULL FROM CurrencyRate WHERE CURRENCY_ID = @CURRENCY_ID)
	BEGIN
	SET @CurrencyExist=1
	RETURN 1
END
ELSE
	BEGIN
	SET @CurrencyExist=0
	RETURN 0
END
GO