SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Execute DDLDropProcedure 'spu_Get_Previous_Plan_Cnt'
GO

CREATE PROCEDURE spu_Get_Previous_Plan_Cnt
  	@prem_finance_Cnt  INT,    
  	@old_prem_finance_Cnt  INT = NULL OUTPUT,    
  	@Version_Cnt   INT = NULL OUTPUT,    
 	@Is_PlanRef_Changed INT = NULL OUTPUT  
AS    
    
DECLARE @Old_Insurance_file_cnt INT    
DECLARE @Insurance_folder_cnt  INT    
DECLARE @Insurance_file_cnt  INT    
DECLARE @Insurance_File_Type  VARCHAR(50)    
DECLARE @Old_Plan_Ref  VARCHAR(50)  
DECLARE @New_Plan_Ref  VARCHAR(50)  
DECLARE @Is_In_Renewal	INT
   
SELECT @Insurance_file_cnt = insurance_file_cnt from pfpremiumfinance where pfprem_finance_cnt = @prem_finance_Cnt    
SELECT @insurance_folder_cnt = insurance_folder_cnt from insurance_file where insurance_file_cnt = @Insurance_File_Cnt    
    
SELECT @Old_Insurance_file_cnt = Max(Insurance_file_cnt)    
 	FROM Insurance_file where insurance_folder_cnt = @insurance_folder_cnt    
 	AND insurance_file_cnt < @insurance_file_cnt    
    
IF ISNULL(@Old_Insurance_file_cnt,0) <> 0    
 	SELECT @old_prem_finance_Cnt = MAX(pfprem_finance_cnt),@Version_Cnt = MAX(pfprem_finance_version)    
  		FROM pfpremiumfinance    
 	WHERE insurance_file_cnt = @Old_Insurance_file_cnt     
    
    
  	SELECT @Old_Plan_Ref = AutoGeneratedPlanRef   
     		FROM pfpremiumfinance    
    	WHERE pfprem_finance_cnt = @old_prem_finance_Cnt     

  	SELECT @New_Plan_Ref = AutoGeneratedPlanRef   
     		FROM pfpremiumfinance    
    	WHERE pfprem_finance_cnt = @prem_finance_Cnt  

  	IF @Old_Plan_Ref <> @New_Plan_Ref   
   		SET @Is_PlanRef_Changed = 1  

  	ELSE IF @Old_Plan_Ref = @New_Plan_Ref   
   		SET @Is_PlanRef_Changed = 0  
    
SET QUOTED_IDENTIFIER OFF    
GO
SET ANSI_NULLS OFF
GO
