    
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
EXECUTE DDLDropProcedure 'spu_Get_Agent_Cert_Year'
GO
CREATE PROCEDURE spu_Get_Agent_Cert_Year    
    @party_cnt INT =0    
AS    
BEGIN    
	SELECT CERTYEARCODE,CERTYEARDESCRIPTION,CERTYEARSTARTDATE,CERTYEARENDDATE,ISNULL(ISDELETED,0)     
	FROM PARTY_CERTIFICATE_YEAR    
	WHERE ISNULL(ISDELETED,0)<>1 AND PARTY_CNT=@party_cnt    
END    
Go
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO 
    