BEGIN TRANSACTION

DELETE FROM Orion_For_Broking..TransMatch
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..MatchGroup
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..AllocationDetail
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Allocation
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..CashListItem
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..CashList
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Cheque
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..TransDetail
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Document
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..ACTNumber_Pool
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..ACTNumber
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..AuditSet
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Budget_Detail
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Budget
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Invoice_Item
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Orion_For_Broking..Invoice
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Sirius_For_Broking..Transaction_Export_Detail
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END
DELETE FROM Sirius_For_Broking..Transaction_Export_Folder
IF @@ERROR <> 0 BEGIN
    ROLLBACK TRANSACTION
    RETURN
END

COMMIT TRANSACTION
