set quoted_identifier on set ansi_nulls on
go

execute DDLDropView 'ClientPolicyAccountTransactions'
go
-- NON-GENERIC REPORT FOR SPECIFIC CUSTOMER. DO NOT USE THIS AS A BASIS
-- FOR LINKING OR CREATING NEW VIEWS.
-- needs ClientsAndPolicies, AccountTransactions
create view ClientPolicyAccountTransactions as select
    ClientsAndPolicies.OrionAccountRef,
    ClientsAndPolicies.ClientID,
    ClientsAndPolicies.Code,
    ClientsAndPolicies.Name,
    ClientsAndPolicies.ClientTypeCode,
    ClientsAndPolicies.ClientTypeDescription,
    ClientsAndPolicies.ClientBranchCode,
    ClientsAndPolicies.ClientBranchName,
    ClientsAndPolicies.ClientLeadAgentCode,
    ClientsAndPolicies.ClientLeadAgentName,
    ClientsAndPolicies.AccountExecCode,
    ClientsAndPolicies.AccountExecName,
    ClientsAndPolicies.ClientCurrencyCode,
    ClientsAndPolicies.ClientCurrencyDescription,
    ClientsAndPolicies.ClientPaymentMethod,
    ClientsAndPolicies.ReminderTypeCode,
    ClientsAndPolicies.ReminderTypeDescription,
    ClientsAndPolicies.ServiceLevelCode,
    ClientsAndPolicies.ServiceLevelDescription,
    ClientsAndPolicies.TermsOfPayment,
    ClientsAndPolicies.ClientRenewalStopReasonCode,
    ClientsAndPolicies.ClientRenewalStopReasonDescription,
    ClientsAndPolicies.SeasonalGiftCode,
    ClientsAndPolicies.SeasonalGiftDescription,
    ClientsAndPolicies.AreaCode,
    ClientsAndPolicies.AreaDescription,
    ClientsAndPolicies.FileCode,
    ClientsAndPolicies.CCJs,
    ClientsAndPolicies.CorrespondenceAddress1,
    ClientsAndPolicies.CorrespondenceAddress2,
    ClientsAndPolicies.CorrespondenceAddress3,
    ClientsAndPolicies.CorrespondenceAddress4,
    ClientsAndPolicies.CorrespondencePostCode,
    ClientsAndPolicies.PreferredCorrespondenceTypeCode,
    ClientsAndPolicies.PreferredCorrespondenceTypeDescription,
    ClientsAndPolicies.PolicyID,
    ClientsAndPolicies.Number,
    ClientsAndPolicies.PolicyTypeCode,
    ClientsAndPolicies.PolicyTypeDescription,
    ClientsAndPolicies.StatusCode,
    ClientsAndPolicies.StatusDescription,
    ClientsAndPolicies.RiskCode,
    ClientsAndPolicies.RiskDescription,
    ClientsAndPolicies.LeadInsurerCode,
    ClientsAndPolicies.LeadInsurerName,
    ClientsAndPolicies.Regarding,
    ClientsAndPolicies.PolicyBranchCode,
    ClientsAndPolicies.PolicyBranchName,
    ClientsAndPolicies.BusinessSourceCode,
    ClientsAndPolicies.BusinessSourceDescription,
    ClientsAndPolicies.BusinessTypeCode,
    ClientsAndPolicies.BusinessTypeDescription,
    ClientsAndPolicies.Quote,
    ClientsAndPolicies.CoverFromDate,
    ClientsAndPolicies.CoverToDate,
    ClientsAndPolicies.InceptionDate,
    ClientsAndPolicies.RenewalDate,
    ClientsAndPolicies.IssuedDate,
    ClientsAndPolicies.AccountHandlerCode,
    ClientsAndPolicies.AccountHandlerName,
    ClientsAndPolicies.PolicyPaymentMethod,
    ClientsAndPolicies.SchemeName,
    ClientsAndPolicies.PremiumIncludingTax,
    ClientsAndPolicies.PremiumExcludingTax,
    ClientsAndPolicies.IPTPercent,
    ClientsAndPolicies.IPTAmount,
    ClientsAndPolicies.VATPercent,
    ClientsAndPolicies.VATAmount,
    ClientsAndPolicies.PolicyCurrencyCode,
    ClientsAndPolicies.PolicyCurrencyDescription,
    ClientsAndPolicies.FuturePremium,
    ClientsAndPolicies.PolicyLeadAgentCode,
    ClientsAndPolicies.PolicyLeadAgentName,
    ClientsAndPolicies.CommissionPercent,
    ClientsAndPolicies.CommissionCharge,
    ClientsAndPolicies.CommissionPayable,
    ClientsAndPolicies.RetainedDocuments,
    ClientsAndPolicies.RenewalFrequencyCode,
    ClientsAndPolicies.RenewalFrequencyDescription,
    ClientsAndPolicies.LTUExpiryDate,
    ClientsAndPolicies.PolicyRenewalStopReasonCode,
    ClientsAndPolicies.PolicyRenewalStopReasonDescription,
    ClientsAndPolicies.RenewalMethodCode,
    ClientsAndPolicies.RenewalMethodDescription,
    ClientsAndPolicies.LapsedReasonCode,
    ClientsAndPolicies.LapsedReasonDescription,
    ClientsAndPolicies.LapsedDate,
    ClientsAndPolicies.TimesRenewed,
    ClientsAndPolicies.ReferredAtRenewal,
    ClientsAndPolicies.ReferredOnMTA,
    AccountTransactions.account_id as AccountID,
    AccountTransactions.TransactionAmount,
    AccountTransactions.TransRef,
    AccountTransactions.AccountingDate
    from ClientsAndPolicies
    inner join AccountTransactions
        on ClientsAndPolicies.OrionAccountRef = AccountTransactions.account_key
go
