set quoted_identifier on set ansi_nulls on
go

execute DDLDropView 'ClientsAndPolicies'
go
-- NON-GENERIC REPORT FOR SPECIFIC CUSTOMER. DO NOT USE THIS AS A BASIS
-- FOR LINKING OR CREATING NEW VIEWS.
-- needs Clients, PolicyFolders, PolicyFiles
create view ClientsAndPolicies as select
    Clients.OrionAccountRef,
    Clients.ID                                  ClientID,
    Clients.Code,
    Clients.Name,
    Clients.TypeCode                            ClientTypeCode,
    Clients.TypeDescription                     ClientTypeDescription,
    Clients.BranchCode                          ClientBranchCode,
    Clients.BranchName                          ClientBranchName,
    Clients.LeadAgentCode                       ClientLeadAgentCode,
    Clients.LeadAgentName                       ClientLeadAgentName,
    Clients.AccountExecCode,
    Clients.AccountExecName,
    Clients.CurrencyCode                        ClientCurrencyCode,
    Clients.CurrencyDescription                 ClientCurrencyDescription,
    Clients.PaymentMethod                       ClientPaymentMethod,
    Clients.ReminderTypeCode,
    Clients.ReminderTypeDescription,
    Clients.ServiceLevelCode,
    Clients.ServiceLevelDescription,
    Clients.TermsOfPayment,
    Clients.RenewalStopReasonCode               ClientRenewalStopReasonCode,
    Clients.RenewalStopReasonDescription        ClientRenewalStopReasonDescription,
    Clients.SeasonalGiftCode,
    Clients.SeasonalGiftDescription,
    Clients.AreaCode,
    Clients.AreaDescription,
    Clients.FileCode,
    Clients.CCJs,
    Clients.CorrespondenceAddress1,
    Clients.CorrespondenceAddress2,
    Clients.CorrespondenceAddress3,
    Clients.CorrespondenceAddress4,
    Clients.CorrespondencePostCode,
    Clients.PreferredCorrespondenceTypeCode,
    Clients.PreferredCorrespondenceTypeDescription,
    PolicyFiles.ID                              PolicyID,
    PolicyFiles.Number,
    PolicyFiles.TypeCode                        PolicyTypeCode,
    PolicyFiles.TypeDescription                 PolicyTypeDescription,
    PolicyFiles.StatusCode,
    PolicyFiles.StatusDescription,
    PolicyFiles.RiskCode,
    PolicyFiles.RiskDescription,
    PolicyFiles.LeadInsurerCode,
    PolicyFiles.LeadInsurerName,
    PolicyFiles.Regarding,
    PolicyFiles.BranchCode                      PolicyBranchCode,
    PolicyFiles.BranchName                      PolicyBranchName,
    PolicyFiles.BusinessSourceCode,
    PolicyFiles.BusinessSourceDescription,
    PolicyFiles.BusinessTypeCode,
    PolicyFiles.BusinessTypeDescription,
    PolicyFiles.Quote,
    PolicyFiles.CoverFromDate,
    PolicyFiles.CoverToDate,
    PolicyFolders.InceptionDate,
    PolicyFiles.RenewalDate,
    PolicyFiles.IssuedDate,
    PolicyFiles.AccountHandlerCode,
    PolicyFiles.AccountHandlerName,
    PolicyFiles.PaymentMethod                   PolicyPaymentMethod,
    PolicyFiles.SchemeName,
    PolicyFiles.PremiumIncludingTax,
    PolicyFiles.PremiumExcludingTax,
    PolicyFiles.IPTPercent,
    PolicyFiles.IPTAmount,
    PolicyFiles.VATPercent,
    PolicyFiles.VATAmount,
    PolicyFiles.TotalPremium,
    PolicyFiles.CurrencyCode                    PolicyCurrencyCode,
    PolicyFiles.CurrencyDescription             PolicyCurrencyDescription,
    PolicyFiles.FuturePremium,
    PolicyFiles.LeadAgentCode                   PolicyLeadAgentCode,
    PolicyFiles.LeadAgentName                   PolicyLeadAgentName,
    PolicyFiles.CommissionPercent,
    PolicyFiles.CommissionCharge,
    PolicyFiles.CommissionPayable,
    PolicyFiles.RetainedDocuments,
    PolicyFiles.RenewalFrequencyCode,
    PolicyFiles.RenewalFrequencyDescription,
    PolicyFiles.LTUExpiryDate,
    PolicyFiles.RenewalStopReasonCode           PolicyRenewalStopReasonCode,
    PolicyFiles.RenewalStopReasonDescription    PolicyRenewalStopReasonDescription,
    PolicyFiles.RenewalMethodCode,
    PolicyFiles.RenewalMethodDescription,
    PolicyFiles.LapsedReasonCode,
    PolicyFiles.LapsedReasonDescription,
    PolicyFiles.LapsedDate,
    PolicyFolders.TimesRenewed,
    PolicyFiles.ReferredAtRenewal,
    PolicyFiles.ReferredOnMTA
    from Clients
    inner join PolicyFolders on Clients.ID = PolicyFolders.ClientID
    inner join PolicyFiles on PolicyFolders.ID = PolicyFiles.PolicyFolderID
go
